### ISSUE TITLE
(BSO) Trip Send Issue

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1005]
## 🐛 Bug Report

I had two trips return at once, one OSB and one BSO. The OSB trip had a clue so I used the C command shortcut to send my minion out to do the OSB clue and at the same time my BSO minion was sent out to do a repeat of its last trip.

The BSO minion trip didn’t return a clue nor was my BSO minion sent out to do a clue. OSB responded to the command just fine.
![989B3488-F0B5-4A6D-97C3-8DEB7F58B00F](https://user-images.githubusercontent.com/65320787/98809393-7577bc00-23eb-11eb-9c13-a343abe23311.jpeg)
![7BE25F18-05FE-48C4-AA6B-7F00A62949FA](https://user-images.githubusercontent.com/65320787/98809398-76a8e900-23eb-11eb-909e-641cfc2f0ff4.jpeg)

**Comment by osrsolympus** [comment]
Had a similar situation just happen where two trips retuned at once, this time the bso trip didn’t have a clue and the OSB trip did. I pressed c to do the clue but it registered as a continue on some previous trips done within the timer for repeating old trips 
![ACA0C18D-215C-4C71-9DE5-EDF0E3357A9F](https://user-images.githubusercontent.com/65320787/108456093-82534980-723d-11eb-8742-41e02e368d9c.jpeg)

**Comment by Lajnux** [comment]
resolved
