### ISSUE TITLE
[BSO] Add a "Y" to repeat trip option to clue scrolls

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1009]
## 🚀 Feature Proposal

Add the "Y" (Or random letters for non-patrons) continuation to clue trips on BSO. This would be great because a majority of clues are done in bulk, and as of now you need to type the command manually lots of times which gets tedious. This would NOT fit in with the main bot though, as you can't stack clues.

**Comment by Lajnux** [comment]
resolved
