### ISSUE TITLE
Combat system proposal

### ISSUE THREAD

**Issue by gc** [oldschoolgg/oldschoolbot#1010]
## 🚀 Feature Proposal

- Add attack, strength, defence, HP, range, mage skills
- You pick which attack style to use with a command
- You don't necessarily need high stats to fight bosses, but you get penalized/buffed for having low/high stats. For example, the current speed at which you do bosses would be medium-high stats (80's), meaning that when the update comes, your kills will be slower, because you start off at level 1 (i.e currently, before the update, you kinda have level 80 in the combat stats), this also means, once you go past level 80 - you would start being faster than you are now.
- We could still requires stats for some things, like raids could require base-70 stats for example.
- Range and mage would be difficult, considering they require consumables (Arrows/runes).

**Comment by ard35** [comment]
Proposal:

We can use a function to determine `DPS` against the monster. 
`DPS` * `weaponAttackSpeed` (in seconds) = `averageDamagePerHit`. 
If `DPS` = 4, `weaponAttackSpeed` = 3 --> `averageDamagePerHit` is 12. 
We can divide the `monsterHP` by the `averageDamagePerHit` to determine how many hits it takes. This would then make it easy to remove consumables or charges from weapons. 

This would be done before a trip is sent out to ensure the player has enough consumables or charges for the kills specified, or the max kills possible with the current consumables / charges they have.

This would also determine how long a trip will be. `monsterHP` / `DPS` = `secondsPerKill`. `killsSpecified` / `secondsPerKill` = `timePerTrip`.

**Comment by Lajnux** [comment]
resolved, but should reconsider combat simulation as long as it's built in a way so the user wouldn't notice much of a difference between current system and the more advanced system.
