### ISSUE TITLE
Daily answers possibly reverted?

### ISSUE THREAD

**Issue by thievious1** [oldschoolgg/oldschoolbot#1012]
I think much like the +w command breaking recently, dailies may be messed up as well. I’ve noticed that dailies don’t accept “newly” added answers that were accepted, but are listed in the trivia docs as possible answers. 
![D8DD4A51-99A6-4FD8-8D3B-F321CAE9D489](https://user-images.githubusercontent.com/65054062/99136605-8ee75680-25eb-11eb-80f6-bb72f14c0058.jpeg)
![D142C5B3-1C79-425D-ABE2-38D1C461C689](https://user-images.githubusercontent.com/65054062/99136606-90188380-25eb-11eb-9c42-7143a8574cb2.jpeg)

**Comment by gc** [comment]
Should be fixed now.
