### ISSUE TITLE
Some dailies are case sensitive it seems, or answer is incorrect

### ISSUE THREAD

**Issue by Scphott** [oldschoolgg/oldschoolbot#1025]
I was doing my daily and answered correctly (but in all lowercase, which shouldn't matter) but it said it was incorrect. I researched afterwards and discovered the answer I gave was correct, but wasn't an answer it expected.
![image](https://user-images.githubusercontent.com/69805753/99615415-fe40ba00-29e0-11eb-9f3f-1b0940221300.png)
![image](https://user-images.githubusercontent.com/69805753/99615438-0698f500-29e1-11eb-9857-80841f28fc44.png)
![image](https://user-images.githubusercontent.com/69805753/99615457-0c8ed600-29e1-11eb-8f60-142c10cda645.png)

**Comment by Sethmare** [comment]
Your answer was correct and the daily answers are case insensitive in all cases I have ever seen. Unfortunately this happens pretty frequently when there is lag at the same time you are answering daily questions.

**Comment by Lajnux** [comment]
resolved
