### ISSUE TITLE
Monocle from elite clue scroll

### ISSUE THREAD

**Issue by ahmalla** [oldschoolgg/oldschoolbot#1026]
I have done over 5.3k elite clue scrolls and have yet to get this item (the monocle). 

Has anyone looked into it being bugged?

**Comment by ahmalla** [comment]
![5165ADE3-4639-4AA8-921F-5D538599E355](https://user-images.githubusercontent.com/68600561/99718014-0e977a00-2a5f-11eb-84b9-17cc537d2555.png)

**Comment by ard35** [comment]
The monocle is not in the possible clue loot for elites. I'll open a PR to add this item in.

**Comment by osrsolympus** [comment]
Dupe of #950 (so that can be resolved as well once the PR is in)
