### ISSUE TITLE
New collection items sometimes are not shown as purple numbers

### ISSUE THREAD

**Issue by imgidedin** [oldschoolgg/oldschoolbot#1028]
## 🐛 Bug Report

- Sometimes, when the minion returns from a trip and a new, previously not on the collection bank, item is dropped, it doesn't show the purple number, indicating it is a new collection. See images below for an indication of what is happening. Pay attention top the Verac's plateskirt:

- Interesting points to make, that can help solve this problem:
-- Dwarven Warhammer was being used, increasing trip length by 40%;
-- Ori was used, which ceiled multiplied the kill() by 1.25;
-- All boosts were in effect (Barrows gloves and Iban's Staff);
-- Minion trip was being send using **y**;
-- The only command executed after the **y** was sent was `=cl boss`, 7 minutes before the bot return.

- Boss collection log (BSO) before the drop happened: 
![image](https://user-images.githubusercontent.com/19570528/99831448-d5820700-2b3d-11eb-9081-f81a43300366.png)
- Barrows returning trip: 
![image](https://user-images.githubusercontent.com/19570528/99831463-de72d880-2b3d-11eb-8909-9dc02622681b.png)
- Boss collection log (BSO) after the drop: 
![image](https://user-images.githubusercontent.com/19570528/99831479-e6cb1380-2b3d-11eb-82e2-2034b3366840.png)

**Comment by mylife212** [comment]
This issue is not just bso-related, as seen with this picture, the pet isn't a purple number despite being new to my log. https://i.imgur.com/hheF4cM.png
No commands were done before the trip returned, so I assume its entirely random. Sent it out with 'y' and I had all boosts in effect if that helps out.

**Comment by Lajnux** [comment]
resolved
