### ISSUE TITLE
COB

### ISSUE THREAD

**Issue by JeremyBekkers** [oldschoolgg/oldschoolbot#1033]
#625  🐛 Bug Report

The new update with the Cob x2 on nightmare doesn't seem to work like it should work. With a x2 boost you'd expect 2 kills on a solo trip. But for me, with 200+ kc, full inquisitor's and Cob, I do a solo trip (1 kill) in 17mins. Without Cob and Inq a solo trip is 19mins..
![image](https://user-images.githubusercontent.com/62512696/99874216-2cdbb200-2be6-11eb-9989-d98cbdbc1808.png)

**Comment by gc** [comment]
Should be fixed now.
