### ISSUE TITLE
[BSO] little nightmare doesn’t drop from pmbs?

### ISSUE THREAD

**Issue by thievious1** [oldschoolgg/oldschoolbot#1035]
I opened 124 pmb and didn’t get little nightmare from any of them, others have mentioned it possibly being bugged as well.
![EA0F00DB-0A64-4849-AC1B-EA4A10134B90](https://user-images.githubusercontent.com/65054062/99891285-d2feda80-2c2d-11eb-970d-bd3240b5e576.png)
![5C128476-9303-441D-A2E1-EAC686FA4BBD](https://user-images.githubusercontent.com/65054062/99891286-d3977100-2c2d-11eb-96bc-29725bbf215c.png)

**Comment by gc** [comment]
Should be fixed now.
