### ISSUE TITLE
Grand Exchange/Open ended trading

### ISSUE THREAD

**Issue by Sethmare** [oldschoolgg/oldschoolbot#1037]
## 🚀 Feature Proposal

Similar to #376 but I wanted to focus more on the user experience and offer my own suggestions.

**Make a Grand Exchange command to handle moderated/automated/offline trades.**

**Example:**
-A user wants to sell their cannonballs so they type `+ge sell 200gp 100 cannonballs` to sell their cannonballs for 200gp each.
-The bot posts the offer to a read-only channel in the support server, along with a code to accept the offer. *(Maybe also fetchable outside of that channel with a command like `+ge offers cannonballs`)*
-Another user wants to buy it so they type something like `+ge buy [offer number] [quantity]`
-The sale is complete and the seller didn't have to be online. They receive a PM from the bot to notify of the sale completion, and the bot updates the offer in the support server.

This could also be vice versa with buyers being able to put offers up and sellers accept them.

**Pros:**
-Transparency with pricing,
-AFK selling (seller won't lose out on sales because he misses a PM/ping)
-Reduced scam risk
-Not being required to join the support server to buy things (if `+ge offers` is added)
-Easily compare pricing to gauge fairness
-Less DMs to server members

**Cons:**
-Less flexible than +sellto (but we don't have to get rid of that command to add this)
-Could be confusing (add a nice little walkthrough to help people format properly)
-MIght need to create more channels in the support server

**Comment by BrandonEnglish848** [comment]
I believe this has been suggested before. Just letting you know in case the post is closed with no explanation.

**Comment by Sethmare** [comment]
I referenced your original issue, and I understand if it does gets closed. I just wanted to offer my own input and perspective on it from a user standpoint. I would hope both issues are considered if this were implemented.

**Comment by BrandonEnglish848** [comment]
Nah I like yours more. I would hope that yours would be implemented instead 👍

**Comment by gc** [comment]
This exists now :)
