### ISSUE TITLE
Ironman Leaderboard

### ISSUE THREAD

**Issue by rsolm5** [oldschoolgg/oldschoolbot#1041]
+lb --im 
Currently one of the higher IM and I would like there to be a separate leader board for us :)

**Comment by kevinsmendes** [comment]
You can use `--im` with `+lb skills`, example: `+lb skills fletching --im`

**Comment by ard35** [comment]
I'm also adding functionality right now to be able to show the overall ironman leaderboards for the `--im` flag.

**Comment by rsolm5** [comment]
I'm aware of the individual leader boards but am looking for the overall leader board like ard35 mentioned. Thank you for working on adding that functionality!

**Comment by TastyPumPum** [comment]
I know this is an old suggestion but I'd also like to see this come into play, if a +"lb cl boss --im" could be added too that would be great.

**Comment by Lajnux** [comment]
resolved
