### ISSUE TITLE
BSO Nightmare boost

### ISSUE THREAD

**Issue by GreyHelm-Inc** [oldschoolgg/oldschoolbot#1046]
Nightmare on BSO is currently a little lacking as suggested by the amount of trips sent in bot channel. As a reference point, around 8000 Malygos trips have been sent in bot channel so far and it was added only 3 days before Nightmare.
![image](https://user-images.githubusercontent.com/73564518/100272029-d5fd1200-2f30-11eb-8ccd-dabb5bc8ba26.png)

My proposal is to add the following to Nightmare:

- A 40% boost for having a dwarven warhammer equipped to a gear setup other than melee

- The chance to have a mystery box drop (and double that trip's loot) like all other bosses

Nightmare also lacks the x2 BSO boost all other bosses have, but adding this would probably be excessive where Cob was added as a boost recently. Let me know what you guys think.

**Comment by imTURBObro** [comment]
Nightmare currently has a 2x boost with cob equipped. 
But for solo runs only.

Are you talking about masses?

**Comment by Lajnux** [comment]
resolved
