### ISSUE TITLE
Possible to add gear sets?

### ISSUE THREAD

**Issue by Vynlladryn** [oldschoolgg/oldschoolbot#1049]
So i know it can be somewhat of a pain to change gear sets depending on the activity you would be doing, so say you're doing malygos and you have your crystal armour abyssal cape on etc etc but your friends want to do some raids, switching out your whole gear set can be somewhat time consuming depending if you're on mobile or even if you're on pc.

Adding the function to add gear sets would make this a lot easier, for example being able to do =addgearset1 melee Bandos Chestplate etc etc

**Comment by Lajnux** [comment]
resolved
