### ISSUE TITLE
Mystery box not giving a reward

### ISSUE THREAD

**Issue by Scphott** [oldschoolgg/oldschoolbot#1051]
## 🐛 Bug Report
Opened a mystery box and it contained NOTHING in it
![image](https://user-images.githubusercontent.com/69805753/100440597-c550b700-306a-11eb-82b9-7f61667ff456.png)

**Comment by osrsolympus** [comment]
Inside the box you find absolutely nothing! What a shame.

Inside the box you find absolutely nothing! What a shame.
