### ISSUE TITLE
=search broken

### ISSUE THREAD

**Issue by Bami420** [oldschoolgg/oldschoolbot#1055]
## 🐛 Bug Report

I’m unable to use =search while others can. Can you please have a look and tell me if/how this can be fixed? See below examples. 

Edit: found these in =b —full —text:

WTF-7499: 1
WTF-7502: 1

Any idea what items that were? 

Thanks

**Comment by Bami420** [comment]
![C3A5DE45-6699-488E-BFB9-E8AC6962F1A5](https://user-images.githubusercontent.com/71937452/100550670-d290c000-327b-11eb-8c61-14e66848992d.jpeg)
![Uploading 2DDC3F96-7389-4A2F-B540-A38FEA3FAEA3.jpeg…]()

**Comment by Bami420** [comment]
Issue is somewhere on bank page 20

![AB4FC28C-30E2-433E-91B4-EF05CD072096](https://user-images.githubusercontent.com/71937452/100551806-67e38280-3283-11eb-92e5-05bf0987d545.jpeg)

**Comment by imTURBObro** [comment]
I've noticed a few other users with the same issue when they do =b —search=

Not sure what is causing it. I'm sure its PvM related though.

**Comment by gc** [comment]
Should be fixed now
