### ISSUE TITLE
+m shame

### ISSUE THREAD

**Issue by sp-chlenged** [oldschoolgg/oldschoolbot#1064]
I propose, in contrast to +m pat, the addition of +m shame.
Hear me out, you send your minion out on a nightmare trip for you know, the 500th time. It dies, so you try again. 20 minutes later and another death, your minion doesn’t deserve reassurance that you love it, it deserves some cold hard shaming.
I implore you to be creative with the savagery, but a few suggestions would be:
You lock your minion in the Yanille pillory and watch as a tramp pelts it with rotten tomatoes.
You telegroup you and your minion to Ice Plateau and d-claw spec it out for failing you. 

This is meant in good humour, not to detract from legitimate additions to the bot but hey we all use

**Comment by gc** [comment]
No
