### ISSUE TITLE
Pickpocketing male ham error

### ISSUE THREAD

**Issue by TylGr** [oldschoolgg/oldschoolbot#1066]
## 🐛 Bug Report
https://i.imgur.com/H8BWCUT.png -> https://i.imgur.com/E88X51y.png

Did a trip of pickpocketing male ham members which on the initial command it said it went on that trip, but doing +m showed female ham members and return loot was also female ham members

EDIT: Looks like it's just visual error, xp received is that of Male HAM members
EDIT2:Pickpocketing cave goblins returns pickpocketing farmer message EDIT3: Turns out it gives loot and xp from farmers

**Comment by Lajnux** [comment]
this should be resolved in oldschoolJS atleast, #1083 should resolve the oldschoolBot part.
