### ISSUE TITLE
Update Craftable Items

### ISSUE THREAD

**Issue by BrandonEnglish848** [oldschoolgg/oldschoolbot#1068]
## 🚀 Feature Proposal
With the addition of mining gem rocks, I thought it was time to check out the list of all possible craftable items. We need to add these to the list of craftables, as well as the --crafting bank filter:

Topaz amulet (u)
Jade amulet (u)
Opal amulet (u)

**Comment by Sethmare** [comment]
I believe, with the way the crafting filter is coded, things are automatically added to the filter once they are added to craftables.

**Comment by Lajnux** [comment]
resolved
