### ISSUE TITLE
=Spawnlamp question .. maybe bug?

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#1070]
## 🐛 Bug Report

![SmartSelect_20201204-035114_Discord.jpg](https://user-images.githubusercontent.com/68685674/101149192-31d83280-35e4-11eb-82ac-64ebd65f5b04.jpg)

my bank was NOT deleted thankfully but I did =spawnlamp and it gave me this response.

is this correct?

**Comment by gc** [comment]
This command is for me only. The message is a troll.
