### ISSUE TITLE
.jpg file instead of displaying loot

### ISSUE THREAD

**Issue by BakedPlayer** [oldschoolgg/oldschoolbot#1080]
## 🐛 Bug Report

Givesa file to click on instead of displaying the image, not sure if bug or just something went wrong but throwing in here below are the pics of the files to click and one of the usual of course. Thanks!
![6F5C6475-654D-4247-99B8-5782D24E60DA](https://user-images.githubusercontent.com/75598650/101308353-e9e52580-3806-11eb-998b-1e4f3a4d0140.png)
![AFC8B3CA-C71D-4F49-8A70-99A1ABE209AC](https://user-images.githubusercontent.com/75598650/101308357-ebaee900-3806-11eb-82b9-944969502565.png)
![4042B10C-5B49-4C46-9E81-29CF193D77D1](https://user-images.githubusercontent.com/75598650/101308366-ee114300-3806-11eb-9338-c71c4d2debc1.png)

**Comment by imTURBObro** [comment]
was a discord issue
