### ISSUE TITLE
Farming bugs/suggestions

### ISSUE THREAD

**Issue by gc** [oldschoolgg/oldschoolbot#1093]
Please post suggestions/feedback/bug-reports on farming in this issue as a comment

**Comment by ard35** [comment]
Small bugs: 

- ehptimer emoji in `=checkpatch` has the incorrect ID, should be `352323705210142721`.

- by @badaman_up#1049 on discord, farming isnt capitalised in +m stats.

**Comment by osrsolympus** [comment]
Suggestion: Make Tithe Farm always harvest 100, or at least make it variable based on tithe farm experience.

—tithe farm harvests don’t die naturally and will only die if you miss a watering cycle which few new players should, and no experienced tithe farmers should.

**Comment by ard35** [comment]
This is already the case with tithe farm. The very first time your minion is inexperienced and will get 85. Each kc thereafter will increase their harvest by 1. After 15 kc, your minion will be doing harvests of 100. 

Do you suggest that the player should learn how to harvest all 100 fruits sooner?

**Comment by imTURBObro** [comment]
I'm not able to purchase farmer's outfit from the shop with =buy option.

didn't seem to exist in shop

**Comment by osrsolympus** [comment]
> I'm not able to purchase farmer's outfit from the shop with =buy option.
It’s =tfs itemname

**Comment by osrsolympus** [comment]
Unsure if saltpetre was coded, but it isn’t in the command list and it’s the only way to be able to use the grape seeds from the tfs.

**Comment by imTURBObro** [comment]
> > I'm not able to purchase farmer's outfit from the shop with =buy option.
> It’s =tfs itemname
> 
> 

and im only able to do it when not busy?

**Comment by ard35** [comment]
> > > I'm not able to purchase farmer's outfit from the shop with =buy option.
> > > It’s =tfs itemname
> 
> and im only able to do it when not busy?

Correct, this is to prevent a bug where you can complete a tithe farm and buy an item at the same time and the points would be overwritten incorrectly. It also makes sense that you can't access the shop while you're in the minigame (such as ingame)

**Comment by ard35** [comment]
This is what's needed before OSB
- compost bins system
- all hops
- roots from trees
- mole parts (PR'd here: https://github.com/oldschoolgg/oldschoolbot/pull/1102)
- zammy grapes
- add farmers clothes to cl

**Comment by ard35** [comment]
- Fix limpqwurt yield

**Comment by PorkyPiggy** [comment]
When I plant strawberry seeds, it seems to use 32 seeds, and then 32 ultracompost. Should be less as there aren’t 32 patches for allotments.

**Comment by Sethmare** [comment]
> When I plant strawberry seeds, it seems to use 32 seeds, and then 32 ultracompost. Should be less as there aren’t 32 patches for allotments.

Each allotment patch should require 3 seeds, each hops patch should require 4 seeds (3 for Jute), and only 1 compost for all of these patches

**Comment by ard35** [comment]
> When I plant strawberry seeds, it seems to use 32 seeds, and then 32 ultracompost. Should be less as there aren’t 32 patches for allotments.

This has been identified as a bug and will be fixed in the next update

**Comment by Sihtric420** [comment]
turn it into a form like bank text but have it where you can scroll between 3 pages.

1. - patches ready to harvest.
2. - patches and remaining time until harvest.
3. - patches with nothing.

![SmartSelect_20201219-093231_Discord](https://user-images.githubusercontent.com/76258747/102694185-1759a800-41e5-11eb-9819-fe2c0db7e632.jpg)
![SmartSelect_20201219-093340_Discord](https://user-images.githubusercontent.com/76258747/102694189-19236b80-41e5-11eb-8658-339ae1eb822f.jpg)

**Comment by Lajnux** [comment]
All farming related issues have been handled, any further bug will be very narrow bugs since they haven't appeared yet and therefor can be reported in it's own issue. Andre is awesome.

**Comment by imTURBObro** [comment]
> All farming related issues have been handled, any further bug will be very narrow bugs since they haven't appeared yet and therefor can be reported in it's own issue. Andre is awesome. 

this is old l can't even play I'm banned
