### ISSUE TITLE
Suggestion: Allow Us to Sacrifice Pets for ~100m Sacrifice GP

### ISSUE THREAD

**Issue by Stonedeamon** [oldschoolgg/oldschoolbot#1094]
## 🚀 Feature Proposal

I'm not sure if this is possible without making them tradeable but it was an idea I recently thought of. Also 100m was just a suggestion, wasn't necessarily set on that number. Thanks!

**Comment by Lajnux** [comment]
pets are possible to be sacrificed. resolved
