### ISSUE TITLE
Vesta (inactive)

### ISSUE THREAD

**Issue by MadManiacal1** [oldschoolgg/oldschoolbot#1095]
## 🚀 Feature Proposal - Item Usability

Vesta's longsword (inactive) is currently unusable in the bot.
In OSRS, it can be converted to Vesta's Blighted Longsword by paying 50m.
My suggestion: Add Vesta's Longsword (inactive) to the "+create fix" category, for the standard "fix" price of 100m.

Thx for the consideration.

**Comment by Lajnux** [comment]
with BSO items being far better than the OSRS deadman mode item there is no need for this to be coded anymore
