### ISSUE TITLE
Ironman - Can't create an ironman

### ISSUE THREAD

**Issue by hugo1khaou** [oldschoolgg/oldschoolbot#1105]
My friend recently made his minion and wanted to join me as an ironman but no matter how quickly he typed confirm it kept refusing to allow him to become an ironman.

We tried getting items in bank, sacrificing an item and doing an action but were unable to make this account an ironman. 

Uncertain if there is an age restriction on being an ironman that doesn't apply to getting a minion (for free) but we were unable to find a way to make this account an ironman

Discord user having troubles: Haz - ID:146454315203035137

![Screenshot 2020-12-14 at 12 34 40 PM](https://user-images.githubusercontent.com/38154681/102040892-0128a200-3e09-11eb-921b-aa92bda29e7a.png)
![Screenshot 2020-12-14 at 12 34 54 PM](https://user-images.githubusercontent.com/38154681/102040896-0554bf80-3e09-11eb-82e2-bf3e39fa611e.png)
![Screenshot 2020-12-14 at 12 35 04 PM](https://user-images.githubusercontent.com/38154681/102041210-bfe4c200-3e09-11eb-80b0-c82772372ec8.png)
![Screenshot 2020-12-14 at 12 35 49 PM](https://user-images.githubusercontent.com/38154681/102041214-c1ae8580-3e09-11eb-80ee-d21f8fd4e982.png)
![Screenshot 2020-12-14 at 12 36 05 PM](https://user-images.githubusercontent.com/38154681/102041216-c410df80-3e09-11eb-8c28-2ab44ee7b2ff.png)

**Comment by gc** [comment]
Should be fixed now.
