### ISSUE TITLE
Allow Nightmare/Zalcano/WT to work for +drystreak commands

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1107]
## 🚀 Feature Proposal

Nightmare, Wintertodt and Zalcano dont work for +drystreak commands, most likely due to being classified as a minigame. would be neat if the drystreak command could work with them!

**Comment by ard35** [comment]
With this will also come leaderboards for these activities, which I've also seen as a previous suggestion.

**Comment by gc** [comment]
Done, will be in next update
