### ISSUE TITLE
Disapearing umb

### ISSUE THREAD

**Issue by thesauce69** [oldschoolgg/oldschoolbot#1111]
## 🐛 Bug Report

I recieved an "error occured" message after opening 83 tmb and then trying to open 62 umb, when i tryed opening again it said I didnt have any umb. I gained 2 bank tabs but thats after opening the tmb so im not sure if i actually got the umb rolls , ive also searched in my bank text for a "wtf" item and dont have any items worth 73gp either as im told those were broken

> `
![Screenshot_2020-12-16-01-25-27](https://user-images.githubusercontent.com/71991625/102440352-b3b55c00-3fe5-11eb-84e3-23b58f95e7cf.png)
![Screenshot_2020-12-16-01-25-36](https://user-images.githubusercontent.com/71991625/102440388-c3cd3b80-3fe5-11eb-8eca-9698f6e32c48.png)
![Screenshot_2020-12-16-01-25-39](https://user-images.githubusercontent.com/71991625/102440395-c92a8600-3fe5-11eb-8f27-ab56b4f9a715.png)
![Screenshot_2020-12-16-21-20-03](https://user-images.githubusercontent.com/71991625/102440422-d182c100-3fe5-11eb-8403-044a4c96e165.png)
![Screenshot_2020-12-16-21-20-05](https://user-images.githubusercontent.com/71991625/102440439-d9426580-3fe5-11eb-8107-fc6a6f6211bf.png)

`

**Comment by Lajnux** [comment]
resolved
