### ISSUE TITLE
Missing BA honor points

### ISSUE THREAD

**Issue by Paah** [oldschoolgg/oldschoolbot#1117]
## 🐛 Bug Report

Missing all points from first BA trip and the decimals from following trips (latter is maybe intended?)
![unknown4](https://user-images.githubusercontent.com/693168/102684213-48cf7500-41df-11eb-814f-cd0421ab2656.png)

**Comment by Paah** [comment]
Another BA trip with points missing
![image](https://user-images.githubusercontent.com/693168/102685791-c26d6000-41eb-11eb-9c23-26326b6e1781.png)

**Comment by gc** [comment]
I think this should be fixed - if its still happening please re-open this and let me know.
