### ISSUE TITLE
gri disable

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#1129]
## 🚀 Feature Proposal

add a =gri disable command that blocks gri being used on your account.
saves mods a job every time someone uses it to grief

**Comment by Wyrmyy** [comment]
true

**Comment by GreyHelm-Inc** [comment]
Disabling this along with =pay would help people become an unofficial ironman. I like the idea!

**Comment by 6enny6** [comment]
bump
