### ISSUE TITLE
(BSO) Attempting to sell 3rd age plateskirt claims item does not exist

### ISSUE THREAD

**Issue by MunsterMc** [oldschoolgg/oldschoolbot#1132]
## 🐛 Bug Report
Selling 3rd age plateskirt does not work unless a quantity is specified, this was not the case before the bulk-selling was added, this might be affecting other items as well

![image](https://user-images.githubusercontent.com/30962666/103171355-eb28d180-484b-11eb-8766-4809534bc3da.png)
Before update

![image](https://user-images.githubusercontent.com/30962666/103171319-ad2bad80-484b-11eb-887d-cb58916692ef.png)
After update

**Comment by Lilbourne** [comment]
I had a similar issue earlier today with this, if you specify a quantity, it should work.
Eg. =Sell 1 3rd age plateskirt

Obviously still a bit bugged but, this should work for now.
