### ISSUE TITLE
Can Sell the custom boss Ori to the Bot

### ISSUE THREAD

**Issue by Robson1212121223** [oldschoolgg/oldschoolbot#1133]
## 🐛 Bug Report

Hi, 

Currently, you can Sell Ori to the bot on BSO, have tried with selected other custom pets and are still unable to do this. From this it looks like a bug since the new update was introduced.

https://i.imgur.com/aG3Ipi7.jpeg

Here is an image of me selling mass items at once, red circle is the Ori, in the command was other untradeable items which were not sold.
Here is another image of someone showing that ori can be sold but other pets still cannot
https://i.imgur.com/WVMufDP.jpg

This has happened to a few people so far. that I know of., myself (Robson#9582), and two others  Wurtle#0660 and JPRx(josh)#2212 

Hope this helps.
Thanks,
Robson

**Comment by Lajnux** [comment]
I don't understand why you in the first place put a item that you don't want to sell in to the sell command. Second it's most likely Ori is using a itemID of a tradeable item in game.
