### ISSUE TITLE
BSO Opening nest boxes

### ISSUE THREAD

**Issue by Lilbourne** [oldschoolgg/oldschoolbot#1134]
Currently able to open nest boxes on OSB, but not on BSO.

Assuming Herblore is being released soon, it'll most likely be introduced to BSO as a safety measure for OSB, as other skills have.

This could have already been planned with Herblore release, but if not, would be a good idea to have this ready.
![SmartSelect_20201228-020930_Discord](https://user-images.githubusercontent.com/70830013/103196215-c0716400-48b1-11eb-80fc-f024381b7c4e.jpg)

**Comment by Lilbourne** [comment]
Does bumping work for this?

Also, some have specified that this may not be working due to a bug but, opening nest boxes works on OSB, which I would assume means that the bug was fixed and pushed to OSB.

**Comment by gc** [comment]
Fixed
