### ISSUE TITLE
BSO Error Item (UMB)

### ISSUE THREAD

**Issue by ArtMatters** [oldschoolgg/oldschoolbot#1135]
I opened a few UMB's and one of the items is apparently glitched and wont show up so it gives an error on any page that tries to show it.

ArtMatters#3174

assuming it is the last item in my bank 
The item name has the letters:
a e 
b h k p r s t
does not have:
i o u y
c d f g j l m n q v w x z
0 1 2 3 4 5 6 7 8 9

**Comment by ArtMatters** [comment]
Beekeeper's hat: 1 <--- this seems to be the item

**Comment by Lajnux** [comment]
resolved
