### ISSUE TITLE
Opened 373 tradeable mystery box to get no items

### ISSUE THREAD

**Issue by Ktownstoner** [oldschoolgg/oldschoolbot#1136]
I opened 373 tradable mystery it gave me none of the items, I checked my bank there are not there. There isn't much else to say. I would like my items or the boxes. It shows the items in my collection log but the items are not there. No errors happend nothing happens out the normal. Maybe now the owner will actually do something and look into this. Quite doubtful as doesnt care unless you pay him.
![Screenshot_20201224-173719_Discord](https://user-images.githubusercontent.com/62821846/103207875-68485b00-48cd-11eb-832e-ef390879afa0.jpg)
![Screenshot_20201224-174139_Discord](https://user-images.githubusercontent.com/62821846/103207888-7007ff80-48cd-11eb-8fa9-d2080bcc69db.jpg)

**Comment by gc** [comment]
```Maybe now [after actually reporting the bug like you're supposed to] the owner will actually do something and look into this. Quite doubtful as doesnt care unless you pay him.```

I won't be looking into this bug, not because "I don't care" but because you're disrespecting me for no reason and I don't want to help you. You're welcome to re-open this with a different message.
