### ISSUE TITLE
HCIM deaths feature broken

### ISSUE THREAD

**Issue by BCicala** [oldschoolgg/oldschoolbot#1138]
## 🐛 Bug Report

HCIM Deaths aren't being updated - 1 week since last post from bot (there's been 13 deaths tweeted since last post)

https://twitter.com/HCIM_Deaths

![image](https://user-images.githubusercontent.com/9968153/103251631-720ea480-4947-11eb-8812-504fbe87a1fd.png)

**Comment by gc** [comment]
Fixed now!
