### ISSUE TITLE
I opened 373 tradable mystery it gave me none of the items, I checked my bank they are not there.It shows the items in my collection log but the items are not there in my bank. No errors happend during or after nothing happened out the normal. 

### ISSUE THREAD

**Issue by Ktownstoner** [oldschoolgg/oldschoolbot#1141]
## 🐛 Bug Report
 
Opened 373 tmb in my server with some friends everything went fine there was no error code or anything that came up. I went to look in my bank after for the items but none of them were there. It showed the items in my cl but not in bank

**Comment by Ktownstoner** [comment]
[![Screenshot_20201224-173719_Discord.jpg](https://user-images.githubusercontent.com/62821846/103301543-a4fc7b00-49cf-11eb-95fe-8981e216180c.jpg)![Screenshot_20201224-174600_Discord.jpg](https://user-images.githubusercontent.com/62821846/103301590-b9407800-49cf-11eb-94ff-32bfcbe5d439.jpg)

**Comment by Ktownstoner** [comment]
@gc

**Comment by Ktownstoner** [comment]
@gc if you could look at it by chance.

**Comment by Ktownstoner** [comment]
@gc

**Comment by Lajnux** [comment]
resolved issue, not sure if refunded. If not reach out to mod or Magnaboy

**Comment by Ktownstoner** [comment]
Took him over 2 months but magna refunded just over a quarter of what was lost
