### ISSUE TITLE
[BSO/OSB?] Agility Arena graceful recolor takes 500 tickets, not 250

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1143]
## 🐛 Bug Report

This issue happened on BSO but may be in OSB too. Posting on behalf of Gizzmo. 

The player had 550 Arena tickets and bought the Brimhaven graceful recolor. Bot removed **500** tickets, when it should have removed 250 tickets, the Graceful was successfully recolored and the player has not bought anything else beyond the Recolor.

Attached the evidence of the bug. They show the player buying the recolor, the Tickets in col log and the remaining tickets in the players bank 
![aa1](https://user-images.githubusercontent.com/63373565/103314525-64adf480-49f1-11eb-9b10-afd02ef65052.png)
![aa3](https://user-images.githubusercontent.com/63373565/103314636-a3dc4580-49f1-11eb-90d8-d2af2a60c2b6.png)
![aa2](https://user-images.githubusercontent.com/63373565/103314647-a8a0f980-49f1-11eb-982c-135af2e7db9d.png)

**Comment by gc** [comment]
Fixed now
