### ISSUE TITLE
zulrah Ely effect

### ISSUE THREAD

**Issue by unicornakazulrah** [oldschoolgg/oldschoolbot#1145]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

On the original release of the ely providing an extra 17.5% savings to food usage, the ely would be checked if it was either in the range or mage gear setups, since the bot is coded to check both setups, mage setup specifically if you have the required 50 magic bonus. I believe when the ely stopped working on the 12/21 update, the ely effect was fixed but it now only works if it is in the range gear setup, at least for zulrah (I haven't tested any other bosses yet). This change doesn't allow the user to use any type bow if you still want to utilize the ely effect. Not sure if this was intentional change or happened on accident when ely was fixed when the champions cape update was released.

**Comment by unicornakazulrah** [comment]
Screenies for proof;
A zulrah trip from 12/18/2020, which had the ely in the mage setup, which shows the ely reduction affect
![Discord_whC9k6xraK](https://user-images.githubusercontent.com/71468925/103321169-f7ed2700-49fd-11eb-8935-cc5f8af4320e.png)

My mage gear setup at the time
![Discord_F2Ngir9cCA](https://user-images.githubusercontent.com/71468925/103321205-223ee480-49fe-11eb-9cfd-51116fa0655f.png)

A trip from today, the mage setup has not changed, ely reduction affect no longer working
![Discord_ZJZNrGtFfi](https://user-images.githubusercontent.com/71468925/103321214-2f5bd380-49fe-11eb-9330-968be40018f1.png)

**Comment by unicornakazulrah** [comment]
When I made the switch today to move the ely to range setup, ely reduction affect now shows

![Discord_OVe1y1E4Dw](https://user-images.githubusercontent.com/71468925/103321233-4995b180-49fe-11eb-9b05-a320ee5d29f3.png)

**Comment by gc** [comment]
Should be fixed in next update - thanks for reporting!
