### ISSUE TITLE
[BSO] Mixing unf potions

### ISSUE THREAD

**Issue by NotShin** [oldschoolgg/oldschoolbot#1150]
## 🐛 Bug Report

When you don't have the cleaned herb needed to make an (unf) potion, it states you don't have enough vials of water.

![image](https://user-images.githubusercontent.com/21049385/103425404-1da23980-4b80-11eb-8e48-4d20190b7ca2.png)

**Comment by ArtMatters** [comment]
Bump

**Comment by Lajnux** [comment]
resolved
