### ISSUE TITLE
Agility Arena tickets dont give proper exp

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1152]
## 🐛 Bug Report
This bug is specifically about the 1k Ticket for exp reward, but it most likely applies elsewhere. 

Redeeming 1k Agility Arena tickets for exp doesn't give the exp it should. It does give some exp, but it is VERY little. 

The screenshots show the bug in action. 
Pic 1 - Exp before redeeming tickets
Pic 2 - Redeeming the tickets for exp
Pic 3 - Exp after redeeming, only 14k exp has been added. Should be over 1m exp
![arena1](https://user-images.githubusercontent.com/63373565/103432979-2104e780-4bb7-11eb-9175-391608453dff.png)
![arena2](https://user-images.githubusercontent.com/63373565/103432983-24986e80-4bb7-11eb-9ee5-a54d4778bbc9.png)
![arena3](https://user-images.githubusercontent.com/63373565/103432985-26fac880-4bb7-11eb-88a4-394711dff44c.png)

**Comment by gc** [comment]
This should be fixed now, closing because I'm 99% sure its fixed.
