### ISSUE TITLE
Patches dieing while protected

### ISSUE THREAD

**Issue by Vanillaah** [oldschoolgg/oldschoolbot#1153]
## 🐛 Bug Report

I paid to protect 2 dragonfruit trees and they both died. 
![Screenshot_20210101-093900_Discord](https://user-images.githubusercontent.com/24986403/103435886-9901fa80-4c15-11eb-857c-a16f4a29633f.jpg)
![Screenshot_20210101-093851_Discord](https://user-images.githubusercontent.com/24986403/103435887-9ef7db80-4c15-11eb-8bc8-d54711b1ed8d.jpg)

**Comment by ard35** [comment]
Thanks for reporting this, it will be fixed when the above PR gets merged. `Until then, only --pay for plants if you know the patch already has something grown in it` (i.e. it does not work if you harvest a patch and then plant in it and pay).
