### ISSUE TITLE
Issue searching bank 

### ISSUE THREAD

**Issue by ahmalla** [oldschoolgg/oldschoolbot#1155]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

Anytime I use the =b —search=XXX command i get the unexpected error message. Assuming one of the broken items in my bank is the culprit

**Comment by ahmalla** [comment]
I’ve been informed that The items “ WTF-5572” needs to be removed from my bank manually l.

**Comment by gc** [comment]
Fixed
