### ISSUE TITLE
Herblore - Torstol potion (unf)

### ISSUE THREAD

**Issue by Cadaveric9419** [oldschoolgg/oldschoolbot#1160]
The ability to combine Torstol Potion (unf) with super attack/strength/defence to make a Super Combat Potion (as it’s an option in-game).

**Comment by Vanillaah** [comment]
This ^

**Comment by ReganSmash** [comment]
This would be so helpful, i just wasted 4k torstols

**Comment by 6enny6** [comment]
bump

**Comment by zabiros** [comment]
+1

**Comment by coolbop32** [comment]
you can now make them back into herbs
