### ISSUE TITLE
[OSB] Mole seed box

### ISSUE THREAD

**Issue by Jonesn4Jonesy** [oldschoolgg/oldschoolbot#1162]
Seed box from mole skin/claw trade-in is missing multiple seeds from the drop table. This is what I recived from 644 nests. https://i.imgur.com/mjVStQA.png

https://oldschool.runescape.wiki/w/Mole_claw
https://oldschool.runescape.wiki/w/Mole_skin

snape grass, herb seeds and many others appear to be missing. 

Thanks!

**Comment by Lajnux** [comment]
Fixed and merged in oldschoolJS
