### ISSUE TITLE
[BSO] Add the 1/10 Doubled loot+mbox perk to missing activities

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1165]
## 🐛 Bug Report

In BSO, there is a 1/10 chance that your trips loot is doubled and you get a mystery box. This applies for *most* activities, but not the following list (could be missing stuff)

- Nightmare
- Hallowed Sepulchre
- Zalcano
- Tithe farm

**Comment by gc** [comment]
All except tithe now do this.
