### ISSUE TITLE
[minor] plural adds an s regardless if the item name already ends with an s

### ISSUE THREAD

**Issue by Thedyolf2** [oldschoolgg/oldschoolbot#1166]
## 🐛 Bug Report

Sorry if this bug is too minor to go here, but thought I'd let you guys know anyways in case it's still unknown.
See attached image
![image](https://user-images.githubusercontent.com/31892925/103495967-d1cfe880-4e3c-11eb-9aa1-f82c569ac359.png)

**Comment by Lajnux** [comment]
fixed with #1204
