### ISSUE TITLE
BSO Dragon Ornamented Items

### ISSUE THREAD

**Issue by Lilbourne** [oldschoolgg/oldschoolbot#1169]
With the introduction of Grandmaster clues, dragon ornamented items were added as a reward.

For almost all players, these items serve no purpose as they are, and I believe having the ability to seperate the items from the or kit would serve well.

Eg. =create dragon kiteshield, would result in seperating the ornament kit from the item leaving you with both the shield, and ornament kit to sell if the player so chooses.

**Comment by Lilbourne** [comment]
Just realised that some items do work with it, but ones that don't (I'm pretty sure) are:
Dragon full helm
Dragon platebody
Dragon kiteshield

**Comment by nwjgit** [comment]
Pretty sure this has been fixed with /create and picking the proper revert item
