### ISSUE TITLE
[OSB] Notify when you get a rare fish

### ISSUE THREAD

**Issue by Jonesn4Jonesy** [oldschoolgg/oldschoolbot#1172]
## 🚀 Feature Proposal

When you get a rare fish there is no notification of it. Please add something such as:
 "You received: 123x Raw Bass, 1x Big bass." 

screenshots showing there is no notification:

First trip: https://i.imgur.com/4jYNRzq.png
Following trip: https://i.imgur.com/4jpr2sy.png

**Comment by gc** [comment]
Fixed in next update - thanks for reporting!
