### ISSUE TITLE
Didn't get casket after solving a Grandmaster Clue

### ISSUE THREAD

**Issue by BIRDIE13** [oldschoolgg/oldschoolbot#1175]
## 🐛 Bug Report
Solved a grandmaster clue. When it was done, i didn't recieve the casket (see attachments and discordlinks).

https://discord.com/channels/@me/713662621634789446/795783792676569118
https://discord.com/channels/@me/713662621634789446/795783792676569118

![3DEhzDt](https://user-images.githubusercontent.com/37814738/103640478-5e1f0000-4f50-11eb-97aa-fe241a9e0a6d.png)
![W9cF9Xv](https://user-images.githubusercontent.com/37814738/103640480-5eb79680-4f50-11eb-90f6-a9778f8e2eb5.png)

**Comment by zaon-rs** [comment]
I've had the same problem. Sent bot out to do grandmaster, when it returned I neither got the grandmaster clues (2) nor the zippy rewards. Happened 07/01 at 2:27am GMT https://i.imgur.com/p23Sn25.png

**Comment by Lajnux** [comment]
resolved
