### ISSUE TITLE
BSO Bug, Cactus patch not being harvested (might be crashing bot)

### ISSUE THREAD

**Issue by Veras2020** [oldschoolgg/oldschoolbot#1178]
I tried 3 times farming my cactus patch on BSO, 1 min trip, so i just waited the minion, but everytime he is supposed to come back, the time is increased by 60 seconds, and the bot crashed (the 3 times i tried!) 
![image](https://user-images.githubusercontent.com/73716299/103684861-03df6880-4f6b-11eb-97fa-b4c7228be631.png) print of the last time i tried

**Comment by gc** [comment]
Fixed
