### ISSUE TITLE
BSO Hammy

### ISSUE THREAD

**Issue by Lilbourne** [oldschoolgg/oldschoolbot#1179]
Currently this marvel of a critter offers the perk of reducing sawmill cost and interrupting commands.

We all know this lil fella is capable of so much more. I therefore suggest, that with the reduction of Sawmill cost, Hammy also scared the sawmill operator into working at twice, or thrice his regular speed.

Works with what perks are already given and fits with the lore.

**Comment by gc** [comment]
Done
