### ISSUE TITLE
[BSO] Mystery Boxes v. TMB

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1185]
## 🐛 Bug Report

🐟 did an oopsie woopsie fwucky wucky when coding the new bso opening stuff and now doing =open x mystery ends up rolling the standard mystery box loot table and not the “almost every known tradeable item in the universe” loot table and you have to do =open tmb. Very +bsowhocares but also now that I’ve lost about 1b in boxes I figure I might as well report it officially instead of complaining in the support server :)

**Comment by gc** [comment]
Should be fixed now - btw its not Fishys fault in any way!
