### ISSUE TITLE
Beat your meat to this idea

### ISSUE THREAD

**Issue by wildchickenz** [oldschoolgg/oldschoolbot#1188]
New BSO boss idea, Beefsquatch, low/mid tier boss. must use crush gear (beat the meat) 75+ Speed increase if used with one of the following, 10% Dragon Warhammer, 8% Elder Maul, 15% Meat Tenderiser. Boost from Dwarven warhammer applies. 
This Beast of a Beef has overruled the lumbridge cow pen and has slain many HCIM and fresh accounts for days. We cannot rid the realm of the beef forever as it respawns, but we can help control its carnage but fighting it. 
Loot.
-Always - 20-200 Cooked Beef - 5 Big bones
-Common - 1-20 Sinew - bucket of milk - Raw Chicken
-Uncommon - 300 Cowhide - 30 cowhide leather
-Rare - HCIM armour pieces
-Mega rare - NPC Mystery Boxs, these boxes would only contain NPCS and remains

Please I spent like 10 minutes on this

**Comment by gc** [comment]
Ok
