### ISSUE TITLE
[BSO] Takon Dwarven Greathammer Interaction

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1203]
## 🐛 Bug Report

Using the Dwarven Greathammer (2x smithing boost) seems to cancel out the 5x smithing boost from the Takon pet.

In the screenshot, the earlier trip is a partial trip of rune platebody smithing with Takon. The latter trip is a full trip of rune platebodies with takon and the Dwarven Greathammer.

![4D9D33A1-9005-481F-8541-DDD74106EB59](https://user-images.githubusercontent.com/65320787/104204681-88af0400-53fb-11eb-98b9-a29fd02fc956.jpeg)

**Comment by osrsolympus** [comment]
Should be noted that the trip after which sent without the Greathammer made 1900 platebodies.

**Comment by gc** [comment]
It's intended for the 2 bonuses to not stack
