### ISSUE TITLE
[OSB][minor bug]Brimhaven tickets doubled in cl skilling

### ISSUE THREAD

**Issue by Jonesn4Jonesy** [oldschoolgg/oldschoolbot#1205]
## 🐛 Bug Report
---
Very minor bug, but thought I mas as well report it.
---

After doing +aa buy recolor my brim tickets in +cl skilling doubled. I had 270 tickets and after buying the recolor my tickets went to 520. This only affected the +cl skilling and not my actual tickets in the bank. Thanks!

Before: https://cdn.discordapp.com/attachments/738158726799949874/798348492208734249/file.jpg

After: https://cdn.discordapp.com/attachments/738158726799949874/798355773058711632/file.jpg

**Comment by gc** [comment]
Fixed in next update, thanks for reporting :)
