### ISSUE TITLE
Situational error message after entering commands following the start of a Mahogany Homes run

### ISSUE THREAD

**Issue by infinitefreshness** [oldschoolgg/oldschoolbot#1206]
I'm receiving this error message if I enter in certain commands (see image for examples) after entering "=mh build" in BSO. The MH contracts start and complete as expected, but it appears that any command that prompts the bot to reply with your minions current status will result in the error message. Stats, gear, bank, and other commands that don't require your minion to be available still work as expected. 

![Capture](https://user-images.githubusercontent.com/68162540/104258297-3e567300-544d-11eb-99df-9bff64d9aa0d.PNG)

**Comment by gc** [comment]
Should be fixed now.
