### ISSUE TITLE
[OSB] Boss/skilling collection logs suggestion

### ISSUE THREAD

**Issue by Jonesn4Jonesy** [oldschoolgg/oldschoolbot#1216]
## 🚀 Feature Proposal

-Remove agility cape from +cl skilling, I understand it counts as a graceful cape but it doesn't match the rest of the log. It also prevents anyone who doesn't get 99 agility first from completing the log. 

-Move Pheonix pet and Zalcano pet to the end of their lines to match the flow of +cl boss and +cl skilling which majority have the pet at the far right.

Thanks for considering :)

**Comment by Lajnux** [comment]
resolved
