### ISSUE TITLE
Change log command

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1219]
## 🚀 Feature Proposal

Add a +changelog command that will show the X most recent updates to the bot, their contents, and the date on which the update occurred. Will help players not monitoring the code or not part of the support server be up to date with modifications and updates to the code.

**Comment by BIRDIE13** [comment]
You can follow the #news and the #bso-news. This will post the same messages in your channel of choice

![update](https://user-images.githubusercontent.com/37814738/104848281-8c9fc200-58e4-11eb-8029-49006621ce0c.png)

**Comment by osrsolympus** [comment]
Yeah I’m aware that’s why I said it would be helpful for the people who aren’t in this server.

**Comment by Lajnux** [comment]
since news now get easy posted in other ppl servers if they set it up, this is kinda not needed. And if they not following the news they prob wouldn't find such a slash command anyway.
