### ISSUE TITLE
DHCB from COX didn't count towards the "=cl cox" log

### ISSUE THREAD

**Issue by BIRDIE13** [oldschoolgg/oldschoolbot#1221]
As shown in the pictures i never got it in my log.

https://discord.com/channels/342983479501389826/757683928751407224/760453848292261918

![asdwad](https://user-images.githubusercontent.com/37814738/104848167-071c1200-58e4-11eb-8c30-8c4a4e3289a8.png)
![file](https://user-images.githubusercontent.com/37814738/104848066-8eb55100-58e3-11eb-9550-137c964ae5c1.png)

**Comment by Lajnux** [comment]
resolved
