### ISSUE TITLE
Hallowed Sack - Sepulchre

### ISSUE THREAD

**Issue by Mr-Dorian** [oldschoolgg/oldschoolbot#1224]
## 🚀 Feature Proposal

Make a buyable item from the Hallowed Sepulchre that is the Hallowed Sack. This item would cost 100 Hallowed Marks and allow for users to spend their excess Marks after purchasing all other items from the Sepulchre. The Hallowed Sack provides items found in coffins within the Hallowed Sepulchre.

Thank you for your time!

**Comment by mylife212** [comment]
is a thing now hampoggers
