### ISSUE TITLE
grandmaster commands

### ISSUE THREAD

**Issue by ahmalla** [oldschoolgg/oldschoolbot#1228]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

heyo
![command](https://user-images.githubusercontent.com/68600561/104984353-669d1f00-59c3-11eb-8171-f3e5ed0415c6.PNG)

=b clue scroll (grandmaster) & =b clue scroll (grandmaster), do not seem to be working

**Comment by thievious1** [comment]
![37343F20-C5CD-4A55-A145-317F5C241454](https://user-images.githubusercontent.com/65054062/104984486-648f8c00-59d4-11eb-9138-0dd32db22f5d.jpeg)

You’ll have to do it without the parentheses, but I do feel it’s an oversight for that to not work seeing as the other clue tiers use them.

**Comment by ahmalla** [comment]
ahhh dumb i should have known that as buying them is the same way -- ty!
