### ISSUE TITLE
Herblore Additions

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#1231]
Add blue dragon scales to blue dragon loot table
(antifires/gives lantadymes another use)

Add Toad’s Legs from pickpocketing gnomes
(agility potion/gives toadflax a use pre lvl 81)

**Comment by 6enny6** [comment]
Also could add chaos druids so ironmen have a nice way to get low level herbs

**Comment by gc** [comment]
>Add blue dragon scales to blue dragon loot table
Wont be doing this because it doesnt match ingame and OSB follows ingame as closely as reasonably possible.

>Add Toad’s Legs from pickpocketing gnomes
Instead, I've made it possible to create toads legs from swamp toads. (next update)

>Also could add chaos druids so ironmen have a nice way to get low level herbs

Adding chaos druids in next update.
