### ISSUE TITLE
Herbs disappeared out of bank after cleaning

### ISSUE THREAD

**Issue by Yetisburgh** [oldschoolgg/oldschoolbot#1234]
I cleaned grimy ranarr weeds to make unfinish potions but after cleaning them, the clean ranarr weeds disappeared out of bank. 
EDIT: I have about 16k vials of water in my bank as well, it's hard to tell from the screenshot
![unknown](https://user-images.githubusercontent.com/75232241/105195484-acafcb00-5b08-11eb-80ef-59bc31eb4a27.png)

**Comment by Lajnux** [comment]
resolved
