### ISSUE TITLE
More bugged items possibly

### ISSUE THREAD

**Issue by Sethmare** [oldschoolgg/oldschoolbot#1239]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

I was trying to get ids for the clue scrolls and got this error for a few of them. I didn't try all of them though.
![Screenshot_56](https://user-images.githubusercontent.com/66145237/105285841-698a4200-5b72-11eb-9816-00afc1449ce2.png)

**Comment by gc** [comment]
Its because theres so many items with that name that it cant fit it in a message.
