### ISSUE TITLE
[BSO] Feedback on Server restrictions 

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1241]
## 🚀 Feature Proposal
The restrictions of the Trading/gambling commands in the support server  is a great update, but it could be better. Listed feedback is here:

- Allow =givebox to work in general
- Restrict the Bso-trading channel commands so you can only use =sellto, =pay and other related commands, blacklisting the non-trading commands in this specific channel. Currently it has been flooded with random commands since its "the new general"
- Do the same thing as above to bso-gambling (Only allowing =dice, =finish [gambling game], =pay and other gambling commands.)

**Comment by Craftpure** [comment]
Please allow =b too as you may need to check quantities for sales
