### ISSUE TITLE
Clue deleted using command to repeat trip bug

### ISSUE THREAD

**Issue by osDreamscape** [oldschoolgg/oldschoolbot#1245]
![azdtefxhyjg](https://user-images.githubusercontent.com/73551894/105622283-1825c100-5dc5-11eb-8c5c-813445a78275.png)
related to known issue with repeating command within 10 min, but selecting "c" to do the clue, in addition to just doing the previous trip instead of the clue, still removes the clue scroll from the bank

**Comment by Lajnux** [comment]
resolved
