### ISSUE TITLE
No herblore lvl/xp after 10 QP on minion

### ISSUE THREAD

**Issue by TimThaens** [oldschoolgg/oldschoolbot#1249]
## 🐛 Bug Report

I've been doing some quests with my minion, and passed the 10QP (12 at the moment). But my herblore lvl is still lvl1

**Comment by TimThaens** [comment]
Ah, I got it at 14QP.
Not sure if it is intended, but the website says 10QP

**Comment by Lajnux** [comment]
Might be a typo on the website, You have to do quests until you complete the druidic ritual quest which is a chance of happening when you do quests. Can be expected to be gotten at around 10-40 QP depending on luck.
