### ISSUE TITLE
Bso trivia

### ISSUE THREAD

**Issue by Osmosisx** [oldschoolgg/oldschoolbot#1251]
## 🐛 Bug 

Bso trivia didn’t give box 2x in a row for correct answers. 
![5FB9B8AF-15E1-4A8D-A684-21101F0E7B8D](https://user-images.githubusercontent.com/68478237/105662588-17149280-5e9e-11eb-99d2-2506446e13b4.jpeg)

**Comment by thievious1** [comment]
That’s the test bot, not BSO :)
