### ISSUE TITLE
ham member xp rates

### ISSUE THREAD

**Issue by ReZeroed** [oldschoolgg/oldschoolbot#1252]
## 🐛 Bug Report

Since I have started pickpocketing ham members I have noticed that when I first use the command =pickpocket male ham member I get 33,750xp when the trip ends, however if I use the command to send out for the same trip again afterwards I get 27,750xp. It also says I am pickpocketing female ham members after using =m right after sending a trip out for male ham members.

https://discord.com/channels/342983479501389826/732207379818479756/803115922784387152
https://discord.com/channels/342983479501389826/732207379818479756/803119737579372605

**Comment by Lajnux** [comment]
resolved
