### ISSUE TITLE
Hunter Wildy Gear Score

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1259]
## 🐛 Bug Report

Equipped full Karil’s and my gear score for black salamanders is 36/100
![346F917E-BFAC-4641-8A92-ED1F7F337CA1](https://user-images.githubusercontent.com/65320787/105799999-cb2c2100-5f63-11eb-8ad5-6b5c2b054472.jpeg)

the only gear for magic def that would be better is full arma so I’m a bit surprised the score is so low

**Comment by osrsolympus** [comment]
Ok so it’s not a bug report, my bad. But if I can just make it a feature proposal without making a new issue:

change the hunter gear max in OSB to be equal to something reasonable. 
![5F8D2436-B1F1-47AA-98A4-A88AD5507376](https://user-images.githubusercontent.com/65320787/105801752-d08b6a80-5f67-11eb-986f-36b9ac9eca5b.jpeg)
That it’s above the gear stats you’d have for corrupted (perfected) gear is unreasonably high, and puts it at levels OSRS will not see in the main game for the foreseeable future or perhaps ever. It is, in the end, a minor difference to pots used or gear lost, but for the sake of making it accurate to how the game is played it could do with a change.

**Comment by Lajnux** [comment]
resolved with wording, hunter might get another whole rework in future
