### ISSUE TITLE
+cl skilling improvements

### ISSUE THREAD

**Issue by Tonks-Beep** [oldschoolgg/oldschoolbot#1260]
Firstly - Sorry if these have already been talked about!

Are there plans to add more of the 99 capes that coincide with the coll log lines to +cl skilling? Seems weird that only Agility is there...

I know this is super nitpicky when there are so many more important/bigger projects going on in the background. But - Is there plans to reorganise the skilling coll log? There are 5 separate lines of agility-related items in there but they're just kinda... All over the place. I heard from someone somewhere about a Hosidius favour system? Whether that's even a thing or not, but who knows... That'll certainly add another 6 lines worth of Graceful recolours so maybe it can all be updated then?

And hear me out on this - I know Aerial Fishing gives more Hunter XP than Fishing XP. However, the 'fishing' section on +cl skilling is pretty bare and the 'Hunter' one is quite packed... The 2 rewards from Aerial fishing are: The Fish Sack & a Golden Tench (also a fish) Just seems like they'd do nicely in the.... Fishing section. Could also add in the 3 Aerial Fishing Rods from the shop as well :) Failing that, it'd be nice to even see the angler outfit + giant fish + Herron collated into 1 row.

**Comment by Lajnux** [comment]
resolved, with cl overhaul rework
