### ISSUE TITLE
WTF items in bank again

### ISSUE THREAD

**Issue by thievious1** [oldschoolgg/oldschoolbot#1263]
Hello hello friends, fairly simple bug report WTF items are in banks again and breaking searches. Reporting this issue on behalf of ajs74.
![7C7E0A61-ED11-483E-AF50-401394EC8BB0](https://user-images.githubusercontent.com/65054062/106056840-b7dc9b00-60b4-11eb-85cd-e07d9031d3df.png)

**Comment by gc** [comment]
Fixed
