### ISSUE TITLE
Herblore: mixing potion gives wrong error message.

### ISSUE THREAD

**Issue by KyeDon** [oldschoolgg/oldschoolbot#1265]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
![image](https://user-images.githubusercontent.com/47357003/106165397-00628a00-6183-11eb-94c4-759b17f72658.png)

As you can see in the image the error I receive is that I don't have enough red spider eggs when in fact the error is that I had no snapdragon potions (unf). Once I had made some snapdragon potions the same command worked without issue.

**Comment by Lajnux** [comment]
resolved
