### ISSUE TITLE
Chinchompas

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1266]
## 🐛 Bug Report

Hunter is giving players the wrong chinchompa ID for red and grey chins in bank.
![D954F2D3-8881-42E0-8292-8E5B3A9578EA](https://user-images.githubusercontent.com/65320787/106189138-de163f80-6175-11eb-9d21-7cd4eb4657aa.png)

**Comment by osrsolympus** [comment]
Bump

**Comment by osrsolympus** [comment]
Bump

**Comment by wildchickenz** [comment]
Bump

**Comment by wildchickenz** [comment]
dump bump pump that thing up
