### ISSUE TITLE
Herbiboar 

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1267]
## 🐛 Bug Report

If you don’t have the required herblore level for Herbi, you can still hunt it but it just won’t provide herblore xp/herbs.

**Comment by Alexsuperfly** [comment]
Herblore is only required to harvest, which is what gives herb exp, the herbs, and pet chance.  As it stands this is mirroring what is possible in the live game, at least from the way the wiki describes it (idk why anyone would willingly not have the herb level to even test this).


So i dont think this should be changed.

**Comment by Alexsuperfly** [comment]
Thanks to beta worlds being able to set your skills to whatever you want, this has been tested and it seems to require the herblore level in order to start tracking.  The wiki was wrong 😠

**Comment by Lajnux** [comment]
#1286 resolves this issue
