### ISSUE TITLE
Aerial Fishing. Cant catch Greater Siren.

### ISSUE THREAD

**Issue by KatoGuttan** [oldschoolgg/oldschoolbot#1274]
## 🐛 Bug Report

After getting the stats individually for catching the Greater Siren from Aerial Fishing, I can't seem to catch 

any of them. The requirements are 91 Fishing and 87 Hunting according to the wiki, which my minion currently possesses.
![Screenshot_1](https://user-images.githubusercontent.com/78279827/106368403-8b8d7c80-6349-11eb-8c1d-76d82a6f467b.png)
![Screenshot_2](https://user-images.githubusercontent.com/78279827/106368425-a3650080-6349-11eb-9a3e-0a15d2e59a98.png)
![Screenshot_3](https://user-images.githubusercontent.com/78279827/106368634-68fc6300-634b-11eb-890c-c7787545edd0.png)

**Comment by TylGr** [comment]
COPIED FROM BUG REPORT I MADE:

Looks like some of the code may be broken, https://discord.com/channels/342983479501389826/668073484731154462/805181407914754048 this person has the required stats for greater sirens but didn't receive greater sirens as loot, it's possible that the roll requires the hunter and fishing level to be 1 more than what is intended (I may be reading the code wrong)

if (
currentRoll > 82 &&
currentFishLevel > greaterSiren.fishLvl! &&
currentHuntLevel > greaterSiren.level!
) {
greaterSirenCaught++;
continue;

**Comment by Lajnux** [comment]
#1275 will resolve this
