### ISSUE TITLE
Equipment Swapper

### ISSUE THREAD

**Issue by BugGamba** [oldschoolgg/oldschoolbot#1276]
## 🚀 Feature Proposal

Basically, have so you can create custom gear swaps. (Can’t think of the right word)

=add range 1 Armadyl Helmet, Armadyl Chainskirt.....etc 

=add range 2 crystal helm (perfected), crystal body (perfected)......etc

=equip range 1 (equips all slots added to range 1) 

Just to make it easier when swapping from cox to mally to nex etc etc, save having to type out massive paragraphs to gear swap.

**Comment by gc** [comment]
Gear presets are planned :)
