### ISSUE TITLE
Add --search to the text version of the bank

### ISSUE THREAD

**Issue by TimThaens** [oldschoolgg/oldschoolbot#1278]
## 🚀 Feature Proposal

+b --search=<search term> 
Works perfect. But it's sometimes unclear what every item is, for example searching for seeds.

+b --text 
Is a great solution, as it perfectly shows the names of all the items.

However, this text based version of the bank doesn't work with --search options.
It would be great if this can be added.

**Comment by TylGr** [comment]
You can also use +b —full —text which provided you with a notepad document of all your items + quantity. 

There is also —names which displays part of the item name in the bank image itself.

**Comment by gc** [comment]
Coded, will be released in next update.
