### ISSUE TITLE
Nex boosts only applying to the first kill

### ISSUE THREAD

**Issue by JerMous3** [oldschoolgg/oldschoolbot#1279]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

Short but fast, after hitting 200kc on Nex with a zaryte bow and some pernix pieces my =nex solo trips automatically go for 2 kill trips. And that's not the problem, but it seems the boosts only apply to the first kill you do and don't add to the 2nd kill, making the average time on 2 kill trips longer than a 1 kill trip with less boosts:
![image](https://user-images.githubusercontent.com/62512696/106382429-de098000-63bf-11eb-9328-a2dae0ad145a.png)

![image](https://user-images.githubusercontent.com/62512696/106382432-e19d0700-63bf-11eb-981c-cbbc35c90331.png)

To add a 'future proposal' with it, maybe make it possible to do =nex 1 solo.

**Comment by ArtMatters** [comment]
This happened too me yesterday as well. I had to remove Zak since it ended up wasting 5 minutes each time.

**Comment by mylife212** [comment]
Hoping this gets fixed soon. It actually punishes you for being a patron (since they're 'forced' to get 2+ kill trips) and those who aren't a patron will naturally place higher on the leaderboards due to faster kills/hr.
