### ISSUE TITLE
Can't use --full

### ISSUE THREAD

**Issue by iScruffy** [oldschoolgg/oldschoolbot#1281]
## 🐛 Bug Report

Any command that include --full i can't use

[19:41] iScruffy: =bank --full
[19:41]Bot School Old: An unexpected error occurred :RSSad:

**Comment by ArtMatters** [comment]
Are you able to check the last page of your bank? There are a few WTF items/beekeeper outfit pieces that can cause this. (Anything that tries to display them breaks)
