### ISSUE TITLE
Suggestion: Gathering/collecting ground items (Blue dragon scales)

### ISSUE THREAD

**Issue by Redquaker** [oldschoolgg/oldschoolbot#1292]
## 🚀 Feature Proposal

It would be nice to have a +gather command to collect items on the ground, particularly for obtaining herblore secondary ingredients, but could be applied to other items as well. Several of the items in question are already obtainable through other means, albeit at lower rates than in the accompanied OSRS wiki guides. This addition would be balanced since choosing to gather ingredients would sacrifice the additional loot received from bossing while increasing the output of the item you're seeking (plus it's realistic since it's possible in-game). For a sense of scale, I list some rates of obtaining the items through bossing (calculated with drop rates and average kills/hr).

Furthermore, blue dragon scales are currently unobtainable in OSB, and only obtainable through TMBs in BSO. The addition of blue dragon scales would also make superior dragon bones from Vorkath usable for herblore.

The main point of this suggestion is to add a method of obtaining blue dragon scales, but the addition of other gathering methods could also be worthwhile (particularly snape grass and mort myre fungus).

**Blue dragon scales**
There is currently no method of obtaining blue dragon scales. Wiki lists gathering at 550/hr.
https://oldschool.runescape.wiki/w/Money_making_guide/Collecting_blue_dragon_scales

**Snape grass**
Currently obtained from farming snape grass (or from Sara at a whopping ~12/hr). Wiki lists gathering at 912/hr.
https://oldschool.runescape.wiki/w/Money_making_guide/Collecting_snape_grass

**Mort myre fungus**
Currently ~48/hr from Vet'ion, wiki lists gathering at 1500/hr. This method could require certain POH structures to be built.
https://oldschool.runescape.wiki/w/Money_making_guide/Collecting_mort_myre_fungi

**Red spiders' eggs**
Currently ~161/hr at Venenatis and ~141/hr at Sarachnis, wiki lists gathering at 500/hr.
https://oldschool.runescape.wiki/w/Money_making_guide/Collecting_red_spiders%27_eggs

**Potato cactus**
Currently ~128/hr from Kalphite Queen, wiki lists gathering at 250/hr.
https://oldschool.runescape.wiki/w/Money_making_guide/Collecting_potato_cacti

**Wine of zamorak**
Currently ~96/hr from Kalphite Queen, ~20/hr from Zammy, ~18/hr from Cerberus, ~10/hr from Chaos Fanatic. Wiki lists gathering at 208/hr. This method could tie in nicely with the new magic skill, since it provides magic XP, requires 31 magic, and consumes law runes.
https://oldschool.runescape.wiki/w/Money_making_guide/Collecting_wine_of_zamorak

**Comment by HouseParan73** [comment]
Bump bump 73

**Comment by J4stMart** [comment]
Could we get this at least for mort myre fungus, before staminas are required for cox

**Comment by LuxrayElite** [comment]
As an IM I support this.

**Comment by jesseman1121** [comment]
I agree with the above. fungus would be nice to see before raids.

**Comment by Lajnux** [comment]
resolved
