### ISSUE TITLE
Daily question

### ISSUE THREAD

**Issue by skuxxmeth** [oldschoolgg/oldschoolbot#1300]
## 🐛 Bug Report

The following question requires an incorrect answer:

What item is used to fill a Druid Pouch?

I consulted with others and found the answer to be "Mort Myre Fungi", which isn't even a real item and should thus be removed.

However, there are multiple answers to the question which I shall list below.

Mort Myre Stem
More Myre Pear
More Myre Fungus

Therefore the daily question should also be changed to the following:

Name one of the items that can be used to fill a Druid Pouch.

**Comment by mylife212** [comment]
Good catch, updated the trivia doc renaming the question and added the answers you listed. Should be added whenever magna merges it

**Comment by Lajnux** [comment]
resolved
