### ISSUE TITLE
Lunar spells + Dragonstone jewellery

### ISSUE THREAD

**Issue by Lilbourne** [oldschoolgg/oldschoolbot#1303]
Was thinking about plank make, and tan leather. Others would probably work good as well.

Also, enchanting dragonstone jewellery does not give a charged version of the item, so making jewellery boxes above basic is still impossible.

Adding a way to charge them would obviously work, or simply giving the charges item upon enchanting.

**Comment by TizHub** [comment]
Support this, would be beneficial to have a few lunars spells. Could be locked behind stats requirements/qp requirement

Plank make - Nice alternative to making planks, although slower than sawmill
Tan leather - Slower but decent xp, would be beneficial for crafting training
String amulet - currently just stringing is slow xp, making glories etc. is a lot slower than other jewellery

**Comment by Tonks-Beep** [comment]
Per Tiz - 

Plank Make
Tan Leather
String Amulet. 
All have a perfect place in the bot for QoL and ease of magic training & I would love to see them implemented one day :D

On top of Tiz' suggestions, I would love to see -

Spin Flax - Flax is in abundance, there's no shortage at all. Currently, Fletching is limited to just cutting bows and not stringing them as obtaining bowstrings just isn't viable. This spell would not only fit nicely into the bot it would be a great help to Fletching & a nice bump to Crafting.

Recharge Dragonstone - An alternative to using Fountain Of Rune, maybe not as essential but in the theme of fleshing out the magic skill, this will certainly fit nicely into the bot. Could be tweaked/'boosted' slightly in the sense of allowing it to do Rings of Wealth? Not in line with actual OSRS but would be a decent-ish way to help bring jewelry boxes into the game as well and lock them behind a sort of skill wall as 89 mage is the level req for the spell. Just a suggestion though, has not a lot of thought behind it, could actually be a terrible idea.

**Comment by Lajnux** [comment]
resolved
