### ISSUE TITLE
BSO BUGGED ITEM

### ISSUE THREAD

**Issue by MrWestOSRS** [oldschoolgg/oldschoolbot#1304]
Not sure of the best way to explain this, but all of my search options/features with my bank are broken due to a bugged item. When i do =b --text and flip to the last page, there's "unknown item with ID 25040". It won't let me drop it either, so i'm unsure of what to do other than report the bug

Thanks!

![image](https://user-images.githubusercontent.com/78562471/106943474-7b7fef00-66f3-11eb-90b2-130464c57186.png)
![image](https://user-images.githubusercontent.com/78562471/106943746-d285c400-66f3-11eb-99b1-6ca2b7e057d9.png)

idk if that's supposed to link it or not, but that's a pic of it

**Comment by gc** [comment]
Fixed the 25040 one
