### ISSUE TITLE
Openables

### ISSUE THREAD

**Issue by JoshTheBaker** [oldschoolgg/oldschoolbot#1308]
A long long time ago, back in July of 2020, Fishy had started working on his PR for Openables that were requested.  These were the Grubby Chest/Sinister Chest and Ogre Coffins.  At this point in time with how the bot has progressed/what skills we have/boss requirements these would very much come in handy to be able to open as the Sinister key provides herbs guaranteed everytime, and the Grubby key provides Herbs/Runes/Potions/Food and other assorted items that are useful in skills.  I don’t speak for the community but I know a lot of people have been waiting quite a long time for these to be added and I know from the understanding of #developers channel it seemed for the most part Fishy was done.

As an addition to this I am also suggesting that the Elven Crystal Chest that is openable with Enhanced crystal keys be added as with zalcano killable we now have Crystal shards that are currently of no use and the Elven Crystal Chest provides quite a lot of items that would be beneficial value wise and skilling supply wise as well providing an item that allows us to change the form of our Tangleroots that being the Crystal Acorn.  
https://oldschool.runescape.wiki/w/Elven_Crystal_Chest
https://oldschool.runescape.wiki/w/Enhanced_crystal_key

**Comment by Ana-In-A-Barrel** [comment]
+1
