### ISSUE TITLE
Farming contracts

### ISSUE THREAD

**Issue by HouseParan73** [oldschoolgg/oldschoolbot#1310]
Currently when you do "fc easier" for an easier contract it automatically gives you an easy contract even if you previously had a hard contract. It would be a nice qol if it instead downgraded to a medium contract from a hard contract first if possible

**Comment by HouseParan73** [comment]
Bump

**Comment by HouseParan73** [comment]
Bump

**Comment by HouseParan73** [comment]
Bump

**Comment by osrsolympus** [comment]
Bump

**Comment by Lajnux** [comment]
resolved
