### ISSUE TITLE
Using ultracompost

### ISSUE THREAD

**Issue by Shadalah** [oldschoolgg/oldschoolbot#1313]
## 🐛 Bug Report
"+defaultfarming tier ultracompost" is the basic command, i manually writed it "+defaultfarming tier ultra compost" it kept using the ultracompost's from bank without giving the benefit because of that space between ultra_compost.
Everything i grew Herbs etc death rate was 60-80%

You can use the command 
"+defaultfarming tier ultracompost" and write the ul trac o mpost how ever you want and it will take em.

Benny asked to post this here.

![add1ce0d07074e09f4cdf769790dc6af](https://user-images.githubusercontent.com/78612237/107066209-5a4bfb00-67e6-11eb-84af-06e8905fbbb2.png)

**Comment by Lajnux** [comment]
resolved
