### ISSUE TITLE
Getting magic into OSB - the easy way!

### ISSUE THREAD

**Issue by Ana-In-A-Barrel** [oldschoolgg/oldschoolbot#1314]
I have an idea on how to easily get magic into osb, without the need for combat being released beforehand, or without the need for any hacky, unauthentic boosting/lamping type solutions, and I feel would also be very minimal coding..

With herblore being released, we were automatically given level 3 (as per the Druidic ritual quest reward) which allowed people to train herblore. I feel magic could be done in a similar way, through the imp catcher quest. We already have imps as a killable monster, so why not make use of it? If we were able to kill imps, to receive one of each type of bead then exchange through maybe something like +imp catcher command, we would be able to reach level 8 magic. I believe that bolt enchanting is already available at level 4, so all we would need is 1 command to be created for the imp catcher quest, rewarding us with the magic xp. 

I have already spoken with a mod about this idea, and had great feedback who fully supported the idea.. and I hope you will too!

**Comment by Oppheng** [comment]
This sounds, for me, like something that would be possible to work with and I think most people would appreciate some bigger updater for OSB. I'm not to active there anymore, other then sending my minion on trips.

**Comment by Lajnux** [comment]
resolved
