### ISSUE TITLE
Magic skill - starting out proposal

### ISSUE THREAD

**Issue by TwiceUponATaco** [oldschoolgg/oldschoolbot#1316]
I know there's some deliberation going on between the best ways to start out with magic from level 1. These are my thoughts for a way to handle it that is similar to in game.

In game the only way to start magic is to use the level 1 spell air strike in a combat scenario. 

I propose that air strike casting be added, BUT that it be restricted by level. As in you can only cast air strike until you hit the level for varrock teleport. Once you get the level for varrock teleport you can no longer cast air strike ever again (until combat is released).

To make things easy, we could just do xp rates of air strike as if you were splashing. 

Alternatively, we could assume a 50% hit rate and let you air strike creatures near lumbridge (cows or goblins which are already +kill able) and receive the drops. As we're inaccurate and using a low level spell the amount killed would be lower than just doing +m kill cow. The xp would then be a split between splashing and killing the monster of choice. 

To make it a fair start for everyone a staff of air should be added to +buy. Additionally mind rune packs could be made +buyable. The air staff should cost 10k and mind rune packs should cost 5k each. This would not be broken because you can only use these runes for a short time.

This would be more fair for everyone starting out than starting at level 4 for sapphire enchant because then everyone can start the skill at an early level, and not just those who were able to prepare enchanting supplies.

**Comment by osrsolympus** [comment]
Why let them use it until Varrock tele? You can feasibly do enchants from level 4

**Comment by TwiceUponATaco** [comment]
For an ironman or someone just starting out it's less feasible to start enchanting bolts right at level 4. 

Maybe varrock teleport is too far to let it go and something like level 7 for sapphire enchant. Or 15 for bones to bananas.
