### ISSUE TITLE
2x dragon claws drop on BSO COX raid, but never got them in bank.

### ISSUE THREAD

**Issue by unrealbigmac** [oldschoolgg/oldschoolbot#1323]
## 🐛 Bug Report
just finish a raid and got 2x dragon claws. never saw them in my bank ever, see screenshots. not sure what else i can do.
would be nice to get them since its my first big drop. or at least fix it so my next drop actually showup!

https://user-images.githubusercontent.com/78720782/107186061-95e6f080-69b1-11eb-8bda-f3f1eef212d4.PNG
https://user-images.githubusercontent.com/78720782/107186065-967f8700-69b1-11eb-840b-fd455ffc3946.PNG
https://user-images.githubusercontent.com/78720782/107186067-967f8700-69b1-11eb-862d-ab1e44e47a7e.PNG
https://user-images.githubusercontent.com/78720782/107186070-97181d80-69b1-11eb-84e6-4c38e490a9bb.PNG

Thanks, love the bot!

2x dragon claws drop on BSO COX raid, but never got them in bank.

**Comment by Lajnux** [comment]
resolved, if need refund contact mod or magnaboy
