### ISSUE TITLE
Smelting trip need over 8hours

### ISSUE THREAD

**Issue by BotBugReport** [oldschoolgg/oldschoolbot#1324]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

Hey,

Before i went to bed last day I've started a +smelt adamantite bar 
After I wake Up I wanted to do another one and my +smelt adamantite bar wasnt finished. It took 8:15 hours and I lost 18k Coal ore and around 3.5k adamantite ore.
![Screenshot_20210208-095121__01](https://user-images.githubusercontent.com/78725763/107197006-a4ee9280-69f3-11eb-8e70-549267419e97.jpg)

**Comment by Craftpure** [comment]
User claimed they lost 2445 adamantite ore, 14670 coal which I have refunded back to the user
