### ISSUE TITLE
Farming contract busted

### ISSUE THREAD

**Issue by tympani** [oldschoolgg/oldschoolbot#1326]
![FABD6023-9E35-40BE-B909-07A0049B963A](https://user-images.githubusercontent.com/74520248/107236379-47564800-69eb-11eb-9797-237d5d2dceba.png)

pretty much is how it looks. Can constantly do +fc medium to change the fc i’m on. No clue if they’ll stack if i keep doing +fc medium.
Just thought i’d share this

note: havent tested with easy or hard. Also havent tested it on bso. Thank you

**Comment by Lajnux** [comment]
resolved
