### ISSUE TITLE
Patreon perks keep reversing to t2

### ISSUE THREAD

**Issue by Kirbbby** [oldschoolgg/oldschoolbot#1327]
So I’ve had help a few times getting my perks back for patreon but just the last time I had it fixed, I happened to notice something. When the _=rp patreon/+rp patreon_ commands were ran a little after my fix, I lost my t3 again. 

For example: I ran my minion at 4:15ish which at the time my t3 was active after just being refreshed with _“=rp Kirby”_. Shortly before my minion returned from his trip, around 4:30 the _“=rp patreon”_ command was ran in attempts to fix someone else’s perks I presume. But when my minion returned at 4:50, I couldn’t send it back out on the same trip due to the trip being too long. 
I’ll post a few pics from yesterday I took to kind of help explain what I’m trying to say with the times.

Thank you all who’s helped me in the meantime! Appreciate every bit of it!🙂

![BEA01AEC-D6B4-42F2-83D7-994700981E76](https://user-images.githubusercontent.com/78751827/107259208-b8592800-6a0a-11eb-8772-71868d05e280.jpeg)
![CE46A81C-A35C-49B5-A267-8F9A4127717E](https://user-images.githubusercontent.com/78751827/107259209-b8f1be80-6a0a-11eb-84e5-6b2dd7319e8a.jpeg)

**Comment by gc** [comment]
This should be fixed - if you have any issues with your patreon perks in the future, you can DM on discord and I'll help.
