### ISSUE TITLE
DFS and DFW don't work as anti-dragon shield

### ISSUE THREAD

**Issue by TwiceUponATaco** [oldschoolgg/oldschoolbot#1328]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

Dragonfire Shield and Dragonfire Ward do not work as anti-dragon shield for purposes of killing blue dragons (presumably anything else that requires an anti-dragon shield as well).
![image](https://user-images.githubusercontent.com/41974029/107270887-1983fa00-6a11-11eb-9267-ceb1f8361045.png)
![image](https://user-images.githubusercontent.com/41974029/107270915-2274cb80-6a11-11eb-9d5b-a24544bdbfab.png)

**Comment by gc** [comment]
Should be fixed in next update. Added all the dragonfire protection shields to count as anti-dragon shield.
