### ISSUE TITLE
Allow players with 99 crafting to tan hides faster

### ISSUE THREAD

**Issue by TwiceUponATaco** [oldschoolgg/oldschoolbot#1329]
## 🚀 Feature Proposal

Describe the feature you're suggesting here, give lots of information and describe it as best you can. Please check that the feature hasn't already been suggested first, by searching the issues in this repository.

In game, when you have 99 crafting you have access to the bank chest downstairs in the crafting guild. There is a tanner upstairs in the crafting guild. It is possible to tan up to 9000 hides per hour using this tanner compared to the Al Kharid tanner when you bank at the bank chest with 99 crafting or the falador hard diary completed.

I propose that those with 99 crafting on their minions be able to tan hides at a faster rate because of this level of access.

**Comment by mylife212** [comment]
There is now a boost for tanning hides w/ 99 crafting
