### ISSUE TITLE
Nightmare Mass automatically starting with 4 members regardless of setting the max to 5

### ISSUE THREAD

**Issue by infinitefreshness** [oldschoolgg/oldschoolbot#1341]
## 🐛 Bug Report

After initiating a Nightmare mass using the command +nightmare mass 5 , the raid que will begin as expected, but automatically starts when a 4th member has joined. Earlier today, the join tally jumped from 3 to 5 for just a moment, but that last person was kicked as it still only allowed the first 4 participate in the mass. 

Another issue I noticed is that selecting the join reaction again to leave a nightmare mass que won't actually pull you out of the party. This makes it so the only way to leave a party is by sending your minion out on another task, causing the entire party to disband and forcing the others to re-que.

**Comment by nwjgit** [comment]
Outdated since nightmare mass is simulated now
