### ISSUE TITLE
Potential Issue with Karambwanji Clue/Pet Rate

### ISSUE THREAD

**Issue by miikaj1** [oldschoolgg/oldschoolbot#1345]
## 🐛 Bug Report

I believe that Karambwanji are rolling clue/pet too frequently (per karambwanji rather than per action); you tend to get several clues per 30 minute interval. Although the wiki doesn't make it 100% explicit, I imagine that the intent is not to give 20 rolls (at 99 fishing) for a clue/pet per action.

This can be changed by moving the updated quantity of karambwanji to after clues and pets have been rolled:
https://github.com/oldschoolgg/oldschoolbot/blob/bbfd69b5ffaa5c5f4105316d407f516ce4819dcd/src/tasks/minions/fishingActivity.ts#L100

**Comment by mylife212** [comment]
This issue has now been fixed, as the clue & pet rate have been removed from karambwanji

**Comment by mylife212** [comment]
i cant read lol, this has the solution to the bug that would be better than removing it the pet/clue rolls IMO. going to re-open
