### ISSUE TITLE
Visual Bug with money

### ISSUE THREAD

**Issue by Robson1212121223** [oldschoolgg/oldschoolbot#1350]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
I believe I was given GP around the same time I diced, which autochuck lost but the funds I had before I was given gp stayed in the bank visually, eachtime i get more GP it is added together but shows more money then I actually have
![Image1](https://user-images.githubusercontent.com/76664628/107824242-12464e80-6d79-11eb-810c-e0770370fac1.jpeg)
![image2](https://user-images.githubusercontent.com/76664628/107824246-12dee500-6d79-11eb-881a-5de710734650.jpg)
![image3](https://user-images.githubusercontent.com/76664628/107824247-13777b80-6d79-11eb-957f-02f44c4d180a.jpeg)
![image4](https://user-images.githubusercontent.com/76664628/107824321-2db15980-6d79-11eb-9f72-83bcace04872.jpeg)

**Comment by gc** [comment]
Fixed
