### ISSUE TITLE
Alching Confirmation

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#1355]
Could the alching process be streamlined at all?

This could be done by adding a default command to set a gp value, where it must then be confirmed if the value is higher

could also allow use of the '--cf' flag when typing 'press k to repeat this trip'
so in the below image my reply would be 'k --cf'

![image](https://user-images.githubusercontent.com/76587427/107851307-e8386f00-6e00-11eb-8f91-908468e5e6a4.png)

**Comment by Ktownstoner** [comment]
Completely agree would be great if this was implemented

**Comment by Lajnux** [comment]
resolved

**Comment by Lajnux** [comment]
not resolved, after further testing.
