### ISSUE TITLE
can't create an ava's assembler

### ISSUE THREAD

**Issue by AttackOfTheMoons** [oldschoolgg/oldschoolbot#1360]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
I killed 50 vorkath for the head. I killed kq for the mithril arrows. I created the ava's accumulator. I cannot make the ava's assembler.
My discord is toe#7659 id: 167511008674447360

:)

**Comment by osrsolympus** [comment]
Perhaps this has something to do with bank searches being case sensitive for some reason/not accepting upper case queries

**Comment by osrsolympus** [comment]
Thanks to some research by crow, it was determined that the drop was fixed to properly be the second item iteration of the Vorkath’s head, and it is also the one on the current +cL Vorkath. However, the +cL boss page displays the old head drop, the +create Ava’s device tries to use the old head drop, and people are getting both types in their bank as the old drops weren’t changed into the new, correct drop.

**Comment by gc** [comment]
Vorkaths head and assembler should be fixed now.
