### ISSUE TITLE
Armour sets count for gear requirements

### ISSUE THREAD

**Issue by notmeta** [oldschoolgg/oldschoolbot#1372]
## 🚀 Feature Proposal

Allow armour sets, i.e. barrows, to count as *having* the gear. Currently if you have an armour set, i.e. Dharok's, and want to do Giant mole it says you need the armour.

Allow sets to count for partial requirements too, i.e. allow Karil's armour set to count as having the crossbow for shamans.

This will help clear bank space.

**Comment by 6enny6** [comment]
your minion can’t wear a box, same as in osrs

**Comment by notmeta** [comment]
> your minion can’t wear a box, same as in osrs

But it could unpack the set, use the gear, and pack it back up upon returning :smile_cat:

**Comment by Lajnux** [comment]
a packed down armour set shouldn't give boosts similar to in game, even tho other single items work from bank.
