### ISSUE TITLE
Problems with fletching

### ISSUE THREAD

**Issue by Ktownstoner** [oldschoolgg/oldschoolbot#1373]
## 🐛 Bug Report

Whenever I got to send my minion back on a trip making diamond bolt tips its always says I don't have enough diamonds or tips to make them and you have to type command out again and y with patron perks doesnt work also

**Comment by Ktownstoner** [comment]
![Screenshot_20210215-055912_Discord.jpg](https://user-images.githubusercontent.com/62821846/107938525-88061200-6f53-11eb-92d5-07bffbbaeb8c.jpg)

**Comment by Ktownstoner** [comment]
Sorry for screen shot after wouldn't let me add it

**Comment by gc** [comment]
This should be fixed in the next update :)

**Comment by Ktownstoner** [comment]
Thank you!
