### ISSUE TITLE
Vorkath logs

### ISSUE THREAD

**Issue by Ktownstoner** [oldschoolgg/oldschoolbot#1374]
## 🐛 Bug Report

I dont know if any other logs are messed up but vorkath log isn't showing anyone having any vorkath's head even if you get the drop. So its shows your vorkath's head on +cl boss but it doesn't show them on +cl vorkath

**Comment by Ktownstoner** [comment]
![Screenshot_20210215-063815_Discord.jpg](https://user-images.githubusercontent.com/62821846/107941935-80953780-6f58-11eb-85e4-fb48ad64751a.jpg)

**Comment by mylife212** [comment]
Bug has been fixed
