### ISSUE TITLE
BSO Agility

### ISSUE THREAD

**Issue by Lilbourne** [oldschoolgg/oldschoolbot#1378]
So this one was interesting. In BSO levels can go up to 120, a great feature absolutely. Although with Agility, it can be quite detrimental the higher level you are, due to the rate of obtaining marks of grace becoming slowed, at increments of being 10 levels higher than the course requirement.

The rank 1 agility man Illusion, informed me he stopped doing agility because his rate of marks was so low, it wasn't worth it to him anymore. He is but a simple man, who provided thousands of free marks of grace for the people who needed a set of full graceful.

If it's possible to cap the mark loss at level 99, I'm sure it would make him, an extremely happy boy. I told him I'd make this apparent on GitHub and get some attention for him.
![SmartSelect_20210216-020025_Discord](https://user-images.githubusercontent.com/70830013/108029745-03bb9980-6ffc-11eb-9e46-6ca7b0971d76.jpg)

**Comment by nwjgit** [comment]
This was fixed.
