### ISSUE TITLE
Command to show cooldown of daily and other commands

### ISSUE THREAD

**Issue by BIRDIE13** [oldschoolgg/oldschoolbot#1379]
## 🚀 Feature Proposal

Create a command like =cd/cooldown/timers to show remaining time of different cooldowns.

Example:
Daily: 5 hours and 16 minutes
Spawnbox: Ready
Spawnlamp: 40 minutes
Givebox: 21 hours and 40 minutes

**Comment by gc** [comment]
Done in next update
