### ISSUE TITLE
Have #bso-notifications only show uniques from gm caskets

### ISSUE THREAD

**Issue by tympani** [oldschoolgg/oldschoolbot#1386]
Right now bso notifications shows each time a gm casket is opened. Its very spammy in the channel.

have it show only when a dwarven blessing is found.

thank you

**Comment by JerMous3** [comment]
And Clue Hunter pieces, since they’re an unique too there :)

**Comment by tympani** [comment]
Please do not include clue hunter pieces. They are not nearly as rare as 3rd age or gilded.
