### ISSUE TITLE
Daily/Trivia Issues

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#1388]
2 Trivia questions need changing.

"Which JMod is the current Head of ESports at Jagex?"
Mod Rogue is no longer the head of Esports at Jagex and the position hasn’t been filled by another mod, so remove this question.

“Which necklace/amulet has the highest strength bonus?”
Accept both Amulet of Strength and Torture as they have the same bonus, currently only Torture is accepted.

**Comment by thievious1** [comment]
Worth noting that the latter question is only an issue on BSO, trivia docs are up to date for OSB.

**Comment by gc** [comment]
Fixed after next bot reboot.
