### ISSUE TITLE
I cannot open my bank on BSO

### ISSUE THREAD

**Issue by Iown99fletch** [oldschoolgg/oldschoolbot#1395]
## 🐛 Bug Report
Write a description of the bug here, give all the information you can about what it is, how it happened.
I type =b and get an error message:
An unexpected error occurred 

My discord is Iown99fletch#7401

**Comment by KokjOSRS** [comment]
I have exactly the same problem!

Discord name: Kokj#0001

**Comment by dingle731** [comment]
i am also getting the same bug

discord name: dong731#9627

**Comment by Ktownstoner** [comment]
I swarley cannot open his bank either or use =open 
![Screenshot_20210220-115805_Discord.jpg](https://user-images.githubusercontent.com/62821846/108602946-00fdd300-7373-11eb-870c-e2576b7dd872.jpg)

**Comment by Big-Al51** [comment]
I'm also having this problem, all =bank commands bring up the error message, and so does =open

Discord name: Big_Al51#8939
![image](https://user-images.githubusercontent.com/79383101/108610013-1ce09380-73ca-11eb-95a9-6993b1a0f959.jpeg)

**Comment by xoMsKittyKatxo** [comment]
I have same issue xo_mskittykat_xo#3229
