### ISSUE TITLE
(BSO) CL Pets Display Error

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1396]
## 🐛 Bug Report

Some old bso pets from before the custom pets were added to the cL pets command never counted toward the log progression. In the image below, I had obtained Lil Lamb and Zippy before the log was updated, and the only reason zippy was logged is because of the hunter error earlier this year.
![2DA6C182-8C91-4448-A1C1-6BD68C646ABB](https://user-images.githubusercontent.com/65320787/108533447-fc6be880-72a6-11eb-88f2-61f9841a0f50.png)

**Comment by gc** [comment]
Closing as an old issue, if this is still an issue, feel free to re-open.
