### ISSUE TITLE
Mage Training Arena

### ISSUE THREAD

**Issue by lyanrewis** [oldschoolgg/oldschoolbot#1406]
With Magic now released, Mage Training Arena would be possibly another good training method that isn't combat related. 
As it's 4 rooms, you could just take an average points gained/hr and runes spent/hr with the normal % variance? 
Can bring into OSB infinity, master wand etc (Bones to peaches to possibly make tabs for pvm boosts/another magic spell?) but mainly the infinity boots to create eternals - thanks to a recent update.

*Edit - haven't seen another suggestion with this but might of missed one, sorry if i have!

**Comment by mylife212** [comment]
MTA is now in the bot
