### ISSUE TITLE
Bones to Bananas

### ISSUE THREAD

**Issue by sn0w1753** [oldschoolgg/oldschoolbot#1413]
Currently, the bones to bananas spell is one of the few early methods for magic training that can be viable with few other requirements; however the spell requires specifically 25 Regular bones in addition to the corresponding runes to cast the spell.  

My current issue with this requirement of *only* Regular bones is that it seems to be out of place with main game magic mechanics; the same spell can be cast to turn an inventory of both regular bones *and* Big Bones alike into the same amount of bananas as there were bones in your inventory.

I typically wouldn’t find this as a game-breaking difference between the bot and main game, but there are times where it is more feasible to acquire Big Bones than it is regular bones.  I have taken the time to ensure that the spell will not work on Big Bones as well looked through the archive to see if there had been a suggestion for this alteration to be considered. Even though I’ve spoken with many other players that were under the same impression that B2b only works on normal bones in main game and informed them of the variation in the bot scripting, it has yet to appear as a suggestion.  I’m unfamiliar with the bot’s coding at the moment, but can’t imagine that it would terribly difficult for the script to factor in Big Bones *or* normal bones into the casting requirement for magic training at the moment.  

I will link the OSRS wiki article (which hasn’t been updated in over 3 months) that explains bones to bananas as verification that in the main game, Big Bones is also a valid alternative to regular bones for the spell. 

https://oldschool.runescape.wiki/w/Bones_to_Bananas

If unsure of the link, I will also attach screenshots of the wiki article as well. 

![0EFC63A7-B48E-4DDD-8606-BAF2B4210552](https://user-images.githubusercontent.com/78341255/108682955-96ee4680-74b6-11eb-8170-1f99ff95d7e7.jpeg)
![843A62FC-D3B1-47DC-B902-76E7824EBA41](https://user-images.githubusercontent.com/78341255/108682957-9786dd00-74b6-11eb-8e9b-7b66984ab6d0.jpeg)

Thank you!

**Comment by Lajnux** [comment]
resolved with combat update +train magic
