### ISSUE TITLE
Herblore xp bug with --zahur

### ISSUE THREAD

**Issue by zabiros** [oldschoolgg/oldschoolbot#1415]
## 🐛 Bug Report

when you mix a potion with --zahur, you get 0 xp; even though it's not faster or anything. 

<img width="755" alt="Screenshot 2021-02-22 at 12 52 15" src="https://user-images.githubusercontent.com/79454174/108704820-d051a100-750c-11eb-8469-a66444bc04dd.png">

as you can see, when I created a super restore normally, I got 142.5 xp; but when I put --zahur behind it, I got 0 xp. 
I know this isn't a big bug, but I've already wasted like 1 or 2 trips with this xD.

**Comment by 6enny6** [comment]
its intended, you’re paying him to do it for you

**Comment by Alexsuperfly** [comment]
no, this issue is valid.

**Comment by zabiros** [comment]
I don't think this is intended. 
As you can see in the following picture, I did not pay zahur at all nor did it take 1 second; I had to wait the full amount of time.

<img width="728" alt="Screenshot 2021-02-22 at 15 33 50" src="https://user-images.githubusercontent.com/79454174/108722377-61cc0d80-7523-11eb-9418-d7c58ce34020.png">

**Comment by Craftpure** [comment]
Sir. Zahur can only clean herbs and make unf pots. It can't make completed pots so the --zahur flag did not work and ran a normal trip

**Comment by osrsolympus** [comment]
Bump
