### ISSUE TITLE
=fav broken on BSO

### ISSUE THREAD

**Issue by ArtMatters** [oldschoolgg/oldschoolbot#1420]
My fav'd items still show up on BSO but using the =fav command error's & it say's I'm at the favorite limit if I try to add another. My OSB does not have this issue. 

ArtMatters#3174

**Comment by 6enny6** [comment]
user has been informed of the fix, issue can be closed

![](https://images-ext-2.discordapp.net/external/5xHOLDymLUC4sIOKUI_yC3Jtnzp_NYT00bQ6pjshOWw/https/media.discordapp.net/attachments/342983479501389826/813513865052291092/unknown.png)

**Comment by gc** [comment]
Should be fixed now.
