### ISSUE TITLE
Bug: Random shaman loot when doing stuff

### ISSUE THREAD

**Issue by HenningLakiere** [oldschoolgg/oldschoolbot#1421]
![Screenshot_2021-02-24-09-41-20-117_com discord](https://user-images.githubusercontent.com/9211934/108980565-15e8a800-768c-11eb-9ac9-b11305c272aa.jpg)
Getting random shaman loot from bso bot.
I only do shaman trips on osb but it seems the bso bot is bugged

**Comment by HenningLakiere** [comment]
![IMG_20210224_102744](https://user-images.githubusercontent.com/9211934/108980839-68c25f80-768c-11eb-81ec-3ac26fb8e600.jpg)

**Comment by HenningLakiere** [comment]
![Screenshot_2021-02-24-10-42-01-016_com discord](https://user-images.githubusercontent.com/9211934/108981643-35340500-768d-11eb-8054-e063b0027392.jpg)
First screenshot got updated randomly

Second screenshot now has the correct loot
(The loot shown in the bottom message of this screenshot)

**Comment by darklinkarisen** [comment]
I'm having this same issue with both bots as well but with very different images. I've seen vorkath loot, zulrah loot, random player's banks, and a few others. Never experienced this on pc and I'm not sure what causes it.
![Screenshot_20210226-064844_Discord](https://user-images.githubusercontent.com/79700071/109297404-f07cab00-77ff-11eb-81d5-82319c6a01fc.jpg)
![Screenshot_20210226-064958_Discord](https://user-images.githubusercontent.com/79700071/109297416-f6728c00-77ff-11eb-90a6-16f6e8b9d82c.jpg)

**Comment by gc** [comment]
Fixed by now.
