### ISSUE TITLE
Spawnboxs

### ISSUE THREAD

**Issue by Osmosisx** [oldschoolgg/oldschoolbot#1422]
## 🐛 Bug Report

Spawnboxs should not matter whether or not the first letter is capitalized. 
![D9529DA0-8E8E-4879-BDDA-F14ABCF93987](https://user-images.githubusercontent.com/68478237/109029012-69f58b80-7690-11eb-95fa-55018e414d22.jpeg)
Also this isn’t a pid thing and happens to a lot of people

**Comment by Osmosisx** [comment]
![7EBB1504-EEFD-4CCA-8E92-1861473BCBA2](https://user-images.githubusercontent.com/68478237/109029709-19caf900-7691-11eb-8c8c-e02d53890c45.jpeg)

**Comment by Alexsuperfly** [comment]
![image](https://user-images.githubusercontent.com/7191512/109057640-fbc0c100-76af-11eb-86da-e7061e933e5e.png)
this shows it working correctly
