### ISSUE TITLE
Let the graceful outfit effect work when equiped in "misc" while doing clues

### ISSUE THREAD

**Issue by cyclopath83** [oldschoolgg/oldschoolbot#1426]
## 🚀 Feature Proposal
For example, when mining or woodcutting, you have your mining/woodcutting gear on.
When you receive a clue, you need to put on your graceful, do the clue, put on your skilling gear.
It would make more sense that clue hunting is "misc" instead of "skilling"

**Comment by JerMous3** [comment]
For this 'issue' we now have the ability to make gearpresets so you can easily swap between different skilling setups.

**Comment by cyclopath83** [comment]
Yes, and I'm using it. But you still have to swap between graceful and your skilling gear.
