### ISSUE TITLE
Press Y to repeat trip BSO

### ISSUE THREAD

**Issue by Lilbourne** [oldschoolgg/oldschoolbot#1432]
Since the update, I've tried entering y to do another trip of the Monkey Hunt event, and does not seem to work.
![SmartSelect_20210226-131232_Discord](https://user-images.githubusercontent.com/70830013/109338594-761a4e00-7834-11eb-8c75-1c211b027385.jpg)

**Comment by 6enny6** [comment]
Seems to also be broken for the birthday event, aerial fishing, and any thieving activity

**Comment by Lilbourne** [comment]
Seems to be the same for non-patrons.

**Comment by gc** [comment]
Should be fixed now
