### ISSUE TITLE
wilvus 100% drop rate

### ISSUE THREAD

**Issue by Krendrian** [oldschoolgg/oldschoolbot#1433]
## 🐛 Bug Report
ReZero discovered wilvus is a guaranteed drop from 1x male ham member https://discord.com/channels/342983479501389826/732207379818479756/814980556268765225

**Comment by ReZeroed** [comment]
to further add to this, I was testing to see if pickpocketing was only not working for vyres, so I had started from the top of the list, after getting the one from hams thinking it was just dumb luck I continued on and got this result. 
![image](https://user-images.githubusercontent.com/75293942/109360879-d371d600-78ec-11eb-9bef-1c19cf4aaa2f.png)

**Comment by osrsolympus** [comment]
This also applies to Peky from wc

**Comment by gc** [comment]
Should be fixed now
