### ISSUE TITLE
Runecrafting - No Loot

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#1434]
When running short trips of fire runes, you don’t receive a return message nor get any loot as shown in the screenshots.
tested with a trip of 1 rune, and a trip of 29 runes

fire rune stack before:
![image](https://user-images.githubusercontent.com/76587427/109366466-69751480-788b-11eb-805e-1b6d06764a14.png)

the trip with no return message: 
![image](https://user-images.githubusercontent.com/76587427/109366505-7d207b00-788b-11eb-82d8-7cdb91fa32ad.png)

fire rune stack after:
![image](https://user-images.githubusercontent.com/76587427/109366521-8873a680-788b-11eb-9902-1a7c0b174995.png)

**Comment by ReZeroed** [comment]
not just fire runes, air runes are also affected 
![image](https://user-images.githubusercontent.com/75293942/109367167-34ec7180-78fa-11eb-9597-a36ca7077570.png)

**Comment by Lajnux** [comment]
resolved
