### ISSUE TITLE
Super Combats 

### ISSUE THREAD

**Issue by ahmalla** [oldschoolgg/oldschoolbot#1437]
Unable to mix super combat potions even though all ingredients  are available 

 
![B79BC4AA-7F38-4A7D-A9FE-2706F72B8D46](https://user-images.githubusercontent.com/68600561/109373559-5b5fcd80-7864-11eb-8300-672f988d277d.png)

**Comment by ahmalla** [comment]
![Uploading D80AD357-BA79-40B5-A781-25089FF838D4.jpeg…]()

**Comment by osrsolympus** [comment]
Dupe of #1160
