### ISSUE TITLE
KC's not being added/updated

### ISSUE THREAD

**Issue by Craftpure** [oldschoolgg/oldschoolbot#1441]
moncke reported in Help and Support that their KC keeps resetting after ever trip
I tested and can confirm it effected my Lizardman trip too

WildChickenz also confirmed this is effecting Mally
Knock reported the same for Corp

Does not seem to be effected my OSB Vorki KC
 Screenshots all attached
![Moncke 1](https://user-images.githubusercontent.com/68561490/109403304-4f533900-7954-11eb-996a-0bbf609bd5fc.jpg)
![Moncke 2](https://user-images.githubusercontent.com/68561490/109403306-4febcf80-7954-11eb-985c-9c4b391a07ce.jpg)
![Craftpure 1](https://user-images.githubusercontent.com/68561490/109403308-537f5680-7954-11eb-8099-0bcdb48f1a8a.jpg)
![Craftpure 2](https://user-images.githubusercontent.com/68561490/109403310-54b08380-7954-11eb-9f05-1ebe55e31d9f.jpg)
![WildChickenz](https://user-images.githubusercontent.com/68561490/109403311-5712dd80-7954-11eb-834d-103eeaae220e.png)
![Knock 1](https://user-images.githubusercontent.com/68561490/109403312-5aa66480-7954-11eb-9377-e0bbca7c8159.jpg)
![Knock 2](https://user-images.githubusercontent.com/68561490/109403313-5aa66480-7954-11eb-9828-0470ba3bfced.jpg)

**Comment by gc** [comment]
Should be fixed now
