### ISSUE TITLE
Wilvus giving loot on PVM trips

### ISSUE THREAD

**Issue by Craftpure** [oldschoolgg/oldschoolbot#1442]
Wilvus is giving loot on PVM trips please see attached. 
![Capture](https://user-images.githubusercontent.com/68561490/109403431-89710a80-7955-11eb-9a54-f688304bb1a9.JPG)

**Comment by gc** [comment]
Nice - this is good, only reason they didn't before is because pvm used different code, but now shares the same code, wasn't intentional
