### ISSUE TITLE
Soul Wars Zeal Check

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#1445]
Add a way of checking how much zeal you currently have

either a new command such as `+sw zeal`, add it to `+cl sw` or add it onto `+sw buy`
also a confirmation would be nice for purchases

currently the only way to check is by trying to buy/imbue an item, if you have under the required amount, it tells you how many you have. If you have over the required amount it auto buys with no confirmation so no way to check

**Comment by osrsolympus** [comment]
Bump

**Comment by 6enny6** [comment]
bump
