### ISSUE TITLE
Sarachnis KC

### ISSUE THREAD

**Issue by ferderb** [oldschoolgg/oldschoolbot#1448]
## 🐛 Bug Report

Hello, this is more of a personal bug, but I'm guessing others have encountered it. I'm currently going for #1 kc sarachnis, and it appears my kc hasn't gone up for the past 29 trips, though I've received drops and it's used food. Discord is Fode1216#4046 if you need more info, screenshots, etc ♡

Thank you, 

Fode1216

**Comment by Alexsuperfly** [comment]
duplicate of #1441
