### ISSUE TITLE
additional server roles 

### ISSUE THREAD

**Issue by chefslav** [oldschoolgg/oldschoolbot#1450]
## 🚀 Feature Proposal

Currently there are 3 main achievement roles in the server (Skiller/Sacrificer/Collector) 

I'd like to propose two additional roles

-Top PvMer (#1 in any Boss KC (so not including men/goblins etc.)
-Top Minigames(#1 for minigame activities? Give those BA folks a shoutout) (#1 gamer hampog) 

also idk if its tracked but a Bankrupt role for 3 users that have lost more to dicing than gained 

thanks for coming to my tedtalk

**Comment by osrsolympus** [comment]
Could use the :slayer: icon for pvm, the :minigames: icon for minigames, and the :bloodmoney: icon if you were to make them role badges as well as server roles.
