### ISSUE TITLE
soul wars multiple trips

### ISSUE THREAD

**Issue by steezoo** [oldschoolgg/oldschoolbot#1452]
## 🐛 Bug Report

I'm pretty sure this bug is well known but was asked to report mine. Have been doing soul wars group trips in our discord, clicked to join a mass then remembered I had to do farm runs so clicked to unjoin then did farm runs. After the farm runs I started a solo soul wars. Mid way through that trip, my minion comes back from both the original soul wars mass and the solo trip. I was aware it was buggy on release but didn't try to abuse it here. Can provide pics of the trips if necessary. Happened around 10:40pm EST March 1st on steezoo#2012.

**Comment by gc** [comment]
Should be fixed now.
