### ISSUE TITLE
=spawnbox in other channels

### ISSUE THREAD

**Issue by ArtMatters** [oldschoolgg/oldschoolbot#1459]
If you use =spawnbox in any channel except bot-channel-bso, it tells you you can't do that, but it puts it on cooldown still.

**Comment by nwjgit** [comment]
`/tools patron spawnlamp` and `/tools patron spawnbox` can be done in any channel, in the oldschoolgg discord, that allows for BSO commands. The cooldown bug was fixed aswell.
