### ISSUE TITLE
BSO - Masses getting 'say C to complete clue' post trips. 

### ISSUE THREAD

**Issue by chefslav** [oldschoolgg/oldschoolbot#1460]
## 🐛 Bug Report

the message to do a clue after finishing a trip is popping up for masses (bso, goldemar) 

![image](https://user-images.githubusercontent.com/72408891/109749964-34c1cf80-7ba1-11eb-94a2-a966117cd297.png)

host doesn't need to get the drop for it to show up either, anyone in mass getting a clue counts

![image](https://user-images.githubusercontent.com/72408891/109750055-5e7af680-7ba1-11eb-8e85-721d8c4a0cc3.png)

**Comment by nwjgit** [comment]
This has been corrected.
