### ISSUE TITLE
Wilvus trips halved

### ISSUE THREAD

**Issue by sarawrxd** [oldschoolgg/oldschoolbot#1463]
## 🐛 Bug Report

Pickpocket trips with Wilvus cap at 20m with T3 patron trips for master farmers

**Comment by ReZeroed** [comment]
normal trips are 40 mins without wilvus and t3, but since wilvus makes thieving twice as fast the trip time goes down to 20 mins

**Comment by sarawrxd** [comment]
I had assumed it was unintentional, as other item boosts typically don't shorten trip length, rather increase the number of actions per trip. Ex: DWWH/Blessing Dwh etc.

**Comment by gc** [comment]
Fixed now I believe.
