### ISSUE TITLE
[OSB] Trip return messages are different for skilling

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1470]
## 🐛 Bug Report

When the bot returns a skilling trip, it returns as "Old School Bot" as a white name which 

can be clicked on for no options. In PVM Trips, it comes back as the normal bot with whatever server roles/names it has. This could be on Discords end though.

These images show the bug in action
1st image - The white name for return trip is odd, as you can see the bot is 'properly' working in the trip I sent out. (Compare the two names)
2nd image - When you click on the bots name it brings up this option
![BotBug](https://user-images.githubusercontent.com/63373565/109859268-c0337300-7c2a-11eb-9ae9-048180c13751.png)
![botbug2](https://user-images.githubusercontent.com/63373565/109859338-d6d9ca00-7c2a-11eb-9ec7-091609831f86.png)

**Comment by mylife212** [comment]
Update: Its not skilling trips that are bugged. Looks like its user dependent? Noticed another with same bug. Once again, could be discords end but keeping this up just in case.
![botbug3](https://user-images.githubusercontent.com/63373565/109971220-fb35b500-7cc3-11eb-9231-eb862c7e1986.png)

**Comment by mylife212** [comment]
actually, its working fine in another server lol. this is a horribly worded issue anyways and chances are that its not related to the bots code.

**Comment by ArtMatters** [comment]
make sure the sever the issue is in has the bot able to post embed images
