### ISSUE TITLE
Plopper not giving x4?

### ISSUE THREAD

**Issue by bigsquid69** [oldschoolgg/oldschoolbot#1475]
Plopper isn't showing a message when he triggers and I got 81 herbs from 9 patches 0 dead. Doesn't appear to be x4. Thanks

**Comment by ArtMatters** [comment]
is plopper equipped, did you apply any compost, what is ur lv, what herb did u plant? try to give a bit of detail to help out a bit :)

**Comment by JerMous3** [comment]
I answered this in his pm (: 

It's because Plopper doesnt have a x4 return message, it looks like u 'only' got 81 herbs

**Comment by ArtMatters** [comment]
Sounds like the previous run didnt plant a full trip then. if it was only 81 after 4x

**Comment by bigsquid69** [comment]
![2BE2456E-3001-42DE-8996-43A88820962D](https://user-images.githubusercontent.com/80061861/110008654-9426f900-7ce1-11eb-878b-dd6f00cd6ee3.jpeg)
![6CCB5548-AB49-44CC-BDD6-E6EBE90148BA](https://user-images.githubusercontent.com/80061861/110008662-95f0bc80-7ce1-11eb-9854-1e83b9e1b100.jpeg)

Looks like jer is correct. Sorry for this time waste 😔

**Comment by gc** [comment]
Plopper will now show a message when you get the 4x loot (coded, not released at this moment)
