### ISSUE TITLE
=b 'name' command not showing the right item

### ISSUE THREAD

**Issue by JerMous3** [oldschoolgg/oldschoolbot#1478]
## 🐛 Bug Report

Reporting this for Avaricebrah (aka RojTheGod)#6152, when checking for any random item in his bank. He got a sanguinesti staff as a result.

![image](https://user-images.githubusercontent.com/62512696/110113878-08ca6800-7db4-11eb-8f2f-8280ffff8076.png)

**Comment by JerMous3** [comment]
![image](https://user-images.githubusercontent.com/62512696/110117717-8e044b80-7db9-11eb-9620-6848c6aef376.png)

Seems to happen to more items (:

**Comment by JerMous3** [comment]
![image](https://user-images.githubusercontent.com/62512696/110117934-e1769980-7db9-11eb-9d9c-49ceb052d22e.png)

It's not item related, seems to be bank related

**Comment by 6enny6** [comment]
NotOwain also had this issue when opening UMBs, opened 6x 2 umb and got the same image every time, although he didnt actually receive these items.

![image](https://user-images.githubusercontent.com/76587427/110124602-31edf700-7dba-11eb-89be-5e83942ab692.png)

**Comment by gc** [comment]
These are visual bugs with the recent update, I'll fix. Anything similar will most likely be fixed too so don't worry about reporting more on it

**Comment by gc** [comment]
Fixed
