### ISSUE TITLE
Bso =b (item name) & umb incorrect display/roll

### ISSUE THREAD

**Issue by AvariceBrah** [oldschoolgg/oldschoolbot#1479]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

Currently if I use =b book of knowledge and a few other random (seemingly) items, i get displayed a single staff.

Also someone got the same roll on 2 umb 5x in a row, something's definitely broke it seems. The only thing I am aware of doing different prior to becoming aware of it was clear my favs. 

(Another player has an issue with something not requested being displaye despits =b (item name) being correctly issued)

![Screenshot_20210305-074713](https://user-images.githubusercontent.com/77698878/110124577-e28ed300-7d87-11eb-85af-1ba05d44b219.png)

![Screenshot_20210305-074709](https://user-images.githubusercontent.com/77698878/110124651-f76b6680-7d87-11eb-92f7-b368f3bd1da5.png)

**Comment by 6enny6** [comment]
![image](https://user-images.githubusercontent.com/76587427/110125894-bee58000-7dbb-11eb-9b0d-dfdca2cd0089.png)
