### ISSUE TITLE
Transparent BG

### ISSUE THREAD

**Issue by ahmalla** [oldschoolgg/oldschoolbot#1481]
The transparent BG’s transparency seems to have been transferred to the border. Or the border has just gone missing idk 🤪
gear background unaffected. 
![77B77CBF-7B03-4248-A140-AC3CDCF83B70](https://user-images.githubusercontent.com/68600561/110130554-fe8d7700-7d7d-11eb-8205-b5652d17eb71.jpeg)
![857BBA95-DEA6-4690-AE86-FAEB1ACF7BF0](https://user-images.githubusercontent.com/68600561/110130558-ffbea400-7d7d-11eb-87c5-6aa9e8f7c0e1.jpeg)
![CD51EFDE-23D0-4604-B944-EDA2C0A376EA](https://user-images.githubusercontent.com/68600561/110130562-00573a80-7d7e-11eb-8329-0947ce068c0b.jpeg)

**Comment by ahmalla** [comment]
:'(

**Comment by gc** [comment]
Fixed in next update
