### ISSUE TITLE
Clue glitches 

### ISSUE THREAD

**Issue by ahmalla** [oldschoolgg/oldschoolbot#1482]
As you can see in the photos below the —tt flag is showing I have 14 elite caskets. 

The =open command says I only have 4. 

![5899FEFD-311B-476A-8890-F6A9F23F72C6](https://user-images.githubusercontent.com/68600561/110137252-7ca14c00-7d85-11eb-85ee-e854d7c4d171.jpeg)

**Comment by ahmalla** [comment]
Also just noticed —tt says I have 24 masters and open says 33

**Comment by gc** [comment]
Fixed
