### ISSUE TITLE
[BSO] Bank image bug not fully fixed(?)

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1489]
## 🐛 Bug Report

Can see my bank image and the bank text under it. I have 44 hard clues in the bank image but 37 hard clues (accurate #) in the text.
![bug](https://user-images.githubusercontent.com/63373565/110197114-49a79880-7e17-11eb-80c7-7984daa7bdd6.png)

**Comment by gc** [comment]
Should be fixed now
