### ISSUE TITLE
Crops Dying with Plopper

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#1491]
Plopper no longer protects crops from death

![image](https://user-images.githubusercontent.com/76587427/110204923-8f8f4b80-7e6d-11eb-8676-8288f9229597.png)

![image](https://user-images.githubusercontent.com/76587427/110204930-9ddd6780-7e6d-11eb-89f5-1bee73743c17.png)

**Comment by gc** [comment]
Fixed in next update
