### ISSUE TITLE
BSO/OSB Trivia Docs

### ISSUE THREAD

**Issue by thievious1** [oldschoolgg/oldschoolbot#1492]
It was brought to my attention recently that the daily/trivia question of "Arrav, famous owner of the Shield of Arrav, has a statue of himself in which building?" cannot be answered by anything other than "heroes' guild" in OSB. In BSO you can answer the question with "heros guild" and a couple of other variations. I have tried checking through the trivia docs and it only lists "heroes' guild" as an acceptable answer but can be seen here where it accepts others.
![kirby](https://user-images.githubusercontent.com/65054062/110222844-f414cf80-7e9a-11eb-97f3-be9b4b05b83a.jpg)
![heroesguild0](https://user-images.githubusercontent.com/65054062/110222896-5b328400-7e9b-11eb-892a-7afef17b3cf1.png)

**Comment by osrsolympus** [comment]
Attempted a fix we’ll see if it works
