### ISSUE TITLE
BSO Raid Boss

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1493]
## 🚀 Feature Proposal

Add a bso-wide raid boss. 

No requirements, everyone can send their minion out to kill it. No loot for individual trips. Could use kc as a virtual hp and after every so many kc (doesn’t matter how many tbh) it rolls loot for everyone with kc, with op drops guaranteed for top 3 kc, and scaling downward for all others. Perhaps more guaranteed milestones for top 10 of less op drops, or perhaps no guaranteed drops at all, but generally better drops for higher kc. 

This will incentivize people to spend large amounts of time (if the hp is high enough) doing a bso activity with no reward for a chance at a bigger reward, but if they don’t roll a rare drop, they’ll end up earning less than how much they could have made farming mally or nex or something like that.

**Comment by gc** [comment]
A BSO raid boss is a potential good idea. Should go in #bso-vote
