### ISSUE TITLE
Zippy loot doubling 

### ISSUE THREAD

**Issue by 2Kurrupted** [oldschoolgg/oldschoolbot#1495]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

BSO: I had 0 GM caskets banked, and was doing 4 GM clues with zippy equipped, after returning it said he had doubled my loot (woohoo) however i then had 16 GM caskets. I've opened 8, and left the other 8 as technically they aren't mine? I think? 
![Screenshot_20210307-192054_Discord](https://user-images.githubusercontent.com/79731323/110231173-d28b1500-7f7a-11eb-9499-e258e9288d11.jpg)
![Screenshot_20210307-192102_Discord](https://user-images.githubusercontent.com/79731323/110231177-dae35000-7f7a-11eb-9bc9-573f132b9daa.jpg)

Let me know what to do with the extra GM caskets if that's the case, thanks

**Comment by shelixd** [comment]
This is because there is a flat global chance of getting a box that will double all your trips loot. It doesnt show up when doing clues, but you got one.

**Comment by 2Kurrupted** [comment]
Ah thanks very much, lucky me. Cheers for clearing that up
