### ISSUE TITLE
OSB-tmk4201

### ISSUE THREAD

**Issue by tmk4201** [oldschoolgg/oldschoolbot#1497]
## 🐛 Bug Report
https://gyazo.com/5540f33fc5490517146aba9393822a18
^ link to bot unresponsive to my commands only =b works in every channel for me 
out of the 3 channels i use for it it usually works in 1 of them at a time unsure where this bug would lie as im not a programmer
but hopefully it helps !~ 
Write a description of the bug here, give all the information you can about what it is, how it happened.

**Comment by Lajnux** [comment]
resolved
