### ISSUE TITLE
Upgraded Dwarven Blessing

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1498]
## 🚀 Feature Proposal

Like the Rada's blessing has 4 different levels with improving perks for each diary tier you complete, let us upgrade the Dwarven Blessing to provide increasingly good perks while consuming gp and items.

For example:

Blessing (1) - Default drop from GM clues, ppot consumption for PvM Boost

Blessing (2) - Upgraded from Blessing (1) using 100x of each of the clue blessings + 2 Dwarven Blessings + 500m gp, gives Blessing (1) boost and has a chance to multiply the number of bones dropped in PvM by 2x

Blessing (3) - Upgraded from Blessing (2) using 20x Dwarven bars + 3 Dwarven Blessings + 1b gp, gives Blessing (1) and (2) boosts and has upgraded defensive and prayer bonuses

Blessing (4) - Upgraded from Blessing (3) using 250 TMBs and 100 UMBs + 5 Dwarven Blessings + 5b gp, Gives Blessing (1) and (2) and (3) boosts and gives a slight modifier to the odds of rolling a box on a trip.

**Comment by nwjgit** [comment]
Suggestion moved to discord: https://discord.com/channels/342983479501389826/1032668754561224734/1197654919730172056
