### ISSUE TITLE
Make BA Mass Optional

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1501]
## 🚀 Feature Proposal

BA is a mostly dead minigame, with 2 games having been done in the OSB server in the past week, both of which were in bso to see Flappy's 2x effect. The last OSB game in the main server was about 10 days ago, with multiple people having tried to start games but having failed due to lack of interested. The BA discord server hasn't seen a game in an even longer time. By making it single player optional, it could revive the game or at least let people play without spending endless time fruitlessly searching for a partner.

**Comment by gc** [comment]
Will make BA solo-able.
