### ISSUE TITLE
Wildy hunter consumption rebalancing

### ISSUE THREAD

**Issue by HouseParan73** [oldschoolgg/oldschoolbot#1503]
## 🐛 Bug Report

     Currently hunter in the wildy (black chins/sallies) have a very high consumption rate relative to in game. Before peak times were coded the avg consumption of pots led to around 4k brews for 200m hunter (meaning 1 brew every 50k hunter exp approximately lol). It would be nice to rebalance this to closer reflect in game usage. 
     Even 1k brews would be an extremely high rate given that it would mean a brew basically every hour but it would perhaps be a middle ground that could be agreed upon. Especially since as more things require food, it would be nice to not have to use a relatively absurd amount of brews and super restores that could be better saved for pvm down the road.

**Comment by LuxrayElite** [comment]
Wildy hunter hasnt been touched and a rebalance seems valid from their suggestions
