### ISSUE TITLE
Dwarven pickaxe missing boost indicator on trips

### ISSUE THREAD

**Issue by gramkuma** [oldschoolgg/oldschoolbot#1504]
## 🐛 Bug Report

After equipping the pickaxe and starting  a trip, there is no text indicator mentioning that you are mining double what you would be normally.

![image](https://user-images.githubusercontent.com/11981967/110285967-5657f800-7fa1-11eb-8649-16ec96103d5e.png)

**Comment by gc** [comment]
Fixed in next update
