### ISSUE TITLE
UMB Items not in bank

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#1506]
UMB Items did not register in bank
![19766A87-8650-48BB-84E0-471F90C9614B](https://user-images.githubusercontent.com/76587427/110387940-43edc500-805a-11eb-8b7d-7fa51c1f4160.jpeg)
![4D9E50BA-C0EF-47F3-B9CC-419F1105F64B](https://user-images.githubusercontent.com/76587427/110387943-451ef200-805a-11eb-8b49-867abbda09fd.jpeg)

**Comment by Lajnux** [comment]
resolved, if need any further refund reach out to a moderator or Magna
