### ISSUE TITLE
OSB - Angler outfit no longer providing a fishing xp boost

### ISSUE THREAD

**Issue by chefslav** [oldschoolgg/oldschoolbot#1509]
## 🐛 Bug Report
I just got the angler outfit, equipped it in skilling but it is not providing a boost to xp (At least not displaying one). I checked with Fishy/Tiz to see if maybe i was just crazy but Fishy noticed afterwards that he hasn't gotten the xp boost in over a month and mentioned it might have been lost during a merge? screenshots below love u goodbye 

![image](https://user-images.githubusercontent.com/72408891/110546419-0d648880-80f4-11eb-8ad2-199457958d9b.png)
![image](https://user-images.githubusercontent.com/72408891/110546345-f6be3180-80f3-11eb-9acf-1256e6082e09.png)

**Comment by Lajnux** [comment]
resolved
