### ISSUE TITLE
[OSB] Have CoX background be purple for valuable drops too

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1510]
## 🚀 Feature Proposal

Basically what title says. Currently the light is only purple when its a new item for log, I think it'd be fitting for boss uniques to also make the light become purple. Maybe a value threshold of 50m+? 

Anti-climatic getting valuable loot with a white light as seen here https://i.imgur.com/uzqAMb4.png

**Comment by gc** [comment]
This is a known bug thats on my list to fix as soon as I can.
