### ISSUE TITLE
Monkey not found in bank OSB & BSO

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#1512]
## 🐛 Bug Report

![SmartSelect_20210310-182639_Discord.jpg](https://user-images.githubusercontent.com/68685674/110717216-3f4a1d80-81ce-11eb-9873-577551c9bb55.jpg)![SmartSelect_20210310-182646_Discord.jpg](https://user-images.githubusercontent.com/68685674/110717222-4113e100-81ce-11eb-8634-4210b489ae33.jpg)

I purchased it from +buy and it shows up in +b —search= but not when I do +b monkey

**Comment by osrsolympus** [comment]
![image](https://user-images.githubusercontent.com/65320787/110718588-44f93080-81d9-11eb-8c67-fea8116dae57.jpeg)

There are three different "monkey" items in the game. The way the bank search works is that it defaults to one item id and won't display the rest.

**Comment by imTURBObro** [comment]
> ![image](https://user-images.githubusercontent.com/65320787/110718588-44f93080-81d9-11eb-8c67-fea8116dae57.jpeg)
> 
> There are three different "monkey" items in the game. The way the bank search works is that it defaults to one item id and won't display the rest.

Thank you. So is this issue for all then?

**Comment by Lajnux** [comment]
you have to use the itemID, resolved
