### ISSUE TITLE
[BSO] Goldemar doesn't drop boxes anymore

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1515]
## 🐛 Bug Report

For quite a bit now, there have been no boxes in the Goldemar mass channel. Not sure if they were accidentally removed or not, since theres been no mention on a nerf.

**Comment by chefslav** [comment]
pls fix. 4k+ dry at goldemar is bad enough but at least the boxes made doing the masses /slightly/ worthwhile. 

A week of nonstop goldemar should yield more than a bunch of hair.

**Comment by Lexthegayotter** [comment]
pepeRiot pepeRiot pepeRiot pepeRiot pepeRiot pepeRiot pepeRiot pepeRiot bring back boxes

**Comment by gc** [comment]
Fixed in next update
