### ISSUE TITLE
[BSO] Goldemar - Broken Dwarven Warhammer - No purple icon

### ISSUE THREAD

**Issue by chefslav** [oldschoolgg/oldschoolbot#1521]
## 🐛 Bug Report

Title - broken dwarven warhammer doesn't get the unique icon when dropping in masses (so far only 1 has dropped since the broken hammer update) 

![image](https://user-images.githubusercontent.com/72408891/110882413-7f310380-82a7-11eb-8fb1-2a3820694996.png)

**Comment by gc** [comment]
Fixed in next update
