### ISSUE TITLE
First Age 1% bonus xp not working

### ISSUE THREAD

**Issue by JerMous3** [oldschoolgg/oldschoolbot#1531]
As shown in the images below, the first age 1% boost only applies to Fletching (from the couple tests I did)

![FirstAgeBug](https://user-images.githubusercontent.com/62512696/111065247-086b5480-84b9-11eb-91b2-ea77f02efd26.png)

**Comment by gc** [comment]
It applies to everything, it's just only visible in fletching because it's the only thing using the new xp system atm.
