### ISSUE TITLE
Remove confirm message from alching

### ISSUE THREAD

**Issue by Hanzigamer** [oldschoolgg/oldschoolbot#1537]
When i do alching on the OSB i always get a 2nd message that i need to confirm that i want to alch the items. First time its fine, BUT when the trip is done and it asks if it wants to do another trip, and i press the random letter asigned i would still need to confirm the alching. Is there any possibility that you could remove the "confirm" from alching? Would make mage training abit easier :)

**Comment by Lajnux** [comment]
same issue as #1355
