### ISSUE TITLE
Opal bolts (e) have the wrong image attached to them in bank

### ISSUE THREAD

**Issue by Avasquado** [oldschoolgg/oldschoolbot#1543]
## 🐛 Bug Report
its pretty small bug but i thought id bring it to your attention because its not something people use very often.

When stacking opal bolts (e) in the bank the image is just of one of them when it should be the image of five. 

https://gyazo.com/f0ef69cc337d2557f8f31fb07c681286

here is a screenshot of how they look in the bank.

Love the work you do, thanks!

**Comment by Lajnux** [comment]
resolved
