### ISSUE TITLE
[OSB] Heron not announced upon receiving pet

### ISSUE THREAD

**Issue by thievious1** [oldschoolgg/oldschoolbot#1550]
Toby has brought it to my attention that Heron isn’t being announced when receiving the pet, cannot confirm if it’s happening in all fishing activities though. He’s sent me a screenshot to show right around when he got pet, and has actually gotten it twice today but not announced either time. 
![D7421EBE-83CB-4664-AD56-39F83FC3FBA5](https://user-images.githubusercontent.com/65054062/111552463-61a0e580-8750-11eb-8570-0918ece71047.png)

**Comment by Lajnux** [comment]
resolved
