### ISSUE TITLE
BSO nightmare

### ISSUE THREAD

**Issue by zoniiiii** [oldschoolgg/oldschoolbot#1553]
## 🐛 Bug Report

Bot never returns from nightmare trip or give any loot
![bso](https://user-images.githubusercontent.com/80907491/111647647-5494fc80-880b-11eb-80ff-a036e0ce4fdb.png)

**Comment by shelixd** [comment]
https://cdn.discordapp.com/attachments/809567397216256050/823382006208397362/image0.png

Another example of the bug. If you could fix asap it would be great as a lot of are playing a bingo :)
