### ISSUE TITLE
Dwarven Pickaxe giving no effects

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#1556]
Dwarven Pickaxe is currently giving no effect or speed boost at all.

with pickaxe: (tried both equipped and unequipped)
![5804E96C-F873-4FFE-A45D-61B5B30045EE](https://user-images.githubusercontent.com/76587427/111690212-d2b1cd00-8824-11eb-8792-c2d9bf30e009.jpeg)

without pickaxe:
![A99D5C7F-56A1-4E2C-AB58-7FD0F768CBEE](https://user-images.githubusercontent.com/76587427/111690269-e1987f80-8824-11eb-817f-a20eeeb7a29b.jpeg)

was also tested on coal at 61 mining and got the same results.

**Comment by gc** [comment]
This seems fine now.
