### ISSUE TITLE
Kill command broken

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#1558]
the +kill simulation command is broken on both OSB and BSO @
![1066F2DA-CB73-46C5-8FB4-0A21BAB4471D](https://user-images.githubusercontent.com/76587427/111693958-2b836480-8829-11eb-8534-166e87f11632.jpeg)
![FF96CA92-5217-4259-B2D5-B03308A03370](https://user-images.githubusercontent.com/76587427/111693969-2de5be80-8829-11eb-9f14-b08c946accc3.jpeg)
![29CB1BB6-2A60-4B11-A42D-A07172A7AEA1](https://user-images.githubusercontent.com/76587427/111693977-2e7e5500-8829-11eb-9f2f-411fc0f96fd0.jpeg)
![0EFC395F-E863-4652-86D5-3A2DE795945C](https://user-images.githubusercontent.com/76587427/111693981-2faf8200-8829-11eb-8fb7-a40684873a85.jpeg)

**Comment by Lajnux** [comment]
resolved
