### ISSUE TITLE
Sepulchre bugs

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#1559]
Sepulchre isnt using the new XP system to show true XP gained
(Shows +90k when actually received 450k)
Strange Old Lockpick also doesn't show as a purple number (new cl item) in the loot.
![image](https://user-images.githubusercontent.com/76587427/111773940-b5254780-88a6-11eb-9504-3e8d87d643b7.png)

**Comment by Lajnux** [comment]
resolved
