### ISSUE TITLE
(BSO) =cl pets

### ISSUE THREAD

**Issue by veigarbso** [oldschoolgg/oldschoolbot#1563]
## 🐛 Bug Report

Add the new BSO pets to the =cl pets like plopper, ishi, wilvus, etc.

Also I got Zippy from questing, but doesn't show up on the =cl pets.

https://i.imgur.com/LjApdLg.png
https://i.imgur.com/GxcvaaS.png

**Comment by gc** [comment]
Added all the missing pets to cl pets.
