### ISSUE TITLE
Nightmare XP in Mass

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#1564]
In mass Nightmare all party members are receiving the full XP for every kill on the trip

For example in a 4 man group each player received 19.2kXP in each stat (6 kills/training on shared), This number should be divided by the amount of players in the mass.

**Comment by osrsolympus** [comment]
Apparently this is the same bug making other masses give too much xp not just Nightmare.

**Comment by Lajnux** [comment]
resolved
