### ISSUE TITLE
Koschei zero kill trip

### ISSUE THREAD

**Issue by J4stMart** [oldschoolgg/oldschoolbot#1566]
Not sure if intentional or not

But it seems like Koschei has actually become impossible to kill, because the trip length exceeds the max trip length.
So since the combat update, you're only able to do a 0 kill trip.

**Comment by J4stMart** [comment]
Once again not sure if intentional or not

But =k koschei returns no message at all now

**Comment by notmeta** [comment]
Good excuse to remove it entirely
