### ISSUE TITLE
Please allow ironmen to quest for Zippy after 5k qps

### ISSUE THREAD

**Issue by themrrobert** [oldschoolgg/oldschoolbot#1568]
With the drop rate for Zippy being more than 1 in 5k qps on average, iron players only have about a 60% chance to get the pet before they are unable to get it forever.

I personally don't want to play my iron if I can't get a zippy, and I would be that a lot of players feel similarly. 

Precedent: Being able to continue questing past 5k would be akin to 'speedrunning' or 'replaying' quests in osrs, for no rewards, (other than the pet). While this feature isn't out yet, it is something they've said they will do and is probably in development.

You wouldn't be able to get more than 5k qps, but you could still quest for the chance at zippy.

Thank you!

**Comment by ArtMatters** [comment]
Even if the droprate was lower than the max QP, this wouldn't make sense to be potentially locked out of zippy even on a normal account for the log slot.

**Comment by wildchickenz** [comment]
I see no reason this should not be implemented. Make trips beyond 5k just have a chance to roll for zippy and not gain any more questpoints.

**Comment by gc** [comment]
In the next update, ironmen will no longer have a max qp. Non-irons still do.
