### ISSUE TITLE
Wrong warrior's guild requirement

### ISSUE THREAD

**Issue by Krikke93** [oldschoolgg/oldschoolbot#1577]
The bot currently requires you to have at least 65 attack and 65 strength to access warrior's guild content. This is different from the ingame requirement of a combined 130 attack/strength (or 99 in either one of them).

For example, my minion has 66 attack and 64 strength, with which I should be able to buy "potato with cheese", but I'm unable to.

**Comment by ArtMatters** [comment]
I mentioned this in testing, and it's currently just intended if you have 65+/65+ only. Not a big deal since you'll want to train both of them regardless.

**Comment by Lajnux** [comment]
resolved
