### ISSUE TITLE
Odium Ward - no Ornament Version

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#1579]
## 🐛 Bug Report

**_this is currently only tested on BSO but I'm pretty sure it is the same for OSB._**

I noticed Odium Ward had a ornamented version Odium Ward (or) and the regular one.

![SmartSelect_20210323-181548_Discord.jpg](https://user-images.githubusercontent.com/68685674/112230978-d6b66400-8c03-11eb-9c13-dc9050359839.jpg)

in the bot, Odium Ward (or) doesn't exist instead it is labeled the same as the non ornament version. so to view it in bank there are 2 ways,  **=b —search=odium** / **=b —search=ward**, or **=b 1 12807** -> ![SmartSelect_20210323-180359_Discord.jpg](https://user-images.githubusercontent.com/68685674/112230913-bdadb300-8c03-11eb-8f56-d6fd0593080d.jpg)

when I did **=gearstats odium ward** the following picture appeared -> ![SmartSelect_20210323-180232_Discord.jpg](https://user-images.githubusercontent.com/68685674/112230829-935bf580-8c03-11eb-998f-1e2af3ebd209.jpg)

when I did **=gearstats odium ward (or)** this happened -> ![SmartSelect_20210323-180155_Discord.jpg](https://user-images.githubusercontent.com/68685674/112230885-aff82d80-8c03-11eb-82a2-f570075c070a.jpg)

yet when I do gearstats with another item that has (or) or an ornamented item, it works -> ![SmartSelect_20210323-180205_Discord.jpg](https://user-images.githubusercontent.com/68685674/112231048-f2ba0580-8c03-11eb-9bfc-1588f6f6af40.jpg)

is it possible to change the name of item ID: **_12807_** to have (or) so the item can exist all on its own?

**Comment by osrsolympus** [comment]
The odium ward (or)‘s official name is odium ward, not odium ward (or). Only Jagex can change the official names of items, sadly. Not a bug.

**Comment by imTURBObro** [comment]
> The odium ward (or)‘s official name is odium ward, not odium ward (or). Only Jagex can change the official names of items, sadly. Not a bug.

thank you for this info!
