### ISSUE TITLE
BSO Ironman Limited Pets

### ISSUE THREAD

**Issue by GreyHelm-Inc** [oldschoolgg/oldschoolbot#1581]
Hi!

So, as we all know, BSO ironmen currently can't obtain limited pets from events gone by. This puts ironmen at a distinct disadvantage off the bat because these pets have enormous boosts for content that is done regularly.

My proposal is to make limited events available to all BSO ironmen full time -- with the original droprates. This allows them to put in the required time (like 2 months for Smokey lol) to get these boosts. There's no downside as BSO ironmen can't deiron at any time. 

Let me know if you think this is a decent idea!

**Comment by NeverWinterNA** [comment]
Agree

**Comment by wildchickenz** [comment]
Great Idea, 11/10 would love holiday pets on BSO ironman so I can have a pet bat named Cob

**Comment by 6enny6** [comment]
support

**Comment by JadHanma** [comment]
+1 with the addition that BSO ironman shouldnt appear in event pets mostdrops list.

**Comment by mylife212** [comment]
Big agree, the pets have great perks that shouldn't be locked for ironmen considering they will never enter the economy

**Comment by JerMous3** [comment]
pets or ironmeme riot

**Comment by zabiros** [comment]
+1 sounds reasonable

**Comment by thievious1** [comment]
I don’t see how this could have any downsides, fully support my ironmeme bso friends :)

**Comment by J4stMart** [comment]
Instead of the events, you could also add the limited pets to pet mystery boxes for ironman. It will still keep them rare, because pmbs are hard to come by, but it still allows the pets to be achievable by ironman.

**Comment by ReZeroed** [comment]
I also support this.

One option could be a separate event called ironmeme that only ironmen can run that could roll any of the discontinued pets provided they are not already on your account, this would prevent ironmen from getting dupes of the pets and also allow any future ironmen to get any discontinued pets from events that might also run in the future.

Or the simple method of just adding a command for spawn x pet, each command could only be used once similar to the rmb for T5 and only ironman accounts could use the command. And any new event pets could also be added this way after the event for a new pet ends. (Though I think hunting for the pets would be the more reasonable method)

**Comment by wildchickenz** [comment]
Bump, this really is a great idea that could lead to more ironman entering the game. Mains would see it as a way to finally 'own' a rare pet that they missed out of.

**Comment by GreyHelm-Inc** [comment]
Any other thoughts on this?

**Comment by 000000653** [comment]
Could this be limited to 1 pet per person? Idk how this would work but I'm concerned mostdrops would be ruined and ironmen will then always be at the top of it regardless of who actually participated in the event. That's my only concern, otherwise great idea, discontinued items always suck the fun out of games for new players.
