### ISSUE TITLE
BSO Hunter Master Cape + Sandy Not Working

### ISSUE THREAD

**Issue by Fartplox** [oldschoolgg/oldschoolbot#1584]
It lists that Sandy doubles loot and shows the loot correctly, but you only receive half that amount. It is likely Sandy is not working as shown. Thank you!

![Screenshot_20210324-213241_Discord](https://user-images.githubusercontent.com/81340823/112411348-c0370800-8cea-11eb-8d00-036f66015738.jpg)
![Screenshot_20210324-213243_Discord](https://user-images.githubusercontent.com/81340823/112411359-c62ce900-8cea-11eb-93c8-970ae33ba5c9.jpg)

**Comment by gc** [comment]
Fixed in next update
