### ISSUE TITLE
[BSO] missing mystery box

### ISSUE THREAD

**Issue by xottz** [oldschoolgg/oldschoolbot#1585]
## 🐛 Bug Report
 I did a daily, reward said said i got a tradable mystery box, didnt get a tradeable mystery box. I had an untradable mystery box before i opened that and then tried to open my tradable and it just wasnt there https://i.imgur.com/YfVXHRz.png https://i.imgur.com/zqQw4V8.png

**Comment by Lajnux** [comment]
resolved, if need further refund reach out to Magnaboy or a moderator.
