### ISSUE TITLE
Fun BSO Easter Pet

### ISSUE THREAD

**Issue by wildchickenz** [oldschoolgg/oldschoolbot#1587]
I propose a bunny, name him whatever you want.
He acts similar to Wilvus. However he will complete a random farm run. It won't be plants you have placed since he is a wild bunny that is hard to keep hold of he sneaks off and completes a strangers farm run and provides all loot from it as well as partial farming xp.

**Comment by wildchickenz** [comment]
Does this need to remain closed? I still propose it as a perk for perkless hoppy.

**Comment by 6enny6** [comment]
re opened as its a good perk suggestion for Hoppy

**Comment by wildchickenz** [comment]
Bump :hamstare:

**Comment by wildchickenz** [comment]
Hello mister Hoppy coder, i still think something like this would be a great perk 👍

**Comment by wildchickenz** [comment]
Maybe May is the month for hoppy to get its perk.

**Comment by gc** [comment]
I don't want to give Hoppy a perk. This farming perk can be added to a new pet though.
