### ISSUE TITLE
BSO Ironman dailies 

### ISSUE THREAD

**Issue by zabiros** [oldschoolgg/oldschoolbot#1588]
## 🚀 Feature Proposal

I'd like to suggest, at least getting 1 box for a correct daily for iron man. atm you probably have a higher chance to get a box from an incorrect daily than a correct daily. (or it doesn't have a difference)
It's really sad to see someone getting junk from a correct daily xD

**Comment by gc** [comment]
Ironmen don't get special treatment. ❄️ 

Also, the chance of getting a box isn't higher when you get it wrong
