### ISSUE TITLE
BSO Goldemar Dwarven crate bug

### ISSUE THREAD

**Issue by zabiros** [oldschoolgg/oldschoolbot#1589]
## 🐛 Bug Report

I somehow got 2x Dwarven crate from goldemar, even though I did not get any purples. 
I think it was after this kill: 

<img width="774" alt="Screenshot 2021-03-25 at 17 39 18" src="https://user-images.githubusercontent.com/79454174/112509754-0f377880-8d91-11eb-83c6-41ad5327f57e.png">

This has happened before aswell, I think hosts also get the Dwarven crates whenever anyone gets it.

**Comment by ArtMatters** [comment]
Did the double loot proc automatically give the entire part double everything? Can you check if the other part members also got 2 crates?

**Comment by Lajnux** [comment]
resolved
