### ISSUE TITLE
BSO Easter event

### ISSUE THREAD

**Issue by Zilther-osb** [oldschoolgg/oldschoolbot#1596]
## 🐛 Bug Report

I've done the Easter Catchrabbits event around 30 times and hadn't gotten the outfit yet. After talking to some members on the discord, I was informed it was because I had already received the Easter Ring from a mystery box and that broke the event for me.

I've included a screenshot of having completed a trip for the event, and then my Collection log with only the ring unlocked.

![2021-03-26](https://user-images.githubusercontent.com/81444101/112691160-440c0400-8e53-11eb-865b-759197637200.png)

**Comment by Sethmare** [comment]
Bump. I am having this same issue and thought it was just bad RNG for a while haha

**Comment by gc** [comment]
This is just one of those unfortunate things in BSO you have to deal with, if you already have the easter ring in your collection log it'll think you've already done the event. Which is impossible in OSB, but possible in  BSO because of mystery boxes.
