### ISSUE TITLE
[BSO] Limit =spawnlamp to #bot-channel-bso

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1602]
## 🚀 Feature Proposal

Would be consistent with =spawnbox, and the command is spammy by nature. Its appreciated when they're spawned in #general but it floods out the chat. 

And now, people are beginning to spawn them in less active channels (seen them spawn in mass channels and even an attempt in patrons...). This will keep happening until its limited to a channel

**Comment by 6enny6** [comment]
+1 they even try it in the mass channels now

**Comment by gc** [comment]
Fixed in next update.
