### ISSUE TITLE
Sandy is not working properly

### ISSUE THREAD

**Issue by KetZuca** [oldschoolgg/oldschoolbot#1605]
## 🐛 Bug Report

Hi, Sandy is not giving me the right number of boxes.
![image](https://user-images.githubusercontent.com/78753944/112740192-f4a7ff80-8f48-11eb-994f-5bfb70fce7d5.png)

Before i start my new trip i check my number of boxes and it shows "6 tmb" and when the trip returns gives me another "6 tmb" but i checked and it doesnt multiply the boxes.
Write a description of the bug here, give all the information you can about what it is, how it happened.

**Comment by ArtMatters** [comment]
Sandy does not multiply boxes without having the master hunter skillcape. After equipping the cape sandy 2x's mystery boxs.(might be still bugged according to fartplox)

**Comment by JerMous3** [comment]
Yes it only works with the Master cape. But it’s weird because the message does say he got 6 while he only got 2 (which is the right amount, but the message there is the bugged part).

**Comment by gc** [comment]
Fixed in next update.
