### ISSUE TITLE
Prayer Master Cape Broken

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#1607]
The Prayer Master cape 40% ppot reduction is currently only working at Malygos

(Its equipped in all 3 screenshots)
Not working at Treebeard:
![image](https://user-images.githubusercontent.com/76587427/112747256-0a024580-8fac-11eb-9d14-85f2fb67f916.jpeg)

Not working at Corp:
![image](https://user-images.githubusercontent.com/76587427/112747266-1ab2bb80-8fac-11eb-9669-3eac6a366f61.jpeg)

Works at Maly:
![image](https://user-images.githubusercontent.com/76587427/112747271-29996e00-8fac-11eb-9805-16f6d8aaa93e.jpeg)

**Comment by gc** [comment]
I just tested this myself and it seems to be working fine, plus nobody in the bso channel confirmed it was bugged.
