### ISSUE TITLE
Move Discontinued Pets/Items to =cl holiday or Their Own CL

### ISSUE THREAD

**Issue by shelixd** [oldschoolgg/oldschoolbot#1625]
It would be nice to move discontinued pets (and any other future discontinued items) to =cl holiday or a separate CL so that the =cl pets leaderboard isn't decided by pets people can't get anymore.

**Comment by ArtMatters** [comment]
Not just the cl pets leaderboard, the lb cl is also affected by this. If it's wanted to keep the pet on the log it should be possible to earn the log slot without recieving the actual pet to maintain it's discontinued status without unfairly limiting collection logs on BSO.

**Comment by gc** [comment]
This is done now I believe.
