### ISSUE TITLE
Sandy + Hunter cape broken again after update

### ISSUE THREAD

**Issue by Fartplox** [oldschoolgg/oldschoolbot#1626]
It was working fine until the update came out (4/1). Now you get half of shown loot.
![image](https://user-images.githubusercontent.com/81340823/113380482-92307400-9339-11eb-973d-dea5fe2f9761.png)

**Comment by Fartplox** [comment]
![Screenshot_20210405-104253_Discord](https://user-images.githubusercontent.com/81340823/113593261-d5216e80-95fb-11eb-91a5-6aa0b5ca9e7e.jpg)
Following up, still broken.

**Comment by Lajnux** [comment]
resolved
