### ISSUE TITLE
Zalcano (updated) requirements [OSB]

### ISSUE THREAD

**Issue by joeywithazero** [oldschoolgg/oldschoolbot#1628]
## 🚀 Feature Edit:

With the release of gauntlet and correct requirements for SOTE being needed, should also roll over to Zalcano and force the same SOTE reqs.

Quest Points as well

- 70 Agility 
- 70 Construction
- 70 Farming
- 70 Herblore 
- 70 Hunter
- 70 Mining
- 70 Smithing 
- 70 Woodcutting

**Comment by Lajnux** [comment]
resolved
