### ISSUE TITLE
Spawn Lamp variation

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#1630]
Currently spawnlamp just picks a random xp value between 1 and 13.4m, 
meaning it has an 85% chance to be between levels 80-99 or a 59% chance of being level 90-99

Could this be changed to pick a random level first, and then randomise the XP value between the min and max of that level.

**Comment by wildchickenz** [comment]
This I like
Far to often people spam 90+ right off the back because it's pretty common
