### ISSUE TITLE
Make Fewer Things Case Sensitive

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1632]
## 🚀 Feature Proposal

Recently, more and more parts of the game have been made case sensitive. Some of it, like “confirm permanent ironman” for BSO, makes sense, but for things like search terms and equipment selection, it just gets in the way without a purpose (for example: if someone is trying to auto equip to their skilling setup, the fact that they wrote Skilling shouldn’t break the entire command). Would just be a nice QoL thing.

**Comment by JerMous3** [comment]
![image](https://user-images.githubusercontent.com/62512696/113474519-be024580-9470-11eb-9a9f-26411035e2ac.png)

I would like to add stuff like this, probably because i didnt use a capital G i didnt get the box :|

**Comment by ArtMatters** [comment]
> ![image](https://user-images.githubusercontent.com/62512696/113474519-be024580-9470-11eb-9a9f-26411035e2ac.png)
> 
> I would like to add stuff like this, probably because i didnt use a capital G i didnt get the box :|

could've been this https://oldschool.runescape.wiki/w/Ghrazi_rapier_(beta)

**Comment by 000000653** [comment]
> could've been this https://oldschool.runescape.wiki/w/Ghrazi_rapier_(beta)

I don't believe the bots use wiki page names for this sort of stuff, they use the actual item names.

**Comment by ArtMatters** [comment]
> I don't believe the bots use wiki page names for this sort of stuff, they use the actual item names.

There's quite a few items that have different names similar to the wiki. Just mentioning it's a possibility.

**Comment by gc** [comment]
No longer an issue.
