### ISSUE TITLE
let's finally have a —skilling filter for selling!

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#1635]
## 🐛 Bug Report / ## 🚀 Future Proposal 

so when I =sellto @ —skilling it says item doesn't exist. but if I do =sellto @ —herblore it works.![SmartSelect_20210403-030403_Discord.jpg](https://user-images.githubusercontent.com/68685674/113472517-68567a80-9429-11eb-81f1-907ebf4522a0.jpg)

**Comment by TizHub** [comment]
You didn't put a price

**Comment by S-hawn** [comment]
Using the --skilling in a trade has never worked. It has always needed to be broken down; such as --herblore, --smithing, --farming etc etc

**Comment by imTURBObro** [comment]
> You didn't put a price
> EDIT: Turns out it actually is broken anyway from a quick search
> 

you don't need a price automatic price is 1gp but total # of said item.

**Comment by imTURBObro** [comment]
> Using the --skilling in a trade has never worked. It has always needed to be broken down; such as --herblore, --smithing, --farming etc etc

what was the point of this response? I'm not posting on github to hear about the info I already posted, I'm hoping to hear something about a fix maybe? or whatnot.

**Comment by S-hawn** [comment]
> > Using the --skilling in a trade has never worked. It has always needed to be broken down; such as --herblore, --smithing, --farming etc etc
> 
> what was the point of this response? I'm not posting on github to hear about the info I already posted, I'm hoping to hear something about a fix maybe? or whatnot.

The point of the response was to inform you that the "bug" you submitted, was not a bug, as well as it was already previously known & I offered different ways you could get around the issue that you presented. If you would've originally posted as a suggestion, I would've agreed as I do feel like it should be a feature in the bot. I'm not sure why you took that response so negatively, but I promise you it's not that serious.

**Comment by imTURBObro** [comment]
> > > Using the --skilling in a trade has never worked. It has always needed to be broken down; such as --herblore, --smithing, --farming etc etc
> > 
> > 
> > what was the point of this response? I'm not posting on github to hear about the info I already posted, I'm hoping to hear something about a fix maybe? or whatnot.
> 
> The point of the response was to inform you that the "bug" you submitted, was not a bug, as well as it was already previously known & I offered different ways you could get around the issue that you presented. If you would've originally posted as a suggestion, I would've agreed as I do feel like it should be a feature in the bot. I'm not sure why you took that response so negatively, but I promise you it's not that serious.

so why didn't you just say "it's not a bug, just doesn't exist" 
whole reason I wish it existed was so we didn't have to do the work around.

**Comment by nwjgit** [comment]
This works properly now.
