### ISSUE TITLE
Bso clbank is broken

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1637]
## 🐛 Bug Report

I am unable to see my collectionlog bank on bso. 
![CC904DE0-DD36-4484-8035-78FDE4AC3245](https://user-images.githubusercontent.com/65320787/113482268-d6239600-946b-11eb-818c-08be2dc3cd12.jpeg)

wondering if this might be because of broken items persisting in the clbank but I have no clue why this is happening

**Comment by gc** [comment]
This seems fixed now.
