### ISSUE TITLE
DST Breaks Trips (extends by 1hr+) - Use UTC instead.

### ISSUE THREAD

**Issue by themrrobert** [oldschoolgg/oldschoolbot#1638]
Hello,

So when it hit 3:00 am Aus, and then went back to 2:00am, anyone who had trips that were supposed to end between 2:00v2 and 3:00v2 started counting upwards when they reached zero. Likely due to absolute value of the difference.

Switching to UTC would solve this problem, as there are no timezone changes, and it's easy to convert UTC into timezone for display purposes.

**Comment by gc** [comment]
We're using UTC now
