### ISSUE TITLE
+PK osbot command

### ISSUE THREAD

**Issue by jmechine** [oldschoolgg/oldschoolbot#1641]
I would like to suggest a PK Command for OS Discord bot +PK or +PKing and it goes on a pking trip and asks where you would like to go in the wilderness upon entering command it will search for @usernames in wilderness and give an option to 
+attack @username or +defend @username
You then take turns rolling dice your damage dealt is decided by the dice roll and to heal you type +eat food type or +potion to drink potion +combo would eat and drink your potions hopefully this isnt too confusing but you get the idea.

thank you

**Comment by nwjgit** [comment]
This was polled and failed in the main discord server.
