### ISSUE TITLE
Double clue scroll drop in osbuddy

### ISSUE THREAD

**Issue by Eotena** [oldschoolgg/oldschoolbot#1646]
![file](https://user-images.githubusercontent.com/33289650/113515344-3bfb4500-9574-11eb-8b35-ce160ac7b266.jpg)
## 🐛 Bug Report

I was doing a sarachnis trip and got 2 hard clue scrolls for some reason.
Please note this was not on BSO.
If this is somehow intended Im sorry for the bother

**Comment by ArtMatters** [comment]
Known issue. You should not actually have 2 hard clues.
