### ISSUE TITLE
Wilvus Suggest

### ISSUE THREAD

**Issue by edeod** [oldschoolgg/oldschoolbot#1647]
Wilvus previously gave 1-3 masters on average every 1-2 trips, which was clearly busted and rightfully toned down.  Going from 1-3 masters to 1 hard clue every like 5-8 trips (or more, not fully sure), is gutting it to a point where it may just be better to do Zak to extend and AFK more for example as opposed to random Tokkul, 500k coins, a few barely seeds etc, which may be perceived as worthless.  This is good to some degree as it offers variation of pets and not always BIS.

Seeing it go from 1b down to 300m lowest end reflects this change and now not 'must use', but probably overshot as best case scenario now is 3m vs 30m before clue wise (90% nerf), which you have to be lucky to hit on now as clue drops are less frequent post nerf.

So the pets not RIP status, _maybe_ roll clue scroll 1/3 chance per 30 mins then % weight to the type of scroll (Med - Master) and quantity (1-3).  This could give back some incentive to using it, without shooting it up to busted status like before.

**Comment by ArtMatters** [comment]
Same as this basically.
https://github.com/oldschoolgg/oldschoolbot/issues/1631

**Comment by edeod** [comment]
Closed due to dupe
