### ISSUE TITLE
Idea for a real life pet pics channel

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#1655]
## 🚀 Feature Proposal -- IRL Pet Pic Channel

so I was thinking it would be awesome if there was a channel for people to post pics of their in real life pets and to chat about them.

**Comment by EngageV2** [comment]
Idk why but i see people roasting others pets

**Comment by imTURBObro** [comment]
> Idk why but i see people roasting others pets

I haven't seen that on any of the servers that I'm in that have this type of thread. 

plus it would cut down on my "spam"
