### ISSUE TITLE
BSO - Dwarven pickaxe not working

### ISSUE THREAD

**Issue by iScruffy** [oldschoolgg/oldschoolbot#1657]
## 🐛 Bug Report

"The Dwarven Pickaxe provides a 2x speed boost to mining. "
Not gaining any speed boost with the pickaxe equipped or unequipped (Tried in skilling and misc)
Gilded pickaxe 11% does work while unequipped no message about dwarven pickaxe

![withoutpick](https://user-images.githubusercontent.com/63420828/114023332-a78e2c80-986a-11eb-8a92-fb1876d394b0.png)
![withpick](https://user-images.githubusercontent.com/63420828/114023340-a957f000-986a-11eb-9deb-bc73ab92f043.png)

**Comment by gc** [comment]
I just tested and it works fine. You need 99 mining to use it though.
