### ISSUE TITLE
Combine perks of Skilling cape and Master cape

### ISSUE THREAD

**Issue by wildchickenz** [oldschoolgg/oldschoolbot#1658]
Currently with 120 thieving and a thieving skilling cape on you fail exactly zero times at vyres. However having the thieving master cape on in its place you fail 30 to 35% of the time, kind of neglecting the 30% boost that it provided in the first place
One way around this is having your skilling cape in your skilling equipment while having the master cape in miscellaneous or wherever else but it has to be equipped somewhere.
I see no reason why the thieving success rate should not be a part of the master cape.

**Comment by gc** [comment]
Done in next update.
