### ISSUE TITLE
Rework Doug

### ISSUE THREAD

**Issue by wildchickenz** [oldschoolgg/oldschoolbot#1661]
Doug was an early custom pet for BSO, it would be more in line with other custom pets if it worked on all non-PVM trips like the rest.

**Comment by wildchickenz** [comment]
This wouldn't be overpowered as Doug is hardly used as-is.

**Comment by ArtMatters** [comment]
With how rare Doug is compared to the newer pets it should probably be better in general.

**Comment by gc** [comment]
Done in next update.
