### ISSUE TITLE
[BSO] Jar of spirits doesn't seem to drop from corp in BSO

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1664]
## 🐛 Bug Report

I can't find the jar in https://github.com/oldschoolgg/oldschoolbot/blob/bso/src/lib/simulation/Corp.ts for BSO, I could be wrong. But me and jess have done well over 4000+ rolls of jar with nothing, so im more inclined to believe its not added. PLEASE add it

**Comment by gc** [comment]
Fixed in next update.
