### ISSUE TITLE
2 OSRS Monsters

### ISSUE THREAD

**Issue by sunnyzulu** [oldschoolgg/oldschoolbot#1667]
I think it would be great to add two different monsters into BSO...

Alchemical Hydra: I think it would make it a bit easier for Irons (and normal accounts) to obtain ferocious gloves and Dragon Hunter Lance.

Spiritual Mage: Again, would make it easier for everyone to obtain Dragon Boots.

**Comment by wildchickenz** [comment]
Both of these are locked behind slayer and I'm sure will be released with slayer
