### ISSUE TITLE
Boosts for Blue Dragon

### ISSUE THREAD

**Issue by verghv5** [oldschoolgg/oldschoolbot#1668]
## 🐛 Bug Report

The info screen says that the zammy spear is the item that gives a 10% boost, but it should be the hasta as you need the anti-dragon shield

![image](https://user-images.githubusercontent.com/30439889/114261389-49fffa00-99a8-11eb-8094-414482bce8e4.png)

**Comment by LuxrayElite** [comment]
I'm going to assume this is related to not being able to obtain a zamorakian hasta as a drop it has to be created. All situations where a hasta would be used currently use the spear as the boost.

It would also mean you need to get two spears just in case you forget to constantly convert back and forth.

so applying the boost for just obtaining the spear seems reasonable but (ironmanstruggles)

**Comment by Lajnux** [comment]
resolved
