### ISSUE TITLE
Takon changes

### ISSUE THREAD

**Issue by edeod** [oldschoolgg/oldschoolbot#1669]
Currently rare (1/4500 from COX) to get and gives smithing boost to make items into bars, but has no effect on smelting bars.
 
It can be said that Dwarven gauntlets are an option for smelting, but like cooking, where you can have Remy or gauntlets for cooking, you don't have that choice for smelting between gauntlets and takon.

Smelting is the common way people get smithing xp and should be added to takon, considering the rarity.

Just seems weird for a pet so rare to get half a skill it's intended for - smithing items but not smelting ores.

**Comment by edeod** [comment]
Bump

**Comment by nwjgit** [comment]
if this is still something you want to suggest a run a poll here https://discord.com/channels/342983479501389826/1032668754561224734
