### ISSUE TITLE
Giveaway command

### ISSUE THREAD

**Issue by Carrotthy** [oldschoolgg/oldschoolbot#1670]
## 🐛 Bug Report

Hey I did a giveaway on a server to test it for myself, and it worked, but i started a trip as the giveaway was going on and the giveaway never finished.

Also I got a message from the bot in my dms saying: "Your giveaway failed to finish, you were refunded the items: [object Object]." I do not know if this is intentional that the giveaway "breaks" if the host of the giveaway starts a trip and also you cannot start a giveaway if you are on a trip.

**Comment by gc** [comment]
Fixed now.
