### ISSUE TITLE
 Gauntlet Normal/Corrupted- OSB

### ISSUE THREAD

**Issue by Hanzigamer** [oldschoolgg/oldschoolbot#1671]
Even though gautnlet is fairly new content, there is something that i think needs to be looked at.

1. Both corrupted and normal gauntlet shares clog, under +clog gauntlet, but it only shows kc for regular gauntlet and not for corrupted. 
2. Both corrupted and normal gauntlet dont show in +m kc

**Comment by osrsolympus** [comment]
1. Is a duplicate issue to #1633 
2. The gauntlet is a minigame and not a boss so it wouldn’t show up under the standard kc interface.

**Comment by Hanzigamer** [comment]
I just hit 100 kc to gain the maximum bonus, and i still have to do 1 kill trip. I think that when you hit 100 kc you should have enough bonus to do 2 kills a trip. Atm it takes 16 minutes for 1 kill
