### ISSUE TITLE
Nex range Xp

### ISSUE THREAD

**Issue by edeod** [oldschoolgg/oldschoolbot#1672]
Bosses like mally / treebeard give XP but unfortunately Nex does not.

Assuming this is due to it originally being massable/ for groups at the start, but now nearly always people do solo nex and mass channel was wiped. 

If it could give range XP that would be nice.

**Comment by wildchickenz** [comment]
Have you checked your XP before and after the trip? Nightmare is similar, it doesn't show XP gained but looking at it with =m stats before and after shows an increase

**Comment by edeod** [comment]
Hi, yeah test a few times, nothing.

**Comment by gc** [comment]
In the next update, you should now get xp for killing nex.
