### ISSUE TITLE
Notifications for DWH show KC as Total KC + Trip length

### ISSUE THREAD

**Issue by themrrobert** [oldschoolgg/oldschoolbot#1676]
The notifications are showing an extra trips worth of KC. My friend just got dwh on first trip of 69, but the notifications show 138. 

Also same thing happened to me, I got mine today at 110 something and the notifications show 11101
![image](https://user-images.githubusercontent.com/10122432/114302585-7ede8080-9a7e-11eb-92d8-2e54f8a4367e.png)

![image](https://user-images.githubusercontent.com/10122432/114302605-9e75a900-9a7e-11eb-82ff-4c186f8eb8e1.png)

**Comment by gc** [comment]
Thanks for reporting, fixed in next update.
