### ISSUE TITLE
leaderboard command skips pages

### ISSUE THREAD

**Issue by ianfights** [oldschoolgg/oldschoolbot#1679]
## 🐛 Bug Report
<h1>What Is The Bug?</h1>
When navigating the leaderboard the leaderboard completely skips pages.
<h1>How To Replicate</h1>
Execute the +lb command then navigate to pages before and after (for example skill total page 27 and 29). Then press the navigation arrows to get that direction.
Once you press the arrows the bot removes the reaction then doesn't change the page. Once you press the reaction again it moves to page after the one being skipped.

This may be caused by the same issue that happened before that iirc disabled most things on the bot with null items and users?

**Comment by ArtMatters** [comment]
This is just lag between it finding the next page, and you not waiting for the next page to show up.

**Comment by POKEBLOX6** [comment]
> This is just lag between it finding the next page, and you not waiting for the next page to show up.

I don't think it is that because it never shows up, and it happens on those pages every time.

**Comment by imTURBObro** [comment]
> This is just lag between it finding the next page, and you not waiting for the next page to show up.

no it's not

same thing is happening for lb cl scroll, lb skills Runecraft,  many different lb have a page that won't load and gets skipped

**Comment by imTURBObro** [comment]
> ## 🐛 Bug Report
> <h1>What Is The Bug?</h1>
> When navigating the leaderboard the leaderboard completely skips pages.
> <h1>How To Replicate</h1>
> Execute the +lb command then navigate to pages before and after (for example skill total page 27 and 29). Then press the navigation arrows to get that direction.
> Once you press the arrows the bot removes the reaction then doesn't change the page. Once you press the reaction again it moves to page after the one being skipped.
> 
> This may be caused by the same issue that happened before that iirc disabled most things on the bot with null items and users?

I've noticed that the pages that are missing/  not loading are the pages I am on. 

probably the same for you

**Comment by POKEBLOX6** [comment]
@imTURBObro Yes it is the same for me

**Comment by imTURBObro** [comment]
> @imTURBObro Yes it is the same for me

@POKEBLOX6 good to know. I mean some of the lb show up that I'm on. like runecraft 1st page and agility first page on bso. but any other skill or cl or minigame the page or 1 of 2 pages that I should be on will not load.

**Comment by POKEBLOX6** [comment]
> @POKEBLOX6 good to know. I mean some of the lb show up that I'm on. like runecraft 1st page and agility first page on bso. but any other skill or cl or minigame the page or 1 of 2 pages that I should be on will not load.

I'm guessing it has something to do with the issue they had with null accounts and items somehow breaking stuff

**Comment by POKEBLOX6** [comment]
I think it broke the kc command so they changed all ``NULL`` to ``undefined`` values

**Comment by gc** [comment]
I don't believe this is an issue anymore.
