### ISSUE TITLE
BSO - Corp Drop Rates are incorrect

### ISSUE THREAD

**Issue by themrrobert** [oldschoolgg/oldschoolbot#1680]
**Description:**
The drop ratees for Sigils are incorrect because of the addition of the divine sigil. 

**Solution:**
The 'SigilTable' drop rate should be 1 in 512. (As opposed to 585)

**Details:**
**Currently, the drop rates are:**
Spectral / Arcane: 1 in 1560  (585 x 8/3)
Divine / Elysian: 1 in 4680   (585 x 8/1)

**But they should be:**
Spectral / Arcane: 1 in ~1365  (512 x 8/3)
Divine / Elysian: 1 in 4096    (512 x 8/1)

**Drop Rates in OSRS  +  RS3 (Pre-EoC):**
```
                OSRS           RS3
Arcane    |     1365          ~1365
Spectral  |     1365          ~1365
Elysian   |     4095           4096
Divine    |     N/A            4096
```

**Comment by gc** [comment]
Changed the sigil table to 1 in 512.
