### ISSUE TITLE
Gorajan boost not working with 3 pieces equiped

### ISSUE THREAD

**Issue by slippy3** [oldschoolgg/oldschoolbot#1682]
I have 3 pieces of the gorajan occult set on and it's not giving me a boost even though it says it works per 3 pieces equiped. I have the gorajan occult helmet, gorajan occult top and gorajan occult legs all equipped in my magic gear but when sending a dungeon it isn't showing me getting any boost. Just showing the boost for having scroll of teleportation unlocked.

**Comment by gc** [comment]
It works based on full sets' equipped, not per piece.
