### ISSUE TITLE
[BSO] Make Kalphite King soloable if you have the full Gorajan Torva set

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1683]
## 🚀 Feature Proposal

What the title says. This would give an option for those who don't like massing to solo it and this gives even more demand for the Gorajan set. **The kills/hr should be considerably slower than massing**.

**Comment by slippy3** [comment]
I would prefer to have kk be soloable at a certain kc milestone instead and the gorajan armour have more dg boosts. Also add a dungeoneering level requirement to make the gorajan armour like how the new necklaces require 99 to make.
