### ISSUE TITLE
[OSB] CoX background doesn't change to purple when you get new collection log item.

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1685]
## 🐛 Bug Report

As the title says, I've noticed that the CoX background hasn't changed colors properly recently. As you can see in the image below, I got a mace drop from nightmare and it was new to my log, yet it was still a white light. I've also noticed the same issue with my friend getting a Zalcano shard, which was new to their log
![coxbug](https://user-images.githubusercontent.com/63373565/114647082-78345100-9caa-11eb-8129-c2d307085e79.png)

**Comment by ArtMatters** [comment]
This isn't an issue with the background most likely as the '1' on the item did not show purple for being a new log item. It's likely an issue with log items in general.

**Comment by mylife212** [comment]
> This isn't an issue with the background most likely as the '1' on the item did not show purple for being a new log item. It's likely an issue with log items in general.

Very good catch. Its most definitely an issue with the item not appearing purple, rather than CoX bg being the bug. Going to close this and open a similar issue, since the title is misleading
