### ISSUE TITLE
Bot doesn't report the results of trips anymore when used through DMs.

### ISSUE THREAD

**Issue by Paah** [oldschoolgg/oldschoolbot#1686]
Very simple to reproduce, send any command to the bot through DM like "+smelt gold" or "+k 5 goblin" for a faster trip. The bot will happily respond that your minion is now busy killing goblins for 20 seconds or whatever, but stay mute 20 seconds later and not report that your minion has returned nor what loot you got. The trips do still complete and you gain xp/loot even without the report though.

**Comment by wildchickenz** [comment]
Thank you! I am not alone on this. Bot responds to every command but will not tell me my minion has returned.

**Comment by gc** [comment]
This should be fixed now.
