### ISSUE TITLE
Sandy doesn't work

### ISSUE THREAD

**Issue by Ktownstoner** [oldschoolgg/oldschoolbot#1688]
## 🐛 Bug Report

Sandy doesn't seem to work it says in chat that it gives you the loot but you don't actually get the loot in you inventory 
![20210414_222147.jpg](https://user-images.githubusercontent.com/62821846/114804779-de36dc00-9d6f-11eb-9966-8688916e3626.jpg)

**Comment by wildchickenz** [comment]
🐛 Bug Report
Write a description of the bug here, give all the information you can about what it is, how it happened.

**Comment by Ktownstoner** [comment]
@gc sorry for tag just thought it would be easier as I don't know if you get notified for  comments. First thing thank you for fixing sandy. Second thing I thought sandy 3x loot at sand geckos was only if you had hunter master cape? Everyone is now getting 3x loot with sandy

**Comment by Ktownstoner** [comment]
At sand geckos that is

**Comment by Ktownstoner** [comment]
None masters at hunter are getting 3x loot while masters only get 2x @gc

**Comment by ArtMatters** [comment]
Mango fixed it.

**Comment by Ktownstoner** [comment]
@ArtMatters this was also posted 3-4days ago
