### ISSUE TITLE
[OSB[ New collection log items aren't purple

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1690]
## 🐛 Bug Report

When you get an item thats new to the log, the '1' doesn't become purple as it should. As you can see in the image below, I got a mace drop from nightmare and it was a new log item, yet it didn't change the '1' color. I've also noticed the same issue with my friend getting a Zalcano shard, which was new. 
![coxbug](https://user-images.githubusercontent.com/63373565/114812104-59eb5580-9d7d-11eb-865c-96835aedd3aa.png)

**Comment by gc** [comment]
This should be fixed now.
