### ISSUE TITLE
Clue hunter unicorn

### ISSUE THREAD

**Issue by englishfarms** [oldschoolgg/oldschoolbot#1696]
## 🐛 Bug Report

I went for the clue hunter outfit. Did it exactly as it said and got the whole set beside the boots and cloak. The unicorn at the beginning did not drop anything (boots and cloak). It will not give me the boots and cloak. Please fix. I need the set.

**Comment by mylife212** [comment]
Bump. still broken on BSO :(

**Comment by themrrobert** [comment]
Just tested again today, still broken =/

**Comment by themrrobert** [comment]
Fixed in [1902](https://github.com/oldschoolgg/oldschoolbot/pull/1902)
