### ISSUE TITLE
Bank image on —full

### ISSUE THREAD

**Issue by JordanPessman** [oldschoolgg/oldschoolbot#1698]
## 🐛 Bug Report
If you have a bank background image and view your full bank it overlays. Here's an example.![image](https://user-images.githubusercontent.com/56947136/114920228-d5391f80-9dee-11eb-886b-29cf7554a5ab.png)

Possible fix would be to only show original background / remove the custom one.

**Comment by JordanPessman** [comment]
Also note this isn't my bank I saw someone else and reported it.

**Comment by coolbop32** [comment]
=b --wide --full
