### ISSUE TITLE
minion error doing castle wars

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#1700]
## 🐛 Bug Report

do I'm doing +m to see how much time on cw I have left and I'm getting error on osb.![SmartSelect_20210416-014812_Discord.jpg](https://user-images.githubusercontent.com/68685674/114983261-01d45200-9e56-11eb-93ae-1f190137df04.jpg)

**Comment by gc** [comment]
Fixed.
