### ISSUE TITLE
Adding to old content before slayer launch

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1702]
## 🚀 Feature Proposal

not really a “feature proposal” but some commentary about slayer. It would be nice if, before slayer was added as the final skill for folks, for some things to be added/reworked on some of the older skills. For example, things like Zeah RC/ZMI/Lavas, power mining iron/chopping teaks, Angler fishing, the blast mine, and dark spellbook for reanimating dead crops for farming and ensouled heads for prayer. Most of which would have positive benefits to skilling and the current bot metas. 

None of these are make-or-break things, but it would be nice to have them in the bot before the last skill was launched. It would encourage more people to skill in certain skills which aren’t super popular rn because of the fact they’re slow and or people are waiting for these better methods to come out.

**Comment by thievious1** [comment]
Fully support this! Would love to see zeah rc added into the bot :)

**Comment by HouseParan73** [comment]
Zmi would be amazing - would also like to add that VM and BF would be great additions

**Comment by Jebusnorris** [comment]
i love all of these suggestions youve made +1

**Comment by Lajnux** [comment]
most of this is on it's way or resolved and Slayer is released, resolved

**Comment by mylife212** [comment]
While some of the content listed has been added/is being worked on... ZMI, Power mining, Angler fishing, blast mining and arceus spells (notably resurrect crop+ensouled head) haven't been added nor have I personally seen any mention of them being in the works yet. Feel its fair to leave this open, because it gives a good idea of some content the bot could benefit from.

**Comment by nwjgit** [comment]
Just about everything here has been added
