### ISSUE TITLE
[BSO] - =m kc shows Nex  KC as "undefined"

### ISSUE THREAD

**Issue by themrrobert** [oldschoolgg/oldschoolbot#1704]
Get some KC at nex, then do =m kc

In the results, Nex is 'undefined'
(The one between Mimic and Goldemar with178 KC)
![image](https://user-images.githubusercontent.com/10122432/115069984-345b6a80-9ea9-11eb-9dfd-d30c04ba667c.png)

**Comment by gc** [comment]
Should be fixed in next update.
