### ISSUE TITLE
Fish sack not extending

### ISSUE THREAD

**Issue by MoistWontons** [oldschoolgg/oldschoolbot#1710]
## 🐛 Bug Report

Fish sack not extending the trips.

I have fish sack equipped in skilling in these two screenshots. 

![](https://i.imgur.com/zfbFJvz.png)

![](https://i.imgur.com/GYEIpme.png)

I removed fish sack from gear, and these are the screenshots. 

![](https://i.imgur.com/a49kPrE.png)

![](https://i.imgur.com/KpWofiP.png)

With fish sack (lobster):

![](https://i.imgur.com/ppzTgYk.png)

Without fish sack (lobster):

![](https://i.imgur.com/LoSF31B.png)

As you can see, with or without fish sack equipped, i'm not getting any bonus or extended trips. I tried two different fishing trips one being barbarian fishing, and the other being salmon. 

Edit: Fixed screenshots & added another example.

**Comment by themrrobert** [comment]
Can confirm doesn't work. Also there's nothing in the code to support the Fish Sack extending a trip, so was probably just missed.

The BSO faq/guide says it should work: (Search 'fish sack')
https://github.com/oldschoolgg/obdocs/blob/master/BSO.md

**Comment by themrrobert** [comment]
I have written a PR that fixes this bug:
[1854](https://github.com/oldschoolgg/oldschoolbot/pull/1854)
