### ISSUE TITLE
Increase drop rate of gorajan shards

### ISSUE THREAD

**Issue by gramkuma** [oldschoolgg/oldschoolbot#1715]
Currently gorajan shards are extremely rare. Each gorajan set takes 10 shards to create while currently, the most any individual has received stands at 9. This renders the dg xp boost perk useless for ironmen, who won’t realistically completely any set before 99 and users who can’t afford to buy the shards. Moreover, it would be easier and cheaper to farm fire giants rather than bother getting a gorajan set. The number of hours you have to put in for a set that doesn’t offer much benefit really doesn’t add up.

**Comment by CottonDog** [comment]
you spelled "Sharts" wrong

**Comment by osrsolympus** [comment]
Hard agree. I’m level 113 with nearly 53m xp and I have 3 shards. It sucks for mains let alone the impact it would have on ironmemes

**Comment by jesseman1121** [comment]
I think putting the tokens back to what they were and making shards buyable through the shop at 1 - 2m tokens would be acceptable.

**Comment by Lilbourne** [comment]
Drop rate is just unbelievably low. I've averaged like 1/20m xp.some others have been luckier, but overall looks like 1/13m xp maybe? So low end around 390m xp for a full 30, or much more for something that ends up just boosting DG xp, and at that point you'd have already made a set and gotten a bit of an xp boost, probably putting you at master cape xp. Just seems odd. Irons are pretty much boned in that aspect.

**Comment by gc** [comment]
They were made more common after this issue was made.
