### ISSUE TITLE
All-time dry streaks

### ISSUE THREAD

**Issue by caffeinebean** [oldschoolgg/oldschoolbot#1723]
Hi, I was just talking to a few folks in the general chat and they said that all-time dry streak hiscores have not been implemented. It's such a shame to lose a glorious drystreak when you get the drop that you probably think doesn't exist after so many kills. Would it be possible to have a command for the all-time longest drystreaks?
Best wishes,
Current highest warhammer drystreak ironmeme

**Comment by gc** [comment]
This isn't really viable to do, sorry.
