### ISSUE TITLE
OSB 2 elite clues in 1 Zulrah trip, but only received one

### ISSUE THREAD

**Issue by Krendrian** [oldschoolgg/oldschoolbot#1724]
![2220CED7-AE32-46F5-964F-594524732266](https://user-images.githubusercontent.com/40904161/115829835-af061780-a3cc-11eb-9248-5ace4ce5fa0e.png)

**Comment by gc** [comment]
You can only have 1 of each clue tier at a time, its just a visual bug that it shows that you got 2.
