### ISSUE TITLE
[OSB]Remove busy check from certain actions

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#1726]
## 🚀 Feature Proposal

remove the minion busy check for certain events.

Currently, you cant check the number of tithe farm points, make tithe farm shop purchases or check farming contracts whilst busy.

I just proposed the change to conform with the majority of point-based systems and shops where it's able to be viewed and purchased from at any time. (Barb Assault, Mahogany Homes, Soul Wars, and although item based: agility arena and castle wars)

Mahogany homes is a good example. 

+mh 

gives the points and how to buy/start the activity

examples:
![Discord_hvRbnYwfFK](https://user-images.githubusercontent.com/12814878/115850218-97a34a80-a41d-11eb-990b-235479cf7f20.png)
![Discord_L4u8vzwJlU](https://user-images.githubusercontent.com/12814878/115850221-983be100-a41d-11eb-8203-6aea81560b9c.png)

**Comment by gc** [comment]
Is fixed now i think.
