### ISSUE TITLE
Corrupted Gauntlet Only Awarding 2 Loot Rolls

### ISSUE THREAD

**Issue by ArtMatters** [oldschoolgg/oldschoolbot#1732]
Currently the corrupted gauntlet is only rolling 2 loots on the normal loot table instead of 3 like it should be. 

https://oldschool.runescape.wiki/w/Reward_Chest_(The_Gauntlet)#Corrupted_Gauntlet_Completed

https://cdn.discordapp.com/attachments/343218314694361088/835626206119460914/file.jpg

**Comment by gc** [comment]
Fixed in next update.
