### ISSUE TITLE
Bank search not working

### ISSUE THREAD

**Issue by jayocz** [oldschoolgg/oldschoolbot#1736]
When using the bank search tool =b —search=bolt 

it is not showing runite onyx bolts.
Even on checking the name on —names it shows bolt in the name.

I have done this in the past but just recently it has stopped working.

it shows all other bolts expect these. 

please pm me in game for pictures !

**Comment by osrsolympus** [comment]
![064028D3-8F99-4150-80C2-0C348910B129](https://user-images.githubusercontent.com/65320787/116005331-733d9e80-a5d4-11eb-9926-97b2aceb44f5.jpeg)


Should be working. Maybe link your photos in a new comment so they’re part of the issue itself.

**Comment by jayocz** [comment]
It’s working now musta been a glitch in the system
