### ISSUE TITLE
COX CM Capes

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1738]
## 🐛 Bug Report

Could be wrong, but we didn’t see it in the code and testers didn’t know, but it doesn’t look like cm raids gives you the milestone capes

**Comment by mylife212** [comment]
Magna confirmed that CM capes aren't obtainable right now.

Going to piggyback this thread and add that CM capes should be removed from the collection log until they are added. Its silly to have something thats not obtainable in the log!

**Comment by gc** [comment]
Buyable in next update.
