### ISSUE TITLE
Check Active Raids command

### ISSUE THREAD

**Issue by calumcook** [oldschoolgg/oldschoolbot#1751]
At the moment with few raiding groups it is difficult for inactive players to know whether it's best to start a raid or wait for a bigger group to finish, or to know how long the wait is for a next big group to come back and there be the potential to start a new raid. If you miss out and form a smaller team you are penalised by the raid taking longer and thus being out of sync with the raiding groups.
Suggestion: a +checkraid or +activeraid command that shows the next 3/5/10 raids to finish in a specific channel so people know how long until a big group return and can be aware of when they need to loiter in the channel to join or can start their own mass raid/complete other minion tasks if the next group is a while away (10+ minutes).

**Comment by gc** [comment]
`+checkmasses` is added now
