### ISSUE TITLE
Double joining at raids

### ISSUE THREAD

**Issue by islauch** [oldschoolgg/oldschoolbot#1756]
## 🐛 Bug Report

I joined a raid mass but before the team left I decided to wait and do a farm run in the meantime. I clicked the "join" reaction to leave the team and my name was taken off the list of participants. But, when the raid began I was listed as going (1 of 3). I didn't check if my supplies were used or not. A "+m" command returned that my minion was doing nothing. After my farm run I joined another raid (1 of 13 participants) and set off. The 13 man raid returned before the 3 man raid. When the 13 man raid returned, I even had time to clean some herbs in between raids on the minion. Then I joined another raid mass queue, while waiting the 3 man raid returned and I got loot. I checked my kc and I went up 2 kc compared to before joining either raid, so both counted. I thought that I had quit the first raid since "+m" did not tell me I was in a raid.
Not sure if this works every time but possibly abusable for double loots.

**Comment by gc** [comment]
Should be fixed now.
