### ISSUE TITLE
Message people when a mass is canceled or fails.

### ISSUE THREAD

**Issue by ArtMatters** [oldschoolgg/oldschoolbot#1757]
Currently if you join a mass and the mass get's canceled you have no way of knowing. This leads to wasting time doing nothing with no way of knowing except watching the chat until your mass leaves. It would be helpful to @ the people who tried to join the mass.

**Comment by AvariceBrah** [comment]
I second this. A ping to the users that joined in channel or a dm would be useful, much like the one you get when you attempt to join a raid or mass you don't have the req for.
