### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by Hanzigamer** [oldschoolgg/oldschoolbot#1759]
When doing +m to check how long minion has left on trip whilst on +collect I get "An unexpected error occurred" message, and it wont tell me how long its left. I got the message while collecting Mort myre fungus.

https://gyazo.com/a6f1eee57b7ef77c81af2edcb8380c7d

I will test on others aswell to see if it happens there aswell or if its just for fungus

**Comment by Hanzigamer** [comment]
Its also same message for snape grass

https://gyazo.com/78944c7b2c72f1895f68e5e197966a29

**Comment by gc** [comment]
Fixed in next update.
