### ISSUE TITLE
=minion long-form not working

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#1761]
![SmartSelect_20210428-222232_Discord.jpg](https://user-images.githubusercontent.com/68685674/116499894-e401e680-a872-11eb-905a-fc49a318c25b.jpg)

so doing =m kc shows killcounts. 

when I type =minion killcounts 
or =minion questpoints it shows the equivalent to =m as @osrsolympus kindly pointed out

which I feel is a bug because it is the long form of the command

**Comment by osrsolympus** [comment]
More specifically, =minion killcounts acts as =m and not =m kc

**Comment by imTURBObro** [comment]
> More specifically, =minion killcounts acts as =m and not =m kc

what do you mean  =m would show me what my minion is doing rn.

=m qp is quest points. also works as =minion qp or =minion questpoints

**Comment by imTURBObro** [comment]
> More specifically, =minion killcounts acts as =m and not =m kc

ur so right.  completely blank minded on that. I fixed the post

**Comment by Lajnux** [comment]
with slashcommands this is no longer a issue
