### ISSUE TITLE
Sacrifice/Create bug

### ISSUE THREAD

**Issue by Flavvs** [oldschoolgg/oldschoolbot#1763]
## 🐛 Bug Report

I’ve got my own server that only I use, and I use both bots in it.  On the BSO bot I finally got the levels to make the spirit shields so I can get the corp background.  I made 2 of each shield.  I then sacrificed 1 of each shield but did it all in 1 command.  I now cannot find an Elysian, arcane or spectral in my bank but the divine has stayed.  Unsure where they’ve gone or what’s happened.  Have photos of my making them and the sacrifice (sacrifice should also be in notifications).

**Comment by osrsolympus** [comment]
Can you post a screenshot of the command you used?

**Comment by Flavvs** [comment]
![Uploading AD83E14C-2AD9-470E-9C05-EBDA9F86B511.png…]()

**Comment by Flavvs** [comment]
![19B7E56A-FC1E-4456-BE4A-A53134FDF1A3](https://user-images.githubusercontent.com/83394635/116595132-e7e94380-a91a-11eb-85de-99a7513bca52.png)
![F2F49FBC-D1B0-4BA7-870B-0E43C00B7414](https://user-images.githubusercontent.com/83394635/116595153-eb7cca80-a91a-11eb-82c8-363331a8ec1c.png)
![186A02D5-BA83-4C7E-B0C2-C47080B0A25F](https://user-images.githubusercontent.com/83394635/116595162-efa8e800-a91a-11eb-97bc-8bd4c62abb62.png)
![B61F0E54-AF85-420D-83CE-185011D7346E](https://user-images.githubusercontent.com/83394635/116595170-f33c6f00-a91a-11eb-8d81-ffff95f9d86c.png)

**Comment by 6enny6** [comment]
no bug, you used =sacrifice which removed 1 set of shields, and then the bankbg command did the second set, shouldn't have done =sacrifice

**Comment by thievious1** [comment]
closing for benny :)
