### ISSUE TITLE
Not getting ranged xp from killing Nightmare

### ISSUE THREAD

**Issue by Drakhna** [oldschoolgg/oldschoolbot#1765]
## 🐛 Bug Report

Melee and Magic xp received was fine from both group and solo kills.

**Comment by osrsolympus** [comment]
Presumably this is because you don’t use ranged to kill the nightmare, therefore you can’t train ranged there

**Comment by Drakhna** [comment]
Makes sense but then you shouldn't receive any magic xp either.

**Comment by osrsolympus** [comment]
Magic is highly advised to be used in both group and mass kills when taking down the pillars so I guess Magna included it for that reason.

**Comment by ArtMatters** [comment]
> Magic is highly advised to be used in both group and solo kills when taking down the pillars so I guess Magna included it for that reason.

Powered staves do not grant xp on pillars so you shouldn't get xp. The only xp you would get would be from spells cast like vengeance or fire surge base xp only. I'd be in favor of removing magic from nightmare as well.
