### ISSUE TITLE
Smelting help! 

### ISSUE THREAD

**Issue by jayocz** [oldschoolgg/oldschoolbot#1773]
I think klik needs a bit of a refresh & update his ability causes him to almost be pointless & it’s a shame! He’s a cute lil dragon 

& ring of forging isn’t coded. 

It’d be cool to see an ability where if equipped he reduces the amount of iron wasted on each trip, and maybe like a chance of double ore (similar to Varrock plate body) just something a little more niche for him!

**Comment by nwjgit** [comment]
Run a poll here https://discord.com/channels/342983479501389826/1032668754561224734
