### ISSUE TITLE
=b and =open returning unexpected errors

### ISSUE THREAD

**Issue by TheHoneybadger-VI** [oldschoolgg/oldschoolbot#1774]
## 🐛 Bug Report

The =b and =open functions have been returning unexpected errors rather than showing my bank / openable items. I can check how much gp I have with =gp, send gp to other people and sell items to other people fine though. Only been happening for the last 6 hours.

**Comment by 6enny6** [comment]
do `checkbank --fix` and itll work again

**Comment by TheHoneybadger-VI** [comment]
Thank you!
