### ISSUE TITLE
Add an option to use staminas when doing herbi instead of using them by default.

### ISSUE THREAD

**Issue by Jebusnorris** [oldschoolgg/oldschoolbot#1775]
## 🚀 Feature Proposal

Using stams for herbi is efficient ingame but it isnt a requirement. it isnt either on the bot, but stams are automatically used if they are in your bank which means you have to use them all elsewhere before doing herbi if you dont want to use them there.

Change herbi so that stams can be used with a command like --stamina similar to how the compost is used for farming, and add a similar command for herbi like the +defaultfarming tier compost/supercompost/ultracompost but instead something like:
+defaultstaminaherbi yes/no or something similar and on case by case basis can use +hunt herbi --stamina

thanks

**Comment by Lajnux** [comment]
resolved, you can do !hunt herbi --ns which makes your minion not use staminas
