### ISSUE TITLE
Ability to set a gear requirement when hosting a CoX mass

### ISSUE THREAD

**Issue by bowiRS** [oldschoolgg/oldschoolbot#1779]
it is annoying to see leeches with 80% or less joining raids. It would be nice if the host can set a minimum requirement.

Example: 

+raid mass 95

This would only allow people with 95% or more to join. There should be a maximum though as people spamming 99% or 100% raids would get annoying. 95% sounds like a reasonable amount.

**Comment by Shadalah** [comment]
Add boost req for tbow/dhcb too

**Comment by nwjgit** [comment]
It's been established in the main discord server that gatekeepting/eliteism for raids isn't allowed. Your best bet to have minimum requirement raids is to play in a different server.
