### ISSUE TITLE
Items list usage

### ISSUE THREAD

**Issue by moz3arte** [oldschoolgg/oldschoolbot#1781]
## 🚀 Feature Proposal (mainly a guidance and not a feature, but also can be a feature added to the bot)

I know kinda big thing to ask, but as many of OSB users (including some friends of mine) didn't ever played runescape, i would like to see a full items list, aswell as they function ingame, mainly what items can we create, what pets do we have/what they do, some items like GWD pages description and they usage, etc.

**Comment by osrsolympus** [comment]
I would suggest using the +w command which will pull up the official OSRS wiki page for just about anything you can think of. It won’t cover the custom bso stuff but that’s usually covered by the BSO news posts

**Comment by nwjgit** [comment]
slash commands, item search, osb/bso wiki and osrs wiki provide everything you're looking for.
