### ISSUE TITLE
+open Egg Sacs Broken

### ISSUE THREAD

**Issue by mplumador** [oldschoolgg/oldschoolbot#1787]
## 🐛 Bug Report

The latest update for OSB removed the ability to open egg sacs dropped from Sarachnis. Will look into the revision history to try and find the breaking change.

**Comment by mplumador** [comment]
It appears to have been broken in oldschool js with this commit:
https://github.com/oldschoolgg/oldschooljs/commit/b4bd7bafc17dc6acfb62a70581b607b3d3a41745#diff-83094b5a1b45ab92abed92ce00a37223f615fa829234efcf9bbed3fd2f1805ad

The import for gianteggsacfull has been removed

**Comment by mplumador** [comment]
This change also breaks opening nest boxes retrieved from birdhouses or trading in giant mole items.

**Comment by gc** [comment]
Should be fixed in next update.
