### ISSUE TITLE
small trip bug with questing

### ISSUE THREAD

**Issue by ReZeroed** [oldschoolgg/oldschoolbot#1797]
## 🐛 Bug Report

After my quest trip ended it gave me a prompt to send again with q, doing =q however sent two trips at the same time and gave twice the rewards after the trip ended.
![image](https://user-images.githubusercontent.com/75293942/117048438-188c0b80-ad67-11eb-994f-db88d17ec661.png)

**Comment by 6enny6** [comment]
bump

![image](https://user-images.githubusercontent.com/76587427/121226230-3aa30d00-c882-11eb-8a42-d9b070571a70.png)
