### ISSUE TITLE
=clbank bug

### ISSUE THREAD

**Issue by AvariceBrah** [oldschoolgg/oldschoolbot#1803]
## 🐛 Bug Report

![Screenshot_20210505-224121](https://user-images.githubusercontent.com/77698878/117309165-cc64c800-ae47-11eb-8083-2dc4f479ef5e.png)

This is my favorite command and approx 33% of the reason I like T3+

Clbank returns that Item does not exist. Checkbank --fix returns 0 and does nothing. Functions fine on osb. Jess also has both clbank nonfunctional upon asking in support.

**Comment by gc** [comment]
In the next update, `=checkbank --fix` should fix your CL bank too.
