### ISSUE TITLE
a change to =cl capes

### ISSUE THREAD

**Issue by IronBump** [oldschoolgg/oldschoolbot#1804]
Same as OSB, remove the untrimmed capes but replace them with the 500m skill cape varients. (or add a =cl master capes)

This got 3 :HamPog: when i suggested so i guess that makes it a priority

**Comment by gc** [comment]
Done in next update:
![file](https://user-images.githubusercontent.com/30398469/117551476-8a2ac900-b089-11eb-9ff5-f7b1a01ac4f1.png)
