### ISSUE TITLE
+m stats --rank

### ISSUE THREAD

**Issue by permedd** [oldschoolgg/oldschoolbot#1815]
## 🚀 Feature Proposal

It would be similar to +m stats, except instead of displaying your level or stats, it will display your rank. For example, if I have 99 woodcutting, I'd like to know what rank I am in woodcutting. or maybe we should make it so that you have stats (Level), xp, and rank, but it will be too long? I'm not sure.

**Comment by nwjgit** [comment]
lb pretty much handles this now
