### ISSUE TITLE
Mally bonuses changed to 'OR' instead of 'AND' after merge.

### ISSUE THREAD

**Issue by themrrobert** [oldschoolgg/oldschoolbot#1816]
Now Mally only gives 5% for ONE of the following:
BGS / SGS / DWH.
If that were meant to be the case, it would give more than 5%.

And before anyone asks, it definitely makes sense to use 3 spec weapons at a boss that takes 8 to 10 minutes per kill.

Plenty of time to DWH + BGS spec, SGS spec 2.5 minutes later (mid-kill), and then have 100% by the end of the kill for the next spawn.

**Comment by themrrobert** [comment]
Looks like it was related to the "Exclusive Item Boosts" patch.

Malygos didn't get the { } treatment on it's boosts, so it was interpreted as an OR instead of an AND.

Updated example:
![image](https://user-images.githubusercontent.com/10122432/117541987-6e60ed80-afcb-11eb-8c79-c556f1e73733.png)

Malygos (AbyssalDragon):
![image](https://user-images.githubusercontent.com/10122432/117542023-a23c1300-afcb-11eb-8a32-c787f58cbbb0.png)

**Comment by gc** [comment]
Fixed in next update.
