### ISSUE TITLE
BIS Necklace won't equip even after having requirements

### ISSUE THREAD

**Issue by AlphaQLater** [oldschoolgg/oldschoolbot#1818]
## 🐛 Bug Report

I just crafted all the three bis necklaces, brawler's hook necklace, arcane blast necklace and farsight snapshot necklace. But when I tried to equip them I get a message saying that I need either 99def,mage,range and 99 dung to wear, I have all these requirements. I posted on help and support channel to ask for help and was redirected to bug report to report this possible bug, please help 
![Screenshot_20210508-063225589 (1)](https://user-images.githubusercontent.com/81002347/117523171-56d43580-afc8-11eb-9124-db9a5e2e4c6d.jpg)
![Screenshot_20210508-063553151 (1)](https://user-images.githubusercontent.com/81002347/117523176-5dfb4380-afc8-11eb-9373-22b094e98359.jpg)

**Comment by 6enny6** [comment]
Definitely broken, 
Slippy had all 3 equipped already so clearly has the requirements too
I asked him to unequip them and try again to test it and now it won't let him re-equip, same error

**Comment by gc** [comment]
Fixed in next update thanks to benny.
