### ISSUE TITLE
Grace working in misc 

### ISSUE THREAD

**Issue by HouseParan73** [oldschoolgg/oldschoolbot#1823]
## 🚀 Feature Proposal

Let grace effect work while its equipped in misc setup. Would be a nice qol to not have to constantly switch between a skilling setup and grace every ~50 mins when you want to do a farm/bh run

**Comment by IronBump** [comment]
use gear presets, kinda what they were made for

**Comment by HouseParan73** [comment]
I do, doesn't change the fact that every 50 mins you're having to change your gear setup, again its a qol change

**Comment by gc** [comment]
In the next update, graceful will now work in any setup, in every place that its used.
