### ISSUE TITLE
=/+buy Arclight/Demonic Gorillas

### ISSUE THREAD

**Issue by sunnyzulu** [oldschoolgg/oldschoolbot#1825]
As we all know, Ironmen do have a rough time getting some BIS gear that ONLY come out of TMBs/UMBs/EMBs/Clue Caskets, specifically the neck slot. 

Firstly, i'd like to propose we add =/+buy Arclight after having so many quest points, my idea would be around 120. It could possibly give a small bonus (2-5%) to fighting anything "Demon", like K'ril Tsutsaroth, Cerberus, etc.

I would also like to propose we add Demonic Gorillas to OSB (and BSO if needed). They are a vital part to OSRS Ironmen, and they would help out big time on the bot.

I think the perfect way it could work would to be to have at least 200 quest points to kill, along with having at least Armadyl Crossbow and Arclight. The drop rate on the Zenyte Shard would stay the same as in-game (1/300) along with adding Ballista to the game (I have thought of no use for this yet as it is famously a PK weapon), and then adding a new monster for Clue Scroll drops (Hard Clue 1/100 Drop Chance, Elite Clue 1/500 Drop Chance).

**Comment by osrsolympus** [comment]
Demonic gorillas are locked behind a slayer requirement and will be released with slayer

**Comment by sunnyzulu** [comment]
What slayer requirement do Demonic Gorillas have?

**Comment by TizHub** [comment]
MM2 - 69 slayer or w/e

**Comment by sunnyzulu** [comment]
I mean whereas that is true, then we shouldn't be able to buy quest cape without the proper slayer level either.

**Comment by TizHub** [comment]
Bot has some inconsistencies, they'll come eventually :)

**Comment by osrsolympus** [comment]
No slayer mobs other than Cerb are part of the bot, and cerb’s status is locked. As much slayer content is locked as possible at the moment. Eventually you probably will need skills to buy a quest cape

**Comment by mylife212** [comment]
Slayer is coming out for OSB soon (out in BSO), and both of these are included in the update
