### ISSUE TITLE
[BSO] Can't equip max cape

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1827]
## 🐛 Bug Report

Max capes now have a requirement to have 2277 total before being worn. This does makes sense but it also requires 99 slayer, making it literally impossible to  equip any max cape in BSO. I haven't heard anything on whether this is intentional or not, so most likely a bug. Could be a merging error too, who knows. 

Link has the bug https://i.imgur.com/J5JItkE.png

**Comment by gc** [comment]
Fixed in next update.
