### ISSUE TITLE
[BSO] 2x Loot bugged with groupkill/mass - gives 2-3x entire loot to host

### ISSUE THREAD

**Issue by themrrobert** [oldschoolgg/oldschoolbot#1835]
I'm not sure if this is in the live code, I just found it while reading the code and don't want to abuse it assuming it is a bug. ( I never noticed anything while hosting, but I never actually compared my bank before + after receiving a 2x )

1st of all, it duplicates EVERYONE's loot and gives to the host. I don't think that's intended...

2nd: It TRIPLE's any non-ori loot, but just doubles any ori-loot.

Relevant code below. As you can see, it adds each players "loot" to "totalLoot", and then after adding Ori loot, it adds their loot AGAIN to totalLoot. So when "handleTripFinish()" is called (only for the host) it gives 2-3x of everyone's loot to the host.

Proposed solution: 1) Make a handleTripFinish-like function work for each player and their respective loot, sort-of like dungeoneering, and of course 2) only count the loot AFTER ori, not before+after.

Temporary stop-gap: Don't pass loot to handleTripFinish on groupkill/mass. (Essentially disables 2x altogether). Not ideal, but will prevent abuse while a better fix is implemented.

groupMonsterActivity.ts:
```
		//for each user in the mass...
			totalLoot.add(loot); //ADDS EACH PLAYERS LOOT TO totalLoot
			const kcToAdd = kcAmounts[user.id];
			if (user.equippedPet() === itemID('Ori')) {
				loot = addBanks([monster.table.kill(Math.ceil(kcToAdd * 0.25)) ?? {}, loot]);
			}
			await user.addItemsToBank(loot, true);
			totalLoot.add(loot); //ADDS LOOT AGAIN
...
		handleTripFinish(..., totalLoot.bank);  //Only host gets the handleTripFinish function
```
handleTripFinish.ts:
```
	//"totalLoot" from groupMonsterActivity.ts is passed as "loot"
		const bonusLoot = new Bank().add(loot).add(getRandomMysteryBox());
		message += `\n${emoji} **You received 2x loot and a Mystery box.**`;
		await user.addItemsToBank(bonusLoot, true);
```

**Comment by gc** [comment]
Should be fixed in next update.
