### ISSUE TITLE
Add a way for players to use Dark relics & random event XP items

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1837]
## 🚀 Feature Proposal

 They should be usable in OSB/BSO, and I think a great way is to copy what BSO does with EXP lamps, where its "=lamp [lamp tier], [skill].
NOTE: In OSRS, Dark relics are functionally an EXP lamp that use a different scaling system depending on the skill, wiki has info on it.

The command would be like: +lamp antique lamp/book of knowledge/dark relic, Herblore.

**Comment by TizHub** [comment]
bump

**Comment by Anzosa** [comment]
bump

**Comment by mylife212** [comment]
bump, should be reasonable to add now that we have the lamp command in OSB!

**Comment by Lajnux** [comment]
resolved
