### ISSUE TITLE
[BSO] Prayer Master Cape not working on Shared style (at mole)

### ISSUE THREAD

**Issue by themrrobert** [oldschoolgg/oldschoolbot#1838]
## 🐛 Bug Report

Killing mole with dwarven blessing on Shared attack style.

I know the prayer cape is supposed to be on the active style, which is forced range, for example on Sea Kraken.

I tried the Prayer Master Cape in every slot, melee, range, and mage, just in case it was forcing mage because mole is melee. 

Never got the reduced ppot usage =/

/edit: I also tried just =train attack, with the Prayer Master Cape equipped in Melee, and that didn't work either =/.

Suggestion: Just make Prayer Master Cape check use isEquippedAnywhere

**Comment by themrrobert** [comment]
Also tried with fire giants, 
=train shared, Prayer Master Cape in melee slot, no reduction :(

**Comment by themrrobert** [comment]
So this bug seems to affect ALL monsters that don't have a 'forced' combat style such as kraken/zily/mally. 

Tried =train ranged with Prayer Master cape in range slot, still didn't work.

**Comment by gc** [comment]
Fixed in next update.
