### ISSUE TITLE
Scale Golden Nuggets to amount of ores, just like real life :)

### ISSUE THREAD

**Issue by themrrobert** [oldschoolgg/oldschoolbot#1841]
## 🚀 Feature Proposal

Would like the amount of nuggets received to scaled to the number of ores mined.

Current the rate is 7 nuggets/hr on average regardless of level.

I have created a PR [1840](https://github.com/oldschoolgg/oldschoolbot/pull/1840) that will target 10 nuggets/hr at level 99 without boosts, and will scale linearly based on the number of ores mined. Lower levels will see less nuggets per hour, but will see greater nuggets per hour as their ability to mine more ore increases with level.

The number of nuggets/hr at level 99 can easily be changed by a simple calculation included in the PR.

**Comment by Lajnux** [comment]
Tasty is working on motherload mine that gonna resolve this, therefor closing this issue.
