### ISSUE TITLE
Trailblazer Graceful not being recognized for bonuses

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#1849]
## 🐛 Bug Report

I have a mixture of trailblazer and dark graceful. equipped in skilling and blast furnace is penalizing me saying I do not have graceful![Screenshot_20210512-033719_Discord-Beta.png](https://user-images.githubusercontent.com/68685674/117945288-ccdfe180-b2d3-11eb-9ea8-f6634d89de1d.png)

**Comment by gc** [comment]
Trailblazer graceful should be fixed in the next update.
