### ISSUE TITLE
Ironman QOL 

### ISSUE THREAD

**Issue by RagingCaucasian** [oldschoolgg/oldschoolbot#1851]
The idea that i have for Ironman is something that i encountered today while on my ironman, I havent had an ironman account for long and Gp for early game food for bosses was always a struggle, i checked in my bank today using =b --sv to see what i could Alch for some good gp to buy some potato's with cheese so i could do some zulrah, I looked at my bank value and it was worth nearly 800m and i was shocked i didnt think i had that much, but that amount is set in Bot sale price not Alch value, so i was hoping Anyone not just Ironman can use the =b --av (Alch Value) just so we can have a visual of what we could alch for some gp.

Thanks,
RagingCaucasian.

**Comment by zabiros** [comment]
ye, would be nice. got my support! +1

**Comment by wildchickenz** [comment]
I don't see why this shouldn't exist, shouldn't be difficult since alch values are already inputted for items. Maybe even reorder the bank to alch value instead of sacrifice value

**Comment by RagingCaucasian** [comment]
> I don't see why this shouldn't exist, shouldn't be difficult since alch values are already inputted for items. Maybe even reorder the bank to alch value instead of sacrifice value

This ^^^ Should add that too

**Comment by imTURBObro** [comment]
> I don't see why this shouldn't exist, shouldn't be difficult since alch values are already inputted for items. Maybe even reorder the bank to alch value instead of sacrifice value

I completely agree with @wildchickenz on this and I completely love your idea @RagingCaucasian . you are 100% right I remember looking at a price of something, went to alch it and instantly wish I hadn't lol. wasn't worth it. so u got my vote 1+

**Comment by AvariceBrah** [comment]
=b --alv or --av
(Alch value) would be a brilliant addition. I literally alch what I know alched decently in the main game or junk XD

Thumbed up

**Comment by gc** [comment]
Added `--av`, available in next update.
