### ISSUE TITLE
King Goldemar suggestion 

### ISSUE THREAD

**Issue by chefslav** [oldschoolgg/oldschoolbot#1852]
**King Goldemar** 
-Add blacksmith outfit to Dwarven Crates (required to fix the hammer + gives Crates more of a use)
-Make the Goldemar CL get filled with the hammer drop instead of fixing the hammer with smithing (currently you can have 0kc and have the logged filled in) **--ADDED ON UPDATE 5/13/2021 THANK YOU!**
-Buff ore/crate drop rate, even if just slightly. 
-Allow Irons to kill goldemar
-**For Irons Only** lower the smithing requirement to fix hammer from 120 to 110

Additional notes:
-If the above changes are made, leaving the current dwarven warhammer rate would be fine, keeping the item rare but incentivizing more users to mass. 
-Irons having a reasonable method of accessing the hammer will also increase the massing population. 
-Dwarven ore has a high failure rate when smelting, do not change this, but increase the amount of dwarven ore coming in - again, another incentive to mass goldemar without making him a resource simulator.  
-Blacksmith outfit coming from crates or the KG drop table makes it more reasonably accessible, especially for irons that can't just purchase boxes. 

-In the last 3 months, since the DWWH was changed to drop as broken and was made rarer, there has been roughly 1 hammer coming into the game per week. There was a 23 day drystreak for a hammer drop not very long ago. 
-there are currently only 7 users with the smithing level required to fix a broken hammer, the odds of all of them having the blacksmith outfit as well is unlikely. 

Edit 5/16/21: - Also I am not against gear boosts/higher reqs to join. Currently 80 crush attack bonus and food is all that is needed to join mass. Upping this to +120 stab/slash or something would be fair I think.

Thank you for coming to my TED talk. 

![image](https://user-images.githubusercontent.com/72408891/118062994-cdbd5580-b35d-11eb-8e9c-4641a205d66b.png)

**Comment by themrrobert** [comment]
Great suggestion, love it all. Keeps hammer rare + valuable while incentivizing more people to mass this boss. 
I would like to add that for irons (and maybe mains too) it would be nice if the blacksmith parts chose a random blacksmith CL slot that was empty, only giving dupes if they're all filled in.

**Comment by mylife212** [comment]
I agree with themrrobert, this is an incredible suggestion. Would love to see this happen! Ironmen having access to Goldemar (and perhaps 110 smith for DWWH) will definitely increase activity too.
