### ISSUE TITLE
[BSO] Master mining cape perk

### ISSUE THREAD

**Issue by 000000653** [oldschoolgg/oldschoolbot#1853]
## 🚀 Feature Proposal
My idea for a master mining cape perk would be to make it so you can rarely get dwarven crates or ores from mining, a rate scaling on length of trip rather than different chances per ore or anything like that.

Probably a rate like 1/1,500 per 1 minute, that'd scale up to 1/50 for a 30 minute trip. If you're doing 32 30 minute trips per day (16 hour days), 1/50 means you'll expect a drop every 25 hours, so a bit over a day and a half of actively mining. Bars look to be 1b each in ge atm, so factoring in 35% chance to fail smelting and 25 hours per bar, this would add about 26m per hour in value to mining. Obviously numbers and rates are flexible if Magna thinks this is unbalanced or whatever, but I think it'd be pretty well balanced.

I'm not sure if crates or ores would be preferable, crates would lead to ores/time being rarer obviously but there's been talk of adding outfit to the crates and I'm not sure you wanna increase the supply of outfit by very much. I think I'd prefer just ores.

**Comment by chefslav** [comment]
I think leaving crates as a goldemar  only drop would be good, but dwarven ore from the cape honestly sounds fair. 120 mining is a big req and only ~5 people have it currently. 

High level req? check
Incentive for users to mine? check

you've got my support on this

**Comment by 000000653** [comment]
bump

**Comment by gc** [comment]
#bso-vote for bso content ideas/suggestions
