### ISSUE TITLE
Prospector boots

### ISSUE THREAD

**Issue by 2Kurrupted** [oldschoolgg/oldschoolbot#1856]
## 🐛 Bug Report
Prospector boots issue where from what I can tell owning both 'Prospector boots' and the 'Golden Prospector Boots' causes it to happen. 
If I search 'Prospector' (=b --search=prospector) I am shown both pairs, however when I directly bring up the standard pair of 'Prospector Boots' (=b Prospector Boots) I am shown a 'Golden Prospector Boots' image instead. 
![Screenshot_20210514-122846_Discord](https://user-images.githubusercontent.com/79731323/118203850-133e6780-b4b1-11eb-9cca-5b9a75026b52.jpg)

**Comment by gc** [comment]
This should be fixed now.
