### ISSUE TITLE
Remove CoX Scrolls announcements from #Notifcations

### ISSUE THREAD

**Issue by animelewds** [oldschoolgg/oldschoolbot#1857]
Just like champion scrolls, these CoX scroll drops are clogging up the #notification channel.
![Screenshot 2021-05-13 193919](https://user-images.githubusercontent.com/81213988/118204033-ecd1eb00-b422-11eb-9692-a68cc243dc7a.png)

**Comment by gc** [comment]
Fixed in next update.
