### ISSUE TITLE
[BSO] Offhand Mace Boost Doesn't Work at KK

### ISSUE THREAD

**Issue by shelixd** [oldschoolgg/oldschoolbot#1859]
Offhand mace boost isnt working at KK. Not sure if its actually not working or if the boost message is just missing.

sheli~: 8% boost for full Torva, 14% boost for Drygore mace, 4% boost for KC, 13% for sheli~ over 300 kc. Dy lol: 8% boost for full Torva, -5% penalty for KC. Larry: 8% boost for full Torva, 14% boost for Drygore mace, 4% boost for KC, 13% for Larry over 300 kc.

I should have an extra 5% over the rest of my team for the offhand.

**Comment by gc** [comment]
Should be fixed now.
