### ISSUE TITLE
BSO Box Bug

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#1860]
## 🐛 Bug Report
 Visual bug where, after opening some boxes, opening more boxes of the same quantity, you appear to get the same items as the initial open. This is persistent and opening a different quantity of boxes does not reset the visuals on quantities previously opened.

**Comment by mylife212** [comment]
This same bug seems to happen with bank searching, I'd imagine they share the same root cause. https://i.imgur.com/GwPUFxj.png

**Comment by gc** [comment]
Fixed.
