### ISSUE TITLE
Sacrifice Leaderboard Down

### ISSUE THREAD

**Issue by Keyzz112** [oldschoolgg/oldschoolbot#1878]
## 🐛 Bug Report

Sacrifice leaderboard failing to load, just leaves up a loading screen shown. 

![170c19ed95bcf05829f26e835435f58c](https://user-images.githubusercontent.com/84282305/118403464-58f06100-b666-11eb-8d18-69d0ab809db2.png)

**Comment by mylife212** [comment]
Issues seems to have resolved itself when bot rebooted https://i.imgur.com/vQHPttt.png
