### ISSUE TITLE
Nightmare KC shows up as "undefined" in the +m kc command.

### ISSUE THREAD

**Issue by eggaroonie** [oldschoolgg/oldschoolbot#1881]
## 🐛 Bug Report

Pretty much what the title says.
(Nightmare KC is under Vorkath)
![Screenshot_20210516-180105](https://user-images.githubusercontent.com/84296933/118419404-bc7f8c00-b670-11eb-9caf-8700de9be547.png)

**Comment by gc** [comment]
Fixed in next update.
