### ISSUE TITLE
Santa Outfit not counting as warm clothing

### ISSUE THREAD

**Issue by ImMrJens** [oldschoolgg/oldschoolbot#1895]
## 🐛 Bug Report

Santa Outfit is not counting as warm clothing for wintertodt!
Equiping it does not reduce food consumption =(

(OSB)

**Comment by themrrobert** [comment]
Infernal harpoon, clue hunter, bunny outfit, etc also don't count as 'warm items'

Basically only 'fire' items (fire cape, staff of fire/ fire battlestaff/ infernal axe/pickaxe / fm cape) + pyro garb, warm gloves, bruma torch, tome of fire count as warm clothing currently.
