### ISSUE TITLE
[BSO] Can't get clues from Skilling if you have clues banked

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1910]
## 🐛 Bug Report

You cannot receive any clue scrolls from skilling in BSO if you have clues banked. I believe this is because skilling clues follow the same limit as the main bot, where it checks for any clues in the bank before rolling, to ensure you don't get duplicates. Because there isn't a clue cap in place for BSO, clues from skilling should be changed accordingly.

This bug is present in mining, and I'd assume for fishing & woodcutting too. Me and my friend have done hundreds of mining trips with no clues, confirming this bug exists.

**Comment by gc** [comment]
Fixed in next update.
