### ISSUE TITLE
Leagues

### ISSUE THREAD

**Issue by gc** [oldschoolgg/oldschoolbot#1912]
The purpose is to get the twisted league rewards in OSB.

The twisted league, would be BSO itself, for several reasons:
- Dev time is minimal, creating and running a 3rd bot for twisted leagues would be a lot.
- BSO is already a twisted league kind of thing, it's a fork of osb with hyper/custom changes.

The only issue is that BSO is a permanent thing, not seasonal, yet in osrs it's seasonal
- the upside is, anyone can participate whenever, with no time pressure or constraints.
- you would get points, and still have access to the leagues rewards of all seasons, not just 1.

In leagues you get points for reaching certain levels and killing certain bosses, many people in bso are already maxed and have killed lots of bosses?
Well, they would indeed get instantly lots of points for that. This might sound unfair to BSO noobs, but they have no time restriction on catching up, so it's not so bad. 

The one thing I'm not entirely sure how to handle is the trophies - not sure if doing it the same way as osrs would be the best or fairest. Infact I was potentially thinking of giving the trophies based on OSB instead, but I'm not too opinionated on it and would be fine to do whatever the community likes the most.

**Comment by J4stMart** [comment]
I would be in favor of having a leagues style gamemode on osb. In osrs you also have to choose for either gamemode, if you want the collection log items on an account.
