### ISSUE TITLE
If "boss" is passed as a second parameter to "+k random", target only bosses

### ISSUE THREAD

**Issue by archubbuck** [oldschoolgg/oldschoolbot#1914]
## 🚀 Feature Proposal

I love that I can use `+k random` to automatically select and begin killing a random NPC but as someone who has progressed in the game I don't want to get stuck killing skeletons when I could be doing Armadyl. It would be nice if I could specify that I want to kill a random boss by using `+k random boss`.

I'm happy to contribute to the repository by implementing this feature if it's approved.

**Comment by TizHub** [comment]
Already a thing! - Added +m kill random (or +k random) which gets your minion to kill a random monster, out of all the ones you can kill!

Taken from: https://discord.com/channels/342983479501389826/346210791747223554/721643702220619847

**Comment by archubbuck** [comment]
No worries at all, @TizHub. I know it's a small change but I think it'd make the `+k random` command much more useful.

**Comment by archubbuck** [comment]
@Favna is this something I can begin working on and contribute to the repository?

**Comment by 6enny6** [comment]
yea @archubbuck

**Comment by Favna** [comment]
@archubbuck I am not involved with this project. Please do not ping me about it.

**Comment by archubbuck** [comment]
Sorry Favna, I meant to ping someone else.
