### ISSUE TITLE
[minor grammatical issue] Enchanting 

### ISSUE THREAD

**Issue by Jonesn4Jonesy** [oldschoolgg/oldschoolbot#1917]
## 🐛 Bug Report

https://i.imgur.com/fZtK73x.png

I believe this should be dragonstone necklace and not not dragon necklace.

**Comment by osDreamscape** [comment]
It's known as a "Dragon Necklace" on OSRS not "Dragonstone Necklace"

**Comment by Jonesn4Jonesy** [comment]
> It's known as a "Dragon Necklace" on OSRS not "Dragonstone Necklace"

Thats weird but you're right. Thanks!
