### ISSUE TITLE
OSB - Equipped preset items throw error 

### ISSUE THREAD

**Issue by RLChristof2** [oldschoolgg/oldschoolbot#1921]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
 When you have preset items equipped already, and go to equip a preset, it gives an error, and says you are missing these items

See screenshots:
https://i.imgur.com/x5eRfFW.png
https://i.imgur.com/vKdSDnw.png
https://i.imgur.com/lVy0egk.png

**Comment by Alexsuperfly** [comment]
it only looks at the bank for the items to verify it can equip them, it could unequip everything first then check but then if it fails youll be naked

**Comment by nwjgit** [comment]
Presets check your bank not worn equipment. You can also use /gear swap if you'd like to move a preset from one setup to another.
