### ISSUE TITLE
mypets leaderboard (lb pets) broke on both bots

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1923]
## 🐛 Bug Report

Doing the "lb pets" command brings up the unexpected error message. I assume this is related to the recent optimizations for Leaderboards, as it began to occur around the time that update went live.  I understand this isn't a top priority issue, but would be great if you could look into it when available!
![lbpet](https://user-images.githubusercontent.com/63373565/119601125-8059d300-bdb6-11eb-8979-a6f42bc52f7e.png)

**Comment by mylife212** [comment]
title is supposed to be both bots, not both boths lol

**Comment by mylife212** [comment]
Found two more commands that are also effected by the "Unexpected error" message. I assume they have the same issue, as they all popped up around the same time. 
![9eo3updhijk](https://user-images.githubusercontent.com/63373565/120849838-a1ec5480-c544-11eb-9e70-c04f4efe3a4b.png)
![ewqe09uwqoi](https://user-images.githubusercontent.com/63373565/120849850-a6187200-c544-11eb-9ca9-9da3acf5af98.png)

**Comment by mylife212** [comment]
OSB now has the unexpected error for channel disable.
![plsfixasap](https://user-images.githubusercontent.com/63373565/121264511-3cba9b00-c885-11eb-81a1-6a63397232af.png)

**Comment by gc** [comment]
Fixed in next update.
