### ISSUE TITLE
(BSO) Add =feed command for Hammy

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#1927]
## 🚀 Feature Proposal

Recently, the Hammy messages have been deleted from BSO because of the =use command. It was a really fun command, and I think adding it back in the form of =feed would be a great solution.  Please think of the poor Hamster:(

**Comment by themrrobert** [comment]
[1929](https://github.com/oldschoolgg/oldschoolbot/pull/1929)

**Comment by mylife212** [comment]
> Basic Hammy - mostly original: [1929](https://github.com/oldschoolgg/oldschoolbot/pull/1929)
> 
> OR for even more Hammy fun, you want this: [1930](https://github.com/oldschoolgg/oldschoolbot/pull/1930)

This is a great PR and is the justice Hammy deserves. Hope it gets merged soon!

**Comment by mylife212** [comment]
PR #1929 or #1930 are both great options. I sure hope Magnaboy looks at them soon!

**Comment by mylife212** [comment]
The Hamvolution has ended, and the PR has been merged. HamSalute
