### ISSUE TITLE
[BSO] Suggestion - Make Takon slightly less rare, 4,500 hours is a long time for irons.

### ISSUE THREAD

**Issue by themrrobert** [oldschoolgg/oldschoolbot#1942]
## 🚀 Feature Proposal
So most of the other pets are Time based.
Also, please make Takon more common, for such a useful pet to take 4,500 hours... takon is the longest-grind pet in the game by an order of magnitude. (not counting Steve which is 2,000 hours, but it's cosmetic only)  Maybe make the CoX pets minute based, or give them a decent rate increase.

'Normies' can just trade Takon around, so 1 Takon helps 10+ normies, whereas every iron would have to get it at some point, and 4500 hours is just the average rate. It's common enough to go 2-3x+ the drop rate, and noone has that kind of time to spend on a Takon.

Also maybe Sandy should be time based also, that way irons get a fair shot to get sandy before 250m xp
At 1 in 16k sandys, there is only a 86.5% chance to get sandy by 500m xp. One of the rarest pets in game, time wise.
Setting it to 1 in 8k minutes would balance out the faster catch rate you get at 500m xp.

Thank you!

**Comment by gc** [comment]
Addressing this in the next update
