### ISSUE TITLE
Apply trip length bonus from HP level to Nightmare

### ISSUE THREAD

**Issue by eggaroonie** [oldschoolgg/oldschoolbot#1954]
## 🚀 Feature Proposal

99 HP allows trips to be 35 minutes long, and with max KC bonus and full Inquisitor's makes individual kills 17:08, so it would be possible to get 2 kill trips while soloing.

**Comment by gc** [comment]
It already does apply to nightmare.

**Comment by J4stMart** [comment]
I've tried searching the code, and I can't find anywhere that it would apply to nightmare.
To make it work for nightmare, I think it should be added similarly to [cyclops](https://github.com/oldschoolgg/oldschoolbot/blob/eaba1f13a06c9629be340dd84bc3899bc7320ca7/src/extendables/User/Minion.ts#L656).
