### ISSUE TITLE
Dung scrolls

### ISSUE THREAD

**Issue by IronBump** [oldschoolgg/oldschoolbot#1955]
## 🐛 Bug Report

Scroll of Cleansing doesn't work, should save 15% of secondaries & produce 10% more potions. 

Scroll of Proficiency isn't even in the dung store but was added on release notes, should save 15% of planks used.

Possibly add the same =use option to all the DG scrolls to unlock that ability rather than just have it in the bank?

**Comment by imTURBObro** [comment]
bump!

![SmartSelect_20210616-005536_Discord.jpg](https://user-images.githubusercontent.com/68685674/122165360-b7fbee00-ce3d-11eb-9104-088420cfcc2d.jpg)

**Comment by WrathsFury** [comment]
Bought every scroll in dg to complete log, but unable to finish since one of the scrolls is not buyable. Also, Scroll of mystery isn't in cl log, but the one in cl log, you cannot get.

**Comment by nwjgit** [comment]
All these issues should be fixed by now. If there are any other issues you know of open a new bug thread.
