### ISSUE TITLE
Unable to join discord server?

### ISSUE THREAD

**Issue by InDisguise2** [oldschoolgg/oldschoolbot#1960]
I accidently left the discord server and I'm unable to join.. Doesn't say why it just says "Unable to accept invite"..

I've recently just subbed through patreon and would like to be able to claim my role.

**Comment by gc** [comment]
What's your discord username?

**Comment by InDisguise2** [comment]
InDisguise, I recently started playing this with my boyfriend and wanted to help him out since he’s really into this game

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by InDisguise2** [comment]
InDisguise#7133

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by gc** [comment]
Well you're not banned, the only reason is if you're in the max amount of servers or using the wrong server invite. Or, do you have an alt account that's banned from the server? Those are the only real possible reasons :)

**Comment by InDisguise2** [comment]
My boyfriend did receive a 1 day temp ban, does that affect me aswell since we’re on the same IP?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by gc** [comment]
Yes it does, and nothing can really be done about that sorry.

**Comment by InDisguise2** [comment]
Alright I’ll just have to wait I suppose. I’ve gotten him to agree to stay clear of your server as he can get angry somewhat easily..

I’ve added your bot to our personal discord so we’ll mostly be using that.
We just like having the benefits of trading with other people

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by gc** [comment]
Mhm, sounds like you'll only have to wait 1 day so its not a big deal. Closing this now

**Comment by InDisguise2** [comment]
Thanks for the quick response <3

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
