### ISSUE TITLE
Fix-Dungeoneering exp capped 2.147b

### ISSUE THREAD

**Issue by AlphaQLater** [oldschoolgg/oldschoolbot#1974]
The dungeoneering exp is capped at 2.147b like thieving was and it's sending null/void trips, solos return no exp or return message and it causes masses to fail aswell. Please fix thank you.
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

**Comment by jesseman1121** [comment]
Some users in the mass were still getting shards and xp. Others were not.

**Comment by AlphaQLater** [comment]
Fixed THANKYOU CYR AND DEVS ❤️
