### ISSUE TITLE
Wilderness Minion Pking

### ISSUE THREAD

**Issue by ScanlonRS** [oldschoolgg/oldschoolbot#1992]
## 🚀 Feature Proposal

It would be interesting if minions were allowed to PvP in the Wilderness at, let’s say, the Chaos Altar, and if minions are there burying bones, players could PK them and obtain bones upon returning from a trip, or if other pkers are there, you could potentially be pked as well.  You could have a PK mass system similar to mass bossing to elevate your chances of success. That’s just one example of what could be done, but anything in a PvP zone would apply.
     Overall, your chances of success to kill a player, as well as the success chance to defend yourself, would be determined by your gear and stats.

**Comment by nwjgit** [comment]
This was polled and failed in the main discord server.
