### ISSUE TITLE
Ma2

### ISSUE THREAD

**Issue by ahmalla** [oldschoolgg/oldschoolbot#2001]
## 🐛 Bug Report

![FE132C8D-FC7D-4C35-8E37-2FE899D99864](https://user-images.githubusercontent.com/68600561/120928598-1f75a900-c69a-11eb-9e79-743e052569c8.jpeg)

**Comment by 6enny6** [comment]
fwhats been reported to me regarding this;

some people, +ma2 works but not +magearena2
some, +magearena2 works but not +ma2
some, neither work

**Comment by MoistWontons** [comment]
[https://i.imgur.com/PtngI97.png](url)
[https://i.imgur.com/TsjRfV6.png](url)

Same issue on BOS, tried spamming it in my server to avoid spam/flood in main server, also tried to use it in main server a few times, nothing works. 
Tried clearing mage arena 1 again, including unequiping any god capes. Nothing.

**Comment by gc** [comment]
Should be fixed in next update.
