### ISSUE TITLE
BSO - Got zippy message but no zippy in bank or CL

### ISSUE THREAD

**Issue by davsan56** [oldschoolgg/oldschoolbot#2002]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

I was questing on BSO to try and get Zippy and I got the message saying he joined me on my adventure

![8845990D-4285-48AE-950C-3150FEA5AEB0](https://user-images.githubusercontent.com/7637218/120929333-b2bcd780-c6b6-11eb-9dc7-c658060070e6.jpeg)

And you can see in my bank and pet CL that there is no Zippy

![7312CBA0-77E1-4B09-96D9-54B466F0DCC5](https://user-images.githubusercontent.com/7637218/120929416-f1eb2880-c6b6-11eb-81fa-ead9cdf6aa56.jpeg)

I talked with Nearly Headless Rick in the help-and-support chat and was told to open this bug. 

My name in the screenshots is davatron5000 but my name in the OSB discord is davsan56.

**Comment by osrsolympus** [comment]
Looks like this isn’t a one off. Joe (disc id: 145097330322833410) showed similar screenshots.

**Comment by Suttyy** [comment]
Hello, I am also experiencing the same issue, I received message that I got zippy but it does not show in bank or on CL.
Discord ID Sutty#0001

![image](https://user-images.githubusercontent.com/85775182/121763464-67556e00-cb7b-11eb-81fd-f8ee836e2c44.png)
![image](https://user-images.githubusercontent.com/85775182/121763500-d4690380-cb7b-11eb-9e26-58d4875bef85.png)

**Comment by nwjgit** [comment]
This thread is outdated. Zippy now properly drops when received so this is probably related to an outdated bug.
