### ISSUE TITLE
[OSB] Bot doesn't DM Daily reminders since last update

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2015]
## 🐛 Bug Report

The Patron perk of getting a DM when your daily is available has been broken for a few days. Probably broke when the fix for trips not sending in DMS was merged.

**Comment by mylife212** [comment]
Bump. Fixed in BSO, not for OSB

**Comment by thievious1** [comment]
Doesn’t work on bso for me, not sure why :(
