### ISSUE TITLE
Ishi giving error instead

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#2026]
## 🐛 Bug Report

so ishi is supposed to force you to do =k ogress warrior when equipped instead this error is given 
![Screenshot_20210609-022426_Discord.jpg](https://user-images.githubusercontent.com/68685674/121312375-eec88600-c8ca-11eb-8dc4-89f55e964a06.jpg)

**Comment by gc** [comment]
Fixed in next update.
