### ISSUE TITLE
selling planks to bot price issue

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#2032]
## 🐛 Bug Report

me and another had 50k+ teak planks in bank and it said a higher amount in the bank with —sv then when sold to bot.![bank.jpg](https://user-images.githubusercontent.com/68685674/121402819-efd7d280-c91f-11eb-8a4a-10fa6e391b07.jpg)![SmartSelect_20210609-123859_Discord.jpg](https://user-images.githubusercontent.com/68685674/121402824-f1a19600-c91f-11eb-89ff-80ab605bc820.jpg)![Screenshot_20210609-123918_Discord.png](https://user-images.githubusercontent.com/68685674/121402829-f2d2c300-c91f-11eb-8e67-3d64075998a8.png)

**Comment by mylife212** [comment]
Cause of this issue is that Planks sell for less than the GE Sell value, due to a recent economy update. Going to close this, but it would be fitting to make a suggestion where the --sv flag shows accurate sell value
