### ISSUE TITLE
Elder Bow Bug

### ISSUE THREAD

**Issue by ReZeroed** [oldschoolgg/oldschoolbot#2043]
## 🐛 Bug Report

When attempting to fletch an elder bow it says you are required to have an elder bow, and not an elder bow (u) making it impossible to fletch them.
![image](https://user-images.githubusercontent.com/75293942/121698919-97245780-cb22-11eb-9b7f-fed0389955ba.png)

**Comment by gc** [comment]
Fixed in next update.
