### ISSUE TITLE
[BSO] Dwarven Knife not giving a fletching boost

### ISSUE THREAD

**Issue by ReZeroed** [oldschoolgg/oldschoolbot#2050]
## 🐛 Bug Report

the dwarven knife is not giving any boost when fletching.
![image](https://user-images.githubusercontent.com/75293942/121781347-5a2a9480-cbf8-11eb-948d-279e363a7c34.png)

**Comment by osrsolympus** [comment]
Not a bug, the Dwarven knife doesn’t have a boost.

**Comment by ReZeroed** [comment]
> Not a bug, the Dwarven knife doesn’t have a boost.

![image](https://user-images.githubusercontent.com/75293942/121796668-06a75d80-cc6f-11eb-95d5-110310e7ca5d.png)
this was the reason for the post

**Comment by osrsolympus** [comment]
Yeah he just changed his mind because Scruffy already boosted fletching.
