### ISSUE TITLE
Achievement Diary Bug - Rooftops

### ISSUE THREAD

**Issue by WrathsFury** [oldschoolgg/oldschoolbot#2075]
## 🐛 Bug Report

Currently the rooftop completions for Achievement Dairies are bugged and there is no way to complete some because it will say that I have not complete the said Rooftop Course. Even if you have completed the lap on the course without failing.
![ardyroof](https://user-images.githubusercontent.com/79944512/121964181-fac7a400-cd1f-11eb-9c35-9ced15483854.PNG)
![ardyroof2](https://user-images.githubusercontent.com/79944512/121964189-fd29fe00-cd1f-11eb-8c9e-bfbd31ab5445.PNG)
![ardyroof3](https://user-images.githubusercontent.com/79944512/121964192-ff8c5800-cd1f-11eb-8029-8baf4e93b7c4.PNG)

**Comment by imTURBObro** [comment]
I'm also having this error
![SmartSelect_20210615-232638_Discord.jpg](https://user-images.githubusercontent.com/68685674/122157821-25ede880-ce31-11eb-9e0c-8d0061c29462.jpg)

**Comment by 6enny6** [comment]
![](https://media.discordapp.net/attachments/828203037733945384/854091944597782528/unknown.png)


![](https://media.discordapp.net/attachments/828203037733945384/854098192295788564/unknown.png)



![](https://media.discordapp.net/attachments/828203037733945384/854096003590520832/unknown.png)

**Comment by LuxrayElite** [comment]
Seems to have been resolved with moving to slash commands, or some other updates. Feel free to re-open if it is encountered again.
