### ISSUE TITLE
BSO Bug - Blue Dragon Slayer Task

### ISSUE THREAD

**Issue by ulises-c** [oldschoolgg/oldschoolbot#2076]
## 🐛 Bug Report

Assigned a blue dragon task and vorkath does not count towards a blue dragon slayer task

**Comment by osrsolympus** [comment]
Provide screenshots please

**Comment by ulises-c** [comment]
![image](https://user-images.githubusercontent.com/13595269/121966895-454b1f80-cd24-11eb-9037-85227b8b7e85.png)

**Comment by osrsolympus** [comment]
Who did you get your task from?

**Comment by ulises-c** [comment]
From Konar. Nothing was specified just "blue dragon" no location
![image](https://user-images.githubusercontent.com/13595269/121967573-7bd56a00-cd25-11eb-8700-e3c4737ceacb.png)

**Comment by osrsolympus** [comment]
if I remember correctly, that’s just how Konar restricts you, since there’s not a good way to do location locking when you’re just playing an idle text game.

**Comment by ulises-c** [comment]
I see thanks. I suppose my only suggestion would be to list the restrictions when assigned the task.
