### ISSUE TITLE
Make Scroll of Proficiency buyable

### ISSUE THREAD

**Issue by AlphaQLater** [oldschoolgg/oldschoolbot#2077]
The scroll of proficiency is currently not buyable from the dg store and I guess the missing scroll in the collection log aswell.

## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

**Comment by AlphaQLater** [comment]
![Screenshot_20210614-190538500 (1)](https://user-images.githubusercontent.com/81002347/121981459-bdeec200-cd9e-11eb-9d48-a0c2ac7b6ae0.jpg)

**Comment by osrsolympus** [comment]
Duplicate of #1955
