### ISSUE TITLE
=bstats monsters & lb kc rabbit

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#2086]
## 🐛 Bug Report

`=bstats monsters` gives error now but works on osb.
![SmartSelect_20210615-232244_Discord.jpg](https://user-images.githubusercontent.com/68685674/122157704-efb06900-ce30-11eb-853e-c2f2b475e41d.jpg)

lb for kc rabbit both bots doesn't load at all
![SmartSelect_20210615-232358_Discord.jpg](https://user-images.githubusercontent.com/68685674/122157717-f50db380-ce30-11eb-838d-559e86abfbf0.jpg)![SmartSelect_20210615-232414_Discord.jpg](https://user-images.githubusercontent.com/68685674/122157720-f63ee080-ce30-11eb-8cc4-25747f4cbcdc.jpg)

**Comment by LuxrayElite** [comment]
These issues have been resolved
