### ISSUE TITLE
Food reduction from offensive stats

### ISSUE THREAD

**Issue by anthonyburrow** [oldschoolgg/oldschoolbot#2141]
## 🐛 Bug Report

Looking at the food usage calculation function ("src/lib/minions/functions/calculateMonsterFood.ts", line 36), it seems as though the reduction of food based on the user's offensive stats are based on the attack styles of the monster rather than the user. This leads to strange and unrealistic results in the offensive stat food reduction.

For example, one could be killing mutated bloodvelds, and specifically +training a melee combat skill (irrelevant in the code). Bloodvelds look at your range gear set for defensive food reductions, and they attack with magical melee (using magic attack stat). The code calculates what appears to be the *user's* food reduction due to their offensive stats based on their magic attack stat in their range gear set, specifically because bloodvelds use magic attack.

This is problematic because the typical range gear setup heavily decreases magic attack, even into the negatives. The result of this is a 0% food reduction due to the user's offensive stats. This is just strange and unrealistic, because the user is training melee and theoretically using their range gear setup in this instance, neither of which have anything to do with magic attack.

Sorry if this is intended, but it seems unintended to me.

**Comment by Lilylicious** [comment]
Already made a PR for this in #2129
