### ISSUE TITLE
Add --barrage & --burst to dagannoths

### ISSUE THREAD

**Issue by badbilliam** [oldschoolgg/oldschoolbot#2145]
## 🚀 Feature Proposal

it's possible to barrage or burst slay dagannoths in the catacombs. 

https://www.youtube.com/watch?v=YnNK2TmjORo&t=4s

max efficiency is somewhere around 85k slayer xp/hr. This method requires staminas and max mage bonus. I think a reasonable proposal would be to be able to barrage/burst dagannoths for 50k/40k slayer xp/hr. I think cannoning is probably more xp/hr, but my ironman doesn't have any cannonballs but has like 100k burst runes from barrows.

**Comment by themrrobert** [comment]
I'm leaning towards no.

We can't let you barrage dagannoths right now. the way its coded is a flat 55% boost, which would far exceed what's possible at dagannoths currently. just because it's physically possible to barrage them doesn't mean you can get a comparable benefit as you would from the standard barrage tasks.

**Comment by eggaroonie** [comment]
That's not really true.
Barraging dagganoths on OSB would have the exact same XP rate as cannoning them, and both XP rates are lower than what can be achieved in game. For most people aiming for efficiency, cannoning them would be preferred as cannonballs are cheaper than barrage runes, but the option to barrage dagganoths would make it a significantly better task for people focused on CL.

**Comment by nwjgit** [comment]
Pretty sure this is now a feature under /config user combat_options

**Comment by LuxrayElite** [comment]
Still cant barrage or burst but unlikely to ever be implemented based on cyrs response
