### ISSUE TITLE
Adding +create Basilisk Jaw to OSB to dismantle Neitiznot Faceguard

### ISSUE THREAD

**Issue by Elessar** [oldschoolgg/oldschoolbot#2149]
+create <base item> works to dismantle ornamented items. =create Basilisk Jar works to dismantle Neitiznot Faceguard on BSO.

I would request/suggest this to be added to OSB aswell.

**Comment by Superwhammybar** [comment]
If https://github.com/oldschoolgg/oldschoolbot/pull/3152 is approved, you can use -revert neitiznot faceguard to accomplish this.
