### ISSUE TITLE
trailblazer graceful set effect not working since update

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#2159]
## 🐛 Bug Report

sense update/merge trailblazer graceful is not giving set bonus. 

before update:
![Screenshot_20210621-231952_Discord.png](https://user-images.githubusercontent.com/68685674/122863027-b459e280-d2e7-11eb-8148-f223a896ca49.png)

after update:
![Screenshot_20210621-231738_Discord.png](https://user-images.githubusercontent.com/68685674/122863038-b7ed6980-d2e7-11eb-9d73-6a07812bf638.png)![Screenshot_20210621-230408_Discord.png](https://user-images.githubusercontent.com/68685674/122863042-b91e9680-d2e7-11eb-97af-2a010f61ba2f.png)

**Comment by 6enny6** [comment]
looks like this was overwritten or something with the changing of how alias/similaritems works
 
see #1996

**Comment by gc** [comment]
Trailblazer graceful should be fixed in the next update.
