### ISSUE TITLE
No collection log for revs/individual rev mobs/misc mobs

### ISSUE THREAD

**Issue by osDreamscape** [oldschoolgg/oldschoolbot#2170]
![image](https://user-images.githubusercontent.com/73551894/123004736-e449ca00-d369-11eb-87a1-258b23af97ab.png)

![image](https://user-images.githubusercontent.com/73551894/123004762-ee6bc880-d369-11eb-833a-5369011a4ea7.png)

Same applies for all revenant types, haven't noticed any other mobs other than desert bandit that also have that issue.

**Comment by gc** [comment]
Revenants can't be killed currently, `+cl [monster]` requires that the monster is killable.
