### ISSUE TITLE
Hydra only has hydra eye, missing other pieces

### ISSUE THREAD

**Issue by osDreamscape** [oldschoolgg/oldschoolbot#2171]
![image](https://user-images.githubusercontent.com/73551894/123004883-19561c80-d36a-11eb-8775-572f32bb5407.png)

![image](https://user-images.githubusercontent.com/73551894/123004935-2ecb4680-d36a-11eb-939a-6a6404a1a64c.png)

**Comment by themrrobert** [comment]
fixed
