### ISSUE TITLE
TKS buy doesnt reflect items on coll log

### ISSUE THREAD

**Issue by osDreamscape** [oldschoolgg/oldschoolbot#2172]
unsure if intended or not, but items (especially the tzhaar weps/armour) dont reflect on coll log when purchased

![image](https://user-images.githubusercontent.com/73551894/123014329-e1a3a080-d37a-11eb-9057-463bf8f1c4a5.png)

**Comment by gc** [comment]
You're showing the collection log of a monster - i dont see why the tzhaar shop should add items to the CL.
