### ISSUE TITLE
imbued zamorak cape (l) acting like max cape ?

### ISSUE THREAD

**Issue by iYeeYee** [oldschoolgg/oldschoolbot#2179]
🐦AsherYeeYee🐦 — Today at 5:24 PM
=equip mage Imbued zamorak cape (l)
👽BSO👽
BOT
 — Today at 5:24 PM
You can't equip a Imbued zamorak cape (l) because you don't have the required stats:  :attack: 99 Attack,  :strength: 99 Strength,  :defence: 99 Defence,  :hitpoints: 99 Hitpoints,  :ranged: 99 Ranged,  :prayer: 99 Prayer,  :magic: 99 Magic,  :cooking~1: 99 Cooking,  :woodcutting: 99 Woodcutting,  :fletching: 99 Fletching,  :fishing: 99 Fishing,  :firemaking: 99 Firemaking,  :crafting: 99 Crafting,  :smithing: 99 Smithing,  :mining: 99 Mining,  :herblore: 99 Herblore,  :agility: 99 Agility,  :thieving: 99 Thieving,  :slayer: 99 Slayer,  :farming: 99 Farming,  :runecraft: 99 Runecraft,  :hunter: 99 Hunter,  :construction~1: 99 Construction.

??????

**Comment by nwjgit** [comment]
This has been corrected
