### ISSUE TITLE
=CL DG Not showing 7th scroll properly

### ISSUE THREAD

**Issue by ArtMatters** [oldschoolgg/oldschoolbot#2180]
https://i.imgur.com/hkilyiR.png

https://cdn.discordapp.com/attachments/343218314694361088/857510506411589642/bank.jpg

I purchased all of the scrolls and have them in my bank, but the 7th one does not seem to show up. 
Apparently the Scroll of mystery is not on the CL and the empty log slot is a scroll that's not out yet.

**Comment by gc** [comment]
In the next update, scroll of proficiency (save 15% of construction planks) will be buyable and scroll of mystery will be in the cl.
