### ISSUE TITLE
Molten Glass creating

### ISSUE THREAD

**Issue by Wingdragon1** [oldschoolgg/oldschoolbot#2183]
## 🚀 Feature Proposal

With the release of the Slayer skill, you can now obtain all the items to craft Molten Glass.
Currently the only method of obtaining Molten Glass is killing Thermonuclear smoke devil.

The items needed for Molten Glass can be obtain through these 2 methods:
Item | Method of obtaining
------------ | -------------
Bucket of sand | Drop from Kalphite Queen
Soda ash* | Drop from Killerwatt

_*: Soda Ash can be cooked using (Giant) Seaweed on OSRS. But the cooking option does not exists within the Bot. (Might be nice to have as well)_

It would be amazing to have this as an alternative/extra method of training Crafting.

_Having the option to use the lunar spell 'Superglass Make' to create more Molten Glass would be a Nice-to-have as well._

**Comment by TastyPumPum** [comment]
This was resolved with https://github.com/oldschoolgg/oldschoolbot/pull/2191
