### ISSUE TITLE
BSO Dark Altar runs bugged (time rising) 

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#2186]
## 🐛 Bug Report

1) I sent the initial command.
   -> got error
2) tried the command for souls 
   -> minion is busy
3) check what my minion might be busy doing.
   -> at the dark altar making blood runes.
4) time is rising,  not finishing and minion hasn't returned yet

![Screenshot_20210624-080007_Discord.png](https://user-images.githubusercontent.com/68685674/123276841-29d1d880-d4cb-11eb-85bc-4ab5c2fa661c.png)![Screenshot_20210624-084346_Discord.png](https://user-images.githubusercontent.com/68685674/123276884-36563100-d4cb-11eb-98d0-059dc8a15a9e.png)![Screenshot_20210624-084348_Discord.png](https://user-images.githubusercontent.com/68685674/123276897-38b88b00-d4cb-11eb-817f-44458e067341.png)![Screenshot_20210624-090350_Discord.png](https://user-images.githubusercontent.com/68685674/123276901-39e9b800-d4cb-11eb-9547-15760b68b2d1.png)

**Comment by gc** [comment]
Should be fixed in next update.
