### ISSUE TITLE
Kodai boost

### ISSUE THREAD

**Issue by overover55** [oldschoolgg/oldschoolbot#2194]
## 🐛 Bug Report

I was attempting to use the command -as burst on dust devils and received and extra kodai bonus even though i do not have a wand.
![Screenshot 2021-06-24 221651](https://user-images.githubusercontent.com/72724048/123373242-e8c4dd00-d539-11eb-9a12-4da3eee29ca6.png)

**Comment by themrrobert** [comment]
fixed
