### ISSUE TITLE
Bso darkaltar bug

### ISSUE THREAD

**Issue by Carrotthy** [oldschoolgg/oldschoolbot#2212]
## 🐛 Bug Report

Not sure if it's same on osb, but found this on Bso.
I'm doing runecrafting and wanted to do soul runes, using darkaltar. Well... When I typed command "=darkaltar soul" as wiki guided, the bot said "unexpected error".  But when I did =m to see what my Minion does, it says that my Minion is doing soul runes. 
Minor Bug, but still a bug. Pic down below.

![Screenshot_20210626-215655__01](https://user-images.githubusercontent.com/82282320/123522997-a7633780-d6c9-11eb-83b3-7ab20ba03313.jpg)

**Comment by gc** [comment]
Should be fixed in next update.
