### ISSUE TITLE
Typing "Autoequip"/"equip melee" brings up an error message

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2216]
## 🐛 Bug Report

What the title says. usually typing the command would say whats missing in the message.
![aaaa](https://user-images.githubusercontent.com/63373565/123529122-6ebc6180-d6bb-11eb-88b1-6476a82c1e85.png)
![ae](https://user-images.githubusercontent.com/63373565/123529123-6f54f800-d6bb-11eb-8d95-3437289d3007.png)

**Comment by gc** [comment]
Will be fixed in next update.
