### ISSUE TITLE
Imbued Heart Purpose

### ISSUE THREAD

**Issue by Tonks-Beep** [oldschoolgg/oldschoolbot#2218]
Marque item. Should at least have some uses, like in-game 👀 

10-15% burst/barrage tasks
10% at Barrows
10% at Kraken
10% at Thermy if maging
5% at Zulrah - Already has a shit load of boosts.

I literally pulled these numbers out my ass, balance them as you see fit.

**Comment by Lajnux** [comment]
resolved
