### ISSUE TITLE
Implementing Potion Boosts from Herblore

### ISSUE THREAD

**Issue by Darkpupitar3** [oldschoolgg/oldschoolbot#2229]
## 🚀 Feature Proposal
Hello I'd like to suggest that potions gained from killing monsters (super str, super attack) or created by the player be used as boosts when fighting monsters. For example, if training strength, a super strength potions adds a boost of 10% much like the dwh or the bgs, then a normal strength potion by 5%. Every 5 minutes in combat 1 dose is consumed from the bank. This would give a use for potions and incentivize players to increase their herblore level to maximize their kills per trip.

Describe the feature you're suggesting here, give lots of information and describe it as best you can. Please check that the feature hasn't already been suggested first, by searching the issues in this repository.

**Comment by Darkpupitar3** [comment]
btw love the bot thanks for all the work on it!

**Comment by nwjgit** [comment]
This has been implemented to various pvm activities
