### ISSUE TITLE
Grotesque Guardians get assigned as a boss task without having obtained Brittle Key

### ISSUE THREAD

**Issue by Jebusnorris** [oldschoolgg/oldschoolbot#2239]
## 🐛 Bug Report

Slayer masters (Konar in this example) can assign grotesque guardians on a boss slayer task without having obtained brittle key prior. Only way to progress is to cancel the task.

[Example](https://i.imgur.com/d8xUqjj.png)

**Comment by nwjgit** [comment]
This was fixed
