### ISSUE TITLE
wrong amount of feathers for agro arrows 

### ISSUE THREAD

**Issue by Heklas** [oldschoolgg/oldschoolbot#2241]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
![image](https://user-images.githubusercontent.com/81737200/123812085-16bc6f80-d8f4-11eb-93f1-a3b0e2a62613.png)

**Comment by Jonesn4Jonesy** [comment]
Adding to this that OSB has the same issue. https://i.imgur.com/jao9VlU.png

**Comment by gc** [comment]
Fixed in next update.
