### ISSUE TITLE
Stop Nerfing Grandmaster Droprates.  

### ISSUE THREAD

**Issue by JoshTheBaker** [oldschoolgg/oldschoolbot#2243]
## 🚀 Feature Proposal

Why do grandmaster droprates keep getting nerfed.  That defeats the purpose of even including them if you are purely adding them to the most recent custom boss that gets added and every other boss that has them drops them at such an obscenely low droprate to what they were dropping at making them not even really worth doing if you're unable to sell the other drops they have/have already completed their log.   

- Vasa: 1/3 for a GM, more than likely 1 gm a trip/every other trip. 
- Goldemar: 1/80 for a GM, roughly 100 Hours for 1 GM.
- Nex: 1/90 for a GM, roughly 15 hours for 1 GM.
- Malygos: 1/140 for a GM, roughly 12 hours for 1 GM.
- Sea Kraken: 1/190 for a GM, roughly 6 hours for 1 GM
- Treebeard: No Longer drops GMs, Drops Masters instead.

I know this isn't going to be necessarily true due to RNG, but that is what you should be expecting based off droprates and how many kills per hour can be completed, that being with the BIS Gear for that boss/patrons tiers..  Making it significantly longer if you dont have the BIS Gear or a specific patron tier to reach those rates.  

My suggestion is purely to stop nerfing the grandmaster droprates for other bosses, making them virtually exclusive to the most current custom boss.  Its dumb and there isn't any reason for it.

**Comment by zabiros** [comment]
+1
pretty dumb that grandmaster clues are more common from hunter than actual bossing.
