### ISSUE TITLE
Add "Onyx" To CoX Drops

### ISSUE THREAD

**Issue by ArtMatters** [oldschoolgg/oldschoolbot#2249]
In the normal game you can get a cut onyx from tekton, and it would be nice to have that ability on the bot. The rate should be about the same on both CM/regular(IMO) as it's more common for normal CoX raid's, but you don't always do tekton. The main issue with this is that the droprate changes based on team size. Not a big deal, just figured it would be nice to have.

**Comment by gc** [comment]
Done in next update.
