### ISSUE TITLE
Revise Corrupted Gauntlet times for minion because its inaccurate

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2255]
## 🚀 Feature Proposal

In the bot, it takes around 16 minutes (could be off by a bit) to complete one corrupted gauntlet at the max boost. This is impossible to get in game, because you have 7:30 minutes to prep and then you fight the boss. In total, one Corrupted gauntlet takes around 8-10 minutes to finish (depending on skill). 

It would make sense if the bot followed the same time. The death chance is somewhat accurate to the in-game, so only time needs to be changed. Note: 

I noticed in the code that Corrupted time is just the normal speed x 2, I think cutting this out and replacing it with something unique to Corrupted would be beneficial and solve the issue efficiently.

**Comment by osDreamscape** [comment]
+1, cgauntlet is already set to scale quite harshly on the bot to account for it's difficulty, the time penalty is both unnecessary and completely against how cgauntlet actually works in osrs

**Comment by mylife212** [comment]
coming in next update ty bop
