### ISSUE TITLE
You seem to have missed a monster

### ISSUE THREAD

**Issue by Redmage805** [oldschoolgg/oldschoolbot#2262]
While doing slayer food is not required for kq
![97B5CC7E-FE80-4E3B-9B31-54B1DC5C6324](https://user-images.githubusercontent.com/86848539/124307754-1ce16480-db1d-11eb-9d47-8d02362349e6.jpeg)

**Comment by gc** [comment]
Added food requirement for KQ in the next update (it will be quite generously low, by the way)
