### ISSUE TITLE
Seaweed spore icon in CL

### ISSUE THREAD

**Issue by spelcheqking** [oldschoolgg/oldschoolbot#2271]
## 🐛 Bug Report

When viewing a collection log with a seaweed spore, it doesn't show the image. Examples are all fossil Island wyverns.

**Comment by spelcheqking** [comment]
![Seaweed_spore_detail](https://user-images.githubusercontent.com/12383343/124370405-53b29a00-dc45-11eb-9bf5-474e2554d4a1.png)

**Comment by osrsolympus** [comment]
To be specific the icon (in OSB) is that of a single seaweed spore, and because it’s so small it gets covered up by the number.

**Comment by nwjgit** [comment]
This has been fixed.
