### ISSUE TITLE
Item quantity in Collection logs are in awkward position

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2272]
## 🐛 Bug Report

I noticed that this occurs in items added with Slayer. The item quantity should be on the top left of the sprite, but clearly they aren't right now.

Here, the seed on right shows how it should look. The `84` is the quantity for Seaweed spore, because the text is so big and not positioned properly, causing it to completely cover up the sprite. 
![image](https://user-images.githubusercontent.com/63373565/124374547-2fb57f80-dc6a-11eb-9f82-79f8788a49dc.png)

These items also have their quantity in a very weird position. 
![image](https://user-images.githubusercontent.com/63373565/124374586-7dca8300-dc6a-11eb-852e-07b452864bd9.png)

These arent the only items bugged though.

**Comment by gc** [comment]
Fixed the weird text one, the other one is kind of a bitch to fix atm and I don't think its a big bug.
