### ISSUE TITLE
[BSO] Commands don't show cooldowns

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2288]
## 🐛 Bug Report
ENGINE UPDATE BUG!!!

Doing a command with cooldown doesn't tell you how long until its available again. 
![image](https://user-images.githubusercontent.com/63373565/124669517-81cfee00-de80-11eb-8aa4-2a95dd215b3d.png)
![image](https://user-images.githubusercontent.com/63373565/124669523-85fc0b80-de80-11eb-8304-de7f3be4d847.png)
(Only showed the "ty" so you can see how the bot didnt respond)

**Comment by imTURBObro** [comment]
I believe this has been fixed.
