### ISSUE TITLE
Crafting Serpentine Helm

### ISSUE THREAD

**Issue by Darkpupitar3** [oldschoolgg/oldschoolbot#2299]
## 🚀 Feature Proposal

Add an option in crafting that lets the player craft a serpentine helm from a serpentine visage. Currently, the helmet is not obtainable. 
Describe the feature you're suggesting here, give lots of information and describe it as best you can. Please check that the feature hasn't already been suggested first, by searching the issues in this repository.

**Comment by osrsolympus** [comment]
The claim that the serpentine helm (uncharged) is not craftable is demonstrably false. In the future, please ensure that the issue you’re submitting is correct.

**Comment by osrsolympus** [comment]
And if you were referring to charging the serpentine helm then a) that’s not crafting and b) you can refer to issues #750 or #802
