### ISSUE TITLE
Ogress warriors no longer drop ishi 

### ISSUE THREAD

**Issue by shelixd** [oldschoolgg/oldschoolbot#2306]
This is just anecdotal/a hunch but I believe that the slayer ogress warrior drop table is overwriting the previous bso ogress warrior table with ishi. This is also probably why kcs were reset since its a kc of a “new” mob.

**Comment by imTURBObro** [comment]
iyeeyee has been on this same hunch about ishi not dropping anymore. that's all he does and he has gone about 10k+ dry

**Comment by shelixd** [comment]
Fixed in todays update thanks to @Lilylicious
