### ISSUE TITLE
Diango doesn't accept Mod Husky as a Content Developer

### ISSUE THREAD

**Issue by acollins41198** [oldschoolgg/oldschoolbot#2307]
As in title, for the daily prompt "Name any content developer for OSRS" saying "Mod Husky" is not a valid answer.

Mod Husky is explicitly a content developer, per https://oldschool.runescape.wiki/w/Mod_Husky

**Comment by acollins41198** [comment]
![Image of issue](https://user-images.githubusercontent.com/2626633/124992042-76133180-e010-11eb-9dd0-b87f595c8e24.PNG)

**Comment by nwjgit** [comment]
This is outdated now since trivia has a set amount of 10 answers in the form of buttons.
