### ISSUE TITLE
BSO QP

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#2308]
## 🐛 Bug Report

BSO uses the MaxQP variable in multiple places like (as previously reported) the check to buy a quest cape, but more recently to see if you can complete achievement diaries. This should not be the case. 
![083533EC-2075-4973-88C2-E3082164F2E6](https://user-images.githubusercontent.com/65320787/125008827-550f0880-e031-11eb-92bd-ca06d71403a2.jpeg)

**Comment by gc** [comment]
Changed in next update.
