### ISSUE TITLE
Falador elite is checked at Ardy rooftops for increased marks

### ISSUE THREAD

**Issue by anthonyburrow** [oldschoolgg/oldschoolbot#2316]
## 🐛 Bug Report

When doing Ardougne rooftop agility, the agility task code checks to see if the user has the Falador elite diary instead of Ardougne elite diary to have 25% increased marks of grace. Pretty sure it should be Ardy?

![Image_2021-07-11_08-23-35](https://user-images.githubusercontent.com/35277453/125197210-5c493880-e222-11eb-9baa-fd01815d5080.png)

**Comment by gc** [comment]
Fixed in next update.
