### ISSUE TITLE
Add a command to search for where you can get x drop

### ISSUE THREAD

**Issue by Steasyc** [oldschoolgg/oldschoolbot#2325]
Example

+/=getwhere Zenyte Shard

-Zenyte shard 
  Kill Demonic gorilla 1/x chance 

(With or without droprate)

If something gets searched that has more than 10 different monster that drops it

List with 10 monsters per page

-clues
-drop location
-different collecting areas

**Comment by osrsolympus** [comment]
Until this is added to the bot, there’s a useful alternative you can use right now. If you do +w itemname, you can scroll down to drop sources and get exactly this information with like one extra step.

**Comment by imTURBObro** [comment]
> Until this is added to the bot, there’s a useful alternative you can use right now. If you do +w itemname, you can scroll down to drop sources and get exactly this information with like one extra step.

yes but this is only useful for ingame items.

this command would be amazing in the sense of BSO's custom items & actual OSRS items. (OSB)

**Comment by gc** [comment]
I think you should just use the wiki.
