### ISSUE TITLE
+as food bug

### ISSUE THREAD

**Issue by osDreamscape** [oldschoolgg/oldschoolbot#2327]
Using +as after running out of food then buying more still seems to think you're missing food. +k works as intended for the same monster. 

![image](https://user-images.githubusercontent.com/73551894/125235751-cc45d600-e297-11eb-9918-b75c0928e254.png)

![image](https://user-images.githubusercontent.com/73551894/125235777-d8319800-e297-11eb-9263-01e8dd8d3351.png)

**Comment by themrrobert** [comment]
I cannot replicate this. Please show me the screenshot showing what kind of food and how much the "=k" trip used,  and also please tell me what kind of food he purchased. @osDreamscape

**Comment by Lilylicious** [comment]
Can't replicate. Please reopen if you can provide a full history including the information asked for above.
