### ISSUE TITLE
+mostdrops, Not showing items that are actually on the CL

### ISSUE THREAD

**Issue by jesseman1121** [oldschoolgg/oldschoolbot#2349]
## 🐛 Bug Report

doing =mostdrops gorajan bonecrusher (u) returns the following message. 

You can't check this item, because it's not on any collection log.

Hoping its not bugged out from dropping too.

--------------------------------------------------
**edit from themrrobert:** The bug actually applies to OSB also. The problem is that it's not considering OSJSMonster drops, and only looking at the 'custom' collection logs. I believe we should fix this by adding a new variable:
```
const allCollectionLogIncludingMonsters number[] 
```
Which includes ...allCollectionLogItems, and ...AllMonsters.allitems() or something similar.

**Comment by imTURBObro** [comment]
having the same issue with elder runes and salve amulet

![SmartSelect_20210715-222438_Discord.jpg](https://user-images.githubusercontent.com/68685674/125886984-4be2c27f-6d1f-4c86-91bc-46a8da08a75a.jpg)![SmartSelect_20210715-221055_Discord.jpg](https://user-images.githubusercontent.com/68685674/125886990-8f627bae-6688-4bde-ad76-cb698d51575c.jpg)

**Comment by kevinsmendes** [comment]
This is a intended change and wont be reverted. We will, although, improve the collection log in the near future to have more unique items on it, so, custom bosses/activities will have their unique items there. For now, it'll stay like this.
