### ISSUE TITLE
Cox KC reset to zero

### ISSUE THREAD

**Issue by DanOV-71** [oldschoolgg/oldschoolbot#2350]
On my 93rd(?) Cox kc as a team of 3 I got an arcane scroll as a drop and we hit the b2b. Saw that i was using 7 brews which was odd, I usually use 4. Looked at my +cl and my Cox kc was 0. My +raids is also 0 despite showing 1.8m points and 4 uniques. 
![Screenshot_20210715-235444_Discord](https://user-images.githubusercontent.com/71439924/125874327-773aec85-9f56-4ac6-8974-ee8e9b21b66b.jpg)

**Comment by DanOV-71** [comment]
I didnt notice a number of things have been reset. Take this old +m stats command,
![Screenshot_20210716-084739_Discord](https://user-images.githubusercontent.com/71439924/125912358-d8c3d130-e978-4e3e-af35-6ce09af84448.jpg)


And what I have now;

![Screenshot_20210716-084849_Discord](https://user-images.githubusercontent.com/71439924/125912410-649acbc8-1044-4bc3-80f6-ea5df3124b26.jpg)

**Comment by gc** [comment]
Your KC should be fixed now, and the bug causing it will be fixed in the next update.
