### ISSUE TITLE
[BSO] add =monster for all custom bosses

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#2353]
## 🚀 Feature Proposal

there is a =monster mally & =monster treebeard, but none of the other custom bosses.

![Screenshot_20210716-043625_Discord.png](https://user-images.githubusercontent.com/68685674/125927207-0347ba3e-c921-4077-b401-ced91b9eee40.png)![Screenshot_20210716-043622_Discord.png](https://user-images.githubusercontent.com/68685674/125927214-f0de5229-40ba-4e16-95bf-b82722e977b9.png)![Screenshot_20210716-043701_Discord.jpg](https://user-images.githubusercontent.com/68685674/125927216-8f3964bb-9c4b-4731-b604-bb717347a7ad.jpg)

**Comment by nwjgit** [comment]
This has been fixed with show_info

**Comment by LuxrayElite** [comment]
Still doesnt apply to some custom bso monsters
