### ISSUE TITLE
Revert changes to +mostdrops 

### ISSUE THREAD

**Issue by SkumRobin** [oldschoolgg/oldschoolbot#2355]
## 🚀 Feature Proposal
As of recently we're not able to check +mostdrops for items that aren't on CL. 
OSB doesn't have itemcontracts and/or people pinging/dming for those items. 

Please revert the changed for OSB

**Comment by jesseman1121** [comment]
+1

**Comment by Lilylicious** [comment]
Mostdrops have been enabled for mods again. There's also work being done to enable it for any item that drops from a monster, not just CL items.

Beyond that, this isn't being reverted.
