### ISSUE TITLE
Ferocious glove/Hydra leather revert CL visual dupe

### ISSUE THREAD

**Issue by DrugsOsb** [oldschoolgg/oldschoolbot#2387]
## 🐛 Bug Report

when you **+create Ferocious gloves** and then **+create hydra leather**
the bot is adding an additional leather to the hydra collection log each time you do it.

**Comment by AvariceBrah** [comment]
In a lot of situations this is how an item is intended to enter the cl, but granted, you shouldn't be able to do it more and more and it count as a drop. Sounds like decent fix would be setting reverts in their own cl OR making it to where their entries don't have a number ticker. 

Just my thoughts.

**Comment by gc** [comment]
Thank you for reporting, fixed in next update.
