### ISSUE TITLE
Reduce Max cape cost to 22.77m

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2392]
## 🚀 Feature Proposal

Currently costs 150m per Max cape, and while it is a fair price for a gp sink I think its still too pricy. 22.77m would fit the 10x osrs price theme for shop items (IE: Warrior helm is 780k in bot compared to 78k in-game). After such a big grind to max, you shouldn't have to drop 500m+ on the capes you earned.

**Comment by osDreamscape** [comment]
Lots of folks will purchase multiple max capes as well, at 150m apiece currently owning all max capes (including infernal when that releases) is 1.2b gp, which is really steep especially for ironmen

**Comment by mylife212** [comment]
Max cape is now being lowered to 2.277m cost HamPog
