### ISSUE TITLE
Offering bones for construction xp (BSO)

### ISSUE THREAD

**Issue by DatBSOGuy** [oldschoolgg/oldschoolbot#2396]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

https://gyazo.com/f2186abf747f5c2be3cf7a0f699a0403

Offering bones not giving cons xp.

**Comment by Lilylicious** [comment]
I can't reproduce this, and the code looks fine. Magna needs to investigate in the database I think.

**Comment by Lilylicious** [comment]
This is caused by the bot not syncing after addXP. The next sync performed will add the XP in a way that's visible.

**Comment by themrrobert** [comment]
Lily and I confirmed this is just visual, but will address the root issue in the future.
