### ISSUE TITLE
Charging dragonfire equipment costs 5 bottles instead of 1

### ISSUE THREAD

**Issue by ArtMatters** [oldschoolgg/oldschoolbot#2411]
Charging any of the dragonfire offhand's currently require's 5 bottled dragonbreath instead of 1 like it does ingame. This means instead of needing 2 dragonfruit seeds, you need 9 per. :(

**Comment by themrrobert** [comment]
This is intended. 

I don't know the exact reasoning, but perhaps because it's so easy to get dragonfruit and you can't use the unfinished potion on the vent to charge it :)
