### ISSUE TITLE
[BSO] Rp roles doesn't count the new CL system for roles.

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2427]
## 🐛 Bug Report

What title says. collection log had a visual rework on it and now rp roles doesn't recognize the logs when applying roles. However, RP roles doesn't seem to work properly with it. I should be getting the Top collector role after rp roles. It also doesn't seem to be adding the top minigame+slayer roles.
![image](https://user-images.githubusercontent.com/63373565/126738931-0521f08f-4183-462a-b232-8b70171d1f2e.png)

![image](https://user-images.githubusercontent.com/63373565/126738920-2fb88d93-28b5-48be-9e66-c50e33d2fe7c.png)

**Comment by JerMous3** [comment]
Hi i'm just here to say it works fine, top collector is where it belongs. Ty

**Comment by mylife212** [comment]
Didn't know it pulled roles from the custom "rolesboss" etc. logs, and the BSO one was outdated. Should be fixed now!

RP roles still doesnt say who it assigns top bso minigame/top bso slayer to though, but thats not an urgent issue.
