### ISSUE TITLE
Elite diary reqs in +ad kandarin are incomplete.

### ISSUE THREAD

**Issue by eggaroonie** [oldschoolgg/oldschoolbot#2449]
## 🐛 Bug Report

Kandarin elite requires your BA Honor Level to be 5, yet this requirement is not shown in +ad kandarin.
![image](https://user-images.githubusercontent.com/84296933/126925738-f301d7d7-a879-4ac9-836f-4706ed993a2d.png)

**Comment by gc** [comment]
This requirement does exist, its just not shown because its a custom function, not serialized in a way it can be shown like this.
