### ISSUE TITLE
Activity Contract

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#2483]
Could add a new form of contract (like =ic) on BSO, that assigns you different activities instead. This could be chop 100 oak logs, kill 100 giant mole or even complete 100 castle wars games. This could cover every minion activity currently on the bot

EDIT: Furthermore, itemcontracts could be changed to only be items you can actually obtain, such as chop 100 oak logs

**Comment by gc** [comment]
In bso-vote pls
