### ISSUE TITLE
+/=drop --all no longer works.

### ISSUE THREAD

**Issue by eggaroonie** [oldschoolgg/oldschoolbot#2488]
## 🐛 Bug Report

Pretty much just the title.
![Screenshot_20210731-155045](https://user-images.githubusercontent.com/84296933/127754161-cee794fe-8233-4f96-b8a4-3cfa6efe18ec.png)
![Screenshot_20210731-155115](https://user-images.githubusercontent.com/84296933/127754164-eabcca53-b8a7-4ad3-b06b-9096ba080c38.png)

**Comment by JerMous3** [comment]
This never worked, like 99% sure on that.
