### ISSUE TITLE
Can't smelt bronze bars

### ISSUE THREAD

**Issue by SjorsOverweg** [oldschoolgg/oldschoolbot#250]
The bot will always reply with "You don't have enough Copper ore" despite the amount of copper ore you actually have.

**Comment by arcticwarrio** [comment]
Add a number less than both tin and copper
Ie if you have 158 tin and 100 copper do +smelt 100 bronze bar

**Comment by SjorsOverweg** [comment]
Have 200 copper and 100 tin, doesnt smelt 100 bars.Op 8 mei 2020 20:06 schreef arcticwarrio <notifications@github.com>:
Add a number less than both tin and copper
Ie if you have 158 tin and 100 copper do +smelt 100 bronze bar

**Comment by Lajnux** [comment]
#406 Closes this issue
