### ISSUE TITLE
Pest Control needed for Achievement Dairies?

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#2509]
![SmartSelect_20210803-005532_Discord.jpg](https://user-images.githubusercontent.com/68685674/127965492-fd4742ee-23f4-443a-864c-41834c2e7c93.jpg)

I am completely stuck on how to complete this last step of western provinces when pest control isn't even coded. 

and there is no CL that has void gear.

I get unboxing the gear seems to be only way but that doesn't seem fair to complete an achievement diary.

any feedback would be greatly appreciated.

**Comment by animelewds** [comment]
As mentioned, youll have to wait until someone codes pest control and its merged into the bot.

**Comment by imTURBObro** [comment]
> As mentioned, youll have to wait until someone codes pest control and its merged into the bot. 

alright I understand that. but me posting this might kind of bring the idea to spotlight? thanks

**Comment by imTURBObro** [comment]
@6enny6 can u plz re open this? I feel it was closed prematurely? it's a legit subject and am I not at liberty to ask this?

**Comment by eggaroonie** [comment]
> > As mentioned, youll have to wait until someone codes pest control and its merged into the bot.
> 
> alright I understand that. but me posting this might kind of bring the idea to spotlight? thanks

Literally everybody already knows that this is an issue.
There are daily discussions about it in the discord. It will get done, just be patient.

**Comment by 6enny6** [comment]
Bop already started working on Pest Control so it’s just a waiting game

**Comment by imTURBObro** [comment]
> Bop already started working on Pest Control so it’s just a waiting game

ty
