### ISSUE TITLE
Light Ballista requires 72 fletching

### ISSUE THREAD

**Issue by eggaroonie** [oldschoolgg/oldschoolbot#2510]
## 🐛 Bug Report

On the bot, the light ballista requires 72 fletching to create, while in game, it only requires level 47.

https://github.com/oldschoolgg/oldschoolbot/blob/0099c3e36e0eb317d164491279a6f72c36ebfe8d/src/lib/skilling/skills/fletching/fletchables/slayer.ts#L19

https://oldschool.runescape.wiki/w/Light_ballista

**Comment by gc** [comment]
Fixed in next update.
