### ISSUE TITLE
Adamant Arrow (p++) issue

### ISSUE THREAD

**Issue by DrugsOsb** [oldschoolgg/oldschoolbot#2527]
[https://cdn.discordapp.com/attachments/804564558777417738/872577539288223864/image0.png]() 
as you can see from the image above, when you sacrifice the arrows, it also tries to do the cannonballs also.

## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

**Comment by Alexsuperfly** [comment]
you told it to do item id 2 and 732 addy arrows
