### ISSUE TITLE
Adding the new TOB creatables + boosts

### ISSUE THREAD

**Issue by JerMous3** [oldschoolgg/oldschoolbot#2533]
With the new TOB items in UMB's and TMB's. It would be nice to have the kits working to create the corresponding items (Sanguine Scythe of Vitur, idk if Holy Rapier/Scythe are creatables, but if so those too).

While doing that, it would be nice to have the kitted/holy versions of Scythe added to boosts (Think it's Grotesque Guardians only atm).

**Comment by nwjgit** [comment]
These are creatable now
