### ISSUE TITLE
trimmed patron bankbgs?

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#2534]
## 🐛 Bug Report

so I was under the impression of patreons with custom bankbg wouldn't have our banks trimmed on loot because that defeats purpose or the image...

how come dailys are doing it again?![SmartSelect_20210805-043050_Discord.jpg](https://user-images.githubusercontent.com/68685674/128328620-35afa070-bba7-4e7d-8dc1-ce8972fea2cb.jpg)

**Comment by JerMous3** [comment]
=b --smallbank and it will disable/enable

**Comment by kevinsmendes** [comment]
> =b --smallbank and it will disable/enable

Not for daylies. I issued a fix for that already. Sorry for that.

**Comment by imTURBObro** [comment]
> =b --smallbank and it will disable/enable

omg nice!

**Comment by imTURBObro** [comment]
@JerMous3 ![SmartSelect_20210805-200937_Discord.jpg](https://user-images.githubusercontent.com/68685674/128440812-0f953b72-5be7-4ed6-b846-4f341adea74b.jpg)

just ran the command and now it's _enabled_ ... which means its been disabled this whole time so as what @kevinsmendes said stands. well good to know it's being worked on.

**Comment by mylife212** [comment]
fix most likely coming in next update
