### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Ghost1Data** [oldschoolgg/oldschoolbot#2539]
Bug report: Farming mysterious seeds. So I began farming max amount of mysterious seeds 2 days ago and noticed a difference in yield and wasn't sure if it was due to different yields or if it was a bug but now I am sure it is a bug. First noticed when I increased seeds planted from 1 to 8. Then tested 8 to 8, then 8 to 1, then nothing, which I got boxes for with no seeds planted. And reconfirmed again with 1 to 8. Attached are all the necessary screenshots.
![Screenshot_20210804-115200_Discord](https://user-images.githubusercontent.com/88522002/128449038-7950b7cf-1e09-47d9-999f-1106cd5d2aa0.jpg)
![Screenshot_20210804-115251_Discord](https://user-images.githubusercontent.com/88522002/128449039-667b66c0-6783-4fa3-8aaf-2c339b84fbf5.jpg)
![Screenshot_20210804-115406_Discord](https://user-images.githubusercontent.com/88522002/128449041-e4ca0bf5-bd17-4a98-aa9d-002e527914ed.jpg)
![Screenshot_20210804-115432_Discord](https://user-images.githubusercontent.com/88522002/128449042-2fab48d2-f311-48a1-b2cb-8f2920552c77.jpg)
![Screenshot_20210804-231356_Discord](https://user-images.githubusercontent.com/88522002/128449043-e8b4e704-18c8-4137-a8b3-7bdd5f9b9ccc.jpg)
![Screenshot_20210805-081631_Discord](https://user-images.githubusercontent.com/88522002/128449044-bc263538-bd71-4462-b7e2-23e53693b356.jpg)

**Comment by Ghost1Data** [comment]
Oops, uploaded 2 non necessary screenshots XD

**Comment by themrrobert** [comment]
Working as intended. You get 1 - 4 boxes per seed planted, and 1 - 6 boxes for tree harvested.
