### ISSUE TITLE
Add Sandpit activity to +collect to get Buckets of sand

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2540]
## 🚀 Feature Proposal

In game, you can collect buckets of sand from Sandpits -  Giving around 1800+ Buckets of sand/hr. This would be a perfect fit for the Collecting activity so Ironmen get a consistent source of sand for crafting.

Requirements could just be 50 mage (Yanille POH tele), since thats all u need. Could add Buckets to buyable for a cheap price (25gp ea?) too.

**Comment by gc** [comment]
Done in next update.
