### ISSUE TITLE
mysterious seeds

### ISSUE THREAD

**Issue by JarPumpking** [oldschoolgg/oldschoolbot#2541]
## 🐛 Bug Report

I believe if you have another type of tree planted and then plant mysterious seeds you get the loot as if they were mysterious seeds + the loot of, in this example, magic trees.
![image](https://user-images.githubusercontent.com/84463806/128537403-95eb4729-9208-48cb-afa4-1827eb968152.png)

**Comment by themrrobert** [comment]
Working as intended
