### ISSUE TITLE
Make god books infinitely +create-able.

### ISSUE THREAD

**Issue by eggaroonie** [oldschoolgg/oldschoolbot#2547]
## 🚀 Feature Proposal

Once you obtain all 4 pages for a god book, and create it for the first time, you should be able to create more of that same book without requiring more pages. This is how they work in game.

This feature would give low-cost shield options for the wildy setup. [namely ranged & mage] Currently, these page sets cost upwards of 15m gp.

Current shield options for range include black d'hide shields, which require multiple materials locked behind very high levels (woodcutting, fletching, smithing, and crafting), blessed d'hide shields, which are incredibly rare clue rewards, and the odium ward/dragonfire ward/twisted buckler, which all require/are rare drops from pvm.

The shield situation for mage is even worse, since **all** of the currently available shields are rare pvm drops.

**Comment by AvariceBrah** [comment]
For osb I can see this being especially useful for ironman but I feel like making it cost free seems a little off. Is there any cost in going to the npc in game? Even a boat ride?

Bso this is a non issue. Pages are one of the most abundant items.

**Comment by eggaroonie** [comment]
In game they are free from the lighthouse guy, and you just get there with a fairy ring, which is also free. There is also an option to purchase them from perdu for 12k gp, so that could be a route worth looking into if we want to add some kind of cost.

**Comment by LuxrayElite** [comment]
Resolved by #4761
