### ISSUE TITLE
Minionstats addition

### ISSUE THREAD

**Issue by AvariceBrah** [oldschoolgg/oldschoolbot#2551]
## 🚀 Feature Proposal

https://raw.githubusercontent.com/oldschoolgg/oldschoolbot/311cd9353d87667a96da6e1510ffa28a4869a95c/src/commands/minionstats.ts

Here firstactivity is used, make the info grab refer to your FIRST interaction with the bot EVER. Not just that minion.

Currently if you had a regular minion for any amount of time and at some time reset and go ironman, your first activity is counted as the Ironmans' first activity if I'm not mistaken. 

Proposal; 
make the firstactivity search your FIRST discord interaction with the bot. 

If there is a second minion on the same bot for the account, insert another another field and return with firstironact.

I.e.

---
First activity: 12/15/2020 (This minion no longer exists!)
Ironman first activity: 4/15/2021
Number of activities: (amount of activities the ironman has done)
---
... Etc

If no more than one minion on that accounts log/history normal return like it is now.

**Comment by AvariceBrah** [comment]
Alternatively, add fields on return and/or a flag for even more info??

=Minionstats
Gives basic return

=Minionstats --all
Gives all minions associated with that bot on that account

=Minionstats --im
Only returns info about an ironman minion that exists (obv cuz permanent ironman)

**Comment by gc** [comment]
This isn't possible - there is only 1 minion per account. When you become an ironman, your data is deleted from the database.
