### ISSUE TITLE
Exchange Crystal Weapon/Armour/Tool/Teleport Seeds for Crystal Shards

### ISSUE THREAD

**Issue by Mr-Dorian** [oldschoolgg/oldschoolbot#2562]
The main game has the ability to trade in your unwanted Crystal Weapon/Armour/Tool/Teleport seeds to Amrod for Crystal Shards.  The exchange command could be:
+Amrod (Qty) (Seed Type)
ie: +Amrod 1 Crystal Armour Seed

The exchange rates for seeds to crystal shards in game are:
Crystal Weapon Seed: 10
Crystal Tool Seed: 100
Enhanced Crystal Teleport Seed: 150
Crystal Armour Seed: 250

**Comment by Lajnux** [comment]
resolved
