### ISSUE TITLE
Nerf Vorkath kills/hr, way too high right now

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2563]
## 🚀 Feature Proposal

Vorkath is currently 50~ kills/hr in the bot right now. This is way higher than in-game, where its around 34 kills/hr. Here are a few ways to fix this issue.

- Remove the DHCB+Dragon hunter lance boosts (30%+20% respectively) , because you get a boost from these weapons anyways due to how the combat system works. Effectively 'double dipping' on boosts. 
- Lower the BGS/DWH boost to 10%
- Increase the base kill time, maybe to 3:45 per? See how that does with the above nerfs
- Furthermore, the Salve boost should be removed from vorkath for balancing reasons. Currently cant obtain it right now, but when we can obtain it, this issue will pop up again. 

I am not sure if those nerfs will bring it to 34 kills/hr (give or take), but should be better than the ridiculous speed now.

**Comment by mylife212** [comment]
The dragonbane combat boosts are overridden for the Vorkath boosts. Meaning by removing the DHCB+lance boosts on Vorkath, it will then default to a 15% boost. 

IMO thats a bit much still. So the base time should be increased further to like 4:30-5:00. Once again, not final numbers but can plug it in and see what kills look like.

**Comment by gc** [comment]
Nerfed in next update.
