### ISSUE TITLE
After getting PKed being skulled at revs, repeating the trip is unskulled

### ISSUE THREAD

**Issue by Sergonomicus** [oldschoolgg/oldschoolbot#2565]
1. Send your minion to kill revenants being skulled
![image](https://user-images.githubusercontent.com/6019601/128781159-495acb28-e9c1-4089-add5-59472702107f.png)
2. Get PKed
![image](https://user-images.githubusercontent.com/6019601/128781189-bb3d4716-811e-41a6-93a3-202b0e932385.png)
3. Try repeating the trip, realize that the trip is being repeated but unskulled
![image](https://user-images.githubusercontent.com/6019601/128781224-741fcd70-798b-4014-b7d1-e70995dfc36f.png)

**Comment by gc** [comment]
Fixed in next update.
