### ISSUE TITLE
Bow of Faerdhinen is 1h in the bot, but 2h in-game

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2568]
## 🐛 Bug Report

What the title says. Can see in the image here that  ashield can be equipped at the same time. Should be fixed ASAP since this makes it better than ACB in OSB. 
NOTE: There are a LOT of variants of the bow in BSO. Theres the corrupted bow, then the regular bow and then the many recolors too.  When it comes to OSB, only the regular corrupted bow is available.  All variants seem to share this same bug though
![image](https://user-images.githubusercontent.com/63373565/128786314-5956825a-5bdb-40d2-b714-68a459b10bee.png)

**Comment by LuxrayElite** [comment]
Seems to have been resolved
