### ISSUE TITLE
PC - flappy not working

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#2571]
## 🐛 Bug Report

![SmartSelect_20210810-004515_Discord.jpg](https://user-images.githubusercontent.com/68685674/128814603-fb5b3de6-b10b-41de-8b88-f0ea6410e8cd.jpg) ![osbot-2.png](https://user-images.githubusercontent.com/68685674/128814667-6a307d0f-b62e-4914-a135-bb58ae300d16.png) I have flappy equipped and don't see anything letting me know it worked.

**Comment by imTURBObro** [comment]
EDIT: I moved amulet of fury and whip from misc to melee. got those boosts now.

still missing barrows gloves boost (unless ferocious replaces that as I posted might be)

**Comment by imTURBObro** [comment]
![Screenshot_20210810-000450_Discord.png](https://user-images.githubusercontent.com/68685674/128811045-35101f29-946f-4487-85e6-4052506928df.png)

when I do =m I get the message in picture above

**Comment by gc** [comment]
Fixed in next update.
