### ISSUE TITLE
PC - =m / =cancel issue

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#2577]
## 🐛 Bug Report

when I do =m & =cancel I get the following messages:

![Screenshot_20210810-000450_Discord.png](https://user-images.githubusercontent.com/68685674/128822558-f292b92c-0e54-4b2b-9dea-c83d03049f09.png)![Screenshot_20210809-235805_Discord.png](https://user-images.githubusercontent.com/68685674/128822562-c3d1fcb7-4759-41a1-b3f8-71298f555e0e.png)

**Comment by gc** [comment]
Fixed in next update.
