### ISSUE TITLE
Change player's attack style on Nightmare to crush.

### ISSUE THREAD

**Issue by Paah** [oldschoolgg/oldschoolbot#2586]
It is clearly intended to use crush weapons on Nightmare, there is minimum crush attack check, there is time penalty for having low crush attack, MVP is determined by crush attack, there is boost for using inquisitor mace and gear.. Yet, for food calculations your SLASH attack is checked. This should be changed to crush attack too.

At the moment for example I am able to meet all the speed boost checks (crush attack, melee str) with my high slash attack slayer gear using Bandos Godsword, which causes me to use less than 1/3 of the food compared to the 'bis' setup on the wiki using actual crush weapons.

Link to relevant line, should be .AttackCrush instead of .AttackSlash: https://github.com/oldschoolgg/oldschoolbot/blob/master/src/lib/minions/data/killableMonsters/index.ts#L311

**Comment by gc** [comment]
Okay. Done in next update.
