### ISSUE TITLE
BSO Tame growth % isn't increasing correctly. 

### ISSUE THREAD

**Issue by Zilther-osb** [oldschoolgg/oldschoolbot#2606]
So I don't know if this started with the last update or not, but I've now been getting only 1.8% growth per trip I send instead of 2. 

This would be fine, but I'm only actually getting 1%, not 1.8% 

I checked my tame, saw I was at 74%
Finished a trip for +1.8792%
Finished another trip for 1.8792%
Checked tame. 76%
Another trip, 1.8792%
Checked tame. 77% 

But That's only 3%, not the 5.6% it should be.

**Comment by gc** [comment]
Should be fixed.
