### ISSUE TITLE
Typo (Pollnivnian Bandit - Thieving)

### ISSUE THREAD

**Issue by Lulamash** [oldschoolgg/oldschoolbot#2635]
There is a typo for the NPC "Pollnivnian Bandit" used for thieving. Currently, it is spelled in the bot as "Pollnivian Bandit", and it is missing the second N to correctly spell "P-O-L-L-N-I-N-V-E-A-N  B-A-N-D-I-T" (https://oldschool.runescape.wiki/w/Bandit_(Pollnivneach)#Bearded). I wasn't sure where to submit this, hopefully this is the correct place. Thanks!

**Comment by gc** [comment]
Fixed in next update.
