### ISSUE TITLE
[BSO] Rename the Elysian shield from MM2 so it can't be used for scams

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2636]
## 🚀 Feature Proposal

Just like how LMS Items got a (LMS) tag next to them to prevent scamming, the same should be done for the Elysian spirit shield from Monkey madness 2 to prevent scamming. This item ID is "19559", a simple rename to "Elysian spirit shield (MM2)" would be perfect.

**Comment by gc** [comment]
Renamed in next update.
