### ISSUE TITLE
Add the colored variants of "Bow of faerdhinen (c) to similaritems.ts

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2637]
## 🚀 Feature Proposal

What title says. The bow of Faerd. (c) can be recolored in-game for cosmetic purposes, and this feature may come to the bot one day, feels appropriate to add them to SimilarItems so it can be futureproofed and retain pvm boosts among the bows. 

Same thing should be done for Blade of Saeldor (c), even tho it has no uses in the bot rn.

**Comment by nwjgit** [comment]
This was completed.
