### ISSUE TITLE
=gearstats elder bow all 0s.

### ISSUE THREAD

**Issue by imTURBObro** [oldschoolgg/oldschoolbot#2641]
## 🐛 Bug Report

I'm not sure if elder bow is ment to have stats or not, but just incase, when I do `=gearstats elder bow` it brings up a empty gear screen with 0s all across the board.

(yes I know I have a elder bow (u), but I wanted to see what the stats were of a elder bow to see if it's worth making or not, being my fletching isn't 105 yet)

![SmartSelect_20210817-071748_Discord.jpg](https://user-images.githubusercontent.com/68685674/129724314-f5006f7f-6e0f-4ac2-8731-b473860107cf.jpg)

**Comment by 6enny6** [comment]
its not supposed to be useful, just for fletching xp

**Comment by imTURBObro** [comment]
> its not supposed to be useful, just for fletching xp

gotcha! makes sense now thank you for clearing up the confusion for me
