### ISSUE TITLE
Imbued zamorak cape (L)

### ISSUE THREAD

**Issue by TaggerFoSho** [oldschoolgg/oldschoolbot#2651]
=equip mage Imbued zamorak cape (L)
shount this only be a lvl 75 mage requirement not max cape? 
![9EB7D59D-61AC-40EE-BB65-3DAAFECA0CC4](https://user-images.githubusercontent.com/87790372/129791204-1a2703d0-274e-4177-ac36-cd0962c15b43.jpeg)

**Comment by nwjgit** [comment]
This is no longer an issue.
