### ISSUE TITLE
Badges displaying incorrectly in +lb.

### ISSUE THREAD

**Issue by eggaroonie** [oldschoolgg/oldschoolbot#2652]
## 🐛 Bug Report

Badges will sometimes duplicate when shown in +lb. This seems extremely inconsistent, as I've only seen it around 2-3 times.

![image](https://user-images.githubusercontent.com/84296933/129797228-2d1b9352-3371-4100-b407-3784fe8bfba8.png)

**Comment by nwjgit** [comment]
This has been corrected.
