### ISSUE TITLE
[BSO] Expand Vasa's random boss list, currently missing a few

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2679]
## 🚀 Feature Proposal

Vasa has the unique feature of dropping loot from any boss which uses `+k` to fight, however I noticed that a few bosses are missing from the Vasa boss list for some reason. They are listed below, would make for even greater variety in loot if they get added! 

- Abyssal sire
- Alchemical hydra
- Barrows
- All 3 Dagannoth kings
- Grotesque guardians
- Kraken
- Sarachnis
- Thermonuclear smoke devil
- Malygos, Treebeard & Sea kraken (Completely understandable if left out though, would be a bit much but feel its worth noting)

**Comment by gc** [comment]
Added all of these to vasas drop table.
