### ISSUE TITLE
Clue Trade Up BSO

### ISSUE THREAD

**Issue by wildchickenz** [oldschoolgg/oldschoolbot#2680]
You can trade up one of each tier below for a master currently.
However BSO won't let you do so if you already have a master in bank.
I think BSO should let you stack them.

## 🚀 Feature Proposal

Describe the feature you're suggesting here, give lots of information and describe it as best you can. Please check that the feature hasn't already been suggested first, by searching the issues in this repository.

**Comment by nwjgit** [comment]
This has been fixed.
