### ISSUE TITLE
Notification spam

### ISSUE THREAD

**Issue by osDreamscape** [oldschoolgg/oldschoolbot#2700]
Remove "abusable" notifications such as clue milestones (or specifically mention it only at the 500/400/200/100th openings respectively)
![image](https://user-images.githubusercontent.com/73551894/130395842-8ce90b0d-d2ee-479d-aa0d-449f190aebb2.png)

anyone with multiple of any tier of casket can open 1 at a time and drop the milestone reward to spam notifs channel

**Comment by themrrobert** [comment]
If this is implemented, keep in mind that you can open multiple clues at once, so it should check oldClueKc vs newClueKc and see if the milestone is `oldClueKc > Milestone <= newClueKc`

**Comment by LuxrayElite** [comment]
Resolved by #5232
