### ISSUE TITLE
Typo on =open message 

### ISSUE THREAD

**Issue by dtafc123** [oldschoolgg/oldschoolbot#2732]
![Screenshot_20210829-230452_Discord~2](https://user-images.githubusercontent.com/88467015/131288139-e99bdba4-a4db-4824-aa56-ae7118e386ec.jpg)
## 🐛 Bug Report

Included screenshot change baby impling jar to baby impling as that is the correct command and consistent with the other implings.

**Comment by osrsjobbo** [comment]
Looks like this has been fixed between the issue being opened and today.

![image](https://user-images.githubusercontent.com/123830708/224821921-d1b777e2-4c6b-47ba-8642-72992c3e966f.png)

Closing as completed.
