### ISSUE TITLE
Remove need to equip boost items for wildy bosses

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2733]
## 🚀 Feature Proposal

To get the boosts from boost items for Callisto, Venenatis, Vetion, Scorpia, Crazy arch., Chaos fanatic+elemental, they have to be equipped  in the wildy setup. It makes sense since you would be risking the item, however it was apparently said by Magna that Wildy bosses will not have any pking mechanics added to them, making this redundant. Therefore, boosts should work from bank for these bosses.

**Comment by nwjgit** [comment]
Outdated with wildy rework
