### ISSUE TITLE
Bronze bar bug

### ISSUE THREAD

**Issue by whitemambz** [oldschoolgg/oldschoolbot#2738]
## 🐛 Bug Report

Can't smelt bronze bars, it says i don't have enough copper ore, while just having mined it. Tin ore also there.
![Copper](https://user-images.githubusercontent.com/89843074/131487189-045af19e-41e3-4de0-82e2-6b02519fd5f8.png)
![Tin](https://user-images.githubusercontent.com/89843074/131487255-b8d800ce-e022-43eb-9b41-35ca77517b65.png)

**Comment by 6enny6** [comment]
trip defaults to the maximum amount of bars you can make in one trip if you don’t specify a quantity.

In this case you do not have enough for a full trip.
If you try +smelt 116 bronze bar it will work
