### ISSUE TITLE
Create a way to stop yourself from gambling

### ISSUE THREAD

**Issue by baannanna** [oldschoolgg/oldschoolbot#2745]
## 🚀 Feature Proposal

Gambling for me like many others is a very addicting part of this game. It can be fun but it can also be horrible. I know its only a game, but its a game I enjoy very much as well as others enjoy. Gambling itself on this game alone has brought me many angry, sad and depressed days. I know that sounds extreme but its true. 

What I am suggesting is some sort of way to take away the gambling commands from your minion. Either permanently or just temporarily. With a 12hr cooldown to remove/restore the commands. 

+stopgamble
=stopgamble (or something like that)

It would take away your minions ability to gamble for at minimum 12 hours. After 12 hours you can restore it and gamble if you want or just let it stay off. 

It would make the game a lot more fun for some people.

**Comment by AvariceBrah** [comment]
If you play in your own server, you can specifically disable any commands, but yeah something that would be a temporarily irreversible would be useful. Cap max possible time in rehab to 36 hours in my opinion. 

> > > =Rehab <#ofhours> 

Alias could be ga for 'Gamblers Anonymous
'
Would you like to send your degenerate minion to Minion Rehab for #ofhours?



**Three options**:

**In-patient option** would be temporarily irreversible, have to wait the time limit you set. Like living in rehab.

**Out-patient option** would be reversible, but you can't check back into rehab until your insurance unloads your caseload + nominal flat fee to cancel maybe.

**Hell no!** Cancel the command. Return something silly like.. 
Your minion says _I thought this was anonymous gambling.... not gamblers anonymous. I **shouldn't** be here.. let's go_

**Comment by LuxrayElite** [comment]
Implemented by #5325 & #2f8b43d
