### ISSUE TITLE
Tames Interface/bank

### ISSUE THREAD

**Issue by gc** [oldschoolgg/oldschoolbot#2751]
- Make a "bank" image for tames, showing each of your tames.
- It could show things like: which one is selected, level, name, etc
- Also is needed for the idea of making "shiny" tames.

Rough mockup:
![image](https://user-images.githubusercontent.com/30398469/131757540-8cbc7e7a-5b19-4bfb-8a29-ca4b00c864fa.png)

**Comment by imgidedin** [comment]
Done in #2755
