### ISSUE TITLE
Volcanic Mine boosts not working properly

### ISSUE THREAD

**Issue by dtosrs** [oldschoolgg/oldschoolbot#2773]
Mining is boosted by 3a pickaxe, crystal pickaxe, gilded pickaxe, dragon pickaxe, etc etc
This isn't working properly at the new feature: Volcanic Mine
It only gives boost for Crystal Pickaxe and Dragon Pickaxe, giving 96k and 80k xp/hr respectively, which matches game.
But there's no boosts for 3a pickaxe and gilded pickaxe, giving only 62k xp/hr

**Comment by imgidedin** [comment]
3a pickaxe and gilded pickaxe wont give boosts anymore beyond their relative tier (3a = dragon and gilded = rune).
3a pickaxe will give a boost similar to dragon when the next OSB update goes live.
