### ISSUE TITLE
Lowering buy prices for irons

### ISSUE THREAD

**Issue by HouseParan73** [oldschoolgg/oldschoolbot#2780]
## 🚀 Feature Proposal

Currently irons pay as much as mains for all buy items (feathers, eyes of newts, broad arrow tips etc). There really isn't much reason to this as irons dont contribute to the economy like a main would and its a lot more difficult to obtain gp on an iron.

Irons should be able to pay in game prices for all shop items. If worried that people will make irons to pay low prices then deiron, then this can be made a feature for perm irons.

**Comment by HouseParan73** [comment]
Bumperino cappuccino

**Comment by gc** [comment]
In the next update, ironmen will pay the ingame prices for: fishing bait, feather, eye of newt, vial, vial of water, broad arrows, broad arrowheads
