### ISSUE TITLE
Barrage doesn't affect food use

### ISSUE THREAD

**Issue by AvariceBrah** [oldschoolgg/oldschoolbot#2806]
https://github.com/oldschoolgg/oldschoolbot/blob/c5cd5079f33098d1b9f4c00760ef35d079f6e24a/src/lib/minions/functions/calculateMonsterFood.ts#L17

Would be awesome if when slaying with barrage on, that it'd reduce the food usage even further.

**Comment by Lajnux** [comment]
the food consumption in bot is overall super low as long as someone equips items in all setups with reasonable effort. And ppl can +buy potato with cheese. don't think this is needed <3 🐳🥰

**Comment by AvariceBrah** [comment]
Fair. Just noticed that despite using blood barrage, it isn't considered.

**Comment by eggaroonie** [comment]
You don't use blood barrage, you use ice barrage. There isn't even an option to use any of the blood spells.

**Comment by AvariceBrah** [comment]
I've never seen a water rune, not a single one, get used XD so now this issue has adapted into 

ITT: **_Fix the use of water runes when barraging on task_**

**Comment by eggaroonie** [comment]
You don't use water runes if you have any kind of water saving staff equipped. Kodai wand, any variation of a staff of water, any combination staff that includes water runes, etc.

**Comment by eggaroonie** [comment]
I mentioned you in #developers with screenshots of this but just for the sake of posterity:

![image](https://user-images.githubusercontent.com/84296933/132455594-fb8d6fea-97cf-4b99-9caf-36993e9e3998.png)
![image](https://user-images.githubusercontent.com/84296933/132455600-46e0bd2a-17a1-4c21-93c1-c53518de44fe.png)
![image](https://user-images.githubusercontent.com/84296933/132455605-c9188aca-ef3f-4540-9492-15b0a48f135d.png)
![image](https://user-images.githubusercontent.com/84296933/132455703-1fb16a84-ca52-49b6-a4e2-7a067ef12d76.png)
