### ISSUE TITLE
Nightmare garden decoration points to Kraken decoration image

### ISSUE THREAD

**Issue by anthonyburrow** [oldschoolgg/oldschoolbot#2841]
## 🐛 Bug Report

The Nightmare garden decoration has the same ID (494) as the Kraken one, so building this decoration shows a Kraken image in the POH.

https://github.com/oldschoolgg/oldschoolbot/blob/f9391758f5958149d7ebfa1ba1a0d3ab56528083/src/lib/poh/objects/garden_decorations.ts#L112-L127

**Comment by gc** [comment]
Fixed in next update.
