### ISSUE TITLE
+minigamesgains (minigains?) command thats like xpgains/kcgains

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2858]
## 🚀 Feature Proposal

Just like Xpgains/Kcgains showing most exp/kc gained in a timeframe, the same should be added to minigames. Not sure what cmd should be though, Minigamesgains is a bit lengthy but minigains is a nice pun+fits well IMO.  

IE: +minigains day Gauntlet , 10 players with most kc in the day are returned

These would be the minigames tracked: `Tithe farm, Wintertodt, Tempoross, Hallowed Sepulchre, Fishing Trawler, Barbarian Assault, Pyramid Plunder, Brimhaven Agility Arena, Champions' Challenge, Mahogany Homes, Gnome Restaurant, Soul Wars, Rogues' Den, Gauntlet, Corrupted Gauntlet, Castle Wars, Chamber's of Xeric, Chamber's of Xeric - Challenge Mode, Magic Training Arena, Big Chompy Bird Hunting, Temple Trekking, Pest Control, Volcanic Mine.`

**Comment by LuxrayElite** [comment]
Should still be considered as an interesting data point since we track so many things already imo
