### ISSUE TITLE
Buying a hallowed ring doesnt give the item, still takes marks.

### ISSUE THREAD

**Issue by Eutherin** [oldschoolgg/oldschoolbot#2864]
![Screenshot_20210914-194105_Discord](https://user-images.githubusercontent.com/25861695/133361868-746e1ab0-cf0a-4063-9a50-3d86d4e1c095.jpg)
![Screenshot_20210914-194357_Discord](https://user-images.githubusercontent.com/25861695/133361875-73b58eb4-6482-4802-8bcd-4dc075695f97.jpg)
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

**Comment by imgidedin** [comment]
Could be a sync issue. Could you do just `+b` and check if the ring is not there?

**Comment by imgidedin** [comment]
User had the ring equipped on its +gear melee.
Solved.
