### ISSUE TITLE
Vorkath not giving boost/exp when on a blue dragons slayer task. 

### ISSUE THREAD

**Issue by Sopison** [oldschoolgg/oldschoolbot#2867]
## 🐛 Bug Report
Vorkath not giving boost/exp when on a blue dragons slayer task. 

![image](https://user-images.githubusercontent.com/51812123/133472165-a71aaf77-280c-4799-a55d-42c542f775b1.png)
![image](https://user-images.githubusercontent.com/51812123/133472240-76c76737-a767-4c4b-9224-1cb5f70d5c53.png)

**Comment by Sopison** [comment]
Meanwhile on 13/09/2021 
![image](https://user-images.githubusercontent.com/51812123/133472413-c99c3560-7199-449f-8766-2d4b00341d2b.png)

**Comment by imgidedin** [comment]
Are you sure you are not on Konar's? Konar's blue dragon task does not give boosts to Vorkath. Same as in-game.

**Comment by imgidedin** [comment]
Konar does not allow Vorkath to be killed during blue dragon tasks.
