### ISSUE TITLE
Allow +rc chaos as a shortcut for runecrafting chaos runes similar to other runes

### ISSUE THREAD

**Issue by Jebusnorris** [oldschoolgg/oldschoolbot#2874]
## 🚀 Feature Proposal

+rc astral allows astrals to be crafted without having to type out +rc astral rune
same with fire runes and other types

this doesnt work for chaos runes...
allow +rc chaos to work instead of having to type out +rc chaos rune

**Comment by Lajnux** [comment]
merging #2885 will resolve this issue.
