### ISSUE TITLE
Add sandstone mining into the bot

### ISSUE THREAD

**Issue by Jebusnorris** [oldschoolgg/oldschoolbot#2876]
## 🚀 Feature Proposal - Sandstone mining

Currently the only way to obtain buckets of sand is from killing kalphite queen in the bot. This is slow and doesn't really reflect the main way people obtain these ingame. [Sandstone](https://oldschool.runescape.wiki/w/Sandstone) in game can be mined and then grinded into buckets of sand. This would allow buckets of sand to be obtained and used for making molten glass through a reasonable and realistic method.

ty for coming to my tedtalk

**Comment by JerMous3** [comment]
Hi, first of all thanks for your ted talk. 
Even though it could be a good addition, u can +collect sand too now 👍🏼
