### ISSUE TITLE
Takon bug 

### ISSUE THREAD

**Issue by 22rifleman** [oldschoolgg/oldschoolbot#2895]
## 🐛 Bug Report

I receive the same xp/hr and platebodies/hr with and without takon equipped. I tried with and without dwarven greathammer and that has no effect as well.

**Comment by 22rifleman** [comment]
I have the dg scroll that saves 15% bars in case that may cause the bug I’m not sure

**Comment by mylife212** [comment]
have you tried a trip with takon equipped but not dwarven hammer? despite takon having a higher bonus, greathammer is prioritized when both are equipped

**Comment by 22rifleman** [comment]
@mylife212 yes I tried with takon equipped and greathammer in bank
