### ISSUE TITLE
Ring of Endurance

### ISSUE THREAD

**Issue by SirRobro** [oldschoolgg/oldschoolbot#2898]
## 🐛 Bug Report

Using a Ring of Endurance (uncharged) gives a bonus in the Sepulchre, but using a Ring of Endurance (charged) does not.

![Screenshot_20210924-111429_Discord](https://user-images.githubusercontent.com/91335433/134699451-6fa4d140-59a5-4a52-81ee-01d8d66a33e6.jpg)

**Comment by 6enny6** [comment]
the ring of endurance shouldnt even give a boost at all at the sepulchre, as it doesnt on osrs.
the uncharged boost was added to give the ring a use on the bot but it should be removed anyway
