### ISSUE TITLE
Favfood doesn't actually favorite the food item, rather the # of HP healed.

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2937]
## 🐛 Bug Report

Sry for confusing title but for example...

If you have Summer pies and Manta rays in your bank, both being foods that heal 22 hp, and your favfood is Manta rays, summer pies are first prioritized when you consume food. 
https://images-ext-2.discordapp.net/external/IEMpDoN7PJdCTGHB2GB1CKXJbEBBh0nJTNGfEFw6kwE/https/i.imgur.com/rSkBIq3.png

**Comment by gc** [comment]
I believe this is fixed now.
