### ISSUE TITLE
Fightcaves chance of survival bugged

### ISSUE THREAD

**Issue by TastyPumPum** [oldschoolgg/oldschoolbot#2953]
Not sure if due to some of the inferno changes, but I've killed Jad 7 times, just went to do fightcaves again and have a 0.9% chance of survival.

![image](https://user-images.githubusercontent.com/79149170/135727388-0917fac3-f669-4a33-9fc8-9c024c0c5458.png)
![image](https://user-images.githubusercontent.com/79149170/135727389-83f08c9c-d7cf-4f23-b2de-12eda7ccf303.png)

Edit - added range gear for you to see if that helps 
![image](https://user-images.githubusercontent.com/79149170/135727439-bc34ee79-1cb3-4022-b546-6000b537b4af.png)

Edit - added the return trip 
![image](https://user-images.githubusercontent.com/79149170/135728851-fedfd1ed-3420-4c1e-bfc1-d19742071951.png)

Back in january 2021, my discord got banned and magna had to transfer my stuff across, so could be related to that also

**Comment by ard35** [comment]
Looks like your kc transferred but your attempts did not (it's at 0). The chance of death calculations use the attempts # instead of the kc. You need to ask Mango if he can transfer the attempts too.

**Comment by TastyPumPum** [comment]
If it's only affecting me because of the transfer I'll close this, thanks for letting me know.
