### ISSUE TITLE
Sellto —tab issue

### ISSUE THREAD

**Issue by DrugsOsb** [oldschoolgg/oldschoolbot#2965]
Quite hard to explain so the images below might help, 
the **+sellto @username $$ —tab** doesn’t seem to be working quite as it should, whenever a price is specified for said tab, I believe it’s checking for amounts available.
Example.

![B9925466-4CA2-4786-BA6A-09CBC0F68091](https://user-images.githubusercontent.com/72406954/135922917-2374ca39-4940-44b5-9a58-10f9bf3b14ae.jpeg)

![3EB2FEFB-5914-4252-8F92-B70EF1995618](https://user-images.githubusercontent.com/72406954/135923164-f8377000-8d37-4d8b-b855-2f1310118a1f.jpeg)

🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

**Comment by gc** [comment]
Should be fixed in next update.
