### ISSUE TITLE
Farming Mushrooms

### ISSUE THREAD

**Issue by bigsquid69** [oldschoolgg/oldschoolbot#2967]
## 🐛 Bug Report
Farming mushroom patch, I receive 24 mushrooms no matter how many patches I plant. I have scroll, and master farmer + plopper. Planting 6 patches. Using ultracompost. 
Also running into and issue with =af where I can plant Limpwurt, but it says wait x time - usually reflects my allotment time remiang on this bug

**Comment by bigsquid69** [comment]
![CA405148-88F8-4637-AE45-B2C018841A80](https://user-images.githubusercontent.com/80061861/136037735-8809d8b3-73a1-45db-a447-6e135f61f38a.jpeg)
![9B904294-68BB-48C7-9A81-33467CDC7D96](https://user-images.githubusercontent.com/80061861/136037742-4bd6b34b-77ef-4742-a92e-d694c2236596.jpeg)
![D973C848-B441-47F8-809E-B58E014E54A2](https://user-images.githubusercontent.com/80061861/136037747-c1ec9dd3-498c-4e3f-88e1-de4cc9386a72.jpeg)

**Comment by bigsquid69** [comment]
One is master outfit and plopper only. 
One is a single plant.
One with scroll and master farmer.
Thanks!!

**Comment by bigsquid69** [comment]
![A621F3F5-FDE6-44FB-9552-731D9CA6E529](https://user-images.githubusercontent.com/80061861/136110276-0dd92f5d-4b20-466a-b2c9-911492e1d34e.jpeg)

**Comment by LuxrayElite** [comment]
This issue seems to be resolved. Feel free to reopen this issue if still present
