### ISSUE TITLE
=bankbg casket

### ISSUE THREAD

**Issue by MS1909** [oldschoolgg/oldschoolbot#2973]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

if (selectedImage.collectionLogItemsNeeded && msg.author.cl().has(selectedImage.collectionLogItemsNeeded))

Having an issue trying to buy the casket background. I have all the relevant items obtained and it's saying that I do not have them in the collection log. The items aren't from untradable mystery boxes and were obtained via completing clues.

**Comment by Alexsuperfly** [comment]
fixed in bb6c27c5682bbe898fc0d015dee99268d7851e12
