### ISSUE TITLE
Allow +m pat while busy on OSB

### ISSUE THREAD

**Issue by eggaroonie** [oldschoolgg/oldschoolbot#2993]
## 🚀 Feature Proposal

Currently, using the `+m pat` command on OSB while your minion is busy will just return a normal "[minion name] is currently busy."

This is in contrast to BSO, where you can pat your minion regardless of whether or not they are on a trip. 

I, and many like-minded individuals who believe in the well being and happiness of their minions, think it is important that this functionality is brought over to OSB.

**Comment by gc** [comment]
Done
