### ISSUE TITLE
unable to kill certain monsters

### ISSUE THREAD

**Issue by Nickoo4444** [oldschoolgg/oldschoolbot#2996]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
Hey, I'm inable to =k certain monsters including skeletons, I get this message.

**Comment by Nickoo4444** [comment]
https://i.gyazo.com/93e1fd15890cf8ac87016c37a0138c39.png

**Comment by eggaroonie** [comment]
Please read the #faq channel in the [support discord](https://www.discord.gg/ob).

**Comment by gc** [comment]
I believe this is fixed now.
