### ISSUE TITLE
add a --replant flag to autofarm, that makes it only re-plant patches already grown

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#2999]
## 🚀 Feature Proposal

Basically what title says. Say you have plenty of patches ready to harvest, while you have some patches with nothing in them at all. If you were to +autofarm --replant (or something), it would only autofarm those grown patches while ignoring the empty ones.

Why? Because its tedious spelling out multiple farming commands for individual patches, and Autofarm is a bit inconvenient for those who don't use every patch as wastes times on patches that the player doesn't care for.

For example, in the image below it'd ignore the patches that have nothing grown. Those with a checkmark would be only ones that get farmed. 
![image](https://user-images.githubusercontent.com/63373565/136860391-9ce39716-d2cd-4ed1-a247-67571d15e40d.png)

**Comment by osrsjobbo** [comment]
@mylife212 Do you think this is closed by /farming auto_farm_filter auto_farm_filter_data:Replant?

**Comment by osrsjobbo** [comment]
Confirmed can close

**Comment by mylife212** [comment]
Yes it is, thanks!
