### ISSUE TITLE
Slayer Boss Task Bug

### ISSUE THREAD

**Issue by Pixels0420** [oldschoolgg/oldschoolbot#3012]
## 🐛 Bug Report

![ae793a1d79acb25db8eeceebaa5439ad](https://user-images.githubusercontent.com/92455852/137169380-68437626-e197-4596-853f-95f309390fbd.png)

Killed 8 Arma but it removed 32 from my remaining kills.

**Comment by 6enny6** [comment]
no bug, it includes killing the minions
