### ISSUE TITLE
Remove the favourites restriction on sellto

### ISSUE THREAD

**Issue by 000000653** [oldschoolgg/oldschoolbot#3059]
## 🚀 Feature Proposal
This shouldn't have ever been a thing. People know what they're selling when using sellto. This restriction only came about due to people specifically complaining about sacrifices and bot selling (and even then, mostly with filters) which has no way to undo, honestly I'm not sure if this was just misinterpreted as sellto instead of just sell. This has caused a deluge of support questions and people thinking selling is bugged when in reality there's just a bad "feature" which gives 0 feedback from the bot about what the issue is.

Additionally, if something is sold to another player unintentionally, people can simply ask for it back and 99% of people will not be dicks and give it back.

**Comment by eggaroonie** [comment]
> Simply just dont use `--cf` in cases where you're selling favorited items, its a slight inconvenience but it stops some bad things from happening.

Just bumping this, you aren't able to trade favorited items at all in OSB regardless of whether or not you use --cf. Definitely best to just remove the restriction entirely from +sellto.

**Comment by eggaroonie** [comment]
Just as an example of that, person isn't using --cf, still can't trade the items until they un-favorite them.

![image](https://user-images.githubusercontent.com/84296933/139624181-fae4e620-7dc2-4074-8888-3174ffac95ec.png)

**Comment by imTURBObruh** [comment]
> > Simply just dont use `--cf` in cases where you're selling favorited items, its a slight inconvenience but it stops some bad things from happening.
> 
> It prevents you without --cf as well, this closure is invalid. It's also, as I said, not remotely a valid "safety measure" and only stops legitimate sales. Most people I've talked to agree with me that this is not a good "feature" for sellto, so I'll continue to bump this issue semi-regularly.

it does not prevent without `—cf` on __BSO__ buy it does on __OSB__. it also prevents sacrificing favs

**Comment by imTURBObruh** [comment]
> Just bumping this, you aren't able to trade favorited items at all in OSB regardless of whether or not you use --cf. Definitely best to just remove the restriction entirely from +sellto.
>
>
> Just as an example of that, person isn't using --cf, still can't trade the items until they un-favorite them.
> 
> ![image](https://user-images.githubusercontent.com/84296933/139624181-fae4e620-7dc2-4074-8888-3174ffac95ec.png)
> 

> just don't use —cf and you can sellto favorites
>
> it's a nice safety measure,  in my opinion it should be OSB allow sellto of favorite items.
>
_Originally posted by @imTURBObruh in https://github.com/oldschoolgg/oldschoolbot/issues/3059#issuecomment-950817168_

I kind of mentioned the fact that OSB should allow +sellto on favorited items  so why would my post be voted 👎🏻... and not yours? gah... lol. 

either way.. another bump.
