### ISSUE TITLE
Unable to sell items I clearly own

### ISSUE THREAD

**Issue by Hewlett12345** [oldschoolgg/oldschoolbot#3080]
## 🐛 Bug Report

Old School Bot has an item storage just like a bank in game. I can buy things from my friends but cannot sell things back to them. Every time I try to sell it back to them I get a message that basically says I don’t have anything like that, when I check my bank I clearly have 40+ or even the bones I tried to sell to my friend I had 9800 of them.

**Comment by 000000653** [comment]
Do you have them favorited? Favorited items on Old School Bot cannot be sold at the moment, you have to unfavorite them to sell them. Also, for what it's worth, questions like this should probably be asked first in the discord support server to not bloat issues.
