### ISSUE TITLE
Missing tzhaar collection log items and monsters

### ISSUE THREAD

**Issue by osDreamscape** [oldschoolgg/oldschoolbot#3085]
![image](https://user-images.githubusercontent.com/73551894/139600645-64c3ef7a-7854-4b54-a36a-e578d7e67d1a.png)

Tzhaar cl is currently missing staff and rings, which can only be obtained as drops from mobs that are missing

Needs TzHaar-Xil, TzHaar-Mej, and TzHaar-Hur added, and killtimes can be scaled based on hitpoints (60/50/40% of existing TzHaar-Ket respectively, which is 35 seconds base).

Add Toktz-mej-tal and Toktz-xil-ul to existing tzhaar collection log

**Comment by gc** [comment]
Done in next update.
