### ISSUE TITLE
Minion able to do more then one action

### ISSUE THREAD

**Issue by Redmage805** [oldschoolgg/oldschoolbot#3086]
I was told that the minion is able to join two different trips at once when involed with the pumpkinhead mass. It works by joining the ph mass while it’s waiting to be sent you send before the mass is trip begins another command it sends the minion on that trip and then when the mass sends your minion also is sent with the mass. 
![D8E14BCF-92C8-483E-9E52-0A41393B11F9](https://user-images.githubusercontent.com/86848539/139604760-36996ab7-282a-4a00-acaa-5e29274d0a6b.png)
![FD2A50B5-4F76-4D69-A4A8-49959066E758](https://user-images.githubusercontent.com/86848539/139604763-87da6e71-97f3-4b2b-b805-fee8bedebfb0.jpeg)

as you can see here one trip ends and then 6 min later another trip also ends as well showing the minion performed both actions. 

I don’t know if this works with other masses.

**Comment by gc** [comment]
Thank you for reporting.
