### ISSUE TITLE
Kcgains cmd

### ISSUE THREAD

**Issue by Kuroka-Kure** [oldschoolgg/oldschoolbot#3088]
## 🐛 Bug Report

Tried using the command on nightmare and it didn't work even thoe it is listed as an example for the command on the oldschool.gg site.
![Screenshot_1](https://user-images.githubusercontent.com/93571648/139795804-57085200-838f-4c5f-82f6-42f7d4fdf5e3.png)

**Comment by gc** [comment]
I've changed the example, checking kcgains for nightmare and other special bosses is not possible.
