### ISSUE TITLE
Message when receiving a pet

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#3090]
Could the ‘you have a funny feeling you’re being followed’ here be put in bold please i didnt even notice til days later

Also it doesn’t say Beaver in the loot received

![41B99DFB-2B3C-4966-835D-DFD2B066767C](https://user-images.githubusercontent.com/76587427/139916329-9372de31-85ef-440d-8059-8d65f7ab5a04.jpeg)

**Comment by gc** [comment]
Fixed both issues
