### ISSUE TITLE
Can't make Super Combat Potions with Torstol Potion (unf)

### ISSUE THREAD

**Issue by DadVax** [oldschoolgg/oldschoolbot#3101]
Currently in OSB & BSO you can only make Super Combat Potions with Torstol.

In game, they can be made with Torstol and Torstol Potion (unf).

![image](https://user-images.githubusercontent.com/79945242/140461799-49760d00-8a76-4d80-86ae-5214b907b5dc.png)

**Comment by 6enny6** [comment]
do `+buy torstol`
