### ISSUE TITLE
Add combat XP to CoX

### ISSUE THREAD

**Issue by TwiceUponATaco** [oldschoolgg/oldschoolbot#3120]
## 🚀 Feature Proposal

TL;DR - Add xp gains to CoX. Mostly combat, but potentially some small amounts of xp in other skills as well.

Examples from Raids:

Solo raid with thieving room and full prep:
![Solo w prep   thieving](https://user-images.githubusercontent.com/41974029/140801573-57b6912b-184c-4b28-994e-5c2a71156843.PNG)

5 man CM raid with full prep:
![5man CM](https://user-images.githubusercontent.com/41974029/140801648-01a43a61-48b6-4f4e-92b7-59d0d175ad64.PNG)

I will add screenshots for xp from other scales as I continue doing raids

**Comment by TastyPumPum** [comment]
CoX now has combat xp
