### ISSUE TITLE
[BSO] Inferno gives a boost for Virtus set AND Gorajan mage. Only have Gorajan

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#3124]
## 🐛 Bug Report

Can see in screenshot that I get a boost for Ancest/Virtus and Gorajan mage. I don't have any virtus armor pieces on, only Gorajan. Perhaps the virtus wand/book give the boost too?
![image](https://user-images.githubusercontent.com/63373565/141072358-7f6755a3-aee3-4d9b-b19a-c8e235491783.png)
Gear I have on: 
![image](https://user-images.githubusercontent.com/63373565/141072391-7c9f3432-83fa-430c-b332-a41e12253f9c.png)

**Comment by JerMous3** [comment]
To add to his, regular Pernix doesnt work neither does a Zaryte Bow.

Ps Nice Rune arrows noob!

**Comment by osrsjobbo** [comment]
Looks like this has been fixed between issue being opened and today.

![image](https://user-images.githubusercontent.com/123830708/224822575-d591f575-17a1-42bb-80de-00d8c3d65ea4.png)

![image](https://user-images.githubusercontent.com/123830708/224822616-2314e852-744c-4e21-9c56-e3c0bfcee869.png)
