### ISSUE TITLE
New =m ep pet equipping system bugged 

### ISSUE THREAD

**Issue by 2Kurrupted** [oldschoolgg/oldschoolbot#3151]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

The =m ep "petnamehere" is allowing for pet changing during trips. Unsure if its intentional but i highly doubt it.
Noticed in oldschool.gg server showing someone how to equippet Klik, and as i typed the command to show them how during my Igne trip, it swapped from Zak to Klik.

**Comment by gc** [comment]
Fixed in next update.
