### ISSUE TITLE
"Say y to continue trip." and +/=m button no longer send repeat autofarm trips.

### ISSUE THREAD

**Issue by eggaroonie** [oldschoolgg/oldschoolbot#3155]
## 🐛 Bug Report

Basically just the title.

Since the update moving autofarm to +/=m, you are no longer able to repeat trips by typing the continuation character, or by using the button interface when doing +/=m.

Bot not responding to continuation character:
![image](https://user-images.githubusercontent.com/84296933/141941635-977a3603-2743-4812-8bbf-ac190b436788.png)

Buttons in =m appearing but not being responsive:
https://user-images.githubusercontent.com/84296933/141941928-8391ae38-1748-4bc8-b32b-a59e559f5419.mp4

**Comment by Superwhammybar** [comment]
Looks like this is a side-effect of moving the autofarm command to a minion command.

Unsure how to fix though.

**Comment by gc** [comment]
Fixed in next update.
