### ISSUE TITLE
Two trips come back

### ISSUE THREAD

**Issue by Budiearby** [oldschoolgg/oldschoolbot#3193]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
I sent a dg trip cancelled and then sent igne trip, both trips came back then sent another igne trip and 2 came back again and it happens everytime i send trips now. Haven’t checked if i get loot from both trips but 2 come back everytime

**Comment by mylife212** [comment]
Should be fixed now - was a bug with the engine update but a fix went through. Feel free to re-open if its still happening
