### ISSUE TITLE
CoX messages in #notifications are off by 1 kc

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#3202]
## 🐛 Bug Report

Got dust kc836, notifications says 835. 
![image](https://user-images.githubusercontent.com/63373565/143393331-75332ca9-466e-42c2-ba2a-b9f50dbb8254.png)
![image](https://user-images.githubusercontent.com/63373565/143393372-1a432b44-710d-467f-9fad-1544157d60bf.png)

**Comment by gc** [comment]
Should be fixed in next update.
