### ISSUE TITLE
+drop command

### ISSUE THREAD

**Issue by SenditJase** [oldschoolgg/oldschoolbot#3206]
## 🐛 Bug Report

Hey team, 

Have been trying to use the +drop Burnt (fish) type here, however it is saying it is invalid item has been selected. 

I have used +bs burnt and confirmed that I have burnt fish I can't get rid of; please check Tuna, Mackerel etc. or provide me with the correct command to use.

**Comment by TastyPumPum** [comment]
As multiple fish have the name "burnt fish", the best way to do this would be "+bs burnt --id" then "+drop quantity id" if you have any troubles feel free to @ me in the discord and I'll help you out

**Comment by SenditJase** [comment]
> As multiple fish have the name "burnt fish", the best way to do this would be "+bs burnt --id" then "+drop quantity id" if you have any troubles feel free to @ me in the discord and I'll help you out ![Untitled](https://user-images.githubusercontent.com/79149170/143563403-1a330042-0a8c-49cd-a007-9305ab395091.png)

Thank you mate, that worked!!
