### ISSUE TITLE
Allow Farming Skill to have a +pick option

### ISSUE THREAD

**Issue by Darkpupitar3** [oldschoolgg/oldschoolbot#3219]
Currently, we have to use seeds every time to harvest/plant a farming crop. This wastes seeds especially when you want to only collect the plant such as potato cactus or whiteberries for farming. My suggestion is to add in a +pick which will only pick the applicable farming plant off while leaving the bare plant behind. This is to build up herblore supplies reliably over time:

From OSRS Wiki:
While planting the seed requires level 59 Farming, picking the berries does not. Picking one white berry yields 29 experience. Once all berries are picked from the bush, it will produce more berries, **approximately 1 per 25 minutes**; one seed can produce a minimum of 4 berries, where the Farming level reduces the chance of using up one of the four "lives" of the patch, much like harvesting herb patches.

**Comment by TastyPumPum** [comment]
This has already been requested in #1125
