### ISSUE TITLE
collect lava scale

### ISSUE THREAD

**Issue by tympani** [oldschoolgg/oldschoolbot#3237]
#3234  Feature Proposal

In osb/bso, it would be helpful in Herblore training if we could collect Lava scales and use those to make Lava scale shards. The shards can make our antifire/super antifire into an extended version and we get 160xp per pot.

extra: give it “wildy code” from black chins and we lose brews/possibly die from this activity.
allow monkey tame to collect as well, with same “cost” of brews/dieing odds

**Comment by TastyPumPum** [comment]
As you aren't able to collect lava scales in game I don't think we should be able to on this.

You can currently kill lava dragons for lava scales, and if #3031 gets merged it will give an alternative way to get the scale shards.
