### ISSUE TITLE
Hellfire arrows disappearing

### ISSUE THREAD

**Issue by Qwertyweezel** [oldschoolgg/oldschoolbot#3248]
## 🐛 Bug Report

I was trying to figure out how to get my borrowed hellfire bow to work for malygos, so I equipped the bow and 333 arrows to my wilderness setup. Couldn't get it working, so I =unequip wildy hellfire arrow, which deleted all but 1 hellfire arrow, which ended up in my bank. I believe the problem occured when I didn't type how many arrows to remove.

**Comment by mylife212** [comment]
could you post pictures of the bug? IE: Equipping the arrows, unequipping them and showing they're deleted

**Comment by themrrobert** [comment]
I'm unable to replicate this.

I suspect the arrows were used when attempting to kill something in the wildy with =k (possibly not wearing the ranged master cape or avas)

You cannot use a qty in the unequip command, it removes all of them.

If you can post screenshots of everything, from equipping the arrows to attempting to kill maly/etc, then I can look farther into it, it will help me narrow down what to look at. (I need to see exactly how 'it didn't work' when you tried to kill maly, etc)

**Comment by Qwertyweezel** [comment]
![Uploading Screenshot_20211207-104036.jpg…]()

**Comment by Qwertyweezel** [comment]
![Uploading Screenshot_20211207-104250.jpg…]()

**Comment by Qwertyweezel** [comment]
![Uploading Screenshot_20211207-104303.jpg…]()

**Comment by Qwertyweezel** [comment]
![Screenshot_20211207-104321](https://user-images.githubusercontent.com/90746611/145061643-c9e6ad0f-3769-4fa1-89c8-7a6b5571ecc1.jpg)
![Uploading Screenshot_20211207-104326.jpg…]()
![Uploading Screenshot_20211207-104500.jpg…]()

**Comment by Qwertyweezel** [comment]
![Screenshot_20211207-104333](https://user-images.githubusercontent.com/90746611/145061667-72bf3326-d31c-4815-8173-7a832fbc000b.jpg)
![Screenshot_20211207-104509](https://user-images.githubusercontent.com/90746611/145061711-33a3df3e-b9c1-4665-9713-a7cfe856ff3e.jpg)
![Screenshot_20211207-104353](https://user-images.githubusercontent.com/90746611/145061712-60d2e7e4-defe-4269-a080-657a1dfbd3ad.jpg)
![Screenshot_20211207-104415](https://user-images.githubusercontent.com/90746611/145061735-e4870c6e-5033-4392-8c4a-15e633839f53.jpg)
![Screenshot_20211207-104516](https://user-images.githubusercontent.com/90746611/145061749-1145bc1b-3a26-4d83-9d5c-3d7f17f59478.jpg)
![Screenshot_20211207-104427](https://user-images.githubusercontent.com/90746611/145061768-68e867b6-3e64-4269-9ab4-3602fdc65846.jpg)
![Screenshot_20211207-104522](https://user-images.githubusercontent.com/90746611/145061785-d1294d70-46f4-471a-a71d-a969c2e2c51d.jpg)
![Screenshot_20211207-104445](https://user-images.githubusercontent.com/90746611/145061789-7ecb7a35-b4c5-4ab5-87a9-8ca541ed27f9.jpg)
![Screenshot_20211207-104452](https://user-images.githubusercontent.com/90746611/145061833-dad6ea2d-1689-4540-a415-eb805361ec3f.jpg)

**Comment by Qwertyweezel** [comment]
Here specifically shows my exact problem.
![Uploading 145061735-e4870c6e-5033-4392-8c4a-15e633839f53 (1).jpg…]()

**Comment by Qwertyweezel** [comment]
![Screenshot_20211207-114241](https://user-images.githubusercontent.com/90746611/145070232-415aa78f-f992-4433-82a8-4401376403b4.jpg)

**Comment by themrrobert** [comment]
Excellent, this is why the screenshots are so useful :D 

It looks like the problem here was in the =autoequip command. I will investigate, thank you for the update.
