### ISSUE TITLE
King Goldemar Simulation not rolling broken dwwh

### ISSUE THREAD

**Issue by imTURBObruh** [oldschoolgg/oldschoolbot#3255]
## 🐛 Bug Report

I've done `=kill 150k kg` multiple times and it has not once rolled the broken dwwh

**Comment by gc** [comment]
its dropped in a special mechanic/way, and isnt part of its normal loottable (this wont work/wont be fixed)

**Comment by imTURBObruh** [comment]
> its dropped in a special mechanic/way, and isnt part of its normal loottable (this wont work/wont be fixed)

alright good to know thanks. I was just very confused lol
