### ISSUE TITLE
(BSO)=m cancel deleted herbs

### ISSUE THREAD

**Issue by toulouseee** [oldschoolgg/oldschoolbot#3267]
## 🐛 Bug Report

I was mixing dwarf weed potion (unfs), but forgot to do =mix dwarf weed potion **--zahur,** so I went to cancel the trip in order to do that but after using =m cancel I lost all 604 of the clean dwarf weeds & vials of water.

**Comment by 6enny6** [comment]
you should read the message when doing `=m cancel`, it tells you that you will lose all supplies from the trip
