### ISSUE TITLE
[BSO] Gearpresets wiped gear from existence

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#3280]
Used gearpreset to unequip clue hunter and equip a RC skilling outfit

Clue hunter, farming master cape and dwarven greathammer were all completely wiped from existence

![image](https://user-images.githubusercontent.com/76587427/145689140-3c420c1c-3080-4609-8ff6-c70ee56f5e24.png)

![image](https://user-images.githubusercontent.com/76587427/145689204-591f3b8e-f426-4084-8e69-a37dae002a42.png)

![image](https://user-images.githubusercontent.com/76587427/145689159-1f070772-86eb-417b-a186-b4d572b1f108.png)

**Comment by 6enny6** [comment]
Another case - Guy lost full torva and more as a result of this

![image](https://user-images.githubusercontent.com/76587427/145690436-03a4432b-1798-411a-bced-66199cd194a6.png)

![image](https://user-images.githubusercontent.com/76587427/145690447-f96b864e-a542-4e6c-8b1e-98c117e88c6f.png)

**Comment by themrrobert** [comment]
Issue verified and reproduced.

Working on fix
