### ISSUE TITLE
Brimhaven Agility Area Ticket Exchange

### ISSUE THREAD

**Issue by Osrs-Chan** [oldschoolgg/oldschoolbot#3283]
## 🐛 Bug Report

When doing =aa buy or +aa buy the bots suggest you should do =agilityarena buy xp 5 or +agilityarena buy xp 5. When attempting to do this command the bots then tell you, "You can only redeem tickets for XP at the following quantities: 1, 10, 25, 100, 1000.". Requesting to have the amount the bot suggest to either 10 or make 5 a possible quantity you could do.

**Comment by TastyPumPum** [comment]
5 won't be an option as it's not an option in game - https://oldschool.runescape.wiki/w/Agility_arena_ticket

Could be rewrote for 10 but then you won't get the message showing the available quantities.
