### ISSUE TITLE
Cave horrors black mask drop

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#3290]
Currently cave horrors drop `black mask (10)`, but the slayer helm requires just a regular `black mask` to create.

You can do `+create uncharged black mask` to turn the (10) into a regular, but no one even knows about this command and we spent ages figuring out how to make a slayer helmet, had to check the code to even find out about that creatable.

Could cave horror drop be changed to the uncharged version, or the slayer helmet creatables be changed to the (10) version please

Apparently this change was made some time in the past but it got reverted back to (10) for some reason, so now were back to the same issue

![image](https://user-images.githubusercontent.com/76587427/146053046-9733689c-251b-4a00-aa85-cf59501d52bd.png)

![image](https://user-images.githubusercontent.com/76587427/146053435-f3618a93-979e-44e3-a37b-c701134a7f54.png)

**Comment by themrrobert** [comment]
This behavior is not currently observed. Cave horrors are dropping 'Black mask'. 

Please create a new issue if this recurs.
