### ISSUE TITLE
[OSB] Make the achievement diary cape work when owned instead of equipped

### ISSUE THREAD

**Issue by Souzer** [oldschoolgg/oldschoolbot#3298]
## 🚀 Feature Proposal

Currently the cape only works when having it equipped making it useless imo since it gives the same boost as full graceful which im sure basically everyone owns. 
So my suggestion is to lower the boost from 10% down to 5% and make it work when having it in the bank, makes more sense too since I don't think ive worn that cape in OSRS before when doing clues

**Comment by eggaroonie** [comment]
hope this helps😊
![osbot~2](https://user-images.githubusercontent.com/84296933/146205635-a5eec6d5-49a4-40a8-a299-5cadce14b76c.png)

**Comment by 6enny6** [comment]
Yeah just equip your AD cape in any setup, you can equip both and receive both boosts 👍
