### ISSUE TITLE
Slepey Tablet drop on BSO phosani

### ISSUE THREAD

**Issue by Temudjinn** [oldschoolgg/oldschoolbot#3319]
Currently, if you own a slepey tablet or have used one, you can't get it as a drop from phosani in BSO.
since we can trade untradeables in BSO this can be a issue for CL hunters that go for all slots, me and a friend both had bought a slepey tablet to speed up phosani grind to get it. right now the only way of obtaining a new unique tablet is through umb's, which goes against the idea of the CL bosses. please make it so that we can still obtain slepey tablets even after having obtained or used 1.

**Comment by osrsjobbo** [comment]
Fixed by [#3976](https://github.com/oldschoolgg/oldschoolbot/pull/3976). Closing.
