### ISSUE TITLE
Trailblazer Graceful not giving boosts again

### ISSUE THREAD

**Issue by imTURBObruh** [oldschoolgg/oldschoolbot#3333]
## 🐛 Bug Report

hey so Benny fixed this the last time it happened but trailblazer graceful isn't counting as graceful anymore and it isn't giving the boosts where any other set would.

also it isn't on the cl for graceful

**Comment by 6enny6** [comment]
fixed by #3259

**Comment by TastyPumPum** [comment]
It shouldn't be on the CL for graceful  should it? As it's only obtainable by boxes. Correct me if I'm wrong, don't know bso that well

**Comment by imTURBObruh** [comment]
> fixed by #3259 

how come it doesn't register still?  has it not been pushed?

**Comment by imTURBObruh** [comment]
> It shouldn't be on the CL for graceful  should it? As it's only obtainable by boxes. Correct me if I'm wrong, don't know bso that well

Mr. e is only obtained by boxes. same for the holiday log

**Comment by TastyPumPum** [comment]
Hasn't been merged yet and then the bot will need to be rebooted once it has
Still disagree about it being on a log, seems stupid to really on boxes for cl completition imo, the mr. e is a custom pet so I feel like an exception

**Comment by imTURBObruh** [comment]
> Hasn't been merged yet and then the bot will need to be rebooted once it has
> Still disagree about it being on a log, seems stupid to really on boxes for cl completition imo, the mr. e is a custom pet so I feel like an exception

ok but there is literally a cl called graceful. and has all but trailblazer. most people get them from boxes anyhow bso.. most items come from boxes on bso
