### ISSUE TITLE
Wintertodt allows reductions for up to 5 warm gear instead of 4

### ISSUE THREAD

**Issue by anthonyburrow** [oldschoolgg/oldschoolbot#3334]
https://github.com/oldschoolgg/oldschoolbot/blob/974785d393ff7aff7b9dfad5834185c6ee82437b/src/commands/Minion/wt.ts#L51

Currently you are able to receive further damage reduction/ time boost for equipping 5 pieces of warm gear for Wintertodt trips. This is basically due to a misplaced break (see link).

Maximum damage reduction in OSRS is achieved when you have 4 pieces of warm gear, not 5.

**Comment by themrrobert** [comment]
Yea it should probably just be rewritten to >= 4
