### ISSUE TITLE
 Festive present bug

### ISSUE THREAD

**Issue by silli3333** [oldschoolgg/oldschoolbot#3342]
nvm

**Comment by mylife212** [comment]
was this the first festive present you bought? The price per present scales up every time you buy one, the #bso-christmas channel in Support has the prices pinned.

**Comment by silli3333** [comment]
I bought one before then bought 20 and only got 1

https://discord.com/channels/342983479501389826/732207379818479756/924746493083136050

![image](https://user-images.githubusercontent.com/96702809/147420963-99239cd6-5309-45d4-a80e-82b9687831bb.png)

**Comment by silli3333** [comment]
nvm im just stupid
