### ISSUE TITLE
Ring of endurance RC boost

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#3347]
Remove the boost to runecrafting for ring of endurance (uncharged)
Currently it checks if you have either charged or uncharged and applies a boost, this should only be for the charged version

see here: https://github.com/oldschoolgg/oldschoolbot/blob/master/src/commands/Minion/rc.ts#L85

**Comment by imTURBObruh** [comment]
@6enny6 
they both register as 1% though in the boosts after sending 

![SmartSelect_20211228-114248_Discord-Canary.jpg](https://user-images.githubusercontent.com/90441459/147592789-b1570ac7-ae67-47f9-9cec-171c1f8db669.jpg)
![SmartSelect_20211228-114314_Discord-Canary.jpg](https://user-images.githubusercontent.com/90441459/147592791-1abbbe3b-1f77-4be4-97a8-7bf2522d9f35.jpg)

**Comment by 6enny6** [comment]
fix hasnt been merged yet see #3351

**Comment by imTURBObruh** [comment]
> fix hasnt been merged yet see #3351 

I'm just saying I brought it up in the past and i forget to who... but they said they both got the same boost % for that reason
