### ISSUE TITLE
Blabberbeak / Mangobeak 

### ISSUE THREAD

**Issue by spellOGpingu** [oldschoolgg/oldschoolbot#3350]
## 🐛 Bug Report

Price match Blabberbeak and Mangobeak 
I.e blabber = 10m bank value, mangobeak = 1m bank value

**Comment by imTURBObruh** [comment]
> ## 🐛 Bug Report
> 
> Price match Blabberbeak and Mangobeak 
> I.e blabber = 10m bank value, mangobeak = 1m bank value 

blabberbeak is untradeable therefore mangobeak too.

**Comment by thievious1** [comment]
mangobeak is tradeable though

**Comment by gc** [comment]
Fixed in next update
