### ISSUE TITLE
Minnow Fishing

### ISSUE THREAD

**Issue by Osceolaosb** [oldschoolgg/oldschoolbot#3364]
Add Minnow fishing to OSB. It is quite difficult for ironman accounts to get a sufficient quantity of sharks. It would require hours upon hours of tempross just to get a few hundred sharks which isn’t even guaranteed.

**Comment by TastyPumPum** [comment]
I'm currently working on this in PR #3361 will hopefully have it finished soon.

**Comment by Osceolaosb** [comment]
> I'm currently working on this in PR #3361 will hopefully have it finished soon.

Ah sweet. Thank you!
