### ISSUE TITLE
[BSO] Can still get Festive paper post-Xmas event

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#3376]
## 🐛 Bug Report

Its intentional that you can make Festive presents etc. post event, however I *believe* getting passive wrapping paper is meant to be discontinued. This is a trip post-update 
![image](https://user-images.githubusercontent.com/63373565/147868734-fa47cf3e-7373-44c9-aaee-8b0aa271681a.png)

**Comment by gc** [comment]
Fixed, ty
