### ISSUE TITLE
TOB Vial of Blood drop uses incorrect item ID

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#3378]
The vial of bloods being dropped at TOB are the incorrect item ID and so currently untradeable, should be 22446

![5BA6FB14-284F-48F6-B38A-D14AC64BC4C9](https://user-images.githubusercontent.com/76587427/147874714-daa526b6-e315-4c1d-94e3-009363bea19e.jpeg)
![7847FADC-F266-429C-9AD4-6AFD7AC5D8FC](https://user-images.githubusercontent.com/76587427/147874717-0af136c7-3ec1-44ee-b6a5-6c1cdee6fd3a.jpeg)

**Comment by mylife212** [comment]
I assume the Vial of blood in Scythe createable will also ask for the wrong one (22405), so that'd need to be changed too.

**Comment by mylife212** [comment]
Bump :)

**Comment by mylife212** [comment]
Bump

**Comment by 6enny6** [comment]
bump

**Comment by 6enny6** [comment]
bump

**Comment by Lajnux** [comment]
easiest option for this issue is to just force the current incorrect item to just become tradeable 🐳

**Comment by gc** [comment]
Fixed in next update (fixed in bso already)
