### ISSUE TITLE
Ava's doesn't give full reduction to darts

### ISSUE THREAD

**Issue by anthonyburrow** [oldschoolgg/oldschoolbot#3387]
In ToB runs you use much more than the intended number of darts with Ava's assembler (~66 average instead of 22).

The end index of this loop referenced below decreases dynamically so there are fewer subtractions to darts done than there should be, i.e. you get a 40% reduction instead of the intended 80%.

https://github.com/oldschoolgg/oldschoolbot/blob/203252d978a6c66330ead1149ec642905d527bf1/src/extendables/User/Bank.ts#L243

**Comment by gc** [comment]
Fixed in next update
