### ISSUE TITLE
[BSO] Re-add =cl all, which shows all of your items

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#3400]
## 🚀 Feature Proposal

This was removed in the last update, and was a very cool feature because it let you filter items from your entire collection log, meaning you could do stuff like... `=cl all --missing` and it'd show you ALL the collection log slots you're missing. Having`Cl all `stay around can only benefit the users.

**Comment by osrsjobbo** [comment]
This is possible with `/cl name:Overall+ flag:Missing (Show only missing items.)`. Suggest closing this issue.
