### ISSUE TITLE
Add Dragon hunter crossbow(b) boost

### ISSUE THREAD

**Issue by DnnySie** [oldschoolgg/oldschoolbot#3405]
The title says it all basically

Currently the [Dragon Hunter Crossbow (b)](https://oldschool.runescape.wiki/w/Dragon_hunter_crossbow_(b)) [25918] Does not give the same boost the regular DHCB give at mally and such. 

Either add a `=revert Dragon hunter crossbow (b)` command to revert the crossbow back to the original dhcb, or allow the (b) version to give boost as well

**Comment by TastyPumPum** [comment]
Are you training range? I've tried some examples on my test bot and it seems to be working
