### ISSUE TITLE
[BSO] Thanksgiving 2021 Collection log counts for overall progress when it shouldnt

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#3408]
## 🐛 Bug Report

As with every other CL in the Discontinued tab, they do not count for overall log completion due to being well, discontinued items. The Thanksgiving2021 log *does* count for overall log, unlike other ones such as Hween 2021. Can see in the image that titles of both logs are different. 
![image](https://user-images.githubusercontent.com/63373565/149082987-1789d755-7411-40ac-8f1f-1edeabdfc2b0.png)

**Comment by gc** [comment]
Fixed
