### ISSUE TITLE
[BSO] 5 Stone spirits are not available at all in the bot, but still appear in CLs.

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#3409]
## 🐛 Bug Report

What the title says. These 5 spirits are: 
Copper stone spirit
Tin stone spirit
Coal stone spirit
Silver stone spirit
Mithril stone spirit

They appear in `cl pvm`, despite being unavailable. Essentially making it an impossible log slot to fill in. 

Can see in image below, nobody has received them. 
![image](https://user-images.githubusercontent.com/63373565/149083756-c3bffe04-6cad-45a7-ba42-ff228e4d60d8.png)

**Comment by imTURBObruh** [comment]
is anything happening with this one? still only 2 are available on the bot
