### ISSUE TITLE
Lowering Tears of Guthix Trip Time

### ISSUE THREAD

**Issue by HouseParan73** [oldschoolgg/oldschoolbot#3420]
## 🚀 Feature Proposal

The trip time currently for tears of guthix is 8 minutes long. This should be lowered to 3.5-4 minutes max. It doesn't take longer than 4 minutes to not only teleport to juna but to then teleport back to whatever you were doing prior to tog.

**Comment by Superwhammybar** [comment]
I would suggest changing the time to be dynamic based on the QP on the user, plus some standard travel time.
This will need a capped limit as BSO has up to 5k QP which would be 50 minutes inside ToG.

**Comment by LuxrayElite** [comment]
Travel time could be eliminated by Games necklace 👀 
I might look into making jewellery boxes a replacement for some tp's
