### ISSUE TITLE
+sw solo doesnt give return message

### ISSUE THREAD

**Issue by rburrou** [oldschoolgg/oldschoolbot#3428]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
+sw solo doesnt give a return message. you can check sw channel. It shouldnt be about configuration since it didnt return in the osb discord either.

https://gyazo.com/ea4fd4383a622359922f30ea58b48258 

see:
https://discord.com/channels/342983479501389826/815473694327308289/931792513222725682

**Comment by TastyPumPum** [comment]
Chances are the bot was down, if you look above your trips you can see others have been getting the return trip fine, your next trip should finish in around 20 minutes so I will check back then :)

**Comment by rburrou** [comment]
> Chances are the bot was down, if you look above your trips you can see others have been getting the return trip fine, your next trip should finish in around 20 minutes so I will check back then :)

(https://gyazo.com/aeefba9bd4c4b865d75700689ef189b9)
https://gyazo.com/f1d522f76023328cb1399809f15bc398

Not saying your not right, but whats the chance of this happening 4 times in a row?

**Comment by LuxrayElite** [comment]
I believe this to have been resolved. Feel free to reopen if encountering this bug again.

(Related to early stages of slash commands)
