### ISSUE TITLE
Hallowed Sepulchre collection log missing the 5 mysterious pages

### ISSUE THREAD

**Issue by osDreamscape** [oldschoolgg/oldschoolbot#3429]
![image](https://user-images.githubusercontent.com/73551894/149635945-1246f2e7-4549-471c-9657-ed1d5fbbeed5.png)
![image](https://user-images.githubusercontent.com/73551894/149635950-2af4717b-8425-45ca-a231-71dccc5481eb.png)
ingame log vs bot log

**Comment by gc** [comment]
Fixed in next update.
