### ISSUE TITLE
Duplicated farm run trip

### ISSUE THREAD

**Issue by Redquaker** [oldschoolgg/oldschoolbot#3440]
## 🐛 Bug Report

On OSB, there was a farm run trip that was duplicated, seemingly due to some delay on the bot which allowed for 2 trips to be sent at the same time. Both trips' worth of herbs (109 ranarrs total) were given, but the correct amount of only 8 seeds were used. See the attached pictures.

![farmtrip1](https://user-images.githubusercontent.com/59510368/149859751-302d5e7d-40c8-4073-8b2b-6e8651891efd.png)

![farmtrip2](https://user-images.githubusercontent.com/59510368/149859827-9176abf3-2e07-4429-8c1b-fdbdf1b4c675.png)

![farmtrip3](https://user-images.githubusercontent.com/59510368/149859770-4d8918c1-74a2-460d-b8e7-8866357d1235.png)

![farmtrip4](https://user-images.githubusercontent.com/59510368/149859772-0bb53124-68e8-4cbf-91d6-e4cfa2ca2e4e.png)

![farmtrip5](https://user-images.githubusercontent.com/59510368/149859777-21942577-13bb-4f95-9d80-be82a8948c79.png)

**Comment by themrrobert** [comment]
How do you know only 8 seeds were used? It's possible it only used 8, but slightly more likely that it used 16, and this information could be important.

**Comment by Redquaker** [comment]
Pictures attached for kwuarm seed count before and after with timestamps. Forgot to include this info in the original post.

![farmtrip6](https://user-images.githubusercontent.com/59510368/150159658-f5c0e9dd-facf-48db-8af4-2fc0c28bad4d.png)

![farmtrip7](https://user-images.githubusercontent.com/59510368/150159671-2049aa47-5222-4538-b626-ce1b6e8db47e.png)

**Comment by gc** [comment]
Feel free to report if it happens again.
