### ISSUE TITLE
Failed TOB Pings

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#3443]
## 🐛 Bug Report

TOB trips give a ping when they fail due to a member lacking the required kc for duos, but unsuccessful attempt to ping when a trip fails due to lack of people joining.

**Comment by LuxrayElite** [comment]
First is was a TOB error, 
Second is a party making issue that affects all masses (might have a different  method of storage)

but ill have a look

**Comment by LuxrayElite** [comment]
Discord seems to be having an error parsing the reject message as actual pings.

Usually we use msg.channel.send(` ${msg.author.id}`) or ${users} to ping you but this method isn't used in the party file as its a reference for group kills, raids, ba etc

hopefully someone with a bigger brain can fix it

**Comment by 6enny6** [comment]
bump for all the wasted hours

**Comment by LuxrayElite** [comment]
This is an issue related to how party handler works and potentially how discord is parsing the mention from my testing

**Comment by KyeDon** [comment]
This is quite infuriating, should be a priority to fix in my humble opinion!

**Comment by themrrobert** [comment]
Fixed
