### ISSUE TITLE
(BSO) Fishing Contest bait

### ISSUE THREAD

**Issue by Aelinz** [oldschoolgg/oldschoolbot#3446]
Today's fishing contest location is Trollweiss Ocean, the bait is snowy knights which are only obtainable from tmb's currently, adding =hunt snowy knight or something would be nice or have it buyable in the meantime

**Comment by TastyPumPum** [comment]
![Screenshot_20220119-091643_Discord](https://user-images.githubusercontent.com/79149170/150100558-a8932f77-5cf2-4403-a263-3582f19e04b7.jpg)
Did you even try and hunt snowy knight? You can you just have to purchase the butterfly jars

**Comment by Aelinz** [comment]
Looking back at my command earlier, I wrote swowy knight by accident and couldn't see it in the =hunt list, my b
