### ISSUE TITLE
Drift net + Support (expert) cape not counting graceful

### ISSUE THREAD

**Issue by Coollegolas** [oldschoolgg/oldschoolbot#3449]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

Support cape should be giving the effect of full graceful everywhere, drift net fishing doesn't have that check included yet.

Untested - Master Agility Cape (probably same issue but not tested)

**Comment by LuxrayElite** [comment]
Master agility cape was reported as a bug a while ago which I made a patch for.

Im primarily an OSB player and aren't aware of all the capes and specific perks from rs3 content.

Will be a quick thing to patch

**Comment by nwjgit** [comment]
This was fixed
