### ISSUE TITLE
=giveaway bug

### ISSUE THREAD

**Issue by rburrou** [oldschoolgg/oldschoolbot#3451]
## 🐛 Bug Report
was playing around with the giveaway function. i put up gmc's to see if it would work. it ate the gmc's and a few other items and never refunded them. just errored out. 

https://gyazo.com/351057fb3dd0846f87f5b8eb1ff79698

Also if the oneAtTime function is supposed to work via only letting you do one =giveaway at a time, its bugged and you can spam multiple of them every five seconds. 

should probably disable function until its fixed else people doing giveaways will just have the item eaten.

**Comment by SpaceDevz** [comment]
No one won, meaning the bot broke. Should return to giveaway hoster though.
