### ISSUE TITLE
BSO TOG

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#3453]
Tears of Guthix trips on BSO take 30 minutes, its only ~5 mins on OSB

**Comment by Superwhammybar** [comment]
ToG minigame works on number of QP a user has (as in the real game).
0.6 seconds (1 game tick) in the minigame per QP. BSO has 5k QP cap meaning 50 minutes in real time. This is instead capped at 30minutes, but it is why it can take 30 minutes on BSO but only 5 minute on OSB.
