### ISSUE TITLE
[BSO] DG shop quality of life 

### ISSUE THREAD

**Issue by vaskebj0rn** [oldschoolgg/oldschoolbot#3456]
i looked around but could find anythings about this anywhere sorry if its actually here. 

add how many items you want to buy instead of having to copy paste the msg 20+ times

example
=dg buy 10 Dungeoneering dye 
=dg buy 400 Offhand Chaotic crossbow

this could save alot of time that is really a waste with this small fix/add if its possible ofc :)

**Comment by TastyPumPum** [comment]
This has now been added.
