### ISSUE TITLE
fishing contest only checks if you have elite tiers not lower

### ISSUE THREAD

**Issue by rburrou** [oldschoolgg/oldschoolbot#3458]
## 🐛 Bug Report
https://gyazo.com/7704166331a2334d64ff6cde302fbae5
https://gyazo.com/49a45f362e9758dbd0b50dc3943aa5f1
https://gyazo.com/821756631d102a67c5b075c0ae298f97

Essentially, you only need to have desert elite done, not the other previous diaries to get the fishing contest boost. 

i used this as an example of a small thing that doesnt really matter but plum said it was worth reporting it even if its just a minor bug.

**Comment by rburrou** [comment]
https://gyazo.com/821756631d102a67c5b075c0ae298f97 
wrong screenshot this is me getting boost but not having easy diary claimed

**Comment by gc** [comment]
Sounds fine to me.
