### ISSUE TITLE
Broken minion

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#3467]
Reporting on behalf of `zecture#4266 / 189036791204937728`

Bso Bank is broken, `=rp checkbank --fix` does nothing, see below

any command returns "That item doesn't exist."

![image](https://user-images.githubusercontent.com/76587427/151218986-77158d2f-a769-42b2-b153-1c28ac3bc475.png)

![image](https://user-images.githubusercontent.com/76587427/151219040-d7f3efe3-625e-4e8d-8aa5-539af921174b.png)

![image](https://user-images.githubusercontent.com/76587427/151219081-6fa91008-26b5-4054-9a46-09a4eb11e954.png)

**Comment by 6enny6** [comment]
Update: its his whole minion not just bank

![15B5BC25-80B0-4473-8243-B5A5D4282CDC](https://user-images.githubusercontent.com/76587427/151223366-3ed0d0b1-2ea7-4cea-89ca-b297cac6b0c1.jpeg)
![1208A14A-21F7-43F6-A8A2-A1EAC449E46B](https://user-images.githubusercontent.com/76587427/151223371-bd68ee4a-fd6c-4817-a839-9b547ec09dbd.jpeg)
![E8D03FFA-5885-4EFE-A268-669FA5BB8323](https://user-images.githubusercontent.com/76587427/151223375-974bcc84-7ce9-4112-b607-4577b7dafa8c.jpeg)

**Comment by gc** [comment]
Its because you have a yellow graceful item (that was deleted, its a fake interface item and not the real one...) equipped, try to unequipall from the setup its in, then do the rp checkbank fix. that should fix it.
