### ISSUE TITLE
+xpgains command shows users as (Unknown)

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#3468]
## 🐛 Bug Report

Should show the full names, so can see where you are ranked. Kcgains is working as intended. This issue is present on both bots. 
![image](https://user-images.githubusercontent.com/63373565/151305816-74c856fd-6fb5-4c43-9944-4910d386ea3b.png)

**Comment by mylife212** [comment]
Nah it did show names a while ago, then at some point went to (unknown). Dont recall there being an update for it to be like how it is now. 
![image](https://user-images.githubusercontent.com/63373565/157318591-8b4a2b0e-c124-4dc1-be8b-858fca14ddd2.png)

**Comment by sunnyzulu** [comment]
Same goes for BSO, too. It's been like this every since runecrafting was SOTW on BSO. I would love to be able to see the names on this again.
