### ISSUE TITLE
BSO Bank value NaN

### ISSUE THREAD

**Issue by unicornakazulrah** [oldschoolgg/oldschoolbot#3479]
## 🐛 Bug Report

My bso bank is showing value of (NaN) and I’ve already tried =rp checkbank —fix. Nothing is being sorted by the actual value of the items. If I do a =b —food —sv for example, it shows everything right including the price tab but actual =b does not. 
![D9320329-C246-49BF-B47E-E63047913030](https://user-images.githubusercontent.com/71468925/151582301-ba6a0dca-0202-4156-ad0a-26679de48b4f.png)
![4F939249-DA92-4321-83D7-C1BC5F6A5AA0](https://user-images.githubusercontent.com/71468925/151582305-5b88ba44-452e-4aa3-82d5-e0df5cade271.png)

**Comment by unicornakazulrah** [comment]
Bank last worked on 1/26/22, the only activities I’ve done since then is fishingcontest, cooking trips, and farming trips.

**Comment by gc** [comment]
Fixed in next update.
