### ISSUE TITLE
easy clues unobtainable? (BSO)

### ISSUE THREAD

**Issue by GamesGotIssues** [oldschoolgg/oldschoolbot#3491]
## 🐛 Bug Report

I have pickpocketed male and female ham members with rogues outfit and wilvus for 3 trips of 1780 each and also other test trips of 50-100 pickpockets and have received 9 from the first one then none for thousands of pickpockets afterward. this is statistically impossible. am I shadowbanned from easy clues?

**Comment by AvariceBrah** [comment]
If this is on OSB then clues are not stackable. Meaning you can only have 1× Clue scroll (easy) at a time.

**Comment by GamesGotIssues** [comment]
> If this is on OSB then clues are not stackable. Meaning you can only have 1× Clue scroll (easy) at a time.

I am on bso, I may be on the wrong github mb

**Comment by AvariceBrah** [comment]
Add the BSO label to the issue if ya can :D

https://github.com/oldschoolgg/oldschoolbot/issues?q=is%3Aopen+is%3Aissue+label%3ABSO

**Comment by mylife212** [comment]
I believe this is due to Thieves armband not working at Ham members, preventing you from getting easy clues at all. Unfortunately doesn't give a headsup or anything when this is the case, best bet is to trade it to someone you trust. 

If Magna is reading this - Thieves armband @ Ham members should get updated to be like how it works at Vyres - Where having armband in bank just doesnt triple loot at all but lets you get every item. Currently, I believe that it just removes Easy clues from drop table @ Ham when you got it in bank.

**Comment by AvariceBrah** [comment]
> I believe this is due to Thieves armband not working at Ham members, preventing you from getting easy clues at all. Unfortunately doesn't give a headsup or anything when this is the case, best bet is to trade it to someone you trust.
> 
> If Magna is reading this - Thieves armband @ Ham members should get updated to be like how it works at Vyres - Where having armband in bank just doesnt triple loot at all but lets you get every item. Currently, I believe that it just removes Easy clues from drop table @ Ham when you got it in bank.

This would be the exact root cause. I forgot all about that. Nice memory.

**Comment by TastyPumPum** [comment]
> 
> I do not have thieves armband

I would double check as wilvus gives you the thieves armband, if you have done thousands of trips and the initial one was fine, i can only think of the armband

**Comment by AvariceBrah** [comment]
Before we began doing the clue lottery I had to toss 36 armbands after realizing I hadn't gotten Any clues in over 9 hours lol

**Comment by GamesGotIssues** [comment]
So sorry guys, you were right and I did have the armband! I'll give them to my friend before I go on my next run. I appreciate the help
