### ISSUE TITLE
TKS

### ISSUE THREAD

**Issue by TitanGH** [oldschoolgg/oldschoolbot#3493]
## 🐛 Bug Report

TKS Sell is not being calculated correctly. The post says it doubles per 1k but 1k costs 12 trillion Tokkul.
![CFCFEFF1-1D55-4B22-A379-9998CD1D15B1](https://user-images.githubusercontent.com/92953146/151855135-0e609da7-1448-4253-8140-68601726f39b.jpeg)

**Comment by LuxrayElite** [comment]
The jump between 100 uncut sapphire incorrect price (3200), to 200 uncut sapphire (117290)?

No karamja diary

**Comment by LuxrayElite** [comment]
Price change seems to occur increments of 30 for sapphire and doubles the price as intented it seems

**Comment by AvariceBrah** [comment]
> Price change seems to occur increments of 30 for sapphire and doubles the price as intented it seems

Could you link the exact file with the calculation please

**Comment by LuxrayElite** [comment]
I haven't looked at the source yet I'm on mobile ATM.

All gems double at 30
Ore doubles at 500 

From testing

**Comment by LuxrayElite** [comment]
I believe this might have been a poor communication/wording by magna to explain the new system

**Comment by TastyPumPum** [comment]
> ## 🐛 Bug Report
> TKS Sell is not being calculated correctly. The post says it doubles per 1k but 1k costs 12 trillion Tokkul. ![CFCFEFF1-1D55-4B22-A379-9998CD1D15B1](https://user-images.githubusercontent.com/92953146/151855135-0e609da7-1448-4253-8140-68601726f39b.jpeg)

The post said 1k as an example everything seems to match to the scales here https://github.com/oldschoolgg/oldschoolbot/blob/master/src/lib/data/buyables/tokkulBuyables.ts
