### ISSUE TITLE
Sac log not working

### ISSUE THREAD

**Issue by SpeadyM** [oldschoolgg/oldschoolbot#3504]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

entering =sl gives the error "an unexpected error occured :RSSad: "
Running =rp checkbank --fix results in "Removed 0 from favorites"
after which =sl kg still gives "an unexpected error occured :RSSad: "
Neither =sl kg, =sl kg --text, =sl kg --all work, all give the "an unexpected error occured :RSSad: "
This error first occurred for me on 1/28/2022 at 9:33 am eastern time. The previous time I used the =sl command was on 1/25/2022 1:22pm eastern and it worked normally.

**Comment by themrrobert** [comment]
Need more info.
1. Is this still happening?
2. Please provide a new instance with a fresh time please if it's still broken, thanks :)

**Comment by gc** [comment]
This would be fixed if you `=rp checkbank` again.
