### ISSUE TITLE
Remove Elemental runes from TKS sell options, as they sell for 0 anyways

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#3514]
## 🚀 Feature Proposal

Title. Players who are unaware that elemental runes sell for 0 tokkul in bot might see they sell for Tokkul on the Wiki, and buy them, only to get 0 tokkul back.

**Comment by themrrobert** [comment]
Wiki should be updated to show they sell for zero, which is the same as osrs after you sell just 1.

The way tks works is there's an object for each buyable, and it's the same object that controls it's sell price, too.

So the best option might be to not allow people to sell items for 0 tokkul, though it would technically still be there.
