### ISSUE TITLE
Slash commands fail in direct messages

### ISSUE THREAD

**Issue by Deerjump** [oldschoolgg/oldschoolbot#3518]
## 🐛 Bug Report

When attempting to use slash commands in direct messages, the bot fails to load options and when trying to send the command, the bot fails to respond.

![image](https://user-images.githubusercontent.com/28033570/152631328-7dab95a6-e2c6-4fc0-9af1-476605aba2a3.png)
![image](https://user-images.githubusercontent.com/28033570/152631412-05b0b544-9422-401f-9bd6-8e7df0035b18.png)

**Comment by Deerjump** [comment]
Assumed the github link would be separate for BSO, but it wasn't. Which is why I am posting this here.

**Comment by imTURBObruh** [comment]
> ## 🐛 Bug Report
> 
> When attempting to use slash commands in direct messages, the bot fails to load options and when trying to send the command, the bot fails to respond.
> 
> ![image](https://user-images.githubusercontent.com/28033570/152631328-7dab95a6-e2c6-4fc0-9af1-476605aba2a3.png)
> ![image](https://user-images.githubusercontent.com/28033570/152631412-05b0b544-9422-401f-9bd6-8e7df0035b18.png)
> 
> 

that usually means bot is offline

**Comment by Deerjump** [comment]
That is not true. I discovered the issue trying to use =m smelt and had to switch to slash commands. Every time I have tested it, it works in the OSB discord server, but not in DMS

**Comment by imTURBObruh** [comment]
oooh I'm so sorry I responded without realizing what you ment by direct messages lmaoo I feel so stupid. I figured it ment the direct message to you in chat, lol 

ya no clue on how the bot works in dm's sorry for my misinformation

**Comment by TastyPumPum** [comment]
This has now been fixed
