### ISSUE TITLE
=m smelting issue

### ISSUE THREAD

**Issue by MadocGambaBad** [oldschoolgg/oldschoolbot#3527]
## 🐛 Bug report

Using =m to repeat smelting trip instead of slash commands makes you do the =m command twice, first time nothing happens and minion is still idle.
![8EA8B164-3735-4F7C-82AB-4479A9356305](https://user-images.githubusercontent.com/80736340/152694350-165de386-6c5d-458c-92f1-f6eac4fb37a6.png)

**Comment by Madoc-Never-Lucky** [comment]
Additionally the =m command no longer tells the user if they don’t have the required materials to repeat a smelting trip, it just says minions not doing anything.

**Comment by imTURBObruh** [comment]
why are you using =m anyhow its / now and use the letter to repeat.

**Comment by LuxrayElite** [comment]
Most likely resolved now all commands are slash and heavily tested
