### ISSUE TITLE
Solo Tob

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#3555]
Most people doing tob are doing hard mode, which means there is not many people running normal tob, even in the main oldschool.gg server

as hard mode has a regular tob kc requirement, and is only massable, it seems unfair to people using the bot who arent in the main server or in a clan

proposed changes:
- let tob be soloable after 50? kc
- remove kc requirement for tob duos

**Comment by mylife212** [comment]
could also add ffa tob as a "solo" option, where your minion joins a team of fake minions (IE zalcano) and does a Tob with them. Since its full of randoms and less experienced players, there could be a hefty time/death chance penalty to encourage team tob with real players.

**Comment by Paah** [comment]
We are not there yet (at least for hard mode) but yes definitely in 1-2 months a system is required to let people solo tob, as every day there are more people finishing tob than new people starting, and the player counts are shrinking. We already have similar system for Barbarian Assault where you get 10% speed penalty for doing it with NPC and something like that would seem about right.

**Comment by TizHub** [comment]
Bump - Tob is dead especially with Nex release, definitely needs some sort of solo mode with penalty

**Comment by kwek20** [comment]
Bump - only me and a clannmate play, we can't duo untill 150kc. Almost impossible to get :/
