### ISSUE TITLE
Reduce Duo ToB KC to 250 or 200

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#3561]
## 🚀 Feature Proposal

Now that ToB has been out for a while, getting a team together for 'newcomers' can be difficult due to so many people doing duos or Hard mode tob since they already have the KC. Reducing the kc req for duos is reasonable because instead of having to scrap together a trio of other players who missed the boat, you can just duo at an earlier kc and go from there.

**Comment by mylife212** [comment]
Bump. I think a 225kc req, would be more fitting because it'd have a little progression path of 225kc unlocking duos > 250kc unlocking Hard mode.

**Comment by gc** [comment]
Lowered from 300 to 150. I made it lower than your suggestion because I think we should make it lower than realistic as ingame based on their being less players and it being harder to find teams.
