### ISSUE TITLE
Elite Clue Reward Table

### ISSUE THREAD

**Issue by MiracleOS** [oldschoolgg/oldschoolbot#357]
A 3rd age axe was received from an elite clue when they are only obtainable from master clues.

![](https://i.gyazo.com/bdd826898751a8c35aa6c1e4cddd6160.png)

Not sure if this is the same case for the 3rd age pickaxe, might be worth looking into.

**Comment by Alexsuperfly** [comment]
the casket had a mimic in it which dropped the axe
