### ISSUE TITLE
add Revert Holy Sanguinesti Staff

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#3598]
## 🚀 Feature Proposal

![Screenshot_20220218-221200_Discord-Beta.png](https://user-images.githubusercontent.com/90441459/154785649-968ee8aa-7cf0-4894-b568-84d014504d61.png)

we can do almost everything except revert the holy sanguinesti staff into holy sanguinesti staff uncharged

**Comment by imTURBObruh** [comment]
all the options to create and revert involve (uncharged), but the one option not available is to revert holy sanguinesti staff into holy sanguinesti (uncharged).

**Comment by imTURBObruh** [comment]
bump
