### ISSUE TITLE
add Revert granite maul (or) & granite maul (or) (ornate handle)

### ISSUE THREAD

**Issue by imTURBObruh** [oldschoolgg/oldschoolbot#3599]
## 🚀 Feature Proposal

we can create them. but cannot revert them.

(or are they not revertable in game)

**Comment by LuxrayElite** [comment]
both are revertable in osrs 

however, the granite clamp and ornate handle are destroyed on reversion 

it might be an order issue, like how you can only create (or)(handle) a specific way 

it might not be easy to distinguish which item to return clearly

**Comment by imTURBObruh** [comment]
ahh
