### ISSUE TITLE
Don't see all available buyables in /lms buy

### ISSUE THREAD

**Issue by imTURBObruh** [oldschoolgg/oldschoolbot#3601]
## 🐛 Bug Report

https://user-images.githubusercontent.com/90441459/154793453-bb870272-98f0-4e14-a27c-da1d2cb058a5.mp4

as you see in video above, the list stops at ring of wealth scroll.

until I accidently typed something and saw items appear that were not there I had no clue this was a issue.

**Comment by LuxrayElite** [comment]
It's a limitation of slash command capabilities only being able to show a max of 25 options.

Which is then trimmed to search for whatever you typed

**Comment by imTURBObruh** [comment]
> It's a limitation of slash command capabilities only being able to show a max of 25 options.
> 
> Which is then trimmed to search for whatever you typed

oh that's so damn lame discord has issues! so will wiki have the complete list or how will this work?
