### ISSUE TITLE
LMS buy issue - Special Attacks not in bank

### ISSUE THREAD

**Issue by imTURBObruh** [oldschoolgg/oldschoolbot#3602]
## 🐛 Bug Report

I purchased 2 of the Golden special attacks and neither are in my bank but my points are spent.
![SmartSelect_20220219-064634_Parallel Space Pro 64Bit Support.jpg](https://user-images.githubusercontent.com/90441459/154804364-cddb3462-52b6-4905-92b8-1daa4230ad21.jpg)![SmartSelect_20220219-064643_Parallel Space Pro 64Bit Support.jpg](https://user-images.githubusercontent.com/90441459/154804366-d6693461-3d16-4935-a75e-8c74a2b4c2af.jpg)![SmartSelect_20220219-065555_Niagara Launcher.jpg](https://user-images.githubusercontent.com/90441459/154804369-1a18efbf-2af2-4e85-a13a-7076e8bfa9fc.jpg)![SmartSelect_20220219-081818_Niagara Launcher.jpg](https://user-images.githubusercontent.com/90441459/154804623-5604afcb-03f4-44ba-bed5-db9d837e7b98.jpg)

**Comment by LuxrayElite** [comment]
These are CL only items, there isn't a physical item in osrs its a toggle feature

also partially reported in #3568

**Comment by imTURBObruh** [comment]
> These are CL only items, there isn't a physical item in osrs its a toggle feature
> 
> also partially reported in #3568 

well I'll be. maybe on bso tho they should become the physical item? do to they do exist on bso. so would only make sense.

![SmartSelect_20220219-162124_GitHub.jpg](https://user-images.githubusercontent.com/90441459/154820997-a30abc9d-17e6-4f20-a313-919326a699b2.jpg)
