### ISSUE TITLE
Make LMS "starting simulation" public

### ISSUE THREAD

**Issue by imTURBObruh** [oldschoolgg/oldschoolbot#3606]
## 🚀 Feature Proposal

![SmartSelect_20220220-015702_Discord-Beta.jpg](https://user-images.githubusercontent.com/90441459/154833777-aaa8865f-eabc-4cd0-bdbb-e91ebc186c44.jpg)

so currently when anyone starts LMS simulation, nobody knows who started it, because it privately tells you and gives you dismiss option saying only I can see the message.

please make it so it posts ex: `Turbo used lms`
Starting Simulation 

for everyone to see like the other / commands. that way when the command used is tapped on, it displays the whole command used.
![SmartSelect_20220220-020052_Discord-Beta.jpg](https://user-images.githubusercontent.com/90441459/154833870-69848cb7-83be-4e7e-aafe-114b1dd5c0fc.jpg)![SmartSelect_20220220-020102_Discord-Beta.jpg](https://user-images.githubusercontent.com/90441459/154833872-c5d9f0fd-d885-4e7b-a28d-5c96b981d700.jpg)

**Comment by gc** [comment]
Fixed in next update.
