### ISSUE TITLE
Add =create Abyssal Tentacle (OR)

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#3607]
## 🚀 Feature Proposal

![SmartSelect_20220220-035346_Discord-Beta.jpg](https://user-images.githubusercontent.com/90441459/154837300-8b727bc9-9c1f-4341-bd0c-aa2cc653c5c9.jpg)
[Abyssal Tentacle(OR) Wiki](https://oldschool.runescape.wiki/w/Abyssal_tentacle_(or))

**Comment by imTURBObruh** [comment]
> 
> The abyssal tentacle (or) is an abyssal tentacle with a shattered relics variety ornament kit added onto it. The kit gives no additional bonuses, and is only used to add aesthetics to the 
> 
> Basically no use, unless you want it for looks?

it does look awesome so kinda for looks, does volcanic or frozen whip have extra bonuses?
