### ISSUE TITLE
Lower/remove the gear stats required to hunt black salamanders

### ISSUE THREAD

**Issue by aekramer** [oldschoolgg/oldschoolbot#3613]
## 🚀 Feature Proposal

The required gear bonuses for hunting black salamanders (and black chins) is insanely high.
They are trash anyway and only reason people go there is for XP, so in my whole life I have never brought anything except a teleport with me incase I was done. Dropping all the sallys while training.

I can SOMEWHAT see the reason for black chins, but even then it seems like a ridiculously high requirement, what kind of gear would even provide you these kind of stats? Karils top + legs barely cut it and there is no way I would risk those for something as silly as black sallys.

Tbh, this should be changed to let you go in without gear but provide (much) higher losses and of course a very low chance to escape a pker.

EDIT: In my whole OSRS carreer I have only ever encountered 1 person attempting to PK me at black sallys, who failed (and I did not have food or any gear) while training to 80/83 on 3 of my accounts

**Comment by LuxrayElite** [comment]
The minimum required gear is black dhide body and chaps

**Comment by aekramer** [comment]
> The minimum required gear is black dhide body and chaps

Not what I was asking.

But even if you don't feel like changing black chins, black sallys is really an exaggeration, make it so you dont obtain any loot then if in no gear and its just for the xp. Its the reason people go there in OSRS.

**Comment by LuxrayElite** [comment]
I'm trying to understand the high requirements, gear only requires a black dhide body and chaps equipped

I understand the request about going in naked and upping the death chance

Perhaps an option to no use brews/restores (with or without gear) as well

**Comment by aekramer** [comment]
> I'm trying to understand the high requirements, gear only requires a black dhide body and chaps equipped
> 
> I understand the request about going in naked and upping the death chance
> 
> Perhaps an option to no use brews/restores (with or without gear) as well

I did not know you also needed brews/restores, did not get that far.

Basically I really am just starting out, did hunter up to 74 (to catch ninjas, wanted to continue to 83 for dragons, but not if that requires me doing red sallys)

Got full graceful, and now looking into sepulchre, getting hunter up early seemed like a good idea with the potential loot from the high level implings. At this stage I don't have access (or the stats) for black dhide, let alone brews/restores. However I would be able to just camp black sallys to train my hunter up

**Comment by Lajnux** [comment]
Black d'hide body/chaps is obtainable pretty easy even on ironmen, yes brews/restores are harder. However the chances to die, lose brews/restores are much lower on black sallys than black chins, adding in a feature to go there naked and higher chance of die is bunch of excess code along with that I then should lower the xp/hour a lot from constant being pked more and die more.
