### ISSUE TITLE
Create Great Blue Heron with Spirit Flakes from Tempoross

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#3626]
## 🚀 Feature Proposal

I figured it would be a nice addition to the use of spirit flakes, we already got the option to create spirit angler using them, why not top it off by adding the recolored version of the fishing heron pet.

![SmartSelect_20220225-014307_Video Player.jpg](https://user-images.githubusercontent.com/90441459/155675896-b5ca44db-3d44-4c7f-8703-a73bb7bf9451.jpg)

**Comment by 6enny6** [comment]
added in #3214

ill look at the conflicts after work tonight

**Comment by 6enny6** [comment]
misclicked close
