### ISSUE TITLE
Lost shiny tame when merging

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#3639]
Robson lost his shiny tame when merging two, correct me if im wrong but isnt shiny one of the attributes it ‘keeps’ when merging? 

if not, kinda annoying that if you get a shiny its locked to the stats it currently has

See photo below

![2685A68B-A392-44BC-880F-9BC62F184E61](https://user-images.githubusercontent.com/76587427/156044764-3a472612-1b39-4976-b348-56067f677289.jpeg)

**Comment by imTURBObruh** [comment]
he merged the non shiny into the shiny.

therefore destroying the shiny.

**Comment by imTURBObruh** [comment]
he merged the non shiny into the shiny.

therefore destroying the shiny.

what he should have done, was to have the shiny be the selected tame, and merged into 579
