### ISSUE TITLE
Make Warriors guild aware of defenders equipped

### ISSUE THREAD

**Issue by aekramer** [oldschoolgg/oldschoolbot#3646]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/15050467/156572414-4468e2b9-ee6f-47cf-b644-27666cf2a9bf.png)

After equipping my iron defender in the melee slot before returning to cyclopses (and going on a huge dry streak) I eventually got another defender.. and it was iron again

**Comment by TastyPumPum** [comment]
It currently checks your bank before giving you the next one, so currently don't equip your highest one, otherwise the same will happen again
