### ISSUE TITLE
+mypets breaks once you have 40+ pets

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#365]
+mypets gives me the "an unexpected error has occurred" message whenever I use it ever since I got 40 pets. It may be related to message limit but not too sure.

**Comment by BrandonEnglish848** [comment]
The quick bandaid would be to take the substring of the output and reduce it to fit within the 2000 character block.

**Comment by Alexsuperfly** [comment]
fixed in #446
