### ISSUE TITLE
Voidling

### ISSUE THREAD

**Issue by DarkBugz** [oldschoolgg/oldschoolbot#3651]
Voidling will occasionally return saying it alched 1x of something I didnt own any of. For example on my last trip after 30+ minutes it says alched 1x rune battleaxe but I had just checked my bank for rune items and had no battleaxe. I also did not receive any on the trip. fwiw I have magic master cape too

**Comment by themrrobert** [comment]
Only way this happens is if you obtained the rune battleaxe without knowing.

Maybe from a mystery box, or a clue, or loot. I know you said it wasn't in your loot, but it came from somewhere.

If you still there's an issue, and you can reproduce it with screenshots, then please do. 

1. Check your bank for rune items `=bs "rune " --id` or `=bs "rune " --text`
2. Run your command
3. Show the result.

Make sure you don't do anything that you don't provide the history of in your screenshots.

Thanks :)
