### ISSUE TITLE
=t kc — to show kc log for tame 

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#3653]
## 🚀 Feature Proposal

we got `=m kc` to show our kc log..

let's add `=t kc` for the tame kc log.. ik me when countless others would love to know how many times our tame has killer whatever. 

also for the tame cl, be nice to have kc there too.

**Comment by imTURBObruh** [comment]
Holy fuck it was giving me error... I go back and now I fucked up with spam... sorry
