### ISSUE TITLE
Barb fishing bug

### ISSUE THREAD

**Issue by Arodab** [oldschoolgg/oldschoolbot#3654]
I noticed this while barb fishing, so I don't know if it's affecting all fish, but the 8% extra fish seem to be giving extra xp as well, and that's not how it works in osrs.

**Comment by Superwhammybar** [comment]
Have you got any screenshots of this? The code looks like it's handling it correctly.

**Comment by Arodab** [comment]
> Have you got any screenshots of this? The code looks like it's handling it correctly.

https://imgur.com/a/JOsbiLB

Ok so I took a better look and seems it was just a coincidence that xp rates were roughly 8% higher than they should be on these trips, I didn't notice some trips were like 27-28min instead of 30. 
I remembered barb fishing in the bot used to be 75k xp/hr, but I guess I was lower fishing lvl last time I did it, without the blessing. Still, the scaling seems way off. You'd never get 90k xp/hr on osrs even with a 5% boost from the pearl barbarian rod.

According to wiki, at 99 fishing, even fishing if spots never moved and you didn't lose ticks dropping fish, you should get
(0.3494*80 + 0.2827*70 + 0.2539*50)*1.025*1200 = 74336 xp/hr (or 78k/hr with a 5% boost). More realistically, you get 60-65k xp/hr depending on how afk you are, and how quickly you drop your fish.

Are there any plans to ever fix osb xp rates? A lot of them are way off, even considering that bot is dumb and can't tick manipulate (not as much as barb tho), and rates across different skills are very inconsistent imo. As a high lvl skiller, I could help with both ehp and non tick manipulation rates, because I afk everything in game.
