### ISSUE TITLE
Small missing item in filterables

### ISSUE THREAD

**Issue by BrandonEnglish848** [oldschoolgg/oldschoolbot#366]
Please add ‘Onyx bolt tip’ to fletching in filterables.ts

**Comment by BrandonEnglish848** [comment]
Please also add these to the filterables:
Fletching:
'Bronze bolts',
'Iron bolts',
'Steel bolts',
'Mithril bolts',
'Adamant bolts',
'Runite bolts',
'Dragon bolts',
'Opal',
'Jade',
'Pearl',
'Red topaz',
'Sapphire',
'Emerald',
'Ruby',
'Dragonstone',
'Onyx'

Food:
'Tuna potato',
'Chilli potato',
'Mushroom potato',
'Wine'

**Comment by Lajnux** [comment]
#513 Closes this issue along with the previous food list update except Chili potato?
