### ISSUE TITLE
Grandmaster capes

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#3671]
Add grandmaster skillcapes if you get 5b xp in a skill - functions same as master capes, just cosmetically different?

**Comment by Lilbourne** [comment]
This sounds neat. Maybe even just like, a golden glow around it?

**Comment by 666TURBO** [comment]
> Add grandmaster skillcapes if you get 5b xp in a skill - functions same as master capes, just cosmetically different?

or how about a pair of golden nerd glasses 🤓

**Comment by 666TURBO** [comment]
lol

**Comment by gc** [comment]
BSO Suggestions now need to go in the #bso-vote channel so it can be voted on.
