### ISSUE TITLE
Gorajan bonecrusher

### ISSUE THREAD

**Issue by DarkBugz** [oldschoolgg/oldschoolbot#3676]
Please add a toggle feature to this item so I can get superior bones for heat res pots

**Comment by 666TURBO** [comment]
I agree, there is a toggle option in the actual game, what happened to adding that? lol
![Screenshot_20220319-041006_Samsung Internet.jpg](https://user-images.githubusercontent.com/90441459/159115109-8d29c439-eb94-43b3-ad3b-9f6a3c5e2afb.jpg)

**Comment by 666TURBO** [comment]
> Please add a toggle feature to this item so I can get superior bones for heat res pots

but on the until this happens if at all side of the subject... send it to someone to hold while you grind your bones.
