### ISSUE TITLE
Lizardman Shaman crossbow bug

### ISSUE THREAD

**Issue by Alex-The-Great-Cyber** [oldschoolgg/oldschoolbot#370]
https://i.imgur.com/9FtLfgF.png

**Comment by MrFluffums** [comment]
Very little information was posted above, but to clarify from my experience:

A few hours ago (~2 AM US Central) Lizardman Shaman could be attempted with:
- [Karil's crossbow] 
OR 
- [Rune crossbow] 
OR 
- [Armadyl crossbow]

It appears that Lizardman Shaman now requires: 
- [Karil's crossbow] AND [Rune crossbow] AND [Armadyl crossbow]

**Comment by Alex-The-Great-Cyber** [comment]
That would be an issue seeing how you couldnt equip both.


Sent from Yahoo Mail for iPhone


On Sunday, July 12, 2020, 4:44 AM, MrFluffums <notifications@github.com> wrote:




Very little information was posted above, but to clarify from my experience:

A few hours ago (~2 AM US Central) Lizardman Shaman could be attempted with:
   
   - [Karil's crossbow]   
OR
   - [Rune crossbow]   
OR
   - [Armadyl crossbow]

It appears that Lizardman Shaman now requires:
   
   - [Karil's crossbow] AND [Rune crossbow] AND [Armadyl crossbow]

**Comment by gc** [comment]
Should be fixed now.
