### ISSUE TITLE
selling castle wars items

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#3733]
to buy castle wars rewards you use `+buy`, but to sell back to the shop its `/create name:revert zamorak halo`.

is it possible to move this from +create/revert to +sell?

i think create/revert shouldnt be used if its supposed to be traded with an ingame NPC

**Comment by nwjgit** [comment]
dupe https://github.com/oldschoolgg/oldschoolbot/issues/4838
