### ISSUE TITLE
Open/kill until you get a specific item

### ISSUE THREAD

**Issue by Arodab** [oldschoolgg/oldschoolbot#3741]
Is it possible to add an option to the /open and /k commands to stop opening/killing something when you get a specific item? Would be a really nice qol for opening caskets without wasting master clues, and killing low lvl monster for low tier clues.

**Comment by BigLazyturtle** [comment]
For kill trips this could be too easily abused with +m cancel.

If this gets put in make sure to not allow canceling trips with it.

Otherwise this would be nice, especially for caskets on osb.

**Comment by gc** [comment]
This is implemented now for /open, but its not possible for /k.
