### ISSUE TITLE
Increase random event timer

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#3766]
Not sure what its currently at on the bot, but on osrs randoms follow you for a full 1 minute before disappearing, seems to be a lot less time on here

**Comment by Superwhammybar** [comment]
The bot currently has it at 30 seconds, do you have documentation on the 1 minute despawn? I can't see it on the wiki. Might be being blind.

**Comment by 6enny6** [comment]
end of first paragraph @Superwhammybar 

https://oldschool.runescape.wiki/w/Random_events

**Comment by Superwhammybar** [comment]
Can't believe how blind I am.
