### ISSUE TITLE
Repeat trip random event conflict

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#3782]
## 🐛 Bug Report

Random event and repeat trip using the same letter

Whilst this can be avoided by disabling random events. And it is a rare occurrence due to the random nature. Probably won't exist post mahoji-migration

It would be best for it to be resolved similar to +m causing repeat trips when the repeat letter was m

![Screenshot_20220412_174601.jpg](https://user-images.githubusercontent.com/12814878/163144531-9254f729-2d2a-44ec-bd0c-0c9246049ef4.jpg)

**Comment by 6enny6** [comment]
could make it so random event answers are buttons as a fix
