### ISSUE TITLE
Sell Price Bug BSO

### ISSUE THREAD

**Issue by VenyaVeritas73** [oldschoolgg/oldschoolbot#3783]
## 🐛 Bug Report

Not sure what kind of bug this is, but it's in the live bot. For sell price it just says [object object], not sure if that's a known bug or not.

![Screenshot_20220413-100805_Discord](https://user-images.githubusercontent.com/98783697/163212270-6942f48e-3cec-4eee-81e4-c022ebc4fd37.jpg)

**Comment by POKEBLOX6** [comment]
Looks like we just need to update the commands/bso/price.ts

From 
`sellPriceOfItem(this.client, item)`
to
`sellPriceOfItem(this.client, item).price`

as the sellPriceOfItem return a JSON object with the two values of price and basePrice

**Comment by POKEBLOX6** [comment]
If someone wants to make a PR now go ahead otherwise I'm going to wait until I get home to make the PR and test

**Comment by gc** [comment]
Fixed
