### ISSUE TITLE
Missing offerables

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#3789]
If you do `+offer x`, or any other mis-spelling of an offerable, it returns the below image which only lists bones for prayer xp. Can the bird eggs and long/curved bone also be added to this list. 

![image](https://user-images.githubusercontent.com/76587427/163434714-3b15bc50-a411-4855-ae62-eefcec1005af.png)

**Comment by gc** [comment]
No longer exists
