### ISSUE TITLE
Approved Mass Pingers Role

### ISSUE THREAD

**Issue by eX-C0n** [oldschoolgg/oldschoolbot#381]
## 🚀 Feature Proposal

I strongly disagree with giving all t3+ patrons the ability to ping @mass. There are many trolls that would abuse it and get the ability revoked. However, we could create a new role, Trusted Pingers, which could be given to select few, active, trusted members within the server; especially those within the massing community. We could then add the role to the pingmass.ts file.

Benefits: trusted members won't spam the @mass mention, and it will offload 90% of the duty of Moderators to ping @mass every 40 minutes, all day, every day.

Downfalls: N/A? :kekw:

**Comment by eX-C0n** [comment]
would also need added to the constants file.. I'll PR it all if i get a role ID for the new role

**Comment by wildchickenz** [comment]
Often Mods are not readily available for pinging. However, if you were to allow a handful of trusted host to +pm this would speed up the time between masses and create less work/annoyance for the Mods if they get a ping at a difficult time for them respond.

**Comment by osrsolympus** [comment]
Easy fix, which I suggested a while back, create an expanded mod/admin team to handle demand without giving random people with money large-scale pinging abilities.

**Comment by eX-C0n** [comment]
@osrsolympus 
> without giving random people with money large-scale pinging abilities

you mustn't have read my feature request then. I specifically said NOT to give patrons @ mass capability. But rather, active, trusted members.

**Comment by osrsolympus** [comment]
It’s not that, and Magna can, ofc, do whatever he wants that’s why these are suggestions and not demands. My point about the money was that the “trusted” folks running masses tend to be patrons because of the fact that they get the extended trip times, so on the odds they’d seem to be the favorites for receiving such a role.

And if Magna doesn’t want to add any such role or expand the admin team, then so be it, it’s his server.

**Comment by eX-C0n** [comment]
@osrsolympus you're the only one saying itd only be patrons. But, you can't even possibly deny that patrons are obviously going to be more trustable than a non-patron. We take our own hard earned money and spend it on Magnaboy, his work, and his contributers work. If that doesn't show to some effect some loyalty, than idk what does.
Regardless, there are a few non-patrons that I'd suggest being able to ping mass, because from what I've gathered, they're trustworthy. There's also some people that don't even do masses that I could recommend to have the ability to ping, just based solely on their activity level within the server.

**Comment by eX-C0n** [comment]
Even in the theoretical space of "odds they’d seem to be the favorites for receiving such a role". If they are the ones hosting the masses, wouldn't it make sense?

**Comment by Alexsuperfly** [comment]
this has been done in the discord, mods can give the `Mass Hoster` role to people in the discord which grants them permissions to run the `+pingmass` command
