### ISSUE TITLE
hey i suggest that u unban me from the discord i was banned like 6 months ago i am a better person Joe The Jazz Man#0078

### ISSUE THREAD

**Issue by PoggersChampers** [oldschoolgg/oldschoolbot#3815]
## 🚀 Feature Proposal

Describe the feature you're suggesting here, give lots of information and describe it as best you can. Please check that the feature hasn't already been suggested first, by searching the issues in this repository.

**Comment by mylife212** [comment]
No.

**Comment by PoggersChampers** [comment]
sus amogus sus sus su s s us
