### ISSUE TITLE
Nex Components from Broken Nex pieces (BSO)

### ISSUE THREAD

**Issue by ATr-ee** [oldschoolgg/oldschoolbot#3817]
Since Chambers of Xeric is partially locked behind the Magic Damage % from Virtus, broken Nex armours could be allowed to revert into their respective components. This would add another sink for Nex items, and would allow players who either don't wish to trade or are ironmen be able to complete Nex armour without being next to absolutely blocked by other "endgame" content.

Only thing to be weary of with this change would be the prices of ancestral pieces since they would be much less sought after. However, afaik, you would still need anc for places that get an anc boost such as zulrah and thermy.

**Comment by gc** [comment]
As a BSO content idea, this should be polled in #bso-vote.
