### ISSUE TITLE
Please fix the +Ash command 

### ISSUE THREAD

**Issue by Dephire** [oldschoolgg/oldschoolbot#3819]
## 🚀 Feature Proposal

The OSRS server I'm in has been using the oldschoolbot for awhile now but the most important command (as you could understand), the mod Ash command "+Ash" has not been working for months now, however the other commands work which is what made me think it was this command in particular that wasn't working. I'm not sure if you were aware of this problem but it would be very much appreciated if this command could be fixed unless there is some way I could do it myself. Thank you!

**Comment by gc** [comment]
The command was removed because we have a limit of only 100 slash commands, and so we can't keep +ash.

**Comment by Dephire** [comment]
Thank you for replying. That's unfortunate :(
