### ISSUE TITLE
/k not enough qp bug

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#3829]
## 🐛 Bug Report

When you don't have enough quest points it suggests to use +quest not /quest

Might be present in other places where you don't have the correct qp

![Screenshot_20220426_083420.jpg](https://user-images.githubusercontent.com/12814878/165246784-d4ae36ca-bab8-4c08-8b8f-b74761b66a91.jpg)

**Comment by Copper-Eye** [comment]
I have fixed to return the correct slash command message in this [pull request](https://github.com/oldschoolgg/oldschoolbot/pull/3830#issue-1215760262). I could not find any other instances but will keep an eye out as more commands are changed to slash.
