### ISSUE TITLE
Raids / tob

### ISSUE THREAD

**Issue by nidyha4437** [oldschoolgg/oldschoolbot#384]
Add CoX, ToB, Nightmare & the other bosses missed

**Comment by Lajnux** [comment]
#429 takes care of ''other bosses missed''. CoX just needs the skill releases and then a more dynamic and fun approach of rework instead of #506 .

**Comment by Lajnux** [comment]
Not a issue that needs to be open on github. Most fixed except ToB. Which is planned coming.
