### ISSUE TITLE
Elder Runecrafting

### ISSUE THREAD

**Issue by ColossalSeagull** [oldschoolgg/oldschoolbot#3842]
When you send an elder rune runecrafting trip it states that you spend 244 essence, and will get 488 elder runes because of a multiplier. However when the run returns you only get 162 runes since it uses 3x essence per rune. Update message at start for elder runes to say correct amount to be runecrafted.

![image](https://user-images.githubusercontent.com/96855950/165979798-12c4231a-c191-4502-b671-fc160a12b743.png)

**Comment by LuxrayElite** [comment]
Seems to be resolved at some point. Feel free to re-open if it is encountered again
