### ISSUE TITLE
=fav giving error

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#3861]
## 🐛 Bug Report

![SmartSelect_20220503-085708_Discord-Beta.jpg](https://user-images.githubusercontent.com/90441459/166466967-772437c0-b272-45f2-9fdb-be2f1c1d4136.jpg)

**Comment by TastyPumPum** [comment]
Works fine for me, id do the "rp checkbank --fix" see if that clears it

**Comment by TURB042O** [comment]
> Works fine for me, id do the "rp checkbank --fix" see if that clears it

it was my list was to long and because it doesn't generate a img now, it gave error. @themrrobert helped me find out the ID's and I spent some time clearing it up lol.
