### ISSUE TITLE
Ability to sell grown Cats for Death runes.

### ISSUE THREAD

**Issue by badgehunter** [oldschoolgg/oldschoolbot#3881]
## 🚀 Feature Proposal

Ability to sell grown cats for Death runes, this would give reason to grow cats other than cl in bso and would actually give reason to buy kittens and grow them in osb. Since you can buy and grow kittens into cats on both but currently it only actually purpose on Bso for cl. The amount of runes would be doubled via easy Ardy diary.

**Comment by TastyPumPum** [comment]
I thought you can sell them for death runes? Have you tried to sell your cat?

**Comment by LuxrayElite** [comment]
note: selling of cats is done by sacrifice

**Comment by badgehunter** [comment]
ah thank you. what an obscure way to do that. i guess this can be closed.
