### ISSUE TITLE
The ability to customize which pet is worn per combat style.

### ISSUE THREAD

**Issue by JWGerbenGB** [oldschoolgg/oldschoolbot#389]
I want to customize the pets I have equipped per style.
This would be done by making pets equippable per style instead of when you equip a pet it goes into all styles.
The downside is that it would take multiple pets of the same kind to ensure multiple equips.

**Comment by Lajnux** [comment]
You can only have one pet following you at a time in OSRS, gear swapping dosen't change that. And this would now when BSO pets enhance stuff be a very weird interaction of double stacking boosts.
