### ISSUE TITLE
Add favorite command buttons to +m

### ISSUE THREAD

**Issue by Redquaker** [oldschoolgg/oldschoolbot#3916]
## 🚀 Feature Proposal

Since slash commands tend to be slow to use due to lag from discord, it would be nice to add "favorite command" buttons to `+m` in addition to the "repeat last trip" and clue trip buttons. A favorite command could use the exact same arguments as the actual typed command, just that you don't need to type at all. The element of customizability would appeal to everyone and help with the transition to slash commands.

This would be very useful for frequently used commands such as birdhouse runs or farm runs/contracts, to name a few. Picture below for a mock-up example.

Not sure on the feasibility of applying this to every possible command though. Just an idea. Maybe "favorite last executed command" would be a decent approach.

![image](https://user-images.githubusercontent.com/59510368/168491385-50730ab1-627c-4213-ae33-ceb966d87546.png)

**Comment by Lajnux** [comment]
The +m command itself is gonna be converted to a slash command if it hasn't been already.

**Comment by Redquaker** [comment]
Depending on what the new +m slash command is, it may still be easier to type that and hit a button versus typing out an entire slash command with arguments, especially on mobile. I would guess that the new +m command will be short/quick/easy to use given that it's probably one of the most used commands on the bot, if not the most.

Generally, it'd be nice to just rely on a single command to send whatever trips you need throughout the day.

**Comment by osrsjobbo** [comment]
@Redquaker  Is this still relevant with the last year of development adding buttons to /m?

**Comment by Redquaker** [comment]
@osrsjobbo Not really relevant anymore since the current state of /m buttons is quite good. Closing this issue.
