### ISSUE TITLE
Item disappeared 👎 

### ISSUE THREAD

**Issue by Trickies** [oldschoolgg/oldschoolbot#3932]
## 🐛 Bug Report

I was making clock work.
I canceled because I didn't specify the amount since it was too much.
I tried again and my steel bars never returned to my bank. 

See pic below:
![image](https://user-images.githubusercontent.com/105902978/169452561-23dbf2ee-64f1-4e12-bc89-2ecf5e1f3a7c.png)

**Comment by gc** [comment]
Cancelling trips makes you lose the items from that trip, a warning is given when you do this.
