### ISSUE TITLE
No Doug Boost at Volcanic Mine

### ISSUE THREAD

**Issue by ImOffendedd** [oldschoolgg/oldschoolbot#3938]
Since Volcanic Mine has been converted to / cmd it doesn't seem to apply the Doug boost
![Screenshot_20220516-001829_Discord](https://user-images.githubusercontent.com/106015470/169692234-84f1e2fe-35a0-4c67-84b1-cf35fa48d357.jpg)
I tried unequipped and re equipping the pet but still no change

**Comment by ImOffendedd** [comment]
Any changes on this yet?

**Comment by gc** [comment]
Fixed
