### ISSUE TITLE
clear all favourite items

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#3959]
add an ‘all’ to the remove option on favourite items to remove/wipe all your favourites.

![44113626-2F31-4B5D-95A6-1F8DCD893064](https://user-images.githubusercontent.com/76587427/170825100-3bae0579-cfa2-4700-850f-15f50c867e58.jpeg)

**Comment by 6enny6** [comment]
if you have too many favourite items (its capped at 100 now?) it is impossible to view the list of them so you can see what to remove due to it throwing an error. Some people completely locked out of changing their favourites right now

![image](https://user-images.githubusercontent.com/76587427/170863764-7a4855a2-87b0-4071-8f2c-701698533129.png)

**Comment by LuxrayElite** [comment]
``/config user favorite_items reset:True`` is the command to do this now
