### ISSUE TITLE
Boosts broken for ogress warriors

### ISSUE THREAD

**Issue by ZappyScript** [oldschoolgg/oldschoolbot#3960]
Without master attack cape I kill 227 ogresses, with the cape I still only kill 227 even tho it states the boost is active.

**Comment by ZappyScript** [comment]
Looking back, I think the boosts are broken for ogresses...

Here's me killing ogresses before the cape: 

![image](https://user-images.githubusercontent.com/16172144/170831046-6ad25d28-c5cb-41b1-a7a0-1b1a8424c56b.jpeg)

Here's after the cape:

![image](https://user-images.githubusercontent.com/16172144/170831058-180193e0-ee9f-448e-a552-65cb9144ce10.jpeg)

And here's one of the very first kills I did: ![image](https://user-images.githubusercontent.com/16172144/170831067-783a6bba-2e6a-4697-a4ee-2e523ea3a36a.jpeg)

**Comment by Lajnux** [comment]
Some boosts only apply to the final trip length making it shorter than the max trip length (Which still is a boost, more trips)
This is also how weekend boost works.

![image](https://user-images.githubusercontent.com/68188574/170834927-4c396841-21d6-451f-90c4-54c965e88168.png)
