### ISSUE TITLE
Bso Herblore Master Cape Issue 

### ISSUE THREAD

**Issue by Robson1212121223** [oldschoolgg/oldschoolbot#3966]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
Hello Dearest People,
When mixing potions on BSO with the herblore master cape, you currently receive extra potions.
However, this regretfully stops the "press Y to repeat" action from working.
Additionally, you cannot do "=m" then click the "repeat herblore trip" button as then it states you cannot go over X time period.
So now you have to type the whole command in to repeat, alot slower with slash commands. 
Could the Button or repeat instinctively make the maximum a trip takes and not what you received back. 
Eg when you get double loots this doesnt effect it.
Thank you,
Kindest Regards,
Robson

**Comment by gc** [comment]
Fixed in next update
