### ISSUE TITLE
Increase pet rate for 200m skilling pets

### ISSUE THREAD

**Issue by Japoolie** [oldschoolgg/oldschoolbot#3969]
## 🚀 Feature Proposal

Increase the skilling pet rate to 15x once 200m xp has been reached in a skill

**Comment by TastyPumPum** [comment]
I believe this is only when you haven't got the relevant pet by 200m for anyone coding this.

**Comment by mylife212** [comment]
its just a flat 15x increased rate at 200m according to Wiki https://oldschool.runescape.wiki/w/Pet#Skilling_pets
