### ISSUE TITLE
y not working with creating mithril 2h

### ISSUE THREAD

**Issue by jordan-git** [oldschoolgg/oldschoolbot#397]
## 🐛 Bug Report

Not exactly 100% if this is a bug as sometimes there's a little lag, but I spanned the commands over about 10-15 seconds.

Apparently pressing "y" to repeat mithril 2h without enough bars gives no response?

Seems like a strange bug so apologies in advance if i'm wrong but thought I should report it.

![Discord_7bFnGpXH89](https://user-images.githubusercontent.com/19174130/87843895-f5639e80-c8af-11ea-984a-33ebe4c775cc.png)

**Comment by jordan-git** [comment]
![Discord_GLAa31kl5d](https://user-images.githubusercontent.com/19174130/88216562-2bf53c80-cc55-11ea-8de7-49b90d4988fd.png)

Same thing just happened but it has been 2 minutes and neither works. I believe it comes down to bot lag. Maybe some syncronous code halting execution?

**Comment by Lajnux** [comment]
bot lag/delay and #406 fixes/closes this issue.

**Comment by Alexsuperfly** [comment]
This is due to the activity not catching in the yes response section, when it asks if you want to resend out the trip, errors should be caught now with 474bb1ace5fdcfe6bd210d85f4f615db120c8541.  The second comment is just bot lag which I believe is mainly discords fault.
