### ISSUE TITLE
 Issue with reverting crystal weapon seed

### ISSUE THREAD

**Issue by gpRollMaster** [oldschoolgg/oldschoolbot#3979]
## 🐛 Bug Report
When trying to revert a crystal weapon seed I select the correct one but it changes to the enhanced version.
I did tried the enhanced version too but that one shows correct 

/create item:Revert crystal weapon seed

Username, please confirm that you want to revert 1x Enhanced crystal weapon seed into 10x Crystal shard.

You don't have the required items to revert this item. You need: 1x Enhanced crystal weapon seed.

**Comment by gc** [comment]
Fixed
