### ISSUE TITLE
/minion use

### ISSUE THREAD

**Issue by DarkBugz** [oldschoolgg/oldschoolbot#3981]
Slepey tablet is not available on the drop menu and cant be used on mobile

**Comment by TURB042O** [comment]
> Slepey tablet is not available on the drop menu and cant be used on mobile

![Screenshot_20220610-233602_Discord.png](https://user-images.githubusercontent.com/90441459/173172713-888841ba-079e-4128-8317-6e71f2e4f210.png)

if it's not in your bank it won't appear in the list. and I'm on mobile.

**Comment by gc** [comment]
It wont show ones you dont own.
