### ISSUE TITLE
Change GE character limits

### ISSUE THREAD

**Issue by NotShin** [oldschoolgg/oldschoolbot#3982]
## 🚀 Feature Proposal

When trying to use emojis in the grand exchange, you will often encounter the message below. This is because the 450 character limit uses the escaped character sequence (i.e. <:cu:982340542895636500>) when using emojis like `:cu:`. A normal user would not know about this and it is incredibly frustrating, so I am suggesting the message below to be updated or change the char limit to raw text input by the user. To help prevent people abusing this an emoji limit can be easily parsed and added to the requirements.

This will allow users to comfortably buy and sell multiple items by leveraging emojis to reduce raw text and whitespace if they so wish. I think this would be a step up from the current implementation and hope you will consider making a change.

> Your message was automatically removed from the grand exchange channel, because it was either over 10 lines long, over 450 characters long OR does not include the phrase "buying"/"selling"

**Comment by gc** [comment]
I suggest using less emotes, or a picture.
