### ISSUE TITLE
+m activities 

### ISSUE THREAD

**Issue by AvariceBrah** [oldschoolgg/oldschoolbot#3983]
## 🐛 Bug Report

Yesterday, probably a little over 24h before this post I used +m activities and it listed my recent activities entirely. Now I get _**An unexpected error occurred**_

The only new activity that got added to the list since then would be mining saltpetre and cluetrip.

Good luck lol

**Comment by TURB042O** [comment]
great minds think a like lol #3996

**Comment by TURB042O** [comment]
> ## 🐛 Bug Report
> 
> Yesterday, probably a little over 24h before this post I used +m activities and it listed my recent activities entirely. Now I get _**An unexpected error occurred**_
> 
> The only new activity that got added to the list since then would be mining saltpetre and cluetrip.
> 
> Good luck lol

great minds think a like lol #3996

**Comment by gc** [comment]
https://github.com/oldschoolgg/oldschoolbot/issues/3996
