### ISSUE TITLE
Permanent Ironman Removal

### ISSUE THREAD

**Issue by Centerpin** [oldschoolgg/oldschoolbot#3992]
Give those the option to remove their permanent ironman status if they have deleted their alternate "main" account.

Just like how OSRS has it, you can have your permanent ironman status removed if requested & you have a 7 day grace period to change your mind.

It gives those who started as an ironman and don't want to continue using 2 accounts an opportunity to become a "normal" account again with only 1 discord.

THAT IS, if they don't have an alternate account already or have already deleted it.

**Comment by TastyPumPum** [comment]
This can never be a thing on bso due to how the discontinued pets are given and I assume it would be alot of work for osb, when they shouldn't have confirmed the permanent ironman if they wasn't sure of it.

**Comment by gc** [comment]
>Would you like to change your ironman to a *permanent* iron? The only thing in your account that will change, is that you will no longer be able to de-iron. This is *permanent* and cannot be reversed, its permanent ironman mode.
Please say \`permanent\` to confirm.

If someone really really wants to deiron a perm iron, they will have to request it done manually.
