### ISSUE TITLE
Minion Activities giving error (osb & bso)

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#3996]
> ## 🐛 Bug Report
> 
> Yesterday, probably a little over 24h before this post I used +m activities and it listed my recent activities entirely. Now I get _**An unexpected error occurred**_
> 
> The only new activity that got added to the list since then would be mining saltpetre and cluetrip.
> 
> Good luck lol

_Originally posted by @AvariceBrah in https://github.com/oldschoolgg/oldschoolbot/issues/3983

## 🐛 Bug Report

![SmartSelect_20220608-090612_Discord.jpg](https://user-images.githubusercontent.com/90441459/172637452-d020dcbd-ca4c-4bf7-9c2b-d7d329d83976.jpg)

I can't seem to find the slash command if it was moved to there so I'm not sure. figured I'd post here incase this is actually a bug.

**Comment by TastyPumPum** [comment]
![Screenshot_20220608-150950_Discord](https://user-images.githubusercontent.com/79149170/172638163-78a06226-31e3-4efd-b1e4-9ffdd7c39217.jpg)

**Comment by TastyPumPum** [comment]
https://github.com/oldschoolgg/oldschoolbot/issues/3983

Already covers this bug

**Comment by TURB042O** [comment]
> https://github.com/oldschoolgg/oldschoolbot/issues/3983
> 
> Already covers this bug

lol. I just told him not knowing I put a github out on it this is funny. ty for linking that
