### ISSUE TITLE
Elysian Spirit Shield - BSO 

### ISSUE THREAD

**Issue by IronicnZ** [oldschoolgg/oldschoolbot#4001]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

Elysian spirit shield food reduction boost for BSO is no longer working, have tried more than one equip slots (mage ranged melee and other) and also tried each attack style corresponding to gearsetup Elysian was placed in (or using during combat). -Note my melee stats are all above 99 too.
First noticed after obtaining then creating an Elysian Spirit Shield from a Sigil + shield combo

**Comment by TastyPumPum** [comment]
Have you tried killing different things? Might just be not working for whatever you are killing

**Comment by IronicnZ** [comment]
Killed a few things, and thought the same, so OSB searched the elysian
boost in oldschool.gg and found a monster it was being used at/ working at
and still had no luck

**Comment by IronicnZ** [comment]
Sorry to reword, i searched Elysian in Oldschool.gg until i found an OSB
mention of it working, then I killed that on BSO and no mention. I also
tried - Malygos, Vorkath  and Man alongside that one monster i searched
