### ISSUE TITLE
If you get Heron from Aerial fishing, the #notifications channel does not mention it at all.

### ISSUE THREAD

**Issue by badgehunter** [oldschoolgg/oldschoolbot#4004]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

while i was aerialfishing, i happened to get heron 2 days ago. didn't notice this for 2 days until i checked my pets collected due i got herbi, i checked today notifications to see at what level i got it and it is missing in the notications entirely. most likely aerial fishing moving to / messed up the pets notifications as there are herons from aerial fishing in there one from day before moving to /.

my disc is badgehunter#2017 if you want to check i actually got heron.

**Comment by TastyPumPum** [comment]
https://discordapp.com/channels/342983479501389826/469523207691436042/997930904318128248

Looks like there have been some since this post so I assume this is fixed. The code looks correct too.
