### ISSUE TITLE
"I don't have that monster!" BSO Custom's missing

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#4005]
## 🐛 Bug Report

![SmartSelect_20220610-193326_Discord.jpg](https://user-images.githubusercontent.com/90441459/173165575-2b42bee9-a692-4674-a77f-18b4b9cd8196.jpg)
![SmartSelect_20220610-215954_Discord.jpg](https://user-images.githubusercontent.com/90441459/173170138-05419f2f-d8c8-4fb0-850a-50fb22ef8e9d.jpg)
~~these are only 2 that I've noticed the response "I don't have that monster!" for. when I know for a fact igne used to work for simulations, but 'rum-pumped' crab idk if ever existed for `=kill`. but it has a cl.~~

so I have checked the situation more deeply and all BSO custom monsters are not in the database for `=kill` my guess is - when you did the simulators [https://www.oldschool.gg/monsters]() the coding must have disappeared for bso. idk just a guess or thought. plz don't use it to troll me.

**Comment by AvariceBrah** [comment]
![Screenshot_20220610-215640~2](https://user-images.githubusercontent.com/77698878/173170111-834c7953-a2fe-419c-b4f1-cea9f238f0f3.png)

**Comment by TURB042O** [comment]
> ## 🐛 Bug Report
> 
> ![SmartSelect_20220610-193326_Discord.jpg](https://user-images.githubusercontent.com/90441459/173165575-2b42bee9-a692-4674-a77f-18b4b9cd8196.jpg)
> ![SmartSelect_20220610-215954_Discord.jpg](https://user-images.githubusercontent.com/90441459/173170138-05419f2f-d8c8-4fb0-850a-50fb22ef8e9d.jpg)
> these are only 2 that I've noticed the response "I don't have that monster!" for. when I know for a fact igne used to work for simulations, but 'rum-pumped' crab idk if ever existed for `=kill`. but it has a cl.
> 
> so I have checked the situation more deeply and all BSO custom monsters are not in the database for `=kill` my guess is when you did the simulators on [https://www.oldschool.gg/monsters](Oldschool.gg Loot SimulatorsSimulator) the coding must have disappeared for bso. idk just a guess or thought. plz don't use it to troll me.

**Comment by gc** [comment]
Fixed in next update.
