### ISSUE TITLE
/POH wont work when minion busy

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#4006]
## 🐛 Bug Report

![SmartSelect_20220610-234332_Discord.jpg](https://user-images.githubusercontent.com/90441459/173172904-0a638e08-6b58-4b28-8e6a-49063880aeb8.jpg)

also there is no command to show what you have built currently in your poh, it used to be `=poh list`

**Comment by gc** [comment]
Fixed in next update.
