### ISSUE TITLE
Allow Gorajan pieces to be reverted

### ISSUE THREAD

**Issue by johnsonn14** [oldschoolgg/oldschoolbot#4009]
## 🚀 Feature Proposal

Allow gorajan pieces to be reverted by getting rid of the nex item but returning 2 gorajan shards.

By deleting the nex item, it would prevent smithing experience to be abused.

This comes from no confirmation coming from the new /smith command and I made 4 gorajan occult helmets by accident.

**Comment by gc** [comment]
#bso-vote this please.
