### ISSUE TITLE
Blocking then skipping slayer tasks tries blocking again

### ISSUE THREAD

**Issue by anthonyburrow** [oldschoolgg/oldschoolbot#4011]
## 🐛 Bug Report

Using the GUI buttons that come from the slayertask command, if you block a monster, and then attempt to skip the next monster that comes up, it tries to block that next monster instead.

I feel like msg.flagArgs.block may be being held True as the command is being recursively called, but I'm not sure about that.

**Comment by LuxrayElite** [comment]
No longer seems to be an issue, feel free to re-open if it re-occurs
