### ISSUE TITLE
Is lapcount gone?

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#4014]
## 🐛 Bug Report

So the only / command I can find is laps and it doesn't give an option for lapcount and doing `=lapcount` or was it `=lapcounts` either way doesn't do anything anymore

**Comment by anthonyburrow** [comment]
It's +m lapcounts, and it still works.

**Comment by TURB042O** [comment]
> It's +m lapcounts, and it still works.

bro thank you... unfortunately the only one i didn't try. lol. tried it without the s and said minion was busy :p but thank you.
