### ISSUE TITLE
[BSO] Inferno / Zuk error has occurred message

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#4017]
## 🐛 Bug Report

So when someone responds with Y or whatever letter/# they're told, it always says a error has occurred 😡 

but it still re-sends the minion because you do =m and it says your back attempting 

![Screenshot_20220612-144607_Discord.png](https://user-images.githubusercontent.com/90441459/173250639-b8d6dac3-f09b-43c1-95f5-56ef093d01ff.png)

so in the end, it still does what it is supposed to, but with a error instead of the correct response.

**Comment by gc** [comment]
I believe this was fixed.
