### ISSUE TITLE
Auto contract issues

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#4027]
If you plant and re-harvest a patch thats your contract it wont give you the auto contract button afterwards. This is because it thinks the replant is your next contract. As seen in the screenshots below. 

My suggestion is that when the bot sees you have a seedpack to open, it overrides this and gives you the auto contract button to get a new one

![E9F6D035-32B0-44BC-A21B-905F650F270A](https://user-images.githubusercontent.com/76587427/173847665-e742cd45-3814-4f30-b301-7d09fc37c5d0.jpeg)

![2DF5F2A1-4060-44B5-9DA5-47FDDBB2A58E](https://user-images.githubusercontent.com/76587427/173847823-7b367220-06cc-46f8-9413-560ff2f9403c.png)

**Comment by osrsjobbo** [comment]
Can you try replicate this bug on this branch? https://github.com/oldschoolgg/oldschoolbot/pull/5001
