### ISSUE TITLE
BSO Slash commands not showing up

### ISSUE THREAD

**Issue by tsbreuer** [oldschoolgg/oldschoolbot#4029]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

Had OSB on my server, invited BSO because i thought it'd be more fun, but there's no slash commands.

![imagen](https://user-images.githubusercontent.com/6902643/173879051-0a8e34e3-1462-463d-b49d-65dd68f4d904.png)

The reason OSB commands arent showing up is because i kicked it just in case it had a conflict. ive also tried reinviting BSO but they still dont show up.

**Comment by NotShin** [comment]
Try using Ctrl+R to refresh the client and see if they appear. Alternatively, you may need to kick and re-invite the bot to your server.

**Comment by tsbreuer** [comment]
The issue was i was using the link on the osbdocs page https://github.com/oldschoolgg/obdocs/blob/master/BSO.md, using the regular link worked.

**Comment by gc** [comment]
Fixed the link.
