### ISSUE TITLE
The new /bank command cannot display items as text like the original +/= bank command 

### ISSUE THREAD

**Issue by ColossalSeagull** [oldschoolgg/oldschoolbot#4031]
## 🚀 Feature Proposal

As title says add a flag to the /bank command that will let you output the bank as text like in the original function of the +/= bank command. This was a function previously available and is helpful in determining what items are in your bank and what they are called. It would be nice if we could also export this as a text file like we could previously. Currently the only export format is .json and it uses id's of items rather than text names and seems to ignore any filter/search done on the bank so it returns your entire bank in the .json which isn't super useful.

![image](https://user-images.githubusercontent.com/96855950/173889791-8e7ca826-ce04-427e-a55e-8f941d8c73f6.png)

**Comment by osrsjobbo** [comment]
This can be achieved using `/banksearch:cabbage format:text_paged`.

**Comment by osrsjobbo** [comment]
It would be nice to have format on /bs though, so I'll open a PR for that.
