### ISSUE TITLE
BSO | Mixing athelas paste

### ISSUE THREAD

**Issue by NotShin** [oldschoolgg/oldschoolbot#4032]
## 🐛 Bug Report

 There is a bug for mixing athelas paste as a tier 3 patreon. When trying to repeat trip there is some issue with max time.

![image](https://user-images.githubusercontent.com/21049385/173984436-1275ea6c-3e4e-4304-b5b4-0850ff3b3ed7.png)

**Comment by RubenJS95** [comment]
I'd like to add that this issue also exists for t2 and non patreons.

**Comment by LuxrayElite** [comment]
Should be resolved by #4226
