### ISSUE TITLE
BSO | Zippy hunt at Eastern ferrets

### ISSUE THREAD

**Issue by NotShin** [oldschoolgg/oldschoolbot#4033]
## 🐛 Bug Report

When hunting Eastern ferrets, the send/return trips do not mention delicious kibble which is required in order to hunt Zippy. The kibble is not removed from the bank either, so it's unclear whether the hunt is active/disabled or if there is a bug currently.

![image](https://user-images.githubusercontent.com/21049385/174098182-f5f46bff-99b7-4491-a42f-becb4853390f.png)

**Comment by themrrobert** [comment]
fixed already
