### ISSUE TITLE
OSB 100+ favorites list error

### ISSUE THREAD

**Issue by RuinMyScape** [oldschoolgg/oldschoolbot#4035]
if you have too many favourite items (100+) it is impossible to view the list of them so you can see what to remove due to it throwing an error. I'm completely locked out of changing my favourites right now.
![170863764-7a4855a2-87b0-4071-8f2c-701698533129](https://user-images.githubusercontent.com/107696007/174310894-1f24a435-1094-4523-b87c-cbbfa32cc10c.png)

**Comment by 6enny6** [comment]
closing due to already being reported here

https://github.com/oldschoolgg/oldschoolbot/issues/3959#issuecomment-1140421253

**Comment by RuinMyScape** [comment]
Yeah sorry its just super annoying and im sure its an easy fix. Not saying
i could do it but it cant be hard to add an "all" option. Sorry for putting
it up again

Op vr 17 jun. 2022 16:41 schreef 6enny6 ***@***.***>:
