### ISSUE TITLE
BSO mass gwd calculations.

### ISSUE THREAD

**Issue by Spiere** [oldschoolgg/oldschoolbot#404]
Not sure if bug but masses in gwd or masses in general must not be receiving the bso 2x boost. Solo gwd kills are same quantity as normal trips even with faster kill times

**Comment by Lajnux** [comment]
Groupmonsteractivity does give bonus loot for masses even GWD. Closes this issue. 
![image](https://user-images.githubusercontent.com/68188574/92382765-6e8fad00-f10d-11ea-97c5-c7d468e3b07f.png)
