### ISSUE TITLE
MISSING ZAK? Unable to send trips, keep receiving errors?

### ISSUE THREAD

**Issue by ghost** [oldschoolgg/oldschoolbot#4043]
## 🐛 Bug Report
Since the update yesterday I've been unable to send trips/have my tame return anything from trips/receive anything from dailys, and now whilst still trying to find out what's wrong i equipped another one of my pets (Scruffy) only to find that i no longer seem to have Zak (which was equipped prior) in my bank, so I then tried to equip another pet, only to get an unexpected error message? 
I've tried doing =rp checkbank --fix, unequiping all gear etc, but nothing seems to be fixed depsite saying 3 broken items were removed (Im presuming one of them was Zak) but still can't get anything to work.
![log](https://user-images.githubusercontent.com/71338065/174639913-1cbacabd-dd33-44be-9d15-f1a1d65ae861.png)

**Comment by Shadax-OSB** [comment]
Update: Tried =rp checkbank--fix again, and now Scruffy has just been deleted from my equipped pet slot??
