### ISSUE TITLE
BSO - Wintertodt trip returns broken

### ISSUE THREAD

**Issue by Redquaker** [oldschoolgg/oldschoolbot#4045]
## 🐛 Bug Report

Wintertodt trips are not returning properly on BSO. The timer shows up once the command is executed but there's never a return message and your minion is just idle after the time elapses. No XP is given; not sure about items but I would assume not as well.

See pictures below for firemaking XP checks and a trip I sent overnight as evidence for no XP being given. I'm not sure if this happens on OSB as well.

![image](https://user-images.githubusercontent.com/59510368/174645068-d85361c7-c477-4c90-bd4b-512799842271.png)
![image](https://user-images.githubusercontent.com/59510368/174645097-3657197f-3760-41a6-90c6-0e709068e123.png)
![image](https://user-images.githubusercontent.com/59510368/174645114-da54ece3-16f7-48c5-869d-02027a0ef5f6.png)

**Comment by gc** [comment]
Closing as an old issue, if this is still an issue, feel free to re-open.
