### ISSUE TITLE
Bank value and weightings/favorites broken

### ISSUE THREAD

**Issue by KroniKStyL** [oldschoolgg/oldschoolbot#4048]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

Woke up at approximately 5:58 AM, kind of tired but ready for the day. Got on my favorite discord bot to check my bank for shiny new gmcs from the last trips of the night. Basically bank value says (NaN) upon using (=b) and the weightings/favorites feature isn't working. Everything is just scattered

**Comment by gc** [comment]
Fixed
