### ISSUE TITLE
BSO | New Repeat Trip button blocking tame

### ISSUE THREAD

**Issue by NotShin** [oldschoolgg/oldschoolbot#4051]
## 🐛 Bug Report

11:09 AM EST: Tame trip returned with message "Say `y` to repeat this trip."
11:11 AM EST: Minion finished trip with repeat button.

Upon typing `y`, it did not repeat my tame's trip and I was forced to reinitiate it manually. This may be intended, but it is unclear with the new "Repeat Trip" button update.

![image](https://user-images.githubusercontent.com/21049385/175086303-73f9e743-9ed1-4611-b2b6-c67385b74ec3.png)

**Comment by gc** [comment]
Your screenshot SHOWS your tame trip being repeated.

**Comment by NotShin** [comment]
This was because I had to manually type =m and press the button to do the tame trip. Typing `y` did nothing because minion trip came in and blocked it despite the new "Repeat Trip" button update.

**Comment by TURB042O** [comment]
> This was because I had to manually type =m and press the button to do the tame trip. Typing `y` did nothing because minion trip came in and blocked it despite the new "Repeat Trip" button update.

minions don't block things.. if anything typing `y` would have sent both trips simultaneously.

**Comment by NotShin** [comment]
> > This was because I had to manually type =m and press the button to do the tame trip. Typing `y` did nothing because minion trip came in and blocked it despite the new "Repeat Trip" button update.
> 
> minions don't block things.. if anything typing `y` would have sent both trips simultaneously.

Typing `y` did nothing as mentioned. I had to manually initiate the trip by typing `m` and pressing the button to repeat my Sea Kraken's trip as shown in the picture.
