### ISSUE TITLE
Dark Totem Pieces Logic Messed Up

### ISSUE THREAD

**Issue by shelixd** [oldschoolgg/oldschoolbot#4053]
Since today the logic for how dark totem pieces drop got changed/messed up. Before they would drop sequentially (base -> middle -> top) and now it only drops multiple of the same piece that is next in the sequence.

Before:

![](https://cdn.discordapp.com/attachments/849482176717389885/989393514393665616/file.jpg)

After:

![](https://cdn.discordapp.com/attachments/849482176717389885/989560028920946778/file.jpg)

**Comment by gc** [comment]
Fixed
