### ISSUE TITLE
add herbiboar to /minion kc list

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#4054]
add herbiboar to the list on `/minion kc name:`

currently doesnt show up, but if you just press enter it does actually tell you your kc

![92212DDC-7A58-43C3-BC3C-854B4D86AEC1](https://user-images.githubusercontent.com/76587427/175349490-4c291b75-1130-4377-9900-964abcc728a1.jpeg)

![FD1EAFD1-48FF-4892-8444-B32FCE8560C7](https://user-images.githubusercontent.com/76587427/175349493-ba88bbdc-522a-42a7-9712-150294b2d42a.jpeg)

**Comment by gc** [comment]
Fixed in next update.
