### ISSUE TITLE
BSO Repeat Button Sends Trips in Different Servers

### ISSUE THREAD

**Issue by VenyaVeritas73** [oldschoolgg/oldschoolbot#4056]
## 🐛 Bug Report

I'm not sure if this is a bug or just discord tomfoolery, but if I have been sending trips in one server, and then go to a different server and do =m and then tap the button to repeat trip, it will send the trip in the original server that I had been doing trips in, and not the server that the command was typed in. It's not really harmful but it is strange.

If this isn't considered a bug I'll go ahead and close the report when told so.

![Screenshot_20220623-221918_Discord](https://user-images.githubusercontent.com/98783697/175461452-ffe6ede8-0980-49d1-9f02-9058b5fcf3f7.jpg)

![Screenshot_20220623-210901_Discord](https://user-images.githubusercontent.com/98783697/175461456-8a8592c8-67ff-4cc1-9bf3-78371fd13dcc.jpg)

**Comment by gc** [comment]
Fixed in next update
