### ISSUE TITLE
add a quantity option to /sell

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#4057]
Add a quantity option to /sell

you can currently do quantities like this but not many people know of it, would be better as a seperate option

![ADF3D8E8-ADB2-47D5-8CE8-0CEFFB6DFB41](https://user-images.githubusercontent.com/76587427/175476134-30723f23-4824-458d-9f26-9ab63f03ef2b.png)

**Comment by gc** [comment]
not really possible to provide a quantity for a group of items like this. i added an extra example in the command description though
