### ISSUE TITLE
KG "Repeat Trip" button not working

### ISSUE THREAD

**Issue by sunnyzulu** [oldschoolgg/oldschoolbot#4060]
![image](https://user-images.githubusercontent.com/81121103/175612349-b3e8bfc6-1175-4866-ac1a-c3cd848a2a91.png)

Just thought i'd put this here, sort of a minor inconvenience.

Solo trip are not able to be repeated by clicking "Repeat KingGoldemar Trip"

**Comment by gc** [comment]
Fixed
