### ISSUE TITLE
Repeat previous trip button on clue return

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#4062]
Add a button to clue return trips that repeats the previous trip you did before the clue. 
The exact same as the repeat button currently on +m

Usage: 
- Killing guards
- click the new patron-only button to do clue on the guards return trip
- click button to repeat the guards killing trip on the the clue return trip

After doing a clue trip, you can already just do +m to repeat the previous monsterkilling trip, would be nice to not have to do +m

**Comment by LuxrayElite** [comment]
Discussed with benny this is about OSB, so is resolved.
