### ISSUE TITLE
(BSO) Repeat trip button claims minion not owned

### ISSUE THREAD

**Issue by toulouseee** [oldschoolgg/oldschoolbot#4064]
## 🐛 Bug Report

When clicking the repeat trip button after finishing a Dungeoneering or kibble making trip, the BSO bot responded saying that I didn’t own a minion for the Dungeoneering trip and just didn’t react at all for the kibble trip. I tested this with Woodcutting, Firemaking, Sawmill, burying bones, and cooking trips, but so far repeating those trips works just fine. 

My best guess would be that since it works fine for slash commands, that it has to do with Dungeoneering and kibble making still running on the old prefix system
![7BB4C599-186A-46DD-B043-F4F01357C983](https://user-images.githubusercontent.com/95940944/175773417-d2b5abe4-0744-42e3-a008-248e2d2b4466.png)
![17B18496-D761-45A7-9FD2-3AA4DA7B85C7](https://user-images.githubusercontent.com/95940944/175773419-c59017ad-a7f2-42c8-a0a1-d14d70b882ee.png)

**Comment by gc** [comment]
Fixed
