### ISSUE TITLE
(BSO) webhooks & trip return messages

### ISSUE THREAD

**Issue by toulouseee** [oldschoolgg/oldschoolbot#4066]
## 🐛 Bug Report

I will try to describe this so that it actually makes sense, but honestly I’m still beyond confused by the situation. 

- Basically, about 3 days ago with the release of the repeat trip button I noticed that the bot wouldn’t repeat my dungeoneering trips via said button (which is still the case, but that’s in another bug report I just posted). 
- after noticing the repeat trip button wouldn’t respond I did the discord bot equivalent of “have you tried turning it off and then on again”, meaning I kicked the BSO bot from my server and re-added it again
- I then came into the much more frustrating problem of no longer getting trip return messages for dungeoneering and farming trips
![0BE849DF-16FC-47C4-9634-8DF2F44F6FA6](https://user-images.githubusercontent.com/95940944/175774033-87e714de-1849-40f0-965d-32f37887fc80.png)
- Maybe a day later (2 days ago) I decided to make a separate test channel to see if it was just dungeoneering and farming commands having issues, and much to my surprise other commands did get trip return messages. In hindsight I should’ve tested the dungeoneering/farming commands in the test channel, but for whatever reason I didn’t and just assumed that the issue was related to those commands
- fast forward to last night, I kicked the bot again because it obviously worked so well the first time, but I still wasn’t getting trip return messages and I was desperate at this point. This is when I realized the issue was related to the channel/server, not specific commands because I no longer got trip return messages in my test channel. 
- I created a 2nd test channel and again, got trip return messages in that one but still not in any of the pre-existing channels. At this point I started looking at channel/server settings

- To sum it up:

**The bug:**
The bot deletes all of its webhooks when it leaves a server, thus somehow disabling trip return messages in channels existing prior to re-adding the bot. It still responds to commands and starts trips perfectly fine, there’s just no indication that the trip ended and you won’t see what loot you received afterwards (even though trip loot does go in the bank). I couldn’t find any way to manually add webhooks to pre-existing channels. 

**The server side semi-fix:**
It’s been years since I coded anything so I can’t really offer any help on the code side of things, but if this happens to anyone else in their server the thing that worked for me was just creating new channels 

**one last thing:**
When messing with the webhooks, I realized you can manually switch the channel it’s linked to, but this just made things significantly more confusing. When changing the webhook from Channel B to Channel A, when starting a trip in Channel A you still wouldn’t receive a trip return message. However, when starting a trip in Channel B, the trip return message would be sent from the bot in Channel A. Essentially: manually switching the webhooks channel (from B to A) only changed the final output location (A), the input still had to come from the original channel (B).
![FA7820D5-E525-4DB1-AC77-B926827EBFF0](https://user-images.githubusercontent.com/95940944/175775680-491759fe-2476-4fa0-9d1a-7a5785d7b2ac.jpeg)

![87C9689B-A891-4926-8FFD-128EF8117A4E](https://user-images.githubusercontent.com/95940944/175775432-e43a0c1a-f353-442c-8c52-2e17fc75462a.jpeg)
![D9C34B80-7DFF-4597-94E8-C4386034CFAB](https://user-images.githubusercontent.com/95940944/175775433-01512d36-f032-47ab-9041-5a209797841e.jpeg)

**Comment by 6enny6** [comment]
issue fixed in next update
