### ISSUE TITLE
[OSB|BSO] "Repeat Trip" not working (sometimes)

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#4068]
## 🐛 Bug Report

so far I can for certainty say on OSB `cox` solo trips it isn't working & BSO I've noticed it not working on ~~`pickpocket`~~ trips, `KG` trips & `Igne` trips.

I'm sure there are many more but this is what I got.

edit: weirdly enough pickpocket worked..

**Comment by BigLazyturtle** [comment]
This appears to affect any trip that can fail (ie. you have a chance of death) (does it affect nex?), this includes inferno (i would assume emerged as well).  Image is of someone asking in BSO support why the repeat trips are not sending
![image](https://user-images.githubusercontent.com/105060609/182050522-c248f11b-4efe-4436-ab27-a4155ddf5d2c.png)

**Comment by gc** [comment]
Closing as an old issue, feel free to re-open if this is still a problem.
