### ISSUE TITLE
Athelas paste trips and T2 patron.

### ISSUE THREAD

**Issue by EissApp** [oldschoolgg/oldschoolbot#4069]
## 🐛 Bug Report

Whenever I try to **resend** a trip of making **Athelas Paste** using the "Repeat Trip" button, it gives me an error message "Minion can't go on trips longer than 37 minutes, try a lower quantity. The highest amount of Athelas pastes you can make is 1620." Meanwhile, when I send a trip manually (/mix athelas paste) the minion make exact same amount 1620, however the trip takes **36 minutes & 59 seconds**. 

it seems like this issue is going for T2 and T3 Patron, it might be effecting other Tiers also but I have no idea.

![image](https://user-images.githubusercontent.com/55485515/175792249-733f0213-ff34-46df-bb7f-4647b983aba5.png)

**Comment by TastyPumPum** [comment]
Duplicate #4032
