### ISSUE TITLE
Quantity doesn't work at igne

### ISSUE THREAD

**Issue by 000000653** [oldschoolgg/oldschoolbot#4070]
## 🐛 Bug Report
Doing igne, if you give it a quantity, it ignores it entirely and just does a full trip anyways
Unsure if it affects mass option too, but solo is what I have proof of:
![Discord_Cn4BQ1Kkm9](https://user-images.githubusercontent.com/40111569/175792745-2b5e474b-70c3-4bd6-abee-3b68d0d373f5.png)

**Comment by gc** [comment]
Fixed in next update
