### ISSUE TITLE
Solo nex = mass?? 

### ISSUE THREAD

**Issue by AvariceBrah** [oldschoolgg/oldschoolbot#4072]
## 🐛 Bug Report

![Polish_20220625_192631904](https://user-images.githubusercontent.com/77698878/175794561-9fe50ba6-3da9-4773-820b-4e4ba16ad4e0.png)

/K name: nex (solo) initiates a mass for some reason in bso

**Comment by AvariceBrah** [comment]
Same thing for igne I've discovered.

**Comment by 6enny6** [comment]
this should now be fixed
