### ISSUE TITLE
Button for new slayer task at the end of autoslay

### ISSUE THREAD

**Issue by TastyPumPum** [oldschoolgg/oldschoolbot#4073]
If possible, at the end of a slayer task could we then get a button to click to get a new slayer task? It's not that bad currently just using "+st" but can imagine it will be more of a pain when slayertask is on slash commands.

**Comment by BigLazyturtle** [comment]
Can we get the autoslay button from =m/+m to also do this if we are currently not on a task?

**Comment by TastyPumPum** [comment]
Believe this has been resolved
