### ISSUE TITLE
Add Crystal shards to Prif Rooftop course

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#4087]
## 🚀 Feature Proposal

In-game, you can get Crystal shards from the Portals within the course at a 1/3~ rate. This comes out to 15 Crystal shards/hr. Should be added to the course in bot too

**Comment by LuxrayElite** [comment]
Already a PR for this awaiting merge

https://github.com/oldschoolgg/oldschoolbot/pull/3550
