### ISSUE TITLE
Ignecarus not showing in recently killed/repeat trip

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#4095]
## 🐛 Bug Report

I've been doing igne over and over and it's never in the recently killed list I have to do `/k name:Ignecarus (Solo)` each time I return. also it doesn't appear as a repeat for the repeat trip button when I do `=m` mentioned In post #4058 by @Wcp7

![Screenshot_20220701-195753_Discord.jpg](https://user-images.githubusercontent.com/90441459/176980950-975398f2-a50e-41de-a5e2-8030b183ed29.jpg)

**Comment by gc** [comment]
This is just due to how the code works, it can't really show here, only 'normal' monsters can.
