### ISSUE TITLE
[BSO 2X Loot] didn't get double from mally

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#4096]
## 🐛 Bug Report

this just seemed very odd to me.

![SmartSelect_20220701-224006_Discord.jpg](https://user-images.githubusercontent.com/90441459/176985402-a31edd6b-d798-47e0-9a6b-b9a5cd674dae.jpg)![SmartSelect_20220701-224034_Discord.jpg](https://user-images.githubusercontent.com/90441459/176985404-3263d7c8-b7a6-4e21-a69c-2a68fffc33f7.jpg)

**Comment by mylife212** [comment]
basically, if Ori works at a monster (IE Malygos), it gives double kill rolls. 10 Malygos will be 20 Malygos worth of loot. 

If Ori DOESNT work at the monster (Nex, KG etc), then its simply doubling whatever loot you got. So 5 Nex kills becomes 5 Nex kills worth of loot multiplied by 2

**Comment by TURB042O** [comment]
> basically, if Ori works at a monster (IE Malygos), it gives double kill rolls. 10 Malygos will be 20 Malygos worth of loot. 
> 
> If Ori DOESNT work at the monster (Nex, KG etc), then its simply doubling whatever loot you got. So 5 Nex kills becomes 5 Nex kills worth of loot multiplied by 2.
> 
> This is working properly, been doing malygos myself and noticed loot is definitely doubled rolls

everything else was doubled but not my lance

**Comment by mylife212** [comment]
yes, because the loot isnt being doubled - the rolls are. if it was a boss like nex or kk, then it'd roll however many kills the trip was normally and double it. For Malygos, its essentially killing 2x the amount of Malygos than the initial trip. So your 4 kill trip is actually 8 kills worth of loot rolls

**Comment by TURB042O** [comment]
> yes, because the loot isnt being doubled - the rolls are. if it was a boss like nex or kk, then it'd roll however many kills the trip was normally and double it. For Malygos, its essentially killing 2x the amount of Malygos than the initial trip. So your 4 kill trip is actually 8 kills worth of loot rolls

damn that should be explained somewhere for everyone because that's confusing as hell and when people including me see double loot. we think exactly that and not double kills
