### ISSUE TITLE
Invention Repeat Trip Button Issue

### ISSUE THREAD

**Issue by unicornakazulrah** [oldschoolgg/oldschoolbot#4097]
## 🐛 Bug Report

the master hammer and chisel and drygore saw are doubling the material upkeep costs when you use the repeat trip button when your trip is over. Tested this in the test server with Bugz as well to confirm. 

![687296BA-B86D-4388-B85A-F148A04C5A59](https://user-images.githubusercontent.com/71468925/177021206-0d13d6a6-6eb0-4184-bb91-950ac7b4d43e.jpeg)

**Comment by unicornakazulrah** [comment]
I did some more testing and found 5 total inventions that are bugged. The master hammer and chisel, drygore saw, mecha mortar, arcane harvester, and silverhawk boots (when doing agility). All 5 of these are the same bug, charging double materials if you use the repeat trip button, currently the only way around it is to re-do the slash command every trip which a lot of people aren’t use to causing a massive loss of materials. Screenshots below. 
![620EB894-AA16-4C47-B225-6320A007E54D](https://user-images.githubusercontent.com/71468925/177335378-aaed471c-187b-4521-9c2b-48318043bcb7.jpeg)
![BDD6FB93-1208-445C-A5D3-70DAA1A94CE7](https://user-images.githubusercontent.com/71468925/177335385-868a9571-1221-4599-88fc-386937742771.png)
![EEDE3759-280C-400C-B3BB-4167F680D808](https://user-images.githubusercontent.com/71468925/177335391-84b801d3-2a08-4459-b177-0480c39f5c04.png)
![65192A13-A908-4C91-8FD1-3E05B9D723B5](https://user-images.githubusercontent.com/71468925/177335395-871a616f-55e0-4d3a-b5e6-c1c868e8003a.png)
![CA5C54F0-4D7F-44B5-A035-F2B12AC76CD8](https://user-images.githubusercontent.com/71468925/177335396-9307d97a-7842-4a2a-9264-43d6cf83dbdb.png)
![18F371DD-2218-47E7-A247-56AE425FF805](https://user-images.githubusercontent.com/71468925/177335403-289f7f82-8316-4ac9-89c1-6bcdece3c394.png)
![ED8DA7C7-A2D0-4D50-A903-03BDAC28AF70](https://user-images.githubusercontent.com/71468925/177335407-f243713c-1457-4f2f-a51a-2beaea452584.png)

**Comment by gc** [comment]
Fixed in next update
