### ISSUE TITLE
[BSO | Invention] add Dwarven Gauntlets to disassembles 

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#4098]
## 🚀 Feature Proposal

all the dwarven items are accounted for (I think) but not dwarven gauntlets

![SmartSelect_20220702-235400_Word.jpg](https://user-images.githubusercontent.com/90441459/177025302-aefe3f4b-0f35-4f18-ae8c-63b56a109c4e.jpg)

**Comment by gc** [comment]
Done in next update
