### ISSUE TITLE
[BSO] add confirmation to clue buttons in =m

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#4099]
## 🚀 Feature Proposal

so my minion is currently on a hour long trip without clue hunter on and without a zippy equipped, because on my phone I typed =m and my keyboard went away and my thumb tapped on grandmaster button accidently and presto... im wasting clues 😢 

please add a `do you want to really do this` confirmation message to clue buttons. thank you.

> on a different subject: ~~is there supposed to be 4 or 5 confirmations for equipping gear to wildy set? I remember there was a warning confirmation but never multiple in a row.~~

**Comment by gc** [comment]
I don't agree (or imagine many others agreeing) that doing clues requires a confirmation.
