### ISSUE TITLE
[BSO] Allow giveaways to work while minion busy again

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#4103]
## 🚀 Feature Proposal

![SmartSelect_20220703-180119_Discord.jpg](https://user-images.githubusercontent.com/90441459/177060223-aa9028f9-b64f-4f36-839d-8e9af8d2163b.jpg)
 ;(

**Comment by TURB042O** [comment]
bump

**Comment by gc** [comment]
Done in next update
