### ISSUE TITLE
BSO sell/sacrifice bug

### ISSUE THREAD

**Issue by ahmalla** [oldschoolgg/oldschoolbot#414]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

Unable to sell or sacrifice 3a gear to bot.

**Comment by Alexsuperfly** [comment]
manually pass the quantity to the command, `3` is being picked up as the quantity because its first character, throwing off the rest of the command parsing

**Comment by ahmalla** [comment]
and how dp i manually pass the quantity to the command
________________________________

**Comment by Alexsuperfly** [comment]
`+command <qty> <itemName>`

**Comment by ahmalla** [comment]
Ooo ok
Ty!

Sent from my iPhone

On Jul 21, 2020, at 9:01 AM, Alexsuperfly <notifications@github.com> wrote:

﻿

+command <qty> <itemName>
