### ISSUE TITLE
Repeating Cast Spell 

### ISSUE THREAD

**Issue by KidSwamp** [oldschoolgg/oldschoolbot#4148]
When using cast spell repeat button, come back saying need to use slash commands text. 
![Screenshot_20220710-032803_Discord](https://user-images.githubusercontent.com/92361063/178137533-92e47d69-8fd9-4737-96ff-326d1218f356.jpg)

**Comment by TastyPumPum** [comment]
The fix is live on osb and will be on bso in due course #4126
