### ISSUE TITLE
Ava's Devices with Quest Point requirements

### ISSUE THREAD

**Issue by serahUIM** [oldschoolgg/oldschoolbot#416]
Basically adding Ava's Attractor, Accumulator and Assembler, each requiring a requisite number of QP (Assembler obviously requiring the 200 for Vorkath, as well as its head as an ingredient for its creation). Assembler could also be a boss kc boosting item

**Comment by osrsolympus** [comment]
Both the Attractor and Assembler exist via the +create command. The Assembler requires 205 QP (Because after DS II you get 5 QP for completing it) and the vorkath’s head.
