### ISSUE TITLE
Scythe of vitur

### ISSUE THREAD

**Issue by ahmalla** [oldschoolgg/oldschoolbot#417]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
I got a scythe of vitur from mystery box and it shows up in text when I do the =b —text command but when I search using “=b scythe of vitur” nothing comes up.

**Comment by ahmalla** [comment]
I should also add its value upon coming out of box was 0

**Comment by jamosaur** [comment]
BSO mystery boxes can  reward you with any item in the game, including placeholder and duplicate items which have no value

**Comment by ahmalla** [comment]
I’m assuming it’s because it’s a charged scythe, which cant be traded and has no value ... but it should show up when I do =b scythe of vitur

**Comment by jamosaur** [comment]
> I’m assuming it’s because it’s a charged scythe, which cant be traded and has no value ... but it should show up when I do =b scythe of vitur

not entirely, it will match the first item ID of the scythe and display that, rather than displaying all of the items with that name iirc

**Comment by ahmalla** [comment]
Oo I see ... so what do you think it is? Just a placeholder? Does the transparent thing I mentioned make sense ?

**Comment by gc** [comment]
This is just a matter of the fact of mystery boxes giving ANY random item, you'll occasionally get "bugged" items that aren't the real item version.
