### ISSUE TITLE
Dragonfire shield & Dragonfire Ward in BSO glitched ?

### ISSUE THREAD

**Issue by richybugray** [oldschoolgg/oldschoolbot#418]
Hi there,

It seems that the skeletal visage, draconic visage are trade able in BSO, butonce i turned it into a DFW or DFS it cant be traded, however in we can trade both versions in OSB.

Any change this could be fixed, so i can help people make thier visages?

Thanks incase,

Greetings Richy Ray

**Comment by Lajnux** [comment]
resolved
