### ISSUE TITLE
Bso mystery boxes are glitched

### ISSUE THREAD

**Issue by ordinaryId** [oldschoolgg/oldschoolbot#420]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

Bso mystery boxes are glitched.
Any word on when they will be fixed?

I have 2 runecraft capes, 1 saradomin robe top, and graceful Cape that ive gotten outta the box.
 When I search for it through b= (insert name) or trade it or equip. It claims I don't have the item.

**Comment by BIRDIE13** [comment]
![012046cd7b6ec5be4c64b3038ac0d9d0](https://user-images.githubusercontent.com/37814738/88678836-284b3500-d0ef-11ea-9bce-7e6650f3c296.png)

**Comment by gc** [comment]
This kind of weird behaviour is expected because BSO gives (or used to) completely random items out of the entire game, which can include weird items that might do something like this.
