### ISSUE TITLE
Get someone competent to work on slayer, don't let him massacre my previous work 

### ISSUE THREAD

**Issue by wyattos** [oldschoolgg/oldschoolbot#421]
Reading all of the changes he's tried making to my pr its clear he hasn't read the code. https://cdn.discordapp.com/attachments/686054078815535113/735682409202188338/unknown.png You sure about this? Maybe actually read the code, and use this cool feature called "search" because all the shit you've changed has worked, I've explained how it works, and if I didn't originally know how it should work we discussed it and agreed upon it.

P.S. if you add revenants without a death system (like your code suggests you're trying to), I'll make sure to abuse it and get a lot of free gp from it.

**Comment by gc** [comment]
Stop being childish. If you do this again I will remove your access to this repo.
