### ISSUE TITLE
Bot thinks I don't have items that I have contained in a set

### ISSUE THREAD

**Issue by belindaaa** [oldschoolgg/oldschoolbot#422]
## 🐛 Bug Report
https://i.gyazo.com/9fb088a7de39fe9ffa4cd6cc64b05a9f.png

https://i.gyazo.com/ec14cc4634c12934720a08d61e3f0d82.png

**Comment by gc** [comment]
If they're in a set, then you don't "have" those items in the set, you have the set item, so you need to unpack it.
