### ISSUE TITLE
Combat achievements for OSB

### ISSUE THREAD

**Issue by Lewis7777** [oldschoolgg/oldschoolbot#4234]
## 🚀 Feature Proposal

Just an idea that I think could be kinda cool and fun.
(I'm unsure how feasible this is due to the bot having a limited amount of slash commands available)

Combat achievements on OSB 
![mqdefault](https://user-images.githubusercontent.com/109689109/180452672-b9479b31-96d1-4cdc-a32c-74e7f66a8c20.jpg)

--How it would work--

You could send your minion to kill a specific boss and try and complete x combat achievement task.

Combat achievements could be for all bosses and all raids, for example;
completing the perfect tob task could require high kc and max boost score and have a very low success rate? you could include minion learning so that your minion gets good at certain tasks allowing you to help out other people in the community complete the group tasks.

There could also be tasks that are just having a certain kc on a boss, e.g;
Grotesque Guardians | Grotesque Guardians Veteran | Kill the Grotesque Guardians 1000 times.

--Rewards--

rewards would include the slayer helms to flex as cosmetics
![Sh5MMaT](https://user-images.githubusercontent.com/109689109/180452456-e14a73e3-1b0c-48ff-a79a-6e3cedb99402.png)
other rewards could include;
kill per hour/speed boosts at certain bosses/raids/inferno/jad
reduced food/supply usage at bosses/raids/inferno/jad
potentially more rewards if anyone has any other ideas.

**Comment by Lewis7777** [comment]
Could be for bso too, I don't play that so unsure.

**Comment by Lajnux** [comment]
I love the idea of combat achievements, a first step if we want it to be similar to OSRS would be to change our current combat system tho. That way proper RNG and kill times for monsters can be achieved along with any specific item tasks. Like killing a monster with just fists etc. 
Without it, a lot of assumptions would have to be coded.
