### ISSUE TITLE
Harvest Bush Patches

### ISSUE THREAD

**Issue by ironman1017** [oldschoolgg/oldschoolbot#4235]
## 🚀 Feature Proposal

Currently when picking berries off a bush from a bush patch you remove the bush and replant a seed.

In game, you're able to leave the fully grown bush there and come back to it later to pick more berries instead of replanting the bush. It would be helpful if there was an option to only harvest the berries from a bush instead of replanting the entire bush.

I know that you are able to collect white berries and jangerberries, but harvesting a bush patch is much faster in comparison. 

This could also be added to fruit tree patches.

**Comment by TastyPumPum** [comment]
Duplicate #1125
