### ISSUE TITLE
Add Barbarian Mixes

### ISSUE THREAD

**Issue by ironman1017** [oldschoolgg/oldschoolbot#4254]
## 🚀 Feature Proposal

https://oldschool.runescape.wiki/w/Barbarian_Training#Enhancing_potions

Players can cut leaping salmon and leaping trout to obtain roe, and can cut leaping sturgeon to obtain caviar. Roe/caviar can be used with a 2-dose potion from the list in the link above to create a mix.

Cutting salmon and trout for roe grants 10 cooking xp, cutting sturgeon for caviar grants 15 cooking xp.

Cutting and mixing potions can both be comfortably done at a rate of ~5.5k cuts/mixes an hour.

**Comment by LuxrayElite** [comment]
Added with #4741
