### ISSUE TITLE
Fix Rocky chance on pyramid plunder

### ISSUE THREAD

**Issue by Arodab** [oldschoolgg/oldschoolbot#4291]
Delete this if I misunderstood the code, but it seems like the Rocky chance is just the base chance, without the lvl scaling. 
![image](https://user-images.githubusercontent.com/79532596/182503348-4ec1c9ad-a78b-4dec-9d5e-3208c1e5b716.png)
![image](https://user-images.githubusercontent.com/79532596/182504046-3042cd1c-9071-4228-8400-99cc2e56e5ff.png)

 
For most things, the difference is negligible, but when the base chance is this low due to very few rolls/hr, it makes a huge difference. Farming is an example, and it scales with lvl on the bot, so I don't see why Rocky should't 
![image](https://user-images.githubusercontent.com/79532596/182503674-146c6891-5198-41c2-a322-1a51667a9307.png)

**Comment by Lajnux** [comment]
#3977 resolves this issue with Skilling pets all instances.
