### ISSUE TITLE
Allow users to use /k for show_info: true while busy

### ISSUE THREAD

**Issue by BigLazyturtle** [oldschoolgg/oldschoolbot#4311]
## 🚀 Feature Proposal

Title says it all, make sure it only works if selected as true.

![image](https://user-images.githubusercontent.com/105060609/183324698-d1ef9a67-f95e-410d-a929-35f2e35ed74f.png)

![image](https://user-images.githubusercontent.com/105060609/183324729-bb32ebe9-cbcb-4e01-b47a-d1806bd812de.png)

**Comment by gc** [comment]
Done
