### ISSUE TITLE
Monster Info & Recently Killed list

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#4328]
## 🐛 Bug Report

Moktang doesn't appear in the recently killed list doing /k & so far trying to get monster info on Moktang and Igne (mass & solo) says not valid monster 

![SmartSelect_20220812-015910_LOP.jpg](https://user-images.githubusercontent.com/90441459/184301825-9d175839-6a72-44d5-9de3-98211917ae31.jpg)
![SmartSelect_20220812-015922_LOP.jpg](https://user-images.githubusercontent.com/90441459/184301854-0ff1311b-ace9-44f0-a8e3-514bfe5fd6aa.jpg)
![SmartSelect_20220812-015939_LOP.jpg](https://user-images.githubusercontent.com/90441459/184301872-06c80bf7-f594-400e-9baf-a2397e95386e.jpg)
![SmartSelect_20220812-020134_LOP.jpg](https://user-images.githubusercontent.com/90441459/184301881-e16f36fc-ccda-4c22-858e-8e0a54a7f847.jpg)
![Screenshot_20220812-020328_Discord.jpg](https://user-images.githubusercontent.com/90441459/184302062-df765fb8-b41e-4a23-8050-07ae9552d473.jpg)

**Comment by LuxrayElite** [comment]
Recently killed seem to be tied exclusively to slayer tasks, I did a week of guards without it being recently killed. (OSB)
