### ISSUE TITLE
Feature proposal - Allowing more skills to be flexible with repeated trips

### ISSUE THREAD

**Issue by bowiRS** [oldschoolgg/oldschoolbot#4342]
Currently when you train herblore and a trip finishes, you can choose to repeat the trip even when you do not have enough materials to repeat the last trip and the game will just let you do a shorter trip with whatever materials you have. 

Not all skills do this, I know for sure cooking and fletching don’t and it would be nice if all skills work like herblore does. Even with these 2 skills that don’t do it there are differences. Cooking says you cannot do the trip while fletching specifically mentions how many supplies you are missing. I’d like to have consistency across all skills.

**Comment by nwjgit** [comment]
Most skills use the maxCanDo logic and will default to the max your minion can do with repeat trip or leaving quantity blank. Format is something that is becoming more and more uniform over time.
