### ISSUE TITLE
Mix command bug

### ISSUE THREAD

**Issue by Carrotthy** [oldschoolgg/oldschoolbot#4347]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
Using the new mix command 
"/mix name:Marrentill Zahur:True" leads to an un doable amount.
![Screenshot_2022-08-16-15-52-38-80_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/82282320/184884970-57730afc-fe99-4d24-b2a3-4f6c66e8285a.jpg)

**Comment by TastyPumPum** [comment]
Fixed in #4352
