### ISSUE TITLE
Make bso not appear on osb channels. and vice versa unless needed for places like in poll.

### ISSUE THREAD

**Issue by badgehunter** [oldschoolgg/oldschoolbot#4349]
## 🚀 Feature Proposal

Currently if you use Bso on #bot-channel-bso in / commands, osb doesn't appear at all. but if you use osb on #bot-channel both of those bots appear, despite you cant use bso on #bot-channel without  'Ban Members' perm.

**Comment by osrsjobbo** [comment]
This is a server configuration, rather than one to be defined in code on this repo. In addition, the described issue no longer occurs. Suggest closing this issue.

**Comment by mylife212** [comment]
What jobbo said.
