### ISSUE TITLE
Quest Points

### ISSUE THREAD

**Issue by FidelisAnimi** [oldschoolgg/oldschoolbot#4359]
Can the quest points cap be reunlocked for ironmen? Not being able to grind zippy once you cap the quest point limit is severely limiting for zippy.

I'm not sure why this was reverted, as I know earlier this year there was an announcement that quest points wouldn't have a limit for ironmen.

**Comment by TastyPumPum** [comment]
> Can the quest points cap be reunlocked for ironmen? Not being able to grind zippy once you cap the quest point limit is severely limiting for zippy.
> 
> I'm not sure why this was reverted, as I know earlier this year there was an announcement that quest points wouldn't have a limit for ironmen.

Magna has said this is due to being able to get it at eastern ferrets now, and the only reason it was in place was due to it being impossible to get zippy on an iron without it originally.

https://discordapp.com/channels/342983479501389826/648196527294251020/946482752268681226

**Comment by mylife212** [comment]
What pum said ^
