### ISSUE TITLE
open_until giving duplicate clue milestone items

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#4369]
if you're below the clue milestone and do `open_until` you don't receive the milestone item (even if finishing total is above the milestone)

if you're above the clue milestone but haven't received one previously, and do `open_until` you receive one for each casket 

this is spamming the notifications channel 

see images below - he opened 17 with open_until and received 17 large spades.

![image](https://user-images.githubusercontent.com/76587427/185790525-9a38da06-5abd-4d4e-b200-4372e1476a71.png)

![image](https://user-images.githubusercontent.com/76587427/185790532-0bd16d34-7c32-41f5-b1ad-656663fb75eb.png)

**Comment by LuxrayElite** [comment]
This (notification spam) has been an issue pre-slash and open_until, for example, if you sac a reward milestone, the next clue gives you the item and pushes a notification to support server.

**Comment by LuxrayElite** [comment]
Resolved by #5232

**Comment by LuxrayElite** [comment]
Re-testing this hasnt been resolved by #5232 @gc
