### ISSUE TITLE
Baxtorian Bathhouses and Leagues

### ISSUE THREAD

**Issue by ColossalSeagull** [oldschoolgg/oldschoolbot#4379]
## 🐛 Bug Report

I completed the leagues task to finish the Baxtorian Bathhouses CL without actually completing the collection log as I have not received the pet. If this is intentional the league task should probably be reworded as finishing a collection log generally means it shows up as green and you have gotten everything. Also if it applies to any other other "finish the CL" tasks if this gets changed they should all be fixed.

![image](https://user-images.githubusercontent.com/96855950/186429691-5ba24b53-a9ef-483b-a2d4-783b92d43323.png)

**Comment by gc** [comment]
It's indeed bugged. Fixed in next update (it'll stay completed for you though). Thank you.
