### ISSUE TITLE
Grand Crystal Tree not finishing plant

### ISSUE THREAD

**Issue by Lilbourne** [oldschoolgg/oldschoolbot#4389]
Yesterday the Grand Crystal Tree wasn't ticking off for the Farm Contract.

Today, I've tried to send the trip to harvest and replant twice, both trips did not send a return message, and after checking the patches, did not harvest or replant at all.

EDIT: Also still using seeds.

**Comment by Redquaker** [comment]
Same happened to me just now. Tried twice and both trips failed to return properly.

![image](https://user-images.githubusercontent.com/59510368/187022145-85f83204-3031-4bf7-a965-4aa3132d8fb6.png)

**Comment by themrrobert** [comment]
Fixed.

Please run =b first, then you will be able to Harvest your patch.
