### ISSUE TITLE
full set boosts

### ISSUE THREAD

**Issue by moffman10** [oldschoolgg/oldschoolbot#439]
## 🚀 Feature Proposal

Describe the feature you're suggesting here, give lots of information and describe it as best you can. Please check that the feature hasn't already been suggested first, by searching the issues in this repository.
making it so that by adding a arma helm if your waring a arma chest and legs it gives you a boost so you can either kill more in the same time or reduce the time it takes to kill the bosses.
because i just feel at this point in time there is no use for a range helm unless doing fight caves

**Comment by gc** [comment]
Full set boosts for something like arma doesn't make a whole lot of sense, but - a point for wearing stuff like this is coming very soon with food requirements and speed increases from gear.
