### ISSUE TITLE
Return fraction of inputs and outputs on trip cancel

### ISSUE THREAD

**Issue by Redquaker** [oldschoolgg/oldschoolbot#4395]
## 🚀 Feature Proposal

Upon cancelling your minion's trip, you get no output items and lose all input items in order to send the trip. Not exactly realistic and this has always been a pain point for everyone.

The inferno on OSB already has fractional return of items upon death, so this sort of system could maybe be applied to other trips. Furthermore, it'd be nice if it yielded a fraction of the output items as well.

Just a few generalized example calcs:
`Time Fraction = [Time Elapsed] / [Time for Full Trip]`
`Actions Completed = FLOOR( [Actions for Full Trip] * [Time Fraction] )`

If the trip uses X items per action:
`Input Items Returned = [Input Items per Action] * ( [Actions for Full Trip] - [Actions Completed] )`

If the trip gives X items per action such as skilling:
`Output Items Returned = [Output Items per Action] * [Actions Completed]`
The same could be applied to XP as well.

When applied to /k for example, the "Actions Completed" would just define how many kills you did in that time.

I'm sure these calcs would vary depending on the type of trip since the math may be different, so these are just examples to get the idea across. I guess the refund logic would also vary case-to-case since for example, if you did the fight caves and stopped right before jad, you wouldn't have all your items left. Something similar to the inferno refund would probably be best for cases like that.

This sort of thing definitely wouldn't be possible with farm runs due to how they work, but getting the seeds and compost back (or a fraction of them) would at least be nice. Maybe there are other special cases that this system wouldn't be possible for.

**Comment by osrsolympus** [comment]
The system as it is now is intentional. This is an idle game and it's not much to ask that, should people want the convenience of stopping a trip that they've sent, they get no rewards for their impatience.

**Comment by SpaceDevz** [comment]
I do not think this should be implemented as like someone else said it is an IDLE game meaning you shouldn't even have to cancel it. 

On another note, even if you got a fraction back it wouldn't be worth enough to make it a necessary feature.

**Comment by gc** [comment]
None of the code would be able to handle this without some fairly major refactoring of each trip where this would need to work. It's possible, but not worth the effort IMO - the bot says it fairly well: your minion drops everything to quickly return to you (As a cost for cancelling, as you shouldnt be cancelling too often). If theres' things we can do to reduce the need to cancel sure.
