### ISSUE TITLE
/Trade quality of life

### ISSUE THREAD

**Issue by ghosts-are-spooky** [oldschoolgg/oldschoolbot#4396]
## 🚀 Feature Proposal

There are times where you might be copying a list of items to trade from another command, this could be a completed trade e.g.
"ghosts are spooky#1111 sold 2x Amulet of glory (t4), 1x Amulet of glory(2), 1x Amulet of glory (t3), 1x Amulet of glory(6), 1x Amulet of glory to xx in return for No items."
or if you're doing a bank text export and filtering.

As it stands, to '/trade items: x,y,z' would not allow me to copy the above message and paste in, as it handles 1 amulet of glory (t4) not 1**x** amulet of glory (t4)

It would be great if the /trade items: can handle items: "Nx Item" where N is a number, x is the letter 'x' and Item is item name.

This also applies to other items: sub-commands e.g. /sacrifice items:

**Comment by LuxrayElite** [comment]
I don't think this is a necessary feature. I understand why you'd copy someone's trade command, not their sacrifice.
You could just copy the command from the initial /trade or /sacrifice

example:
![image](https://user-images.githubusercontent.com/12814878/187068414-43feb24b-e74b-4d8f-9537-ace60aad088d.png)

**Comment by ghosts-are-spooky** [comment]
@LuxrayElite I was doing bank searches and trying to sacrifice from text lists. understood on being able to copy from commands, but it would just be a nice QoL if easy to parse.

**Comment by gc** [comment]
Done in next udpate
