### ISSUE TITLE
if you do tokkulshop trip, it doesn't add the item obtained from it to collection log.

### ISSUE THREAD

**Issue by badgehunter** [oldschoolgg/oldschoolbot#4398]
## 🐛 Bug Report

tokkulshop trip does not trigger the items being collected for sake of collection log. in the above on you can see me obtaining the obsidian platebody from tokkulshop trip. And at bottom one there is no obsidian platebody in collection log.

![Untitled](https://user-images.githubusercontent.com/31507359/187276128-c4acc818-eee2-4957-b96c-65a86f935808.png)

**Comment by LuxrayElite** [comment]
Collection log is linked to tzhaar monsters rather than the shop.

Tzhaar-ket drop the item

**Comment by mylife212** [comment]
This is intentional as the Tzhaar shop in-game doesn't add to your CL either.
