### ISSUE TITLE
Need defer reply on /sacrifice & /trade

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#4400]
## 🐛 Bug Report

Basically anywhere the Not sacrificed filter is used you need to defer the reply due to wait times

prior example: https://github.com/oldschoolgg/oldschoolbot/issues/3684 (bank)
fixed this way: https://github.com/oldschoolgg/oldschoolbot/pull/3854

**Comment by gc** [comment]
Done in next update
