### ISSUE TITLE
Let us equip/unequip multiple items at once

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#4402]
## 🚀 Feature Proposal

It is VERY tedious needing to equip items one by one in slash commands, no reason to not allow us to do multiple items in 1 go.

**Comment by TastyPumPum** [comment]
Pr #4164 deals with this, but would be good if that pr could get a review or merged soon

**Comment by mylife212** [comment]
The pr that Pum mentioned is being merged
