### ISSUE TITLE
"/raid tob check" does not work while minion is busy

### ISSUE THREAD

**Issue by Redquaker** [oldschoolgg/oldschoolbot#4412]
## 🐛 Bug Report

Cannot check if you're ready to do ToB if your minion is busy. Doesn't seem like there should be any reason to lock out this command while busy.

![image](https://user-images.githubusercontent.com/59510368/187963569-50e3b0b9-0733-4b3c-a1d9-59c8d69ca490.png)

**Comment by gc** [comment]
Done in next update
