### ISSUE TITLE
Rename the "/BSOminigame" commands to "/CustomMinigames"

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#4428]
## 🐛 Bug Report

Ever since /bs became a command, it also brings up the /**bs**ominigames due to sharing 2 letters. This makes it nearly impossible to see the /bs command. Changing the name to customminigames will solve this issue and make /bs much more user-friendly.

While an alternative solution exists in changing /bs > /banksearch, the convenience of typing 2 letters for the command is incredible. Full name would ruin that.

Image of what /bs currently brings up: 
![image](https://user-images.githubusercontent.com/63373565/188364162-354d64f0-4572-48aa-8387-2ea925f28189.png)

**Comment by gc** [comment]
I think this needs to be polled.
