### ISSUE TITLE
7 is more than 1

### ISSUE THREAD

**Issue by TitanGH** [oldschoolgg/oldschoolbot#4441]
## 🐛 Bug Report
![A8B27C8F-A085-4BF4-92A0-60A29B9E030C](https://user-images.githubusercontent.com/92953146/189465802-7fff47a0-ca39-40c6-8b58-bc640baa2163.jpeg)

**Comment by LuxrayElite** [comment]
Zalcano never used to handle a quantity input, when it was migrated to /k it just calls the old command ignoring the additional inputs of the command
