### ISSUE TITLE
Remove ping - Mass nightmare

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#4442]
## 🚀 Feature Proposal

Due to mass nightmare using the prior party maker and massing system it pings on sending a trip (or on a trip failing to start which is impossible now)

now we can no longer mass(with other people) it doesn't need to ping on a successful trip send:

![image](https://user-images.githubusercontent.com/12814878/189477793-102117ee-650e-4372-a5ee-6a3e481eb1c9.png)

**Comment by gc** [comment]
Fixed in next update
