### ISSUE TITLE
Doubleloot

### ISSUE THREAD

**Issue by ahmalla** [oldschoolgg/oldschoolbot#4444]
doubleloot ping not working.

robochimp seems to have a doubleloot ping but doesn’t add when using / command. Skyra doubleloot role is added when using .roles doubleloot but doesn’t send out the ping when a token is used or a t4/t5 uses perk. 

## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

**Comment by themrrobert** [comment]
Known issue, fixed in repository.
