### ISSUE TITLE
Birdhouse wait time has increased to two hours? 

### ISSUE THREAD

**Issue by S-h-a-d-a-x** [oldschoolgg/oldschoolbot#4477]
## 🐛 Bug Report

![bhrun](https://user-images.githubusercontent.com/110609319/191385896-9b1cab7f-f99d-4cc1-89f0-5cd67dfd6e69.png)

Started happening around 8pm GMT yesterday (20/09), not sure if its related but it coincidentally coincided with the Bot returning .jpg files after finishing a trip or running a command.

**Comment by Lajnux** [comment]
![image](https://user-images.githubusercontent.com/68188574/191453432-4e153303-efd4-4d40-9088-da8da71bf86b.png)

it just shows the wrong `ready in X hours`. still 50 min as far as the actual time says when it's supposed to be done.
