### ISSUE TITLE
BSO - Command to check double loot timer

### ISSUE THREAD

**Issue by Redquaker** [oldschoolgg/oldschoolbot#4479]
## 🚀 Feature Proposal

Since the swap to slash commands, there is no longer a command to check the double loot timer on BSO. Previously, this command was `=rp doubletime`. The timer that's listed on the bot's profile is only updated infrequently and cannot be relied upon.

Bringing back this command as a slash command would be nice for QoL especially since double loot is happening much more often now.

**Comment by TURB042O** [comment]
@Redquaker when double loot is active it will say in the status of the bot in the member list.

where it says `/help` will become the remaining time.

**Comment by TURB042O** [comment]
> @Redquaker when double loot is active it will say in the status of the bot in the member list.
> 
> where it says `Playing /help` will become the remaining time.
> 
> 

![20220923_135423.jpg](https://user-images.githubusercontent.com/90441459/192037621-e3f16ffb-b02c-4cd7-bfe5-881f7f0c790d.jpg)
above is the view from the member list

![20220923_135444.png](https://user-images.githubusercontent.com/90441459/192037719-1925ae18-559a-41dd-b50b-f2d74da697f6.png)
above is if you tap on the bot and view its profile.


where I highlighted yellow will say double loot with a timer.

**Comment by Redquaker** [comment]
I'm aware of the timer on the BSO profile, but as I mentioned in my original post, it's updated very infrequently. It could still say "20 minutes remaining" or whatever even though there are 5 seconds remaining or even after double loot is over.

**Comment by TURB042O** [comment]
> I'm aware of the timer on the BSO profile, but as I mentioned in my original post, it's updated very infrequently. It could still say "20 minutes remaining" or whatever even though there are 5 seconds remaining or even after double loot is over.

my bad yeah you're right. I notice that today. so I had to go off of the message gpRollMaster sent me as when it started. 

I hereby bump this post in hopes for a / command 👍🏻

**Comment by Redquaker** [comment]
Closing since this has been added via `@BSO cd`.
