### ISSUE TITLE
Different Gear Setup for Venenatis

### ISSUE THREAD

**Issue by dontkillspwn** [oldschoolgg/oldschoolbot#448]
## 🚀 Feature Proposal

Can you add another gear setup other than full verac’s for Venenatis that is ranged and can be utilized in the safe spot. For example, full black dragon hide with a toxic blowpipe or armadyl crossbow could be a ranged setup. The safe spot being referenced does exist and is viable as shown in this video:
[Venenatis Safespot](https://www.youtube.com/watch?v=PoVBIIOByn8&feature=youtu.be&t=386) 
Please consider adding these changes as they would create more variety and be more emblematic of the way Old School Runescape is conducive to many approaches for engaging with content.

**Comment by nwjgit** [comment]
This has been addressed.
