### ISSUE TITLE
Herblore mixables error

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#4482]
## 🐛 Bug Report

Certain /mix options aren't valid under the listed name.

Example: Nihil dust is listed however only Nihil shard and Nihil are valid options to produce the dust.

Example 2: Cadantine blood potion (unf) is listed but invalid, cadantine blood potion is valid

Unsure if there are any others.

**Comment by ghosts-are-spooky** [comment]
Nihil dust looks to be working fine, Cadantine has an issue which I've fixed (not live). Is there anything else? @LuxrayElite

**Comment by LuxrayElite** [comment]
> Nihil dust looks to be working fine, Cadantine has an issue which I've fixed (not live). Is there anything else? @LuxrayElite
Doesnt seem to be working fine for me 👀 
![image](https://user-images.githubusercontent.com/12814878/193149236-7b8a474c-525f-4f31-9e8e-9142e4c16bb2.png)
![image](https://user-images.githubusercontent.com/12814878/193149303-00022b9a-52a8-4eff-9d37-6b7d25667d8d.png)

Havent encountered any others AFAIK

**Comment by ghosts-are-spooky** [comment]
My bad - just checked and it was working on BSO branch but not master, updating now
