### ISSUE TITLE
No lvl 99 message

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#4485]
## 🐛 Bug Report

Managed to achieve 99 hunter on a bh run however it wasn't mentioned in the return trip

Unsure if this is a repeatable error :)

Trip message:
![image](https://user-images.githubusercontent.com/12814878/191843294-bec1269c-f57c-4246-9dcb-5a482ef7e3c1.png)

Server notification:
![image](https://user-images.githubusercontent.com/12814878/191843229-c6fae105-0e59-4314-82d9-425a9f3e52eb.png)

**Comment by LuxrayElite** [comment]
Also multiple users hit 99 farming without a level up message :(

Seems to be a global thing across skills

**Comment by Lajnux** [comment]
merging #4631 resolves this
