### ISSUE TITLE
OSB is giving constant "Application did not respond" errors 

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#4486]
## 🐛 Bug Report

Title. Began a day or so ago, and it doesn't seem to be a discord issue as BSO works fine and discordstatus.com has no issues reported. Very annoying bug and should be looked into ASAP

**Comment by Ktownstoner** [comment]
100% agree I don't think it's discord either, also it used to send trips even though it failed but doesn't even send trips anymore

**Comment by TURB042O** [comment]
bso has been doing this too.

but most the time the command is sent we just see that error and not the actual command successfully being sent

**Comment by mylife212** [comment]
Haven't seen any reports of this recently, so going to close
