### ISSUE TITLE
[Suggestion][OSB] Change sacrifice role on discord to accommodate top Ironman

### ISSUE THREAD

**Issue by Jonesn4Jonesy** [oldschoolgg/oldschoolbot#4489]
## 🚀 Feature Proposal

Currently the Top Sacrificer role is given to the top 3 gp sacrificers and top 1 unique sacrificer. My suggestion is to extend the 1 unique sacrificer to be 1 normal user and 1 ironman user. Its close to impossible for ironmen to compete for this role given that normal users can buy and sacrifice items. 

Side note: I believe there is also alot of support for people wanting this same setup for other roles such as collector, top skiller, etc.

**Comment by gc** [comment]
Done in next update
