### ISSUE TITLE
You Cannot use a command right now

### ISSUE THREAD

**Issue by mljn3** [oldschoolgg/oldschoolbot#4490]
## 🐛 Bug Report

Currently, I am unable to use the bot right now as it believes my bot is busy.

I believe the bot lagged while i was attempting to trade with someone and its stuck on that commands.

the trade window has closed and cannot be seen anymore

**Comment by mljn3** [comment]
Just to say, i can still interact with the bot E.G use claim daily function

**Comment by gc** [comment]
We think we fixed this now. Reopen if its still an issue
