### ISSUE TITLE
Slayer isn't working

### ISSUE THREAD

**Issue by Lajnux** [oldschoolgg/oldschoolbot#4498]
## 🐛 Bug Report
Doing slayer tasks dosen't send out any trip anymore, it dosen't return any error message and when manually trying to send out the trip it just errors, check image below.
![image](https://user-images.githubusercontent.com/68188574/192135223-516839ca-4f1d-4648-b100-0090cfe3bb52.png)

**Comment by gc** [comment]
I believe this is fixed now, re-open if not.
