### ISSUE TITLE
Patron buttons improvement

### ISSUE THREAD

**Issue by ghosts-are-spooky** [oldschoolgg/oldschoolbot#4499]
## 🚀 Feature Proposal

Add existing buttons to new locations:
Auto farming contract: 
After harvest that shows completed contract through auto farming contract.
After open seed packs and getting new contract through auto farm contract.
These are because you typically do multiple 'actions' when doing runs, and can often chain multiple contracts.

Repeat trip:
After birdhouse run 

Currently you can @bot do a BH run, but then need to find the previous message to send your past trip

**Comment by LuxrayElite** [comment]
Repeat button is generally on all trip related return messages now

Auto contract is on majority of trips returned if not toggled off, can open seed pack from the same button
 #4920 #4620
