### ISSUE TITLE
Command to check items kept on death in wilderness

### ISSUE THREAD

**Issue by Redquaker** [oldschoolgg/oldschoolbot#4509]
## 🚀 Feature Proposal

There used to be a command to check items kept on death at revs, but this was removed in the slash command migration. Having this functionality again would be great for QoL and help people that haven't done revs yet in making a gear setup.

**Comment by Redquaker** [comment]
With the wilderness changes recently, and eventually wildy slayer, it's ever more relevant that people should have a method of easily checking what items are kept upon death.

Listing the 1/300 chance of being smited somewhere would probably be beneficial as well (maybe just on the trip send?). From what I can tell, this 1/300 is the same chance for bosses and revs (or 1/20 without prayer potions at revs). Knowing what the +1 item is would be pretty nice as well.

**Comment by nwjgit** [comment]
/gear view setup:Lost On Wildy Death Now handles this.
