### ISSUE TITLE
Shooting starts - Trekking

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#4510]
## 🐛 Bug Report

Currently, shooting stars have temple trekking as an excluded activity where it's impossible to get a spawn, however, both Canifis and Burgh de Rott have shooting star spawn locations.

Both are located next to a bank and would be logical to be included even if not the most popular minigame in the bot

Spawns on the world map:
![image](https://user-images.githubusercontent.com/12814878/192888718-ae3274aa-00c7-4a3f-978a-f13eb51fdae4.png)

**Comment by gc** [comment]
Fixed
