### ISSUE TITLE
Bot Dicing Glitch

### ISSUE THREAD

**Issue by Wedh-OSB** [oldschoolgg/oldschoolbot#453]
![D2D129C0-7BBF-4322-AC73-FF1630B7F9A0](https://user-images.githubusercontent.com/69096022/89113289-e4349900-d43c-11ea-89d7-80e0dd18e447.png)
![30FD4D70-62B9-41C8-A405-3296DCC6ADA4](https://user-images.githubusercontent.com/69096022/89113291-e565c600-d43c-11ea-92ac-647621c0ba98.png)

## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
 
I diced 40m and it lagged a bit and diced my whole cash stack..

**Comment by Lajnux** [comment]
Not a bug, there is a chance in BSO when dicing that whole cash stack gets shoved.
