### ISSUE TITLE
Fix repeat task buttons for slayer

### ISSUE THREAD

**Issue by BigLazyturtle** [oldschoolgg/oldschoolbot#4531]
## 🐛 Bug Report

Slayer repeat trip attempts to repeat killing the same monster instead of repeating the slayer task that was done.  So if a user uses slayer autoslay it will repeat that command instead keeping the user selections from the previous. (Affects osb & bso)
![image](https://user-images.githubusercontent.com/105060609/193380066-d355f8ae-96bd-46f9-9a7f-bcfefc7dfa5a.png)

**Comment by osrsjobbo** [comment]
I'm going to close this. Since this issue was opened, a 'New Slayer Task' button got added to the trip finish for slayer tasks which I think is a good resolve. 

![image](https://user-images.githubusercontent.com/123830708/217386879-0ce68918-920f-4065-9277-4dc5513110e9.png)
