### ISSUE TITLE
Add Wilderness Slayer / Krystilia as slayer master

### ISSUE THREAD

**Issue by Redquaker** [oldschoolgg/oldschoolbot#4533]
## 🚀 Feature Proposal

Title. This would allow for the acquisition of larran's keys, dagon'hai, slayer's enchantment + slayer's staff (e).

**Comment by nwjgit** [comment]
This is being worked on: https://github.com/oldschoolgg/oldschoolbot/pull/5426

**Comment by nwjgit** [comment]
added with https://github.com/oldschoolgg/oldschoolbot/pull/5426
