### ISSUE TITLE
Leagues Task Reverted

### ISSUE THREAD

**Issue by ColossalSeagull** [oldschoolgg/oldschoolbot#4534]
I unlocked all the slayer unlocks to complete the leagues task. Confirmed that I had completed it and then relocked the stuff that I didn't actually want. I noticed today that it has reverted my completion of the task and now says its uncompleted. Do you have to keep all the stuff unlocked? If so can that be changed? Or was it a bug to revert the completion? If so is there anyway to get it completed again without having to spend a ton of points to re-unlock everything?

![image](https://user-images.githubusercontent.com/96855950/193432217-88f44c4a-05b2-4620-a0e8-3656bc9a4302.png)
![image](https://user-images.githubusercontent.com/96855950/193432241-5505d96d-1e84-4073-b418-fdc8949a560d.png)

**Comment by gc** [comment]
Sometimes we add more/new requirements to existing tasks, at which point, there'll be a mixture of whether or not you have already completed the task. You have finished the task and cant finish it again, but you technically dont meet the requirements to finish it.
