### ISSUE TITLE
Mypets - slash equivalent 

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#4539]
## 🐛 Bug Report

On obtaining a pet it still tells you to do +mypets instead of the slash equivalent

![Screenshot_20221002_173044.jpg](https://user-images.githubusercontent.com/12814878/193465247-08636000-ec1c-41ef-bbc6-15d3c71f6bf1.jpg)

**Comment by gc** [comment]
Fixed
