### ISSUE TITLE
Dragonfire Ward bugged?

### ISSUE THREAD

**Issue by dylnwood** [oldschoolgg/oldschoolbot#454]
## 🐛 Bug Report

Dragonfire Ward appears to be generally bugged.

**Issue 1: Not appearing in bank search correctly.**

> "+b --search=Dragonfire ward" returns "That item doesnt exist."

> "+b --search=dragonfireward" returns image of DFW in the bank as intended.

**Issue 2: Not equippable**

>  "+equip [gear type] Dragonfire ward" returns "You don't have this item, so you can't equip it."

> "+equip [gear type] dragonfireward" returns "You don't have this item, so you can't equip it."

**Comment by Alexsuperfly** [comment]
fixed in #440

**Comment by dylnwood** [comment]
Still not working on my end. Being patched still?

**Comment by Alexsuperfly** [comment]
its not deployed yet

**Comment by dylnwood** [comment]
ok
