### ISSUE TITLE
Hunter success chance bso 

### ISSUE THREAD

**Issue by DarkBugz** [oldschoolgg/oldschoolbot#4543]
The level scaling for successful hunting caps at 99 instead of 120 for bso.

**Comment by gc** [comment]
This should go in #bso-vote, unless it was previously like this and therefore might be a bug.

**Comment by DarkBugz** [comment]
Fishy said when he originally coded hunter he put no such level cap so it might be new with slash commands.

**Comment by Lajnux** [comment]
> Fishy said when he originally coded hunter he put no such level cap so it might be new with slash commands.

I only said I don't remember putting such a change but then I checked back now on the old PR and I did actually add it so that hunter potion wouldn't break.
