### ISSUE TITLE
Issue with getting bonus slayer points when doing Inferno 

### ISSUE THREAD

**Issue by gpRollMaster** [oldschoolgg/oldschoolbot#4553]
prior slayer task info
You've completed **879** tasks and received **15** points; giving you a total of **1740;** return to a Slayer master.

After completion of inferno info
You've completed **880** tasks and received **15** points; giving you a total of **1755;** return to a Slayer master.

Loot: 32,880x Tokkul, 1x Infernal cape
XP: +80,000 :ranged:+35,000 :hitpoints:+25,000 :magic:You received 125,000 :slayer: XP (76k/Hr)
You made it through 100.00% of the Inferno.

Didnt miss out on a lot of points but would be nice to get this addressed as if it was the 50 tasks in a row and above its a lot more that would be lost.

**Comment by gpRollMaster** [comment]
![inferno slayer](https://user-images.githubusercontent.com/97349844/194128080-258abf70-a27e-4e1b-a273-02316918df79.png)

**Comment by ard35** [comment]
Fixed on next update
