### ISSUE TITLE
bso-vote Arcane Harvester config

### ISSUE THREAD

**Issue by ghosts-are-spooky** [oldschoolgg/oldschoolbot#4559]
## 🚀 Feature Proposal

Arcane harvester material usage is high for single seed harvests. Usage should be based on seeds used, crop types should have different weighting, build config to turn off for crop types e.g. herb - true | flower - false.

Usage should be based on quant of seeds used +14 votes
crop types should have different weighting +5 votes (not wanted enough)
Build config to turn off for crop types e.g. herb - true | flower - false +31 votes
-4 votes

**Comment by gc** [comment]
Please don't make github issues for bso-vote things, unless they are bugs, or OSB-related.
