### ISSUE TITLE
Shooting stars - no clue button

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#4563]
## 🐛 Bug Report

If you receive a clue scroll while doing a shooting star you don't get a button to do the received clue if a patron.

![Screenshot_20221009_000642.jpg](https://user-images.githubusercontent.com/12814878/194730761-0872fc21-7b49-43de-a17d-8569346d0518.jpg)

**Comment by gc** [comment]
Fixed in next update.
