### ISSUE TITLE
Incorrect error on changepet

### ISSUE THREAD

**Issue by ghosts-are-spooky** [oldschoolgg/oldschoolbot#4569]
## 🐛 Bug Report

Trying to swap a pet while on a trip the error:

You still have a pet equipped, cancelling.

It should state you can't swap pets on trip

**Comment by gc** [comment]
Is this on BSO or OSB?

**Comment by TastyPumPum** [comment]
Swapping pet mid trip works fine on osb.
I've only had this error on bso

**Comment by gc** [comment]
Should be resolved. You can re-open if not.
