### ISSUE TITLE
+gearstats mage unexpected error

### ISSUE THREAD

**Issue by Rhastae** [oldschoolgg/oldschoolbot#458]
![image](https://user-images.githubusercontent.com/26942414/89178574-d0487e80-d585-11ea-97b4-39b61d085c8d.png)

Getting a reply from Old School Bot that an unexpected error occured when trying to check my mage gear stats.

**Comment by Alexsuperfly** [comment]
what gear are you wearing in your mage set

**Comment by Lajnux** [comment]
command no longer exists, all stats is shown in +gear setup
