### ISSUE TITLE
"@bot old school b" opens page 2 never 1

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#4590]
## 🐛 Bug Report

I thought it was just me but I had someone else do it and they got same result. 

it automatically opens page 2, never 1

![Screenshot_20221012-222933_Discord.jpg](https://user-images.githubusercontent.com/90441459/195492715-36af728a-bfeb-41b6-82d6-48627e33f365.jpg)

**Comment by TastyPumPum** [comment]
#4584
