### ISSUE TITLE
--cf for drop not working

### ISSUE THREAD

**Issue by Voice-Guy** [oldschoolgg/oldschoolbot#460]
## 🐛 Bug Report

when trying to use --cf command for dropping items the bot still asks for verification
![image](https://user-images.githubusercontent.com/69152085/89183696-3b318f80-d55d-11ea-9974-55f1095890db.png)

**Comment by Lajnux** [comment]
works fine, close issue.
![image](https://user-images.githubusercontent.com/68188574/92393428-2ded5f00-f120-11ea-87bf-de3849bd3fc1.png)
