### ISSUE TITLE
[BSO] Remove mini pumpkinhead from the DC pet log and Dc pet bank filter

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#4626]
## 🚀 Feature Proposal

Title. As pumpkinhead pet is most likely not discontinued in the traditional sense (only available during 1 time period and thats it), it shouldn't be in the mentioned log/bank filter. 

Players can check if they got the mini PH pet via the Hween 2021 CL if they would like to.

**Comment by gc** [comment]
Mini pumpkinhead is discontinued
