### ISSUE TITLE
bad performance for bank filter: items not sacrificed

### ISSUE THREAD

**Issue by jesseklein** [oldschoolgg/oldschoolbot#4627]
## 🐛 Bug report

There appears to be performance issues associated with the "Not sacrificed" bank filter.  Running /bank filter:not sacrificed seems to stall the bot out for at least 30 seconds, and possibly interupt more than the command user's activity.  See chat in bso general regarding a couple attempts from me where this occurred

1st occurence (bot died alot appeared to be coincidence)
 https://discord.com/channels/342983479501389826/792691343284764693/1033238817001447467

2nd time (right before this report)
https://discord.com/channels/342983479501389826/792691343284764693/1033463288870207569

**Comment by TastyPumPum** [comment]
This should have been fixed now - https://github.com/oldschoolgg/oldschoolbot/commit/a83e9a41fb4a81c7e09a23d03e37f68f4cb2cc44

**Comment by jesseklein** [comment]
I agree, this appears to be fixed
