### ISSUE TITLE
Equipment presets

### ISSUE THREAD

**Issue by matteo4prez** [oldschoolgg/oldschoolbot#463]
My suggestion:
We should be able to get 2-3 presets each attack type so we can easily switch between gears. For example to kill corp you need z spear and certain defence stats so you could equip the correct gear and do "+equip (melee) save preset1" and to equip it later on "+equip melee preset1" this way you can easily switch between tasks like corp and  callisto Here you need veracs. Also in addition u can make it so patrons get more presets since they support the game.

**Comment by coolbop32** [comment]
we now have +gearpresets
