### ISSUE TITLE
OSRS collectionlog data and misc.

### ISSUE THREAD

**Issue by Thedyolf2** [oldschoolgg/oldschoolbot#4665]
## 🚀 Feature Proposal
Hi! 
As a long term patreon, first I'd like to mention that I greatly appreciate that the bot's still going in such glory.
Recently, RuneLite implemented !log chat commands in their Collection Log plugin, this is a plugin that grabs data from Collectionlog.net and shares it in chat. I'm familiar with the /cl command however as far as I know this only works for the minion. I would love to see an ability to share in game logs in the future through discord by use of the commands. 

Additionally, a webpage that allows you to hide all minion commands and just show the regular commands would be helpful, since a lot of commands changed when the change was made to slash-commands, and the command list seems to be very cluttered with 99% minion commands.

**Comment by TastyPumPum** [comment]
I do like the idea of the collection log, however I assume users would then have to install the third party plugin and share their data with it in order for it to work? Not sure if that's a good idea "forcing" users to do that.  

Getting a list of all the none bot commands on the website would be a great idea too though.

**Comment by Thedyolf2** [comment]
Correct, as of the moment, Jagex does not share Collectionlog data as of right now, and is not planning on it seeing how janky their hiscores are and barely able to provide proper boss hiscores. 

Collection log is indeed a 3rd party plugin that gathers data from the client and shares it with a website database, currently having over 18,000 users, and as of RL policy does require the user to explicitly consent to sharing this data. I do however understand this comes with moral and ethical questions as in promoting such a service, since if they do ever become malicious of any sort, it could be seen as been promoted. 

Alternatively, some form of export string could be generated directly from Runelite, and be imported and linked to a certain rsn on discord. This does come with multiple downsides: manual process, does need to be updated manually, someone needs to update a plugin to do so, strings could technically be manipulated and result in fake logs, etc. however does throw away any risks in terms of consent. 

Just stating some possibilities out there, as I'm not certain on what the Old School Bot's policies and intentions are, but even a possibility to manually create log images with slash commands (e.g. /cl type:cerberus pet:0 jar:0 primordial:2 pegasian:0 eternal:1 smouldering:5) would be some quality content. However, for ease of use, any way of linking in game with the discord bot could be an opportunity :)

**Comment by gc** [comment]
You should just use their discord bot. We could potentially add it to our bot, but it would be just extra stuff to maintain with our little time.
