### ISSUE TITLE
Farming level doesn’t notify when you have gained a level 

### ISSUE THREAD

**Issue by bushturky** [oldschoolgg/oldschoolbot#4669]
Simple as above, see pictures 
![C22B683C-4A4D-457C-8500-56B124856852](https://user-images.githubusercontent.com/117435025/199922145-079a033a-abdf-4
![2FAA574E-1627-4F03-BCFD-0C6796999B27](https://user-images.githubusercontent.com/117435025/199922184-f072a263-f841-432c-a5a9-bbc0636aa780.jpeg)
828-a141-7cc4acd26b25.jpeg)

![4F2AAD88-AC74-43B8-BB98-3E8399409ACE](https://user-images.githubusercontent.com/117435025/199922163-c80e561a-4658-416b-9f30-4a217ffde691.png)

**Comment by LuxrayElite** [comment]
partial dupe of #4485 but good to know its not just 99 that it isn't working with

**Comment by nwjgit** [comment]
Farming now properly shows levels ups.
