### ISSUE TITLE
ALL NEW UPDATES

### ISSUE THREAD

**Issue by EngageV2** [oldschoolgg/oldschoolbot#468]
Isnt BSO literally labeled the experimental bot

Okay well 
1. Dont delete BSO anytime soon cuz its too popular
2. Put all the updates on a test run through BSO first, because the BSO channel is so active that we can be the “beta” testers for all updates so something like the Food update doesnt happen again because BSO players will give an honest opinion.
3. I recommend having a BSO dedicated Mod, i’d nominate myself but yeah.
4. Add more BSO commands because OSB has a bunch of commands that BSO doesnt

**Comment by Lajnux** [comment]
No actual issue, Magna assigns moderators based on activity, knowledge and usefulness for the server. BSO is a experimental fun bot, not a test bot as first thought. Updates are cared about for BSO aswell as OSB. But BSO got more freedome of changes. More commands is coming to both modes whenever time and creativity flows. 

Close issue.
