### ISSUE TITLE
[Typo/Misleading] Website Commands +Open Example

### ISSUE THREAD

**Issue by fennecOS** [oldschoolgg/oldschoolbot#469]
## 🐛 Bug Report

WHERE: https://www.oldschool.gg/oldschoolbot/commands

DESC: In the Minion Commands tab, +open example says +clue command, while it IS a command, it's not specifically a Minion command, it's a "Fun" command and it is already stated in the "Fun" section. 

SOLUTION: switch where it says "+clue hard" with "+m clue hard" which is the Minion command to do a clue scroll, which is what I think was meant to be there

Relevant pictures attached

Minion:
![image](https://user-images.githubusercontent.com/69169058/89242044-f64a3f00-d5d6-11ea-87b5-438fc3507396.png)

Fun:
![image](https://user-images.githubusercontent.com/69169058/89242065-03ffc480-d5d7-11ea-914e-d58f17aa3a1e.png)

**Comment by Lajnux** [comment]
Now using a maintained wiki page. resolved.
