### ISSUE TITLE
Can't craft blood runes at GOTR

### ISSUE THREAD

**Issue by DayV-git** [oldschoolgg/oldschoolbot#4707]
in gotr when blood runes are chosen, it looks them up in runecraft file: 

https://github.com/oldschoolgg/oldschoolbot/blob/979bfd6620977d342483236e452aa2966ea486e1/src/tasks/minions/minigames/guardiansOfTheRiftActivity.ts#L112

But blood runes aren't an option there:

https://github.com/oldschoolgg/oldschoolbot/blob/master/src/lib/skilling/skills/runecraft.ts

**Comment by Lajnux** [comment]
Will solve itself when true blood rune altar is coded into the bot

**Comment by TizHub** [comment]
bump - Can we get true blood altar pls
