### ISSUE TITLE
New CL items at Revenants don't appear as purple

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#4732]
## 🐛 Bug Report

When you get a new CL slot, the item is outlined in purple to indicate so. At Revenants, this appears to have bugged out and it shows up as any other item. It definitely worked before though. 

Image of bug below (Can verify its not a dupe) 
![image](https://user-images.githubusercontent.com/63373565/202834110-7dd5720a-6a64-416b-9112-c0f2d71a80a9.png)

**Comment by themrrobert** [comment]
This is fixed by PR #4676
