### ISSUE TITLE
Remove the ping in #notifications when you complete a CL (or add opt-out)

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#4737]
## 🚀 Feature Proposal

IMO, having a ping when you finish a CL ruins the 'suspense' of a trip returning, as you'd know that if there isn't a "double ping" (Bot pinging for trip AND finishing CL in support) - that you got nothing, and vice versa - double ping = you got something good. Not to mention, those who aren't active in support may be annoyed by the occasional pings. **Its worth noting that there is no way to hide a direct ping on discord - as in removing the "1" on server icon so there is no real workaround right now.**

Just having the bot say "mylife212 finished their Cerberus log" without a ping does the job fine IMO.

That being said - there may be those who prefer the pings so I think the best option is adding something to `user config` that opts them out of the CL notification entirely.

**Comment by gc** [comment]
Done in next update
