### ISSUE TITLE
[BSO] Items not adding to cl (perm iron)

### ISSUE THREAD

**Issue by osDreamscape** [oldschoolgg/oldschoolbot#4753]
Multiple items in last 24 hrs not adding to cl after obtaining them on perm iron

![image](https://user-images.githubusercontent.com/73551894/204155619-57d59af9-ab15-4f2e-975a-ccd4b5b13b85.png)

latest was Zak, but also yew roots from farming, preventing diary completion

**Comment by gc** [comment]
Can you show an image showing you got the zak yourself?

**Comment by themrrobert** [comment]
with date+timestamp ofc

**Comment by themrrobert** [comment]
was anything else happening at the same time? Running another command / trip returning / etc?

**Comment by TastyPumPum** [comment]
![Untitled](https://user-images.githubusercontent.com/79149170/207851975-ee175ac1-ad1c-4122-afac-e20a979297b2.png)
In the discord with dream so will reply on his behalf while hes asleep

**Comment by gc** [comment]
Confirmed bug, we'll look at adding it to your CL manually. Fixed in next update.
