### ISSUE TITLE
+create Zamorakian Hasta

### ISSUE THREAD

**Issue by KrugGrunt** [oldschoolgg/oldschoolbot#476]
Kinda self explanatory, can we have Zammy Hasta added to +create? Requiring 55 fishing like it does in old school, with a tweaked buy cost like everything else in +buy. Other requirements could include 5 smithing, QP needed for Tai Bwo Wannai Trio, 15 agility etc, as is the case in old school. Our best 1 handed weapons are limited to d scim and whammer, SotD is barely better than either and with equipment bonus requirements coming it would be nice to have for allowing a shield to be worn with it.

**Comment by jamosaur** [comment]
https://github.com/oldschoolgg/oldschoolbot/pull/457

**Comment by Lajnux** [comment]
resolved #457
