### ISSUE TITLE
/data info bugs

### ISSUE THREAD

**Issue by VenyaVeritas73** [oldschoolgg/oldschoolbot#4764]
## 🐛 Bug Report

I encountered a few bugs while going through the list of commands in /data. I'm not sure if they've already been reported but I didn't find anything from the search function in the github channel in the support server.

OSB/BSO /data personal farmed crops shows global farmed crops and is empty.
OSB/BSO /data personal activity types and personal activity durations time out when the command is running.
OSB/BSO personal TOB wipes and global TOB wipes time out when the command is running.

I've included a screenshot of the bots timing out if that helps.
They're small things but I wanted to bring them up since I noticed them.

![image](https://user-images.githubusercontent.com/98783697/205784043-2f67aac2-7ca7-415e-ae9a-ee38ed549554.png)

**Comment by gc** [comment]
All these issues should be fixed in the next update.
