### ISSUE TITLE
Daily Reward

### ISSUE THREAD

**Issue by DrGr33nLungz** [oldschoolgg/oldschoolbot#478]
## 🐛 Bug Report

I did my daily today and got the question “name any monster in the wyvern cave located on fossil island” I responded “Ancient wyvern” and it said it was incorrect. Ancient wyvern are definitely found in the wyvern cave.

**Comment by DrGr33nLungz** [comment]
![250EDBE0-6DA7-4C28-BEE5-3FB6BB09C1CF](https://user-images.githubusercontent.com/69238968/89390129-ebbda180-d6cb-11ea-8826-66b79edcd565.png)
![A6F8BA10-C2DF-4BCA-9AB5-011401E3C749](https://user-images.githubusercontent.com/69238968/89390139-ef512880-d6cb-11ea-85ab-4a96eca87efc.png)

**Comment by eX-C0n** [comment]
You more than likely lagged, the bot lagged, or you replied too slow, and it didn't catch your response. It happens.
