### ISSUE TITLE
Add Revs Protection (GP SINK)

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#4793]
Add a protection option to the revs command to have a virtual clan protect you from PKers, no more deaths at revs.

Cost a few mill per trip or something, idk how much exactly but would be a good gp sink atleast - IIRC on osrs it was 150m osrs gp for a weeks protection, correct me if im wrong

would also mean people can pay to safely use revs weapons at revs without chance of being smited and losing them

**Comment by Lajnux** [comment]
I'm all for GP sinks! But where do we draw the line for the sinks? For example RC runners would be a very good GP sink, potentially sinking billions also Corp boosting, mob tagging, Blast furnace runners etc etc. And all of them are commonly used in game. (Blast furnace slight less)

**Comment by TastyPumPum** [comment]
Imo something like this definitely needs to be polled first to gauge the communities opinion on it. As Fishy said it's hard to say you can use this but then rc runners are not allowed
