### ISSUE TITLE
[OSB] Very minor issue with notifications

### ISSUE THREAD

**Issue by FatOrangeKitty** [oldschoolgg/oldschoolbot#4803]
Very minor issue with notifications. Not sure if it's happened to other CLs but just noticed this now. It also skipped the 53rd person. This image is edited also, I just condensed the list.
![image](https://user-images.githubusercontent.com/41413252/209071618-5bcc7af3-5cac-4730-bda6-7148ea4dd4a1.png)

**Comment by gc** [comment]
I made a change which should maybe fix this, you can re-open this is if it happens again
