### ISSUE TITLE
Clue Scroll Leaderboards and ease of opening

### ISSUE THREAD

**Issue by GemShop** [oldschoolgg/oldschoolbot#481]
## 🚀 Feature Proposal

Similar to how there are leaderboards for gp and kill counts I am suggesting a clue scroll leaderboard as well as being able to open multiple at a time. I have been saving up beginner and easy clue scrolls and i have roughly 800 of each at the moment in hopes that an update like this goes through. If I have to manually open each of them that is fine as long as there is a leaderboard to keep track of them.

**Comment by Lajnux** [comment]
half issue solved  #385 .
