### ISSUE TITLE
"Last sales" command

### ISSUE THREAD

**Issue by TastyPumPum** [oldschoolgg/oldschoolbot#4814]
Would be neat if we could get a last sales command which lists the last 10 or so trades of an item and what it was for. 

Could maybe make exclusions of only showing trades above 1k value, would help new players identify the prices of items.

**Comment by gc** [comment]
This has several issues:
- This has the issue of privacy (the seller/buyer would have to be anonymous)
- Many trades are not just gp for item, they are items for items, gp for items, gp and items for items, etc.
- Fake trades can be done in this setup to make items look like more than theyre worth

A G.E system, where it shows last trades in the G.E, is the only way I see this being possible.
