### ISSUE TITLE
Mahogany homes - option

### ISSUE THREAD

**Issue by Jiminy49** [oldschoolgg/oldschoolbot#4815]
## 🚀 Feature Proposal

Would it be possible to add an option to mahogany homes start to choose expert, adept etc?

It would make a big difference for ironmen, using mahog homes is many hundreds of mil cheaper than normal con, and adept vs expert is about 400-500m cheaper

would really appreciate it

**Comment by LuxrayElite** [comment]
It's been coded before but never made it in
I'm sure someone could find it and update :)

**Comment by Redquaker** [comment]
PR #3148 implemented this but was never merged. Would be a really nice one to see IMO
