### ISSUE TITLE
Holiday items having pink shirt icons

### ISSUE THREAD

**Issue by Souzer** [oldschoolgg/oldschoolbot#4826]
The following items show as a pink skirt in the bank and when equipped;

[Snow imp costume head](https://oldschool.runescape.wiki/w/Snow_imp_costume_head) 
    [Snow imp costume body](https://oldschool.runescape.wiki/w/Snow_imp_costume_body) 
    [Snow imp costume legs](https://oldschool.runescape.wiki/w/Snow_imp_costume_legs) 
    [Snow imp costume gloves](https://oldschool.runescape.wiki/w/Snow_imp_costume_gloves)
    [Snow imp costume feet](https://oldschool.runescape.wiki/w/Snow_imp_costume_feet) 
    [Snow imp costume tail](https://oldschool.runescape.wiki/w/Snow_imp_costume_tail) 
[Bulging sack](https://oldschool.runescape.wiki/w/Bulging_sack)

**Comment by gc** [comment]
Fixed in next update
