### ISSUE TITLE
"/bank filter:orikalkum-material" not working

### ISSUE THREAD

**Issue by ghost** [oldschoolgg/oldschoolbot#4836]
## 🐛 Bug Report

![20230103_171415.png](https://user-images.githubusercontent.com/90441459/210456956-de2157a0-c318-4139-a1b7-2107fdc0f0b9.png)

the only material that does not filter seems to be Orikalkum

**Comment by nwjgit** [comment]
closing this since user deleted account and a similar thread exists: https://github.com/oldschoolgg/oldschoolbot/issues/5093
