### ISSUE TITLE
Vet'ion ring of the gods drop

### ISSUE THREAD

**Issue by Joepicklebob** [oldschoolgg/oldschoolbot#484]
## 🐛 Bug Report

Looking at the all drop notifications tab on discord and searching ring of the gods only and seeing not a single ring of the gods drop for the last 2 months make me curious if the drop isn't working. I'm 830 dry of ring and most people are getting the 1/5k before ring.

**Comment by Alexsuperfly** [comment]
the scroll is 1/1k and youre just dry on the ring

**Comment by Joepicklebob** [comment]
your telling me not a single person has got the ring in the last 2 months?

**Comment by gc** [comment]
We removed wildy ring drops from notifications because they're not really spectacular
