### ISSUE TITLE
Shades of Morton - no zealot effect

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#4847]
## 🐛 Bug Report /feature request

The recently added zealot outfit doesn't have it's 5% chance to save bone/Ensouled head bonus in the bot (which stacks with chaos altar)

Don't believe this was brought up in testing.

**Comment by nwjgit** [comment]
fixed in https://github.com/oldschoolgg/oldschoolbot/pull/4862
