### ISSUE TITLE
Small suggestion (+kc dks)

### ISSUE THREAD

**Issue by Mecenary020** [oldschoolgg/oldschoolbot#485]
## 🚀 Feature Proposal

Just a small suggestion that should be easy to implement, can the command "+kc DKS" output the killcount for all 3 kings? For example: 

+kc dks
Dagannoth supreme: 151
Dagannoth prime: 5234
Dagannoth rex: 512

It doesn't seem very important but it would be nice to be able to check the three all at once without having to do the "+m kc" command which outputs a massive list of all creatures killed on the bot, and so I wouldn't have to do the kc command for each king separately.

**Comment by nwjgit** [comment]
Implemented in /cl
