### ISSUE TITLE
Gary can't be equipped

### ISSUE THREAD

**Issue by ghost** [oldschoolgg/oldschoolbot#4851]
## 🐛 Bug Report

![SmartSelect_20230107_214545_GitHub.jpg](https://user-images.githubusercontent.com/90441459/211179966-ac7576ff-1003-4be9-9265-5e8df7ac53e8.jpg)

the return gives a message as if we have picked up a pet but when attempting to `/gear pet equip:Gary` it gives the error message:

> [That's not a pet, or you do not own this pet.](https://discord.com/channels/342983479501389826/792691343284764693/1061462814499295352)
![SmartSelect_20230107_220720_GitHub.jpg](https://user-images.githubusercontent.com/90441459/211180103-6292bac3-7220-45ce-97b6-f92d9332f385.jpg)

**Comment by nwjgit** [comment]
Gary can be equipped now.
