### ISSUE TITLE
Necromancer Robe Top & Bottom icons are reversed & Vladimir Drakan legs icon missing

### ISSUE THREAD

**Issue by ghost** [oldschoolgg/oldschoolbot#4852]
## 🐛 Bug Report

![image.jpg](https://user-images.githubusercontent.com/90441459/211180602-8f8a13a3-e226-4b38-891e-232368a997da.jpg)

**Comment by nwjgit** [comment]
Adding to this, The icon for the legs dropped by Vladimir Drakan is also broken/missing. 
![collection_log_1702481837354](https://github.com/oldschoolgg/oldschoolbot/assets/69014816/6b1b9049-6067-45cf-979d-c533830aa531)
