### ISSUE TITLE
[OSB] Shades of morton - gold coffin boost

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#4855]
## 🐛 Bug Report

Currently the golden coffin isnt extending the maximum trip length

This is sending a trip with golden coffin equipped in skilling: +4m max trip length but defaults to 30m trip regardless

I would have expected this boost to atleast give +1 to shades used

Looking at the code the "bonusTime" variable is never used to influence duration/trip time
https://github.com/oldschoolgg/oldschoolbot/blob/821496ddd0f26dd4ce1ba097a9fe832a32cc7526/src/mahoji/lib/abstracted_commands/shadesOfMortonCommand.ts#L264-L270

![image](https://user-images.githubusercontent.com/12814878/211211643-f8fd100d-6b13-4132-8e9d-c12f80dab82d.png)

**Comment by TURB042O** [comment]
@TastyPumPum ![Screenshot_20230222-233853.jpg](https://user-images.githubusercontent.com/90441459/220765657-b03baa08-dca2-4c2b-a636-95cb817f37e7.jpg)

BadgeHunter just sent me this. the coffin still isn't working
