### ISSUE TITLE
Slayer task nechs w/ barrage gives double void staff reduction in time

### ISSUE THREAD

**Issue by Dawerd** [oldschoolgg/oldschoolbot#4874]
![Screenshot_2023-01-17-04-55-13-997_com discord](https://user-images.githubusercontent.com/118944501/212806830-ec70517d-31bd-4f74-92a4-a2f9a0aab6c5.jpg)
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

**Comment by TastyPumPum** [comment]
Duplicate #4750
