### ISSUE TITLE
[BSO] Can't equip Bow of Faerdhinen (c) when it is owned.

### ISSUE THREAD

**Issue by dylithian** [oldschoolgg/oldschoolbot#4885]
![image](https://user-images.githubusercontent.com/64990317/214481485-83b0a0f4-9a46-4c0f-b064-af9036da3c36.png)

Tried to equip it to the ranged preset, but it doesn't work.

Commands used:

/gear equip gear_setup:Range item:Bow of faerdhinen (c)

/bank search:faerdhinen format:text_full

**Comment by 6enny6** [comment]
check the ID of the one you have, im assuming only the regular corrupted one is equippable and not the recoloured variants

**Comment by dylithian** [comment]
I was able to equip it with the auto parameter, so it's definitely equippable. I imagine it's probably looking for the wrong ID but I'm not sure how it got equipped and had stats through the auto parameter then.

**Comment by ColossalSeagull** [comment]
Try using /bank search:bow of fae flag:show_id and using the id in the gear equip command?

**Comment by osrsjobbo** [comment]
@dylithian Please can you provide the ID as described above?

**Comment by dylithian** [comment]
@osrsjobbo This is the output from the command.

![image](https://user-images.githubusercontent.com/64990317/215366842-ca4ea87f-eda4-483a-a114-d4f52ad4410a.png)

Equipping it with the ID worked.
