### ISSUE TITLE
Add command to check points at Volcanic Mine

### ISSUE THREAD

**Issue by Redquaker** [oldschoolgg/oldschoolbot#4886]
## 🚀 Feature Proposal

Currently, there's no way to check your points balance at Volcanic Mine. Having a command that does this would be great.

**Comment by LuxrayElite** [comment]
I know whilst this isn't what is being pitched it follows a similar vein so doesn't really warrant a new suggestion thread imo.

I think there maybe a few other minigames / quirky currencies that it can be hard to check without attempting to buy an item from the associated store 

Would I be possible instead to move all points / currency into a single command that returns an embed unless one is specified.

Example /balance returns everything as an embed
/Balance option_name:gp gives purely gp as the current /gp does.

**Comment by osrsjobbo** [comment]
@LuxrayElite  I didn't want to go on a tangent and create something like your suggestion till I had feedback from somebody else that this sort of thing would be both desired and likely to merged in if I wrote it.

If you want to raise issues for minigames with missing stat commands I will take a look and implement something.

@Redquaker  I am about to open a PR which will give volcanic mine a `stats` command similar to pest control which shows both games completed and current point balance.
