### ISSUE TITLE
Incorrect Grammar/Inconsistent formatting on some food items

### ISSUE THREAD

**Issue by rwheelus** [oldschoolgg/oldschoolbot#4887]
## 🐛 Bug Report

This is related to starting a trip and having the food item used be Chili potatoes. 

Generally when you use other potatoes (e.g. Potato with Cheese), the formatting is **Removed ##x Potato with cheese** (in bold). When you use Chili Potatoes, though, it isn't bolded and it uses an apostrophe to pluralize the word potatoes (potato's).

See screenshots:
![image](https://user-images.githubusercontent.com/67128674/215157656-821578eb-cd8e-44f7-abfd-af1525b3f727.png)
![image](https://user-images.githubusercontent.com/67128674/215157719-736de833-3f83-4088-bbd9-708cb9892821.png)

Anyway, it's a small thing, but an apostrophe doesn't pluralize words and the plural of potato is "potatoes."

**Comment by TastyPumPum** [comment]
I would imagine this is due to the different type of trips rather than the different type of food

**Comment by osrsjobbo** [comment]
As @TastyPumPum suggested, this looks command specific: https://github.com/oldschoolgg/oldschoolbot/blob/master/src/mahoji/lib/abstracted_commands/wintertodtCommand.ts#L66

Will look at a PR to make wintertodt more consistent.
