### ISSUE TITLE
Add status on invention toggle command

### ISSUE THREAD

**Issue by ghosts-are-spooky** [oldschoolgg/oldschoolbot#4901]
## 🚀 Feature Proposal

User Toggle shows the current status of items, whereas user toggle_invention doesn't, this would be useful and consistent to add.

<img width="395" alt="Screenshot 2023-01-30 at 07 24 30" src="https://user-images.githubusercontent.com/10942752/215413294-cbdc2a07-79d2-4dcb-a677-5d182c8de7ed.png">
<img width="381" alt="Screenshot 2023-01-30 at 07 24 36" src="https://user-images.githubusercontent.com/10942752/215413306-e0415952-5c9f-46ad-9142-6020971f310a.png">

**Comment by gc** [comment]
Done in next update
