### ISSUE TITLE
Tob team size cap

### ISSUE THREAD

**Issue by DarkBugz** [oldschoolgg/oldschoolbot#4903]
I, and everyone else running tob rn, think the max team size should be removed. It's causing issues with repeat trips because it saves the size of how many went on the last trip rather than the max trip size set when hosting. Tobs been out long enough now that it's not really necessary to cap

**Comment by mylife212** [comment]
To clarify, is this asking for repeat trips at ToB to be like nex, where it doesn't save previous size of trip and instead makes a 'new' mass that adheres to the normal cap? (5 players in this case). If it's instead asking for the team cap at ToB to be over 5 players, then that won't happen as thats the cap in-game.

**Comment by DarkBugz** [comment]
Yes exactly that

**Comment by gc** [comment]
Done in next update
