### ISSUE TITLE
Barb fishing at lower levels possibly bugged?

### ISSUE THREAD

**Issue by TylGr** [oldschoolgg/oldschoolbot#491]
https://i.imgur.com/yaAua2h.png

As you can see it stats "fishing 489 barbarian fishing" with the loot only containing 243x Leaping trout. Possibly visually bugged due to lower level however xp rate seems to be correct.

**Comment by osrsolympus** [comment]
Fishing has a fail chance so (especially at lower levels) you won’t actually fish as many as your set out to.

**Comment by Alexsuperfly** [comment]
this is intentional since its made in such a way that you can get one of the 3 fish outcomes or nothing per attempt, other fish dont have this problem since they are primarily caught in a singular fashion so the calculations to figure out how many attempts you fail can be pre-calculated
