### ISSUE TITLE
TOA stuck thinking/app did not respond

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#4925]
Every single TOA i've been the host of has sat in 'old school bot is thinking...' for 5 minutes and then times out to the below image.

Only does it when im host and not anyone else, and has done it on every single one since release that i've hosted. 

The raid still does send, but if you dont meet requirements (kc for example) then it doesnt send and everyone is left idle, and no one even knows that were idle because the message that would tell us is now 'did not respond'

No idea why

![image](https://user-images.githubusercontent.com/76587427/216809996-7c4bc114-6afd-463c-9a63-a5bc27d76d44.png)

**Comment by 6enny6** [comment]
i think we have figured out it happens if the character limit of a message is hit. if i host less than 8 man it doesnt happen but 8 man it does.

Same thing happens on the help command if user is missing too many things

**Comment by gc** [comment]
Addressed in next update
