### ISSUE TITLE
Remove Fang/Lightbearer from server loot notifications

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#4926]
## 🚀 Feature Proposal

Because they are the most common unique, it can tend to make #notifications flooded with announcements. This is why CoX/ToB doesn't announce prayer scrolls/avernic either, so makes sense to apply it here too.

**Comment by osrsjobbo** [comment]
Did some work to quantify this:

![image](https://user-images.githubusercontent.com/123830708/217392910-f941cd0e-d1fe-477d-8e29-e7838af88066.png)

**Comment by osrsjobbo** [comment]
Here is the same analysis, but only looking at the 711 entries, grouped by loot drop.

![image](https://user-images.githubusercontent.com/123830708/217394175-8a9eb7c5-d76b-4919-a145-e242b689ffe5.png)

**Comment by mylife212** [comment]
Bump. Notifcations is literally just fang/lightbearer drops lol

**Comment by osrsjobbo** [comment]
Not sure if this has launched yet, but Magna did a commit which silences these yesterday.

https://github.com/oldschoolgg/oldschoolbot/commit/7b52e1df4957974843547444433fb571183c1e21
