### ISSUE TITLE
Sanitise users in masses

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#4928]
## 🚀 Feature Proposal

Some people like to be funny and use || within their names or minion names making mass messages distorted

Would be nice to sanitize names to strip discord syntax

Reported via Suslord in testing discord post release
![image](https://user-images.githubusercontent.com/12814878/216848118-82736fdf-5c1a-4377-a98a-12ff142a8de9.png)

**Comment by osrsjobbo** [comment]
Possible list of things to exclude:
* Anything listed here: https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-
* >>> (code blocks)
*  || (spoiler, as op described)
