### ISSUE TITLE
Mod Perks

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#493]
## 🚀 Feature Proposal

Give Mods T5 patron perks. It’s a good reward for their work and also means they can show people all the commands without being shot down by the bot.

**Comment by osrsolympus** [comment]
Gonna bring this up again so people don’t get their minions stuck and have to wait for a T5 to unstick them with +economybank. Just give mods T5 perks. It’s fair and also necessary.

**Comment by Lajnux** [comment]
The minion stuck problem should be worked on rather than giving moderators/contributors a perk that devalues the T5 patreon. Moderators do a awesome job along with contributors. No hate. ❤️ 😍

**Comment by osrsolympus** [comment]
Ok that is literally just something I added in my comment. Yes it should be worked on, but it hasn’t been. Regardless, re: my original point which had nothing to do with stuck minions, it makes zero sense for there to be commands which MODERATORS cannot use. No hate. ❤️😍if Magna or Alex wants to close this issue they can but I sure as hell won’t.

**Comment by mylife212** [comment]
I also support this, mods have to deal with quite a lot of stuff. They deserve t5 perks as an award and to show people commands. No reason why not

**Comment by chefslav** [comment]
even tho this devalues my T5-only-UIM.... support.

**Comment by coolbop32** [comment]
mods can now give themselves any tier they need
