### ISSUE TITLE
Can equip 2h through "items" option but not "item"

### ISSUE THREAD

**Issue by Redquaker** [oldschoolgg/oldschoolbot#4937]
## 🐛 Bug Report

See below for pictures of attempting to equip a 2h item with both the `item` and `items` options under `/gear equip`. Only the `items` option works without manually unequipping the current weapon+shield.

![image](https://user-images.githubusercontent.com/59510368/217682172-d29107b1-42f2-4cf1-b66f-a397fbbd3f58.png)
![image](https://user-images.githubusercontent.com/59510368/217682387-65d3ed7a-b2f6-46c8-a0c3-82a6cd93333a.png)

**Comment by nwjgit** [comment]
This now works properly.
