### ISSUE TITLE
[BSO Only] Fang, Lightbearer and Ward still use pink sprites

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#4943]
## 🐛 Bug Report

Title. Even when equipped, its still the pink placeholder from Tournament worlds.

**Comment by nwjgit** [comment]
![Discord_0ThbQojfgI](https://github.com/oldschoolgg/oldschoolbot/assets/69014816/2f1061f5-67c4-4f0b-90cf-cb25619f5498)
These items now use the correct icons.
