### ISSUE TITLE
Tumeken's shadow not using charges

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#4948]
## 🐛 Bug Report

Currently Tumeken's shadow isn't using up charges when being used 
Charges prior to trip returning
![image](https://user-images.githubusercontent.com/12814878/218309415-7937a0a2-2eb7-4902-b96f-b38b3ed45513.png)
charges after hosting a mass with staff equipped
![image](https://user-images.githubusercontent.com/12814878/218309452-a280e189-82bd-46f4-90fa-ac2a65219faa.png)

PS the staff equipped is the charged version.

**Comment by LuxrayElite** [comment]
Update: 
Staff was given 20000 charges
Last time the staff was charged was 6th feb (it had 15k at this point)

![image](https://user-images.githubusercontent.com/12814878/218309656-3c742d5c-b7c7-451b-9beb-39db3278743a.png)

so some point after this time charges were no longer removed

**Comment by 6enny6** [comment]
this is fixed
