### ISSUE TITLE
(Mostly for BSO) Add a toggle to clue buttons

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#4949]
## 🚀 Feature Proposal

This is mostly a BSO issue due to stackable clues but can be applied to OSB too.

When you get a clue in a trip, Patrons can click a button to complete it. However, it is easy to misclick and accidentally send a Grandmaster clue trip - which is annoying because players tend to save them for clue sessions w/ proper boosts equipped or to sell. A toggle would be a lifesaver for this and would only benefit the players in a convenient way

**Comment by osrsjobbo** [comment]
Would you prefer the toggle to be per tier? Or to stop all clue buttons showing?

**Comment by nwjgit** [comment]
This has been added with `/config user toggle name:Disable Clue Buttons`
