### ISSUE TITLE
Creating and revert tumeken's guardian variants increases cl and mostdrops

### ISSUE THREAD

**Issue by DarkBugz** [oldschoolgg/oldschoolbot#4950]
I assume this isn't intentional since it's been fixed for other createables in the past

**Comment by TURB042O** [comment]
what cl has it been fixed for? it does it for every creatable I can think of.

**Comment by nwjgit** [comment]
Only items that are on a counted cl are prevented from adding more to cl. Example: Every great blue heron made will add +1 to creatables cl but reverting great blue heron to a heron won't add a heron to the skill pets cl. This is the norm for most every item that has a revert.
