### ISSUE TITLE
Slayers Black Demon Mask invades Master clue cl

### ISSUE THREAD

**Issue by ghost** [oldschoolgg/oldschoolbot#4960]
## 🐛 Bug Report

![collection_log_1676809047131.png](https://user-images.githubusercontent.com/90441459/219947736-6bdd8913-99a4-407e-b953-aaa61327dc05.png)

after doing missing and text flags on the cl it said black demon mask. 
![SmartSelect_20230219_062501_Word.jpg](https://user-images.githubusercontent.com/90441459/219947838-10923f99-40e3-443d-8a00-c20c0f59eb7c.jpg)

![SmartSelect_20230219_062616_Discord.jpg](https://user-images.githubusercontent.com/90441459/219947839-6b518cde-cb98-4449-8e9c-f41f65bb2a76.jpg)

![collection_log_1676809161013.png](https://user-images.githubusercontent.com/90441459/219947873-adda2184-c567-4a9c-80aa-7e4ffb8ea714.png)

**Comment by nwjgit** [comment]
This now displays the right icon
