### ISSUE TITLE
Shades of Mort'ton gold coffin not fixed 

### ISSUE THREAD

**Issue by ghost** [oldschoolgg/oldschoolbot#4967]
## 🐛 Bug Report

in reference to #4862

![Screenshot_20230222-233853.jpg](https://user-images.githubusercontent.com/90441459/220766148-b7321afa-83b5-4a37-b9aa-209b70bec759.jpg)

BadgeHunter just showed me this so the coffin still is bugged.

**Comment by LuxrayElite** [comment]
A paritial fix was merged the current fix is still marked as a draft in reference to comment on #4855 

#4877 is the new pr to fix coffins
