### ISSUE TITLE
Master clue dissapeared

### ISSUE THREAD

**Issue by Ragnar1997** [oldschoolgg/oldschoolbot#497]
Looks like my master clue dissapeared after i completed a clue. Not able to open a casket. 

![osrs disc bot master clue](https://user-images.githubusercontent.com/69463350/89779919-b3292800-db10-11ea-9441-61dae913d538.PNG)
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

**Comment by Alexsuperfly** [comment]
ive seen it not realize the casket is in the bank for a minute or two, can you try again
