### ISSUE TITLE
gamemode icon next to their name on +stats command

### ISSUE THREAD

**Issue by permedd** [oldschoolgg/oldschoolbot#498]
## 🚀 game mode icon on the +stats command

is there a way to put ironman/ultimate ironman and also hardcore ironman next to members names when you do +stats (player name)? so then we can see which mode they are playing such as nonironman/ironnman/ultimate/hardcore ironman

so forexample +stats dids he is the #1 ironman when searching him on discord maybe he can have the ironman icon next to his name which is shown on the image
![image](https://user-images.githubusercontent.com/37475765/89798934-c0501200-db24-11ea-8c7c-d60a70f93ee6.png)

and so on that goes for ultimate/hardcore ironman and if they are not an ironman they wouldn't have any icon next to their name.

**Comment by Alexsuperfly** [comment]
jagex doesnt respond with the account mode of the looked up player, so unless we submit 5 requests every lookup we cannot know the status, and even then it can be wrong for hardcore ironmen that have died but not gained any more exp
