### ISSUE TITLE
A command like "loot_show_id", "loot_show_name" and an option to make it permanent would be very beneficial for bso since not everybody will know what they got as loot.

### ISSUE THREAD

**Issue by yuuzota** [oldschoolgg/oldschoolbot#4984]
## 🚀 Feature Proposal

Describe the feature you're suggesting here, give lots of information and describe it as best you can. Please check that the feature hasn't already been suggested first, by searching the issues in this repository.

**Comment by zweetkonijn** [comment]
This is a great idea! 
I sometimes also get confused with the drops I'm getting.
I quited OSRS in 2018, so everything added after that is new for me.

A command like /loot_show_name that would return an image with your last loot including the names would be great.

Or a config option to always turn this on or off.
Like /config_loot name: True

**Comment by TastyPumPum** [comment]
This was coded in #3777 but Magna was against the idea
