### ISSUE TITLE
Components not added to cl

### ISSUE THREAD

**Issue by DarkBugz** [oldschoolgg/oldschoolbot#4985]
Creating components does not fill creatables cl because it's a revert. This could be fixed by changing it to something like: /create item: armadylean components - helmet; bandosian components - tassets, etc. Also applies to plates in osb

**Comment by TastyPumPum** [comment]
https://github.com/oldschoolgg/oldschoolbot/pull/4575/files

This should be fixed for bandosian components, have you had recent trouble with it?

probably needs changing for armadylean components though

**Comment by DarkBugz** [comment]
Yeah I just did bandos yesterday on bso and it wasnt added to cl. Maybe it was only fixed for osb?

**Comment by LuxrayElite** [comment]
Resolved by #5213 (BSO) & #5214 (OSB) 

Should work on next reboot :)
