### ISSUE TITLE
Osb-masori

### ISSUE THREAD

**Issue by FeoutcastJ** [oldschoolgg/oldschoolbot#4987]
## 🐛 Bug Report

Osb Masori using armadyl components, however it's not been counted as a armadyl item. 

For example having masori equipped and no armadyl chestpiece in bank, you can't then go kill vorkath, as its not reading masori

**Comment by osrsjobbo** [comment]
This will be closed by https://github.com/oldschoolgg/oldschoolbot/pull/4981/files
