### ISSUE TITLE
Iron Ore & Coal

### ISSUE THREAD

**Issue by Wedh-OSB** [oldschoolgg/oldschoolbot#501]
## 🚀 Feature Proposal

1. Either add the Ring of Forging or remove the 50% chance to fail smelting iron ore. At current iron ore is not even worth the time smelting.

2. Any decent way of obtaining coal - right now smithing is completely bottlenecked by the lack of coal supplies in the game. Aside from mining it, zulrah is the only reasonable way to get it.

**Comment by Alexsuperfly** [comment]
iron fail chance follows the game, that will not be changed, ring of forging will likely become an option when enchanting gets released

coal is also normally difficult to obtain without 50k f2p bots mining it all the time so i dont think mining rates should be changed just to let you smelt more
