### ISSUE TITLE
Phantom dice

### ISSUE THREAD

**Issue by parallack** [oldschoolgg/oldschoolbot#502]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
I was doing a few dice on the BSO (loaded into another server). Diced 10m, then 30m, then 100m b2b2b. I won them all. I then attempted to dice 5m and the bot didn't appear to respond. I attempted the 5m dice again and the bot still didn't respond. Thinking it was a connection/discord issue I went to the main BSO server and noticed the bot was working just fine for others. It still did not recognize basic commands for me such as =m or =gp. Finally the bot pinged me on the initial server I tried to dice the 5m on to inform me that I had lost my dice of 400m? I wish I could provide more info for you than this but I was experiencing no network connection issues and others appeared to be using the bot without interruption. Below is a screenshot of the event. Time is in gmt-6.
![glitched dice](https://user-images.githubusercontent.com/69537065/89938976-e3d69380-dbdc-11ea-9699-251ff837689f.png)

**Comment by ard35** [comment]
![image](https://user-images.githubusercontent.com/57806957/89939387-e7224d00-dbe5-11ea-82a6-c9b6b17037b5.png)

**Comment by parallack** [comment]
RIP sorry for the waste of time. wasn't aware of this "feature"
