### ISSUE TITLE
[BSO] stash build_all stuck waiting

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#5024]
## 🐛 Bug Report

Currently unable to use the build_all command due to the bot getting stuck "thinking" this only happened once I bought the supplies I was missing

before buying gold leaf:
![image](https://user-images.githubusercontent.com/12814878/227227222-8c4108e7-c63c-4c81-9c97-284b122f4fb2.png)
supplies (not really relevant but):
![image](https://user-images.githubusercontent.com/12814878/227227479-8897e775-0122-4856-a181-429df985d217.png)

after purchasing gold leaf (Item I was missing):
![image](https://user-images.githubusercontent.com/12814878/227227099-b77f539f-fa54-4a69-98fd-3cfcb8be0370.png)

**Comment by gc** [comment]
Should be fixed now. Feel free to re-open if its not.
