### ISSUE TITLE
Hunter experience reset for black chinchompas

### ISSUE THREAD

**Issue by jesseklein** [oldschoolgg/oldschoolbot#5026]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

My hunter xp used to give a 10% boost to my speed hunting black chinchompas.  This boost no longer is showing and my hunting speed went down. See message from bso help and support channel showing pumpum screenshots 15min before this issue was submitted.

https://discord.com/channels/342983479501389826/970752140324790384/1088503923284914276

**Comment by DarkBugz** [comment]
All hunter kc got wiped for everyone.

**Comment by gc** [comment]
This is apparently fixed now. Feel free to re-open if its not.

**Comment by jesseklein** [comment]
Agreed.  This has since been fixed
