### ISSUE TITLE
Small bug report

### ISSUE THREAD

**Issue by THCinabag** [oldschoolgg/oldschoolbot#503]
[##]([url](url)) 🐛 Bug Report

Theres a buddy in my server, hes the owner of the server, Old School Bot will allow him to set his rsn but it wont acknowledge that its valid username when he attempts to +stats. We have tried changing his name but it never works. We are out of options and we are coming to you for help

**Comment by Alexsuperfly** [comment]
have you considered that the name they are trying to use isnt valid

**Comment by jamosaur** [comment]
it would help having the RSN so it can be checked @THCinabag

**Comment by Lajnux** [comment]
No further information was provided. Close issue.
