### ISSUE TITLE
/bank filter: not sacrificed no longer works

### ISSUE THREAD

**Issue by Jones-y** [oldschoolgg/oldschoolbot#5030]
## 🐛 Bug Report

the bank filter for "not sacrificed" no longer works. It worked fine as of 18 hours ago.

Issue affects both OSB and BSO.

**Comment by Jones-y** [comment]
Not sure if it's related but the sacrifice icon when you run the "is" command isn't showing up anymore.
[https://i.imgur.com/jevHX3N.png](url)
[https://i.imgur.com/JRdzdoW.png](url)
``

**Comment by KyeDon** [comment]
This is also affecting `/sacrifice filter: not sacrificed`

**Comment by KyeDon** [comment]
![image](https://user-images.githubusercontent.com/47357003/227729651-133361b2-4a20-45ab-9c0e-d949cdb90918.png)
??

**Comment by KyeDon** [comment]
We are STARVING for this to be fixed 😭
