### ISSUE TITLE
Get rid of time variance on mining + woodcutting

### ISSUE THREAD

**Issue by Redquaker** [oldschoolgg/oldschoolbot#5043]
## 🚀 Feature Proposal

Currently, there's a time variance/range of return times when repeating a woodcutting or mining trip. However, having this uncertainty in when the bot will return doesn't really enhance the bot in any way. Sometimes people will want to know exactly when their trip will return, not a 10 minute range of when.

Of course, this is a measure to implement RNG into gathering skills, similar to the real OSRS. However, another more convenient model could be used instead...

**Current Model:**
- Fixed quantity of actions
- Varied time

**Possible Model:**
- Varied quantity of actions
- Fixed time

See aerial fishing for an example of the "possible model" already in practice. This would be much more convenient.

As for implementing this idea into a command... maybe allowing the user to input a number of minutes with a "time" option could work, similar to old aerial fishing. Otherwise, an unspecified time would default to the user's maximum trip time.

To prevent people from re-rolling their trip to get a better outcome, simply just don't print the amount of actions performed upon sending the trip.

**Comment by Lajnux** [comment]
the command itself is working as intended, the thing that happened was that information on repeat trip got removed when Magna made a update to the repeat trip function. This would be resolved if repeat trip can get access to the minions max trip lengths again.
