### ISSUE TITLE
/view Tame not working for me

### ISSUE THREAD

**Issue by Hynloran** [oldschoolgg/oldschoolbot#5048]
/view Tame doesn't work for my tame Charizard, I think it's because he has a broken item in his "eaten" items 
![SmartSelect_20230327_185852_Discord](https://user-images.githubusercontent.com/32245502/229361967-1249be27-19ea-4ec5-9a2b-d9af966f1a27.jpg)

**Comment by turb042o** [comment]
have you done `/tool users fixbank` already?

**Comment by gc** [comment]
Try `/tool users fixbank `, reopen if its still happening.
