### ISSUE TITLE
tokkulshop

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#5057]
can tokkulshop please be looked into, buying 12 sapphires in 30 mins is a bit too much of a nerf

**Comment by LuxrayElite** [comment]
master branch doesnt seem to follow the shop stock for all tokkul items 👀 

https://oldschool.runescape.wiki/w/TzHaar-Hur-Rin%27s_Ore_and_Gem_Store

Aware it doesnt implement the inner city shops either but 🤷
