### ISSUE TITLE
(Both bots?) Patron bitfields are broken and aren't working.

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#5066]
## 🐛 Bug Report

I've seen it only in BSO so far, but heard reports of OSB too. Basically, Patrons aren't able to access perks as their bitfield isn't on their account anymore. Everyone experiencing it is a paying patron from what I can tell, should be looked into ASAP!

**Comment by gc** [comment]
Anyone with issues with patron perks can DM me for help.
