### ISSUE TITLE
remove random events from toa

### ISSUE THREAD

**Issue by 6enny6** [oldschoolgg/oldschoolbot#5069]
title

**Comment by gc** [comment]
You're getting the event while you're banking

**Comment by 6enny6** [comment]
you dont get random events within TOA or at the bank/lobby as it is inside a pyramid. A lot of people skill at TOA bank for this reason

**Comment by LuxrayElite** [comment]
Bennys logic is supported by the osrs wiki in random events and the limited permitted banks which allow random events don't include toa 
![image-3](https://user-images.githubusercontent.com/12814878/232306727-49958705-558a-4bbe-b1fa-2ac5f7a47575.png)

**Comment by gc** [comment]
Done in next update
