### ISSUE TITLE
Increase minion's capability to learn from mistakes

### ISSUE THREAD

**Issue by DeusVexus** [oldschoolgg/oldschoolbot#5076]
Currently, the way the minion "learns" for "solo" tob is incredibly slow and unrealistic

After over 50 attempts in the raid (an attempt is only _counted_ after getting _past maiden,_ mind you, there are many more attempts that fail at maiden), there is still an insane chance of failure in each room and the raid over all.

It doesn't really make sense for my minion to just continue failing over without really learning from their mistakes. 

Each attempt should improve the percentage of success 
Each failure at maiden should increase the percentage of success in maiden.
Each success in a room should increase the chance of success in that room.

additionally, although this may be more difficult to implement, a minion with a large amount of pvm experience (total boss kc elsewhere) should have a much higher affinity for learning pvm

**Comment by TastyPumPum** [comment]
Going to close this as this isnt really an issue, the poor learning is due to the bug that is in #5077
