### ISSUE TITLE
Solo tob not calculating as if your team size is 3 or as if your team is comprised of 3 of yourself

### ISSUE THREAD

**Issue by DeusVexus** [oldschoolgg/oldschoolbot#5077]
I'm pretty sure with the way solos are calculated in tob, it isn't actually calculating as if your team is a size of 3 and the teammates are all you.
This results in incredibly low success rates (~2% for a success at 40+ attempts)

**Comment by Redquaker** [comment]
What are your gear scores for TOB? If any are below 80%, you get a severe penalty to death chance per room.

At 40 attempts and 0 KC, you should have a ~50% chance to complete the raid in a trio if all gear scores are above 80%.

**Comment by DeusVexus** [comment]
99.8% melee, 98.4% range, 100% mage, 99.4% total
i just dont have scythe and im using rune arrows and adamant darts instead of dragon arrows and darts

**Comment by mikkoof** [comment]
Problem seems to be when the tob team is created for solo, only the user is added to the team [here](https://github.com/oldschoolgg/oldschoolbot/blob/6f8ce67dd44a94561f3ff74d9e04f3d1087f7d43/src/mahoji/lib/abstracted_commands/tobCommand.ts#L338) then if you wipe in any room, [this](https://github.com/oldschoolgg/oldschoolbot/blob/6f8ce67dd44a94561f3ff74d9e04f3d1087f7d43/src/lib/data/tob.ts#L516) will always cause the raid to wipe.

**Comment by mylife212** [comment]
Bump. This is still an issue, and its really annoying because even if you have 1k+ kc, still constantly wipe.

**Comment by LuxrayElite** [comment]
Should be fixed now

#5286
