### ISSUE TITLE
Hard clues currently give the wrong Pirate hat

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#508]
## 🐛 Bug Report
Hard clues currently give the **Big pirate hat**, which is exclusive to Elite clues, instead of the **"Pirate's hat"**. It seems that the Pirate's hat item is replaced by the Big pirate hat instead. This can be confirmed by doing a simulation of 1000 hard clues. 

Proof that Hard clues currently give the Big Pirate hat https://i.imgur.com/lnIRXIe.png
Hard clues should actually give the Pirate's hat, as seen in the Hard clue log. https://i.imgur.com/2rXjf6N.png

**Comment by gc** [comment]
This has been fixed in our library and will be fixed in the next bot update ( or a soon one)
