### ISSUE TITLE
Bso /kill & /k info =  no results for killables with (solo) option

### ISSUE THREAD

**Issue by AvariceBrah** [oldschoolgg/oldschoolbot#5082]
For some reason bso says it doesn't have this monster when /kill nex is attempted. 

I haven't attempted with osb.

**Comment by AvariceBrah** [comment]
This has been the result for any /kill that has (solo)/(mass) suffix + also affects the show_info field when using /k

**Comment by AvariceBrah** [comment]
Bump

**Comment by AvariceBrah** [comment]
I hate mobile format I'm sorry about closing and reopening

**Comment by nwjgit** [comment]
Nex was added to `/kill` next update. i'll close this thread since you have another thread about the /k info issue here https://github.com/oldschoolgg/oldschoolbot/issues/5533
