### ISSUE TITLE
Motherlode Mine, Golden Nuggets, and Gem Mine

### ISSUE THREAD

**Issue by Sethmare** [oldschoolgg/oldschoolbot#509]
## 🚀 Feature Proposal

Motherlode Mine:
-Add command _+mlm_ or _+mine motherlode_ to have minions gather assorted ores (coal, gold, mithril, adamantite, runite) based on mining level, with higher mining levels giving better chances at valuable ores. Each ore would give a small amount of bonus xp (see https://oldschool.runescape.wiki/w/Motherlode_Mine#Cleaning).
This would add a good mixture of ores into the economy to assist with the demand for smithing materials.

Golden Nuggets:

Motherlode would also become the sole source of gold nuggets, like in game. The gold nuggets' uses could be expanded to allow players to purchase "bags full of gems", "soft clay packs", "coal bag", and the "gem bag" to assist with gem mining (see below), all in exchange for golden nuggets.

Gem mine:
Add _+mine gems_ command to allow players to mine assorted gems from Shiloh Village. Rates could be boosted by owning a gem bag, owning full graceful, and/or having a certain amount of Quest Points (equivalent to hard Karamja Diary for the special underground mine)

Bonus: Give a chance to receive random gems from any mining activity, with more frequent rates while wearing an amulet of glory in _+gear skilling_ (https://oldschool.runescape.wiki/w/Amulet_of_glory _"Other Uses"_)

**Comment by Lajnux** [comment]
#818 resolves part of this issue
