### ISSUE TITLE
Team CoX loot image has the ToA Chest instead

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#5091]
## 🐛 Bug Report

SOLO cox has the right image for the loot. However, Teams shows this: 
![image](https://user-images.githubusercontent.com/63373565/235281720-1441f8c4-4686-4a55-ae3d-8129d847dcf1.png)

**Comment by mylife212** [comment]
Turns out its an issue with team raids, not cm. Edited accordingly: 
![image](https://user-images.githubusercontent.com/63373565/235331990-567a19ec-ca87-4768-9369-2e1db40851e8.png)

**Comment by 6enny6** [comment]
seems to be fixed

![Image](https://user-images.githubusercontent.com/76587427/236416960-5b5d7b57-c16c-485a-bdb2-bbd463779ef5.jpeg)
