### ISSUE TITLE
Spoiler the Loot image when you get a purple at CoX

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#5092]
## 🚀 Feature Proposal

ToA has a spoiler added for purples to add suspense, right now Cox just spoils it. Should also apply to Twisted kit/Dust from cms! 
![image](https://user-images.githubusercontent.com/63373565/235281753-99cb25bf-e372-43d4-b7e9-747d1d8fa2ef.png)

**Comment by gc** [comment]
Should be fixed with next update (reopen/ping me if its not)
