### ISSUE TITLE
BSO ToB broken

### ISSUE THREAD

**Issue by Felris** [oldschoolgg/oldschoolbot#5095]
## 🐛 Bug Report

Been sending solo tob trips all day on BSO. Haven't been getting return messages. But after a few hours I realized my tob attempts isn't going up either.
Here you can see me sending a tob trip. Checking on it to see if it's still active (because I was expecting no return message so I was just checking if I had wiped), and then /m again and my trip is done with no return message.
![image](https://user-images.githubusercontent.com/8431944/235394766-c33b65e8-9249-45ce-bceb-0ff8120ed6d9.png)

![image](https://user-images.githubusercontent.com/8431944/235394860-7fbcb408-9148-4802-a7d2-5de8cd52e41d.png)
This image shows me checking my tob attempts (21) and then sending a tob trip. No return message. Then checking my tob attempts again and it's still 21.

**Comment by shelixd** [comment]
Same issue with CoX
