### ISSUE TITLE
Add a 10% gmc boost for having dwwh equipped  

### ISSUE THREAD

**Issue by DarkBugz** [oldschoolgg/oldschoolbot#5101]
This brings new gmc rate up to exactly the same as old rates. Math available on request.

**Comment by TastyPumPum** [comment]
Imo, it would be better to have a new "teleportation" item added or clue specific item rather than an already expensive big content item, and this should probably be polled in bso-votes than posting here.

**Comment by ghosts-are-spooky** [comment]
@DarkBugz requesting math on this please
