### ISSUE TITLE
OSB Shades of Morton

### ISSUE THREAD

**Issue by DadVax** [oldschoolgg/oldschoolbot#5102]
When opening with gold keys for zealots pieces you can receive dupe pieces.

You cannot get dupes until the full set in game.

![E19556F7-291D-4249-B394-1AD3DE6A6609](https://user-images.githubusercontent.com/79945242/236323446-ad5e6b86-9d52-4e83-be99-1546b26cb69b.jpeg)
![6D0B0BEE-72D3-49CA-954A-F84FA7DB55A6](https://user-images.githubusercontent.com/79945242/236323457-959db631-0d4d-4921-b99e-c0ca1dc1ef43.jpeg)

**Comment by TastyPumPum** [comment]
It's the same with dark totems on this, as the bot only checks the bank youll get dupe pieces if you do mass openings/killings etc

**Comment by 6enny6** [comment]
If you opened the implings 1 by 1 you would not receive dupes, as Pum said the code can only check your bank for dupes and cant check the loot from the same opening
