### ISSUE TITLE
minigame Shades of Mort'ton is not listed in Drystreaks (therefore can't do drystreak for gary)

### ISSUE THREAD

**Issue by ghost** [oldschoolgg/oldschoolbot#5105]
## 🐛 Bug Report

title says all

![SmartSelect_20230506_011920_Discord.jpg](https://user-images.githubusercontent.com/90441459/236605958-bff988e9-1f04-40d8-993a-a399090816e9.jpg)

**Comment by LuxrayElite** [comment]
Shades of morton is now available under drystreaks (both bots) however gary cannot be check for.

**Comment by nwjgit** [comment]
Gary will be added to shades cl next BSO update.
