### ISSUE TITLE
Mystery box gave false items

### ISSUE THREAD

**Issue by Rhastae** [oldschoolgg/oldschoolbot#511]
https://imgur.com/a/BkufPuK

I opened 2 mystery boxes with the OSB bot and received a clue casket and a clue, which never happened before. Confused, I searched the bank for treasure trail related items, and found no addition of the two rewards from the mystery box.

**Comment by gc** [comment]
This is a Casket: https://oldschool.runescape.wiki/w/Casket - you can check the mystery box page to see that this is what it drops.
