### ISSUE TITLE
Minion is busy when buying fossil notes.

### ISSUE THREAD

**Issue by turb042o** [oldschoolgg/oldschoolbot#5113]
## 🐛 Bug Report

title says all![SmartSelect_20230508_103219_Discord.jpg](https://user-images.githubusercontent.com/90441459/236866051-5fb9bb08-3929-40dd-b209-93ea7018cc00.jpg)

**Comment by TastyPumPum** [comment]
Done like that on purpose like offering bird eggs.

**Comment by turb042o** [comment]
> Done like that on purpose like offering bird eggs.

Tom explained that to me but it makes no sense for it to be under `/buy` then. the bird offerings are at least under `/offer` which minion cannot be busy to do.

it makes no sense / is very confusing for a `/buy` option to not work when minion is busy yet all it does is give you notes instantly... no need to wait for minion to be free in my honest opinion! 

![SmartSelect_20230508_110550_Discord.jpg](https://user-images.githubusercontent.com/90441459/236874061-eb4b2282-b3d4-4746-b906-a9507f849270.jpg)
