### ISSUE TITLE
LMS buyable price change

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#5114]
## 🚀 Suggestion

The Trouver parchment got a price reduce from 30 to 18 in march of 2022 (shortly after the release of LMS to the bot)

https://github.com/oldschoolgg/oldschoolbot/blob/87a9c2356ffee5c1cd13250bfcdebee74655718d/src/lib/data/CollectionsExport.ts#L2209

https://oldschool.runescape.wiki/w/Trouver_parchment

**Comment by gc** [comment]
Done
