### ISSUE TITLE
Separate banks for sets of items/tabs

### ISSUE THREAD

**Issue by Maxwall-jpg** [oldschoolgg/oldschoolbot#512]
## 🚀 Feature Proposal

Sometimes the bank can be a bit cluttered. Would it be possible to to have a separate bank tab than the main one. I was thinking things like runes or food could be auto sorted into respective tabs.  +bank can be the regular section & there could be things like +bank food or +bank runes .

**Comment by Alexsuperfly** [comment]
bank filters are our way of doing this, you pass a parameter like `--food` or `--potions` and it will show a page with only those items on it
