### ISSUE TITLE
Miscommunication with /droprate & BSO Wiki Custom Pets 

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#5130]
## 🐛 Bug Report

![Screenshot_20230520_075936_Discord.jpg](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/03ae491f-94aa-4bea-bf56-19e5276fbada)
![SmartSelect_20230520_075957_Discord.jpg](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/1abd3b94-6a22-4dee-84b3-e60e679c0a44)

seems the few pets under /droprate have the message that with each pet in cl, gets 1.5x rarer... but it doesn't match up with [BSO Custom Pets](https://bso-wiki.oldschool.gg/custom-items/pets) .. meaning some of the pets in droprate say this when they don't have the footnote on the website & the rarer info is different than on the website.
![SmartSelect_20230520_075806_Samsung Internet.jpg](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/1a2ea6d4-a556-4d71-bf1e-37b58d3442fc)

**Comment by gc** [comment]
I suggest you edit the wiki if its wrong.

**Comment by TURB042O** [comment]
> I suggest you edit the wiki if its wrong.

I wasn't saying the wiki exactly was wrong. I was wondering if the command might be wrong.
