### ISSUE TITLE
Add names to unf potions

### ISSUE THREAD

**Issue by Hanzigamer** [oldschoolgg/oldschoolbot#5131]
Would it be possible to add name to the unfinished potions, similar to grimy and clean herbs? it would be nice too see what kind of potions it is, without having to set filter for name. 

![image](https://github.com/oldschoolgg/oldschoolbot/assets/80713862/692d743d-9d2b-4331-8a68-641c5a54d18f)

**Comment by gc** [comment]
Done in next update
