### ISSUE TITLE
[BSO] leagues task duplicates

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#5136]
https://github.com/oldschoolgg/oldschoolbot/blob/e5e7761098c5e52d9e5bb46c8581272a60d325d8/src/lib/leagues/eliteTasks.ts#L554-L560

This is a duplicate task with the same requirements as earlier in the code.

https://github.com/oldschoolgg/oldschoolbot/blob/e5e7761098c5e52d9e5bb46c8581272a60d325d8/src/lib/leagues/eliteTasks.ts#L245-L251

**Comment by gc** [comment]
Fixed
