### ISSUE TITLE
BSO bug (not a bug as it turns out) *gone pepehands* dice 9b by accident

### ISSUE THREAD

**Issue by drbobbert** [oldschoolgg/oldschoolbot#514]
There is a bug where if you dice any amount of gp in BSO, and you type =b before the dicing has occurred it stakes your entire cash stack.
![image](https://user-images.githubusercontent.com/69747044/90328856-364fef80-dfe3-11ea-94cf-9994a008acb3.png)

Can someone look into this?

I didnt intend to stake 9 bill, only 10m and ive been scammed by the bug.

I suspect this also work if you win so this is a doubling bug too no clickbait

**Comment by drbobbert** [comment]
![image](https://user-images.githubusercontent.com/69747044/90329063-ca6e8680-dfe4-11ea-89c7-75657a6f00b6.png)
I have since replicated the bug.

**Comment by Sethmare** [comment]
I believe this was an intentional feature.

**Comment by drbobbert** [comment]
so i just unknowingly dice 9b
RIP
