### ISSUE TITLE
Have LMS trip returns say how many total wins your minion has

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#5159]
## 🚀 Feature Proposal

Title. The only way to check total amount of LMS wins is via the /minigames lms stats command, which is fine but can get tedious to constantly check when you're close to the next cape. Can be something like... ``` Minion finished playing 7x Last Man Standing matches, you received 33 points and now have 4706 points in total. Your total win count is now 966, 50.02 points/hr```

**Comment by gc** [comment]
Done
