### ISSUE TITLE
Fletching Magic Longbow

### ISSUE THREAD

**Issue by The-KingCrab** [oldschoolgg/oldschoolbot#517]
## 🐛 Bug Report

Tried fletching Magic longbows, it gave me an error that I didn’t have enough magic longbows (u). In reality I didn’t have any bow string.
![C4B21072-18DB-4534-B361-9B27BADACB92](https://user-images.githubusercontent.com/69774008/90346775-ea5c7500-dff9-11ea-9945-71e5d150906b.jpeg)

**Comment by Lajnux** [comment]
resolved
