### ISSUE TITLE
BSO - Chincannon Toggle?

### ISSUE THREAD

**Issue by DadVax** [oldschoolgg/oldschoolbot#5171]
Chincannon has to be equipped to be used but also has a toggle on/off option. Having to equip it makes you lose max gear score. Could it be changed to just work from bank with toggle on? Not sure if it’s intended or an oversight.

![4DB67084-4636-4EFB-B859-ED58D4947F99](https://github.com/oldschoolgg/oldschoolbot/assets/79945242/884eaedc-561b-4076-9a0b-c702c48769dc)

**Comment by gc** [comment]
It's intended, you don't have 100% gear score, but that doesn't matter because you're already getting a huge boost. So really it makes no difference.
