### ISSUE TITLE
Countdown timer for corp mass

### ISSUE THREAD

**Issue by CottonDog** [oldschoolgg/oldschoolbot#519]
This would create a timer to countdown ~40mins when a mass is started. People keep having to check +m, or ask when next mass will be. I know people could use common sense math to see when next one will be, but this is just a QOL.
![corp timer](https://user-images.githubusercontent.com/69830366/90462331-485a8c80-e0ce-11ea-9436-3bc29d3e9c42.JPG)

**Comment by Alexsuperfly** [comment]
if the only one mass could be taking place at one time then this could be possible, but anyone anywhere can make and participate in a mass so theres no way to know how to give the correct answer
