### ISSUE TITLE
Achievement Diary Boostable Error

### ISSUE THREAD

**Issue by dasangrypanda** [oldschoolgg/oldschoolbot#520]
When using the command "+diary RSN" to check what achievement diary a character can complete, the bot shows boostable diaries as well. It does not calculate the imbued heart boost for magic, and as such is showing certain diaries can't be completed. Here's a specific example below... 

The wilderness elite diary requires 96 magic. This can be boosted from 87 with the imbued heart, but the bot does not show it as boostable for the character in question.

**Comment by dasangrypanda** [comment]
This calculation error is also true for the ardougne diary which can be +9 mage boosted as well.

**Comment by Lajnux** [comment]
this command was removed
