### ISSUE TITLE
[BSO] Double dart boost - Inferno

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#5201]
## 🐛 Bug Report

Currently you get two applications of boosts based on your dart type for regular inferno runs due a repeated line of code outside of a conditional statement

https://github.com/oldschoolgg/oldschoolbot/blob/41b1437b4056672d848291db6bd55586a73190eb/src/mahoji/lib/abstracted_commands/infernoCommand.ts#L318-L328C2

**Comment by gc** [comment]
Fixed
