### ISSUE TITLE
BSO Leaderboards dont update

### ISSUE THREAD

**Issue by JerMous3** [oldschoolgg/oldschoolbot#5228]
Hello,

With the new Growable pets added to BSO, i'm trying to complete that log and keep rank 1 cl overall.
But for some reason the leaderboards dont update for me, it says im still on 19/28 while i'm currently on 27/28.
It also doesn't add to cl overall. 

![Error cl](https://github.com/oldschoolgg/oldschoolbot/assets/62512696/3255cd7d-74b0-4f40-bf16-3db0229b2a00)

## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

**Comment by LuxrayElite** [comment]
Resolved when #5230 is merged
