### ISSUE TITLE
[BSO] When an equipped pet grows upon a trip return, the message does not send. 

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#5244]
## 🐛 Bug Report

Title. My Zammy bird grew into an Owl when my FoG trip returned & the bot never sent me a return message - as seen in image below. The same exact thing happened with Dungeoneering when my other god pet grew - I didn't get a message. Heard reports this is happening with kittens too. **The trip DOES give the appropriate loot, pet grows etc etc - just no return message is sent.** 
![image](https://github.com/oldschoolgg/oldschoolbot/assets/63373565/c3977b4d-b5ed-49f4-a905-3d89a1527967)
![image](https://github.com/oldschoolgg/oldschoolbot/assets/63373565/cd64a590-e993-467f-9c8a-e9a08bea4820)

**Comment by DarkBugz** [comment]
All trips where a cl slot unlocks are not giving return message

**Comment by mylife212** [comment]
Agreed, its the cl unlocks that cause the issue. (Had it happen when i got egg slot itself)...That being said, my trips are now returning as they should when a pet grows/get a new CL slot. Closing issue.
