### ISSUE TITLE
CA: Fighting as intended 

### ISSUE THREAD

**Issue by isaac-tendies** [oldschoolgg/oldschoolbot#5246]
## 🐛 Bug Report

I don't know anything about code so might be nothing but:

**Obor has no requirement?** 
![image](https://github.com/oldschoolgg/oldschoolbot/assets/40436142/0e475a1c-c40c-4591-8195-9703a8e9406b)

**Bryo seems to have requirements based on gear?** 
![image](https://github.com/oldschoolgg/oldschoolbot/assets/40436142/5fe0af49-c205-4283-9d5a-86cf8bdbd123)

**Comment by gc** [comment]
Fixed
