### ISSUE TITLE
CA: The worst ranged weapon

### ISSUE THREAD

**Issue by isaac-tendies** [oldschoolgg/oldschoolbot#5247]
## 🐛 Bug Report

**Armadyl task checking for Nex duo completion**
![image](https://github.com/oldschoolgg/oldschoolbot/assets/40436142/bafe5abe-2ab5-4d42-8119-1f37bfcea344)

**Comment by gc** [comment]
Thank you - fixed here https://github.com/oldschoolgg/oldschoolbot/pull/5259
