### ISSUE TITLE
CA: Perfect Phosani Nightmare

### ISSUE THREAD

**Issue by isaac-tendies** [oldschoolgg/oldschoolbot#5248]
## 🐛 Bug Report

**Perfect Phosani kill checking for Phantom Muspah kill**
![image](https://github.com/oldschoolgg/oldschoolbot/assets/40436142/738d06c6-c33e-4bc1-a90f-fba80f23bbfc)

**Comment by gc** [comment]
Thank you - fixed here https://github.com/oldschoolgg/oldschoolbot/pull/5259
