### ISSUE TITLE
CA: Shayzien Specialist 

### ISSUE THREAD

**Issue by isaac-tendies** [oldschoolgg/oldschoolbot#5250]
## 🐛 Bug Report

**This should be a CoX raids task instead of regular shamans**
![image](https://github.com/oldschoolgg/oldschoolbot/assets/40436142/4a7103bc-28d4-46ea-a1d1-84b031e3ce46)

![image](https://github.com/oldschoolgg/oldschoolbot/assets/40436142/2c2d4fc6-973a-446b-a5de-3e7f4fab574b)

**Comment by gc** [comment]
Thank you - fixed here https://github.com/oldschoolgg/oldschoolbot/pull/5259
