### ISSUE TITLE
CA: From Dusk...

### ISSUE THREAD

**Issue by isaac-tendies** [oldschoolgg/oldschoolbot#5251]
## 🐛 Bug Report

**GGs task checking for Demonic gorillas**
![image](https://github.com/oldschoolgg/oldschoolbot/assets/40436142/2a68ae4c-3f7f-4283-bc39-e9d0477d46be)

**Comment by gc** [comment]
Thank you - fixed here https://github.com/oldschoolgg/oldschoolbot/pull/5259
