### ISSUE TITLE
CA: Hardcore Raiders

### ISSUE THREAD

**Issue by isaac-tendies** [oldschoolgg/oldschoolbot#5252]
## 🐛 Bug Report

not sure if intentional but this ToA task to duo with no deaths is marked as **Not Possible**
![image](https://github.com/oldschoolgg/oldschoolbot/assets/40436142/72011ee2-b9af-4219-9578-2c0727bf6a38)

**Comment by gc** [comment]
Thank you - fixed here https://github.com/oldschoolgg/oldschoolbot/pull/5259
