### ISSUE TITLE
CA: Perfect Het

### ISSUE THREAD

**Issue by isaac-tendies** [oldschoolgg/oldschoolbot#5253]
## 🐛 Bug Report
 
 **Tombs of Amascut** task checking for **Theatre of Blood** completion
 
![image](https://github.com/oldschoolgg/oldschoolbot/assets/40436142/1b575e59-4d86-41e8-a19e-0da5a22fbdaf)

**Comment by gc** [comment]
Thank you - fixed here https://github.com/oldschoolgg/oldschoolbot/pull/5259
