### ISSUE TITLE
CA: Team player

### ISSUE THREAD

**Issue by isaac-tendies** [oldschoolgg/oldschoolbot#5254]
## 🐛 Bug Report

Marked as **Not Possible** but Zalcano is killable so this task should be completable
![image](https://github.com/oldschoolgg/oldschoolbot/assets/40436142/a576e4ed-3df3-471d-9fd9-f7023d5e1212)

**Comment by gc** [comment]
Thank you - fixed here https://github.com/oldschoolgg/oldschoolbot/pull/5259
