### ISSUE TITLE
CA: Enigol Diet II

### ISSUE THREAD

**Issue by isaac-tendies** [oldschoolgg/oldschoolbot#5255]
## 🐛 Bug Report

**Corrupted Gauntlet task checking for ToB completetion**
![image](https://github.com/oldschoolgg/oldschoolbot/assets/40436142/239cc3c1-7e1f-49ad-afcc-12f6a047f6ea)

**Comment by gc** [comment]
Thank you - fixed here https://github.com/oldschoolgg/oldschoolbot/pull/5259
