### ISSUE TITLE
CA: Corrupted Gauntlet GM (50 kc)

### ISSUE THREAD

**Issue by isaac-tendies** [oldschoolgg/oldschoolbot#5256]
## 🐛 Bug Report

**Checking for 150 KC instead of 50 KC**
![image](https://github.com/oldschoolgg/oldschoolbot/assets/40436142/eb4e43d6-9b4c-4078-a1a5-2fa61d03db61)

**Comment by gc** [comment]
Thank you - fixed here https://github.com/oldschoolgg/oldschoolbot/pull/5259
