### ISSUE TITLE
CA: Movin' on up

### ISSUE THREAD

**Issue by isaac-tendies** [oldschoolgg/oldschoolbot#5257]
## 🐛 Bug Report

**ToA task checking for Wintertodt** 
![image](https://github.com/oldschoolgg/oldschoolbot/assets/40436142/00bef140-d1bc-454d-bb1f-6f0a9377aa0d)

**Comment by gc** [comment]
Thank you - fixed here https://github.com/oldschoolgg/oldschoolbot/pull/5259
