### ISSUE TITLE
Weird Fletching Output

### ISSUE THREAD

**Issue by BrandonEnglish848** [oldschoolgg/oldschoolbot#526]
## 🐛 Bug Report

Was trying to fletch "Dragon Bolt" in the first command. It reported an error like usual, but then when the correct command was issued, it submitted it with additional s. It just doesn't look as neat as it could. Not a bot-breaking bug, but a *could use a nice fix* bug.
![image](https://user-images.githubusercontent.com/25591206/90644753-b8663100-e1fa-11ea-8d41-d36e132f0878.png)

**Comment by Lajnux** [comment]
Fixed in #1204 .
