### ISSUE TITLE
Change the item icon for Cat/kittens

### ISSUE THREAD

**Issue by bigsquid69** [oldschoolgg/oldschoolbot#5262]
Similar to herb seeds that have "irit" and "cada" on the photo to help distinguish them apart can we have cats and kittens with a "k" or a "c" or similar in the item icon. The "your kitten has grown into a cat" message sometimes gets lost or just doesnt show. And it is impossible to look at the photo thru the /gear view and see if it has grown or not. 
Thanks 🙏

**Comment by TURB042O** [comment]
Kittens have small not as bold eyes, as where grown cats have bold dots / slashes for eyes.

### kitten:
![SmartSelect_20230816_060003_Discord.jpg](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/bcadbcd7-bc40-4db3-9778-60d41cee6d43)

### cat:
![SmartSelect_20230816_060020_Discord.jpg](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/56bddf5d-f50b-42a8-b4a8-a8d7a81c20ce)
