### ISSUE TITLE
GE my listings won't load

### ISSUE THREAD

**Issue by ghosts-are-spooky** [oldschoolgg/oldschoolbot#5273]
## 🐛 Bug Report

It seems that after the increased slots were added, the my_listings will fail to load over a certain amount. I am currently seeing this issue with 15 slots on BSO.

**Comment by KyeDon** [comment]
Any update on this? I'm seeing the same behaviour on OSB, I can't use more than 15 GE slots. It sits there trying to load and eventually times out.

It really sucks that you get the reqs to have more ge slots and then can't even use them!

**Comment by gc** [comment]
Probably fixed now, can re-open if not.
