### ISSUE TITLE
Magus Vestige missing form duke sucellus cl

### ISSUE THREAD

**Issue by Hanzigamer** [oldschoolgg/oldschoolbot#5278]
Title speak for it self, but there is no vestige in the cl for duke

![image](https://github.com/oldschoolgg/oldschoolbot/assets/80713862/f787b839-1a95-4cc8-a220-6902971f82ec)

**Comment by Hanzigamer** [comment]
Also the axe piece is missing

**Comment by nwjgit** [comment]
> Also the axe piece is missing

"Eye of the duke" is the axe piece, but that is shown in the cl.

The two missing items from duke cl are:
Magus vestige
Ice quartz
