### ISSUE TITLE
3rd age pick / axe not giving bonuses

### ISSUE THREAD

**Issue by Centennials** [oldschoolgg/oldschoolbot#528]
On BSO,

When going to mine, cut logs, etc. 3rd age pick and axe are no longer giving correct bonuses to activity. Watched Veras unequip and equip axe while re-attempting sulliusceps, and then tg03 attempt coal several times.

That's all. Cheers - thanks for yalls work on the bot.

**Comment by Lajnux** [comment]
resolved
