### ISSUE TITLE
Multiple item trades + #payitem feature

### ISSUE THREAD

**Issue by rickico** [oldschoolgg/oldschoolbot#529]
## 🚀 Feature Proposal

Describe the feature you're suggesting here, give lots of information and describe it as best you can. Please check that the feature hasn't already been suggested first, by searching the issues in this repository.

Multiple item trade: +sellto @User price1 item1 price2 item2 price3 item3 price4 item4 --cf
The 'wait' timer could be increased by 5 second every item listed so the customer would have time to check prices, the 'bot' could list like: would you like to buy item1 for price1, item2 for price2, item3 for price3? Type Buy to proceed. or a trade screen with the visual of the items could be opened with 'asking' price in the --sv value...? 

&& the +payitem feature for giving out items in giveaways, even when the user is not online, could be useful! less carpals <3 
if only i knew how to code right i'd code it for you :3

**Comment by Lajnux** [comment]
A version of this have now been implemented #1130 .
