### ISSUE TITLE
Putting wrong items in drystreak shows lb kc

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#5291]
## 🐛 Bug Report

this has been a bug for ages but now I'm just noticing what it is doing

in the picture I put a broken dwarven warhammer (from kg) in a drystreak for kk. instead of saying that item doesn't exist for that boss. it shows the exact same info doing /lb kc for kk does.![Screenshot_20230828_050856_Discord.jpg](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/e9c40fc3-bdc9-46fc-9537-b6e64a611c49)

**Comment by Lajnux** [comment]
how is this an issue? Of course, you would be dry exactly the same as the lb kc on an item that can't drop from that monster.

**Comment by TURB042O** [comment]
> how is this an issue? Of course, you would be dry exactly the same as the lb kc on an item that can't drop from that monster. 

well yeah so it should say that ofc  not just copy the leaderboard info. lol 😅 if you don't see how that's a issue then idk
