### ISSUE TITLE
Lumbridge Achievement Diary/Quest Points

### ISSUE THREAD

**Issue by aldiron** [oldschoolgg/oldschoolbot#5295]
I was finishing up questing to get the Lumbridge & Draynor Achievement Diary done, and it was saying I didn't have the required amount of quest points. I tried questing and it was saying I was at the max of 293, when 298 was needed for the diary. I have completed Desert Treasure 2 as well. I just tried these commands roughly 5 minutes before posting this, but also had the same issue yesterday. I did try searching to see if anyone else had experienced the same issues but in the searching, I did not find anything.

![M1Aq7N4](https://github.com/oldschoolgg/oldschoolbot/assets/61025996/92e2d13e-4f69-4878-b6fd-6cd8a186f92f)

**Comment by gc** [comment]
This will be fixed in the next update/reboot, thank you for reporting.
