### ISSUE TITLE
BSO - New Mystery Box Items

### ISSUE THREAD

**Issue by dangolgotdamn** [oldschoolgg/oldschoolbot#530]
## 🐛 Bug Report

I opened an untradeables mystery box on BSO and received a medium clue scroll that I cannot open. 
![1](https://user-images.githubusercontent.com/69935281/90692921-ccc22200-e22a-11ea-90c3-1bcf09a9a5d9.PNG)
![2](https://user-images.githubusercontent.com/69935281/90692922-cd5ab880-e22a-11ea-8402-2166b7b20d3a.PNG)

**Comment by Lajnux** [comment]
#559 will close this issue if approved.

**Comment by Lajnux** [comment]
fixed #559
