### ISSUE TITLE
Add broken dragon pickaxe to Volcanic Mine

### ISSUE THREAD

**Issue by borsii** [oldschoolgg/oldschoolbot#5303]
## 🚀 Feature Proposal

Title.

A broken dragon pickaxe is a rare loot (1/100) from opening [ore packs](https://oldschool.runescape.wiki/w/Ore_pack_(Volcanic_Mine)) from the [Volcanic Mine](https://oldschool.runescape.wiki/w/Volcanic_Mine) [reward shop](https://oldschool.runescape.wiki/w/Petrified_Pete%27s_Ore_Shop).

**Comment by nwjgit** [comment]
The Dragon pickaxe (broken) is also a cl item for volcanic mine.
