### ISSUE TITLE
Kits on Scythe Disappear

### ISSUE THREAD

**Issue by shelixd** [oldschoolgg/oldschoolbot#5305]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

When your scythe of vitur runs out of charges and gets unequipped, if there is a kit on it (holy/sanguine) it disappears and the regular scythe gets put in the bank.

**Comment by mylife212** [comment]
This is still a bug, lwy just lost a sang kit due to scythe running out of charges.

**Comment by Lewis7777** [comment]
i got owned by this pls fix
