### ISSUE TITLE
Multiple Combat Achievements per trip

### ISSUE THREAD

**Issue by ghosts-are-spooky** [oldschoolgg/oldschoolbot#5308]
## 🚀 Feature Proposal

Currently you can only get 1 combat achievement per trip regardless of if you kill the boss 1 time or 100 times. It would be good to allow 1 per quantity/kill rather than capping it. In game you can get multiple per kill, though I understand this isn't for all, and some are not compatible, but locking 1 per trip feels like it just artificially makes doing CAs longer.

Example here of 5 tasks in 1 kc: https://youtu.be/bUtz9Swdmt0?t=6179

**Comment by Lewis7777** [comment]
much needed update

**Comment by ghosts-are-spooky** [comment]
Some people don't have github accounts, so posting their votes as images here:
![image](https://github.com/oldschoolgg/oldschoolbot/assets/10942752/6cb6587f-d62d-45d3-b5b7-365d51f3c217)
![image](https://github.com/oldschoolgg/oldschoolbot/assets/10942752/a7bc2387-ee58-4caa-8c6f-1add1b6e4f3a)
![image](https://github.com/oldschoolgg/oldschoolbot/assets/10942752/5faf805e-a4d2-40d3-b4e4-365e711a54da)

**Comment by RLChristof** [comment]
I 100% agree with this change. I'll even take it a step further, why don't we add a submenu to 

`/m k <monster> Attempt CAs: True/false`

Whenever I was doing CAs in OSRS, I would hunt multiple at a time and would usually keep going until I got it.

**Comment by gc** [comment]
Done
