### ISSUE TITLE
[BSO] Thieving Skillcape Perk not included in Thieving Master Cape or derivatives

### ISSUE THREAD

**Issue by Redquaker** [oldschoolgg/oldschoolbot#5309]
## 🐛 Bug Report

The perk for "+10% chance of success from Thieving cape" from the level 99 thieving skillcape is not included in the Thieving Master Cape / Support Cape / Completionist Cape. You need to equip both types of capes to get all boosts, which doesn't make sense for a higher tier item.

**Comment by gc** [comment]
Fixed in next update
