### ISSUE TITLE
CA interfering with Nex loot

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#5312]
## 🐛 Bug Report

Since the release of combat achievements the embedded message which usually displays loot at Nex is no longer being sent.

Trip return
![image](https://github.com/oldschoolgg/oldschoolbot/assets/12814878/8c3c5ffc-8886-45bf-97a1-3b7478433de8)

Checking loot using /loot view
![image](https://github.com/oldschoolgg/oldschoolbot/assets/12814878/f85db2c4-174f-48d5-97ea-90a4e4117f1a)

example prior to CA's

![image](https://github.com/oldschoolgg/oldschoolbot/assets/12814878/b6469dbf-415c-4746-a3f8-366ad7f58f3c)

**Comment by mylife212** [comment]
Bump :))) This is an extremely annoying bug that literally disrupts the flow of massing

**Comment by TastyPumPum** [comment]
Should be fixed reopen if it isn't
