### ISSUE TITLE
Give Virtus robes (top/bottom) each a 4%(or less?) boost for Barrage tasks and Inferno

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#5315]
## 🚀 Feature Proposal

title. In game, Virtus robes increase the damage of Ancient spells by 4% per piece, so having it give this boost for Barrage tasks just makes sense. Virtus mask should not be included imo, as you use slayer helm when barraging.  

An 8% boost might be too much in terms of balancing though, so maybe 2-3% works better.

**Comment by nwjgit** [comment]
Virtus now gives 2% boost for each item worn when barraging anything under /k. I don't believe inferno got a boost. If thats something you still want to suggest just open a new thread with that suggestion.
