### ISSUE TITLE
Can't view tames list when monkey casting

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#5320]
## 🐛 Bug Report

![SmartSelect_20230905_225049_Discord.jpg](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/a5638ce1-5218-4d47-b50d-20aa053bf725)

I can't view my list while my monkey is on casting trip

![SmartSelect_20230905_225214_Discord.jpg](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/b2faeb16-f2a6-4b21-90d2-5236291cafcb)

or view it's status

**Comment by nwjgit** [comment]
Fixed next update.
