### ISSUE TITLE
tempoross unique from tame trips

### ISSUE THREAD

**Issue by luckystarfsh** [oldschoolgg/oldschoolbot#5324]
## 🐛 Bug Report

I think the fish barrel and tackle box drops are broken for tame trips, on 1 of my tame trips I got 25 soaked pages which is the drop that's supposed to replace the fish barrel/tackle box after you have them in your cl but I don't have either in my tame cl so I shouldn't be getting that drop.

**Comment by gc** [comment]
Fixed in next update (Will check tame CL instead of users bank)
