### ISSUE TITLE
Smokey not working for Ironman when equipped

### ISSUE THREAD

**Issue by Jahic11** [oldschoolgg/oldschoolbot#5328]
## 🐛 Bug Report

Never used Smokey before. Equipped Smokey on my Ironman. Started opening boxes. Did not receive extra roll procs and did not see extra roll message. Figured it was bad luck as at the time I didn’t know it showed an extra roll message. Unequipped Smokey. Opened a few more boxes and got extra roll messages. Opened about 50 boxes of various types before realizing it wasn’t working as intended.

**Comment by gc** [comment]
Fixed in next update
