### ISSUE TITLE
BSO OSB Crystal Key Open Tag Difference

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#534]
## 🐛 Bug Report

In BSO, when doing =open to see a list of openables in your bank, crystal keys are listed as crystal chests. This is in contrast to OSB where the keys are listed under openables.
![E05A43E7-719D-4C8B-9EC2-6E050CC524B6](https://user-images.githubusercontent.com/65320787/90849318-0420f380-e33d-11ea-8907-dc9fb61d8358.jpeg)

**Comment by Sethmare** [comment]
This might be best fixed by throwing "_You can open_ ___" instead of "_you have_ ___" and use Crystal Chest for both bots. Trying to open crystal key doesn't work and some people may not know what a crystal key opens.
