### ISSUE TITLE
Can't mix antipoison mixes

### ISSUE THREAD

**Issue by Usvaaa** [oldschoolgg/oldschoolbot#5346]
## 🐛 Bug Report

Can't use /mix command to create an antipoison mix on OSB. I get this message: "You don't own: 0x Roe, 0x Antipoison potion (2)." even though I have roe and 2 dose antipoison in bank. All other barbarian mixes can be created (though it's impossible to get the required items for some)
![clIRxUB 1](https://github.com/oldschoolgg/oldschoolbot/assets/145182372/e8e7fb5f-533f-4864-bd84-421640a9e0e9)

**Comment by nwjgit** [comment]
Already fixed with next osb reset https://github.com/oldschoolgg/oldschoolbot/pull/5314
