### ISSUE TITLE
Revert Mystery Box Changes

### ISSUE THREAD

**Issue by ajro9630** [oldschoolgg/oldschoolbot#535]
## 🚀 Revert Mystery Box Changes

The recent mystery box changes have been confusing and unnecessary. The joy of a mystery box has now been tarnished as there is no excitement for an untradeable, or even a pet. This update also takes away from the fun grind of grinding pets. 

The complete mystery of a mystery box was what made them compelling, but now having multiple different types, without any real reason, has tarnished this.

Please revert the mystery box changes to add back the true mystery.

**Comment by Lajnux** [comment]
The different mystery boxes was embraced by the BSO community and is now being normally traded over and used.
