### ISSUE TITLE
BSO : Mystery Box Update

### ISSUE THREAD

**Issue by NotShin** [oldschoolgg/oldschoolbot#536]
## 🚀 Feature Proposal

1. Add anyone who answers correctly within the time frame to a list and then randomly pick a winner for the mystery box. In doing so, no single person would be able to win by by simply being fast enough or cheating if anybody does. It would also be mobile friendly. There's the case of people answering abstract mystery boxes based on item ids, so a code correction is still needed for that.

2. When you win a mystery box, it states **1x mystery box** even if you get one of the new boxes.

3. When you drop one of the new boxes from a chat-based activity, it will state 1x strange device, object, or box. Can these names be mapped similar to **=open** text?

**Comment by NotShin** [comment]
2 and 3 resolved by [fixups](https://github.com/oldschoolgg/oldschoolbot/commit/e95dba056e02f36e689887670c0b7a04e6788a7b)

**Comment by NotShin** [comment]
#537 submitted for 1

**Comment by Lajnux** [comment]
resolved
