### ISSUE TITLE
Remove ping when you begin a Baxtorian Bathhouse trip

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#5371]
## 🚀 Feature Proposal

When you send a Bath house trip, you get pinged by the bot. No other trips are like this, and can be annoying when you tab out too fast - because it sends a notification lol. 
![image](https://github.com/oldschoolgg/oldschoolbot/assets/63373565/540495f5-95ad-4f02-afdc-0993cf6555b7)

**Comment by gc** [comment]
Done in next update
