### ISSUE TITLE
[OSB] Incorrect mutated bloodveld QP check

### ISSUE THREAD

**Issue by FatOrangeKitty** [oldschoolgg/oldschoolbot#5377]
## 🐛 Bug Report

Mutated bloodvelds currently check for 105qp. There are no reqs like this within the main-game for mutated bloodvelds. The check should just be for 50 slayer.

**Comment by DayV-git** [comment]
I presume the qp check comes from the fact that you need to complete sins of the father to gain access to the multi combat cannon spot

**Comment by gc** [comment]
>I presume the qp check comes from the fact that you need to complete sins of the father to gain access to the multi combat cannon spot

Something like that yea
