### ISSUE TITLE
Farming Return Message Inaccurate with Plopper

### ISSUE THREAD

**Issue by ColossalSeagull** [oldschoolgg/oldschoolbot#5383]
The message says you get 100% for Plopper but then at the end it adds 4x for plopper. Same thing when planting in a patch that didn't have anything planted it says you get 4x from plopper but really you only get 3x and I'm assuming the 3x isn't from plopper but 100% from plopper, and 100% from the farming master cape
![image](https://github.com/oldschoolgg/oldschoolbot/assets/96855950/53f15ed9-bc39-4c07-aba3-65529c8a7743)

**Comment by gc** [comment]
Fixed in next update. Thank you for reporting. I've given you a TGB for your reports.
