### ISSUE TITLE
No Gambling role means no Gambling

### ISSUE THREAD

**Issue by Ava-Addams** [oldschoolgg/oldschoolbot#5385]
As per the current No gambling on the bot allowing you to opt out of gambling for x amount of time These Would be Added in.

Allowing users to opt out of gambling which has been currently done, is for a reason, this is added as people, myself included have no willpower or self control. Currently users can "opt out" of gambling, but it is not really opting out of gamling. It just doesnt let you dice.

I prepose a proper no gamling role to actually help people that maybe do lack self control  and still want to be able to trade with others etc.

To add a no gambling role, that actually means no gambling.

This role will block the following commands:

/finish
/kill
/gamble dice
/choose
/pick

Ontop of that it will disable you from talking in the gambling channel.

If seen gambling or trying to bypass the gambling role, and reported by another player, the role will be taken off you and bank wiped.

(Above could maybe be adjusted or w.e)

This may seem extreme but you want the roll your accept the consequences.

**Comment by LuxrayElite** [comment]
I aren't in the know for gambling, but kill, choose and finish are not intended to be gambling command. 

Kill is a utility used to simulate drop tables.

Finish is a similar command but extends to minigames/raids.

Choose is just a random choice command. 

I'm unaware of /pick unless that is referencing lucky_pick which should be blocked

Majority of the other stuff can be resolved discord side and wouldn't require any hard coding in the bot.

Current commands covered by the gambling ban:

Duel, Lucky pick, slots, dice, hot cold, give random item.

It took roughly 3 years for a gambling block to be implemented, it would be nice to support those who opt-out but don't want  to restart as iron. (Although we're welcoming in the ironcord)

**Comment by nwjgit** [comment]
- `.roles nogamble` 
Type this into any channel will block all the gambling specific channels.

- `/config user toggle name:Lock Self From Gambling (Currently Off)`
Run this command to black gambling commands

Anything more than this won't accomplish anything. Even if those five commands are blocked, you and another person could still send your minion to /k 5 imps and use the loot value to determine a winner for whatever was wagered. 

I suggest doing the above two commands and if that isn't enough make your minion an ironman. There is also the option to ask any mod to blacklist you. If this is a serious issue, especially if it manifests IRL, I encourage you to seek professional help.
