### ISSUE TITLE
Gatherer's Cape doesn't give +100% like farming master cape

### ISSUE THREAD

**Issue by ColossalSeagull** [oldschoolgg/oldschoolbot#5386]
## 🐛 Bug Report

After the update the Gatherer's Cape doesn't give +100% like farming master cape does. See screenshot below. Extra proof that I have it on can be seen in that I saved 50% seeds.

![image](https://github.com/oldschoolgg/oldschoolbot/assets/96855950/7ea53a67-3fff-4b2f-9539-e111aa784aa5)

**Comment by gc** [comment]
Fixed in next update. Thank you for reporting.
