### ISSUE TITLE
/k info - Wildy spiders

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#5390]
## 🐛 Bug Report

Currently you cant do /k show_info:True for Spindel or Venenatis returns application did not respond

![image](https://github.com/oldschoolgg/oldschoolbot/assets/12814878/f262d72d-6812-410e-bc0c-d99c9de9b89f)

**Comment by nwjgit** [comment]
Spindel and Venenatis now work with /k show_info:True
