### ISSUE TITLE
Log basket doesn't work when equipped

### ISSUE THREAD

**Issue by DayV-git** [oldschoolgg/oldschoolbot#5399]
## 🐛 Bug Report

Log basket doesn't give the 5 mins extra time when equipped, since it uses the `owns` command which appears to default to not checking gear 

https://github.com/oldschoolgg/oldschoolbot/blob/32a86be282421750a800614576516d01d5c2c667/src/lib/skilling/functions/determineWoodcuttingTime.ts#L38
https://github.com/oldschoolgg/oldschoolbot/blob/32a86be282421750a800614576516d01d5c2c667/src/lib/MUser.ts#L667

**Comment by gc** [comment]
Fixed in next update, thank you for reporting.
