### ISSUE TITLE
Abyssal amulet boosts aren't working properly

### ISSUE THREAD

**Issue by kiddoooooooo** [oldschoolgg/oldschoolbot#5410]
## 🐛 Bug Report

Noticed that the boosts on the abyssal amulets are inaccurate for the tiers pictured below. Tiers have 70/75/85 % boosts but all are only receiving 50% boost. The elemental and elder tiers are accurate at 65%. I was not able to test the combo runes. 

![image](https://github.com/oldschoolgg/oldschoolbot/assets/98784267/cb1abb66-1c95-415f-9469-ab37f09f6f10)

**Comment by nwjgit** [comment]
This isn't a bug or issue. The rates were nerfed back in august of 2022 here https://github.com/oldschoolgg/oldschoolbot/pull/4393 and the wiki was never updated to reflect the nerf. This should be reported in the #wiki channel on the main discord.

**Comment by nwjgit** [comment]
I mentioned it to them here: https://discord.com/channels/342983479501389826/847902471271874580/1197913082953990204
just letting you know so we don't double post the same issue.
