### ISSUE TITLE
[bso] Ash Sanctifier does not give 5x xp

### ISSUE THREAD

**Issue by BigLazyturtle** [oldschoolgg/oldschoolbot#5420]
## 🐛 Bug Report

Provided image below. 24,650xp/290 ashes = 85xp/ashes (699,528,991 - 699,504,341 = 24650)

Per osrs wiki its 85xp per ash - https://oldschool.runescape.wiki/w/Abyssal_ashes

It should be giving 425xp per ash in this specific case for bso.

![image](https://github.com/oldschoolgg/oldschoolbot/assets/105060609/2638d80c-ebbd-48f6-acf7-25bf0a97f98f)

**Comment by BigLazyturtle** [comment]
Also now that I see it, it should be checking if you have the elite Kourend & Kebos diary or it should instead give 42.5 xp per (this would also affect osb)

![image](https://github.com/oldschoolgg/oldschoolbot/assets/105060609/2fae404f-be8a-43df-a25d-8c65789e1dee)

**Comment by gc** [comment]
Fixed in next update
