### ISSUE TITLE
Herbs cleaned during farm runs do not get tracked in personal herblore data

### ISSUE THREAD

**Issue by Redquaker** [oldschoolgg/oldschoolbot#5428]
## 🐛 Bug Report

See pictures below for an example of herbs cleaned during a farm run not being logged into personal herblore data. These herbs also don't seem to count towards the relevant BSO leagues task for cleaning herbs.

**Before**
![image](https://github.com/oldschoolgg/oldschoolbot/assets/59510368/6b2df413-cb43-4b6b-a34d-438dfa087606)

**Trip Return**
![image](https://github.com/oldschoolgg/oldschoolbot/assets/59510368/dc3fd9dd-76ca-40aa-bba7-2c8e8116ce3b)

**After**
![image](https://github.com/oldschoolgg/oldschoolbot/assets/59510368/e6489e5b-3881-4244-966c-a1eb6b06371d)

**Comment by gc** [comment]
Fixed in an upcoming update
