### ISSUE TITLE
Cox Chincannon

### ISSUE THREAD

**Issue by DarkBugz** [oldschoolgg/oldschoolbot#5432]
Currently chincannon does not give 60% boost in masses. The 60% is divided by the team size but it only counts one persons chincannon. In a 10 man mass this is a mere 6% boost while no one gets loot. The original proposal of chincannon was that only one user would need chincannon to get the full effect. I think it should be changed so that no matter the mass size you get a 60% boost in exchange for no one getting loot.

**Comment by gc** [comment]
Fixed in next update
