### ISSUE TITLE
Skilling mass minigames option.

### ISSUE THREAD

**Issue by KnOwNTooWeLL** [oldschoolgg/oldschoolbot#544]
It would be cool if you could do some type of skilling mass like wintertodt or blast furnace to the game and the more people you had the better rate at which you got more exp or higher chance for better items or more items etc. maybe have a 30 cap out or 25 whatever you guys think is best so it balanced. maybe there could be a type of efficiency bonus per person maybe 1 or 2% giving a higher rate of ores at blast furnace. I just thought of it so this is about all I got is just a small idea.

**Comment by Lajnux** [comment]
Duplicate/Similar. Connected with #524 . Close issue.
