### ISSUE TITLE
Allow people to go to Gambling Rehab

### ISSUE THREAD

**Issue by EngageV2** [oldschoolgg/oldschoolbot#547]
Seen this on a RSPS & it worked for me and others

Allow for a +rehab or =rehab or some sort of +stopgambling command that once entered you’d get a confirm prompt. And upon saying confirm 

Your account would be Locked From Dicing/Dueling or receiving invites for dicing/dueling for X amount of time
On the RSPS it lasts until you do the command again. 

Whoever is reading this might think its stupid, but if you ask around im sure it’d be something people wouldnt mind and gamble addicts would appreciate, especially those who just get a ton of duel invites

**Comment by Alexsuperfly** [comment]
the bot is not your mother, if you dont want to gamble dont do it
