### ISSUE TITLE
[OSB] Multiple Same Trip Returns

### ISSUE THREAD

**Issue by FatOrangeKitty** [oldschoolgg/oldschoolbot#5495]
## 🐛 Bug Report

No idea what caused this, but I got the same 4 return messages in rapid succession, and I'm 99% sure I received all loot. Was just a standard trip, did nothing special before or after.
![image](https://github.com/oldschoolgg/oldschoolbot/assets/41413252/6c332978-18a4-4753-9426-3487931e5314)

**Comment by nwjgit** [comment]
I've been tracking this for about a month and haven't seen this happen or reported anywhere else. If i had to guess it was just some one time server latency issue. If it happens again feel free to report it again.
