### ISSUE TITLE
Junk chance for magical runes.

### ISSUE THREAD

**Issue by bigsquid69** [oldschoolgg/oldschoolbot#5500]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

I have been disassembling runes for magic mats. And have noticed all the runes are not giving accurate junk/ the junk chance. Wrath runes shows. 19.24% and i have been regularly getting 43-44% on full trips. Same for elder runes. They should give 2% junk max. And they give way more. Thanks 🙏

**Comment by DarkBugz** [comment]
Runes have an additional chance to produce junk as part of their materials. Similar to how a bow can give 40% dex 40% idk and 20% whatever. Runes give x% magic and x% junk. On top of the failure chance to get junk based on the level.

**Comment by nwjgit** [comment]
I imagine you're comparing the junk received, at the end of the trip, to "Junk Chance: xx.xx%" at the start of the trip. 

Runes materials given, by percentage, are: powerful: 10, magic: 30, base: 30, junk: 30. This means with 0% junk chance you will still receive 30% junk. Then you must factor in junk chance. Using wrath runes with no boosts, gives junk chance of 24.24%. This effectively makes your junk received 46-47% of the original quantity for wrath runes. 

This isn't a bug but would make for a good suggestion to change how "Junk Chance: xx.xx%" is presented to the users.

**Comment by gc** [comment]
@nwjgit Explained it right.
