### ISSUE TITLE
Leagues command bugged

### ISSUE THREAD

**Issue by Coollegolas** [oldschoolgg/oldschoolbot#5501]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

Since the end of July, all forms of this command, including "leagues claim," "leagues show_all_tasks," and "leagues check," have ceased to function properly on my account. I have observed that these commands are operational for most other players, indicating that this issue is specific to my account or configuration. I know at least Saiyan is also having the issue if there's something in common between our accounts.

Issue Details:
Affected Command(s): /leagues, leagues claim, leagues show_all_tasks, leagues check.
Date of Issue Onset: End of July (specific date not available).
Issue Type: Command functionality failure.
Account Status: Other players can use the commands successfully.
Reproducibility: Consistently failing for my account.

Let me know if there's anything else you need.

**Comment by gc** [comment]
I'll follow up with you on discord about this, try to ping me when youre online (and im online too)

**Comment by gc** [comment]
Fixed
