### ISSUE TITLE
Inconsistent trip returns for wildy content with PKers

### ISSUE THREAD

**Issue by Redquaker** [oldschoolgg/oldschoolbot#5510]
## 🐛 Bug Report

Any wildy activity with PKers (essentially, wildy bosses + revs) seems to have a chance for trip return messages to not post. Since it's only a "chance to happen", it seems likely that this may occur whenever a death happens (also a "chance to happen"). Perhaps the code is breaking when it determines that a death occurs?

Due to the nature of a trip return not happening, I can't really provide any good picture evidence of this.

The entire trip is voided, no KC is gained, no items are gained. The code seems to just crash.

**Comment by Redquaker** [comment]
Here's a decent enough picture of it happening

![image](https://github.com/oldschoolgg/oldschoolbot/assets/59510368/276deece-fb2f-4a71-ace8-83d99d04d256)

**Comment by nwjgit** [comment]
The quick fix is to not use anything in your ammo slot in wildy. 
i'll work on an actual fix here soon.

**Comment by nwjgit** [comment]
Edit: You need to put a blessing in the wildy slot for the trip to not vanish.
I'll find a fix here soon.
