### ISSUE TITLE
Mysterious tree contracts only give 1 seed pack

### ISSUE THREAD

**Issue by gpRollMaster** [oldschoolgg/oldschoolbot#5523]
Is there a reason mysterious tree contracts only give 1 seed pack instead of the standard 3 (4 if arcane harvester is enabled)?
If arcane harvester is enabled, still only gives 1

![Screenshot_20231115-182127](https://github.com/oldschoolgg/oldschoolbot/assets/97349844/ee17ac23-9b7f-4158-873f-dcaf89c6b3ea)
![Screenshot_20231115-182711](https://github.com/oldschoolgg/oldschoolbot/assets/97349844/6551bf0d-e607-430b-9440-87bb75b7001e)
![Screenshot_20231115-185048](https://github.com/oldschoolgg/oldschoolbot/assets/97349844/d8bc742e-e7de-4626-a088-4cf081b8ad0c)

**Comment by nwjgit** [comment]
The jane message also isn't showing the correct amount of seed packs

**Comment by nwjgit** [comment]
Fixed.
