### ISSUE TITLE
Wildy trips still vanish

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#5538]
## 🐛 Bug Report

#5513 did not seemingly catch everything regarding wildy trips vanishing 

(Checked that this pr was live before creating the issue)

![IMG_20231209_110237](https://github.com/oldschoolgg/oldschoolbot/assets/12814878/70b8ed0c-5ba6-44c5-8e18-cf87a5248d17)

**Comment by nwjgit** [comment]
Can you provide more detail, which bot, what trip, original trip message.

**Comment by nwjgit** [comment]
I went back and tested this myself. Everything works fine and I haven't seen any reports of this happening in the main server. There isn't any relevant information in the provided screenshot. If this issue is happening please provide the requested information in a new issue thread.
