### ISSUE TITLE
/kill OSB VS BSO Limit

### ISSUE THREAD

**Issue by RaymondRu** [oldschoolgg/oldschoolbot#5556]
## 🐛 Bug Report
The /kill command doesn't work with patron limits for most BSO specific monsters
ALSO
Moktang apparently doesn't have a limit on the /kill

**Comment by nwjgit** [comment]
Moktang is fixed next update, and custom BSO monsters have their max `/kill` quantity reduced by 75%. so the max a T3 could do normally is 250_000 but for a bso custom monster it is 62_500
