### ISSUE TITLE
false daily reward and answer

### ISSUE THREAD

**Issue by Fr00bik** [oldschoolgg/oldschoolbot#556]
## 🐛 Bug Report
https://gyazo.com/e493e7a8ace787cf718d7223e426bf11
so i typed daily,and i got this question wich i instantly answered coz it was easy one,and it said that its incorrect answer lol

**Comment by NotShin** [comment]
You need 32 quest points or more.

**Comment by Fr00bik** [comment]
uggh i always was thinking its 33 coz all f2p quests complited":{ my bad
