### ISSUE TITLE
Divination Issue Thread

### ISSUE THREAD

**Issue by nwjgit** [oldschoolgg/oldschoolbot#5602]
Making a list of issues related to Divination myself and the community have made note of. Anyone feel free to add to the list, I'll bring other threads in here as well to keep the issue spam down.

- Cache minigame doesn't ping the user on return
- Spirit weed crop yields spirit weed and not grimy spirit weed (grimy spirit weed is already coded)
- No quantity for harvesting energy
- No Divination collection log
- No Divination bank filter
- Spirit weed missing mini bank label similar to other herbs
- Guthixian Caches cl doesn't show completions
- Can't see guthixian cache charge amount anywhere
- Add cache minigame to cooldown list
- Doopy doesn't send a notifcation to main discord
- ~~Divination cape/hood missing from cl capes~~ https://github.com/oldschoolgg/oldschoolbot/pull/5613
- Add diviners outfit to global presets

**Comment by nwjgit** [comment]
Could also add: `await user.addToGodFavour(['Guthix'], data.duration);` to guthixianCacheActivity.ts to give guthix rep when doing caches.

**Comment by TURB042O** [comment]
> - Spirit weed crop yields spirit weed and not grimy spirit weed (grimy spirit weed is already coded)

![Screenshot_20240130_172433_Discord.png](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/70d80224-bfd4-4fca-be82-f8be8761e566)

do you have this enabled?

**Comment by TURB042O** [comment]
> - Can't see guthixian cache charge amount anywhere
![Screenshot_20240130_173223_Discord.png](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/44631346-0a84-4384-8556-1a1e160dacdf)
it gives a boost. From what I can tell that about it


> - Add cache minigame to cooldown list
it resets at 12am UTC everyday for everyone, no need for it to be on cd list. but what it does need is a button like fishing contest has that appears when it is available and you haven't done it yet for the day.

**Comment by TURB042O** [comment]
why are my comments being deleted?

**Comment by nwjgit** [comment]
> why are my comments being deleted?

This isn't a discussion thread. This is for tracking issues with divination. I'll add any issues you comment to the main body. The information from the deleted comments didn't provide anything valuable. 

If you would like to start a discussion on anything related to divination that can be handled in the main discord server.

**Comment by TURB042O** [comment]
> > why are my comments being deleted?
> 
> This isn't a discussion thread. This is for tracking issues with divination. I'll add any issues you comment to the main body. The information from the deleted comments didn't provide anything valuable. 
> 
> If you would like to start a discussion on anything related to divination that can be handled in the main discord server.

I'm banned remember?

and how did they not hold anything of value? the farm trips don't give grimy herbs because clean herbs on farm trips is more than likely on.. etc. my bad this isn't a discussion thread but i feel that some of your issues aren't actually issues.

**Comment by LuxrayElite** [comment]
Add diviners outfit to global presets

**Comment by TURB042O** [comment]
### these are not issues so you should remove them from _your_ list.

in response to:
> - Add cache minigame to cooldown list

![SmartSelect_20240130_184722_Discord](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/713626f3-27cd-4b30-9fed-46e67aa20028)
I brought the thought up with cyr and this was how he put it in his response.

in response to:
> - no quanity for harvesting energy

![Screenshot_20240131_172848_Discord](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/761e0224-e188-46a0-bfdd-7d3c0f0d347e)
it definitely tells you how much energy has been collected. only reason it wouldn't is if one is doing ancient and hasn't unlocked the city of Atlantis

in response to:
> - Spirit weed crop yields spirit weed and not grimy spirit weed (grimy spirit weed is already coded)

![Screenshot_20240130_172433_Discord](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/6d006e50-3ac9-4b53-aae4-b4e70a85cfbc)
u might wanna toggle this off in `/config user toggle`


now you may delete this or you may mark it off-topic but let me be real I'm not trying to cause issues I'm just helping out.

**Comment by LuxrayElite** [comment]
> * no quanity for harvesting energy

I believe this in reference to the command that you are forced to send a full trip instead of X memories/energy

`/divination harvest_memories energy:Ancient (Level 110) type:Convert to Energy quantity: 10` for example

Amount of energy =  Memories collected /10

**Comment by nwjgit** [comment]
> now you may delete this or you may mark it off-topic but let me be real I'm not trying to cause issues I'm just helping out.

- I think it should be added to cooldown list, ultimately it's up to Magna to decide, everyone else is just a recommendation.
- What Lux said about the energy quantity.
- This isn't a toggle issue. You can check the code yourself that Spirit weed crops yield spirit weed, not grimy spirit weed.

Again this isn't a discussion thread. There isn't anything to fix, troubleshoot, or discuss besides posting current issues. Here is an example https://github.com/oldschoolgg/oldschoolbot/issues/5602#issuecomment-1918909768 I'll add these issues to the main post. This is just a place to track current issues with divination. Any discussion can be handled on the main discord server. If you're banned from the discord server that should be handled with a ticket and or the mods.

**Comment by TURB042O** [comment]
![SmartSelect_20240201_081415_Discord.png](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/be7a1555-823a-4047-be75-214e5f9b864c)

u can cross off the ping on trip return jonesy <3
