### ISSUE TITLE
Nightmare mass fail

### ISSUE THREAD

**Issue by AvariceBrah** [oldschoolgg/oldschoolbot#5603]
## 🐛 Bug Report
 # OSB AND BSO

Nightmare mass, immediately sends a trip and says. 

-`BSO avaricebrah's party of 4 is now off to kill 7x Nightmare. Each kill takes 5 minutes, 1 second instead of 25 minutes----`

-`OSB avaricebrah's party of 4 is now off to kill 6x Nightmare. Each kill takes 5 minutes, 9 seconds instead of 25 minutes-----`

Checking the trip says 
`OutofNamesinc. is currently killing The Nightmare in a team. 29 minutes, 45 seconds remaining.`

Running check mass yields no return regarding the trip. 

# #
Was going to Duo nightmare with someone I'm reintroducing to bso but can't....

**Comment by LuxrayElite** [comment]
Majority of massing content now uses fake masses with "bots" with the exception of raids

So this is working as intended

**Comment by LuxrayElite** [comment]
![image](https://github.com/oldschoolgg/oldschoolbot/assets/12814878/616a45ce-04dc-4382-8405-9963ee1ed69c)
Its been over 2 years since legitimate masses were possible

**Comment by nwjgit** [comment]
Not an issue. Nightmare is no longer able to be massed with real players. `/k name:Mass Nightmare` just sims a four person mass with your minion and 3 copies of your minion.
