### ISSUE TITLE
Completionist Cape doesn't give you back quest Master Cape when you revert it

### ISSUE THREAD

**Issue by slippy3** [oldschoolgg/oldschoolbot#5614]
## 🐛 Bug Report

When you revert completionist Cape, it doesn't have quest Master Cape added to the list of capes to refund, but requires you to have one when purchasing a completionist Cape. gg 1b sadge

**Comment by nwjgit** [comment]
I made a fix for it. I'm pretty sure it was just an oversight. You could probably check with Cyr/Magna or open a ticket to get a refund.

**Comment by nwjgit** [comment]
Fixed next update.
