### ISSUE TITLE
Reset /lb completionist when new reqs get added

### ISSUE THREAD

**Issue by slippy3** [oldschoolgg/oldschoolbot#5615]
## 🚀 Feature Proposal

Reset the lb when new reqs get added, it only changes people's percentages if they personally do /completionist check. The way it is currently there won't ever be a new first to comp cape when new reqs get added unless everyone's percents get reset for the update or every currently comped player does /completionist check to reset their own percentage

**Comment by gc** [comment]
Done in next update (added a command for us to reset it)
