### ISSUE TITLE
Remy does not boost cooking (well only tested wine making) 

### ISSUE THREAD

**Issue by Rupz2** [oldschoolgg/oldschoolbot#562]
Equipped Remy in range head. Boost did not work. Tried changing to skilling head but still had same trip of 1000 jugs made and 200k xp
![Screenshot_20200827-182109_Discord~2](https://user-images.githubusercontent.com/68561490/91505569-cfc2af80-e8c7-11ea-96ec-044d822a94b5.jpg)

**Comment by gc** [comment]
Remy doesn't help with making wine :(
