### ISSUE TITLE
training manual

### ISSUE THREAD

**Issue by bowiRS** [oldschoolgg/oldschoolbot#5637]
When using the manual, it does not say how much exp you got (lamps do say it). It should appear in the redeem message. “You received XXX exp”

![image](https://github.com/oldschoolgg/oldschoolbot/assets/79149170/70a4e74e-e0f2-441c-a5a9-11077ff3fa8b)

**Comment by TastyPumPum** [comment]
User is at max xp in the skill the lamp was used on, reviewed the code and it works otherwise
