### ISSUE TITLE
Can we buff BSO masses

### ISSUE THREAD

**Issue by EngageV2** [oldschoolgg/oldschoolbot#564]
Can we please get more kills per person 
In masses.. similar to OSB

Already spoke to magna about it. But github incase someone forgets

**Comment by Lajnux** [comment]
same comments as #542 also Zak the Yak is now a thing that boosts trip length of raids by a lot making masses even more efficient (if enough ppl, but that's up to the mass hosters to get togheter a nice mass team). Close issue
