### ISSUE TITLE
Guthixian cache minigame score not being counted

### ISSUE THREAD

**Issue by DarkBugz** [oldschoolgg/oldschoolbot#5649]
It's been over a week and no one is on the high scores. On top of that, music cape is saying i need to do a cache trip still.

**Comment by TURB042O** [comment]
> It's been over a week and no one is on the high scores. On top of that, music cape is saying i need to do a cache trip still.

![SmartSelect_20240205_063013_Discord](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/a0a17022-eb6d-49d1-b7f2-d11b1a4581c3)
what are you talking about?

**Comment by TastyPumPum** [comment]
> > It's been over a week and no one is on the high scores. On top of that, music cape is saying i need to do a cache trip still.
> 
> ![SmartSelect_20240205_063013_Discord](https://private-user-images.githubusercontent.com/133211494/302289018-a0a17022-eb6d-49d1-b7f2-d11b1a4581c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDA5NTksIm5iZiI6MTcwNzE0MDY1OSwicGF0aCI6Ii8xMzMyMTE0OTQvMzAyMjg5MDE4LWEwYTE3MDIyLWViNmQtNDlkMS1iN2YyLWQxMWIxYTQ1ODFjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxMzQ0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjkzOTIyZmY1MTMxYTI4OTYyNzE4MGJlNjk1MjkwMDVmYzMyNDNjMjhhMThiY2QyOTFhOTRiYmI1OTA2ZjMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AIQimYlqlqaujLGm-YlrD-kiz6vYK2-QxYouYCEDyho) what are you talking about?

Was fixed in #5651
