### ISSUE TITLE
despite stronghold of security is not repeatable, it has repeatable button.

### ISSUE THREAD

**Issue by badgehunter** [oldschoolgg/oldschoolbot#5650]
## 🐛 Bug Report

![image](https://github.com/oldschoolgg/oldschoolbot/assets/31507359/a5ed20bd-7e03-4555-862a-3abb536e7487)

when pressing just repeat trip, it does the same text as if you were just tag it. and if you do /activiteis other stronghold of security, it says that you have already completed it.

**Comment by gc** [comment]
Fixed in next update
