### ISSUE TITLE
Bsominigame divine dominion

### ISSUE THREAD

**Issue by AvariceBrah** [oldschoolgg/oldschoolbot#5658]
# 🐛 Bug Report

## divine_dominion 

/bsom ...... ce_god_item command returns the following now.

**That item doesn't exist.**

Favor check still works fine though.

**Comment by TURB042O** [comment]
> # 🐛 Bug Report
> ## divine_dominion
> /bsom ...... ce_god_item command returns the following now.
> 
> **That item doesn't exist.**
> 
> Favor check still works fine though.

![Screenshot_20240206_153127_Discord](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/9abc259d-e85f-4f94-a858-c42da627eef0)
you need to select item then jtll show you a list
