### ISSUE TITLE
2 Future Suggestions. Inferno & Runecrafting

### ISSUE THREAD

**Issue by EngageV2** [oldschoolgg/oldschoolbot#570]
Inferno: Literally same as fightcaves with a few twists

Its obviously lower % chance of success
Requires 10 fire cape sacrifices  to be able to start doing the =inferno or :inferno minigame. 
(Maybe if u sacrifice 100 fire capes you instantly get a inferno cuz thats alot of time and why not)
Once you sacrifice the 10 capes u dont have to sacrifice anymore unless you want to do the 100 for instant cape. 

Edit: changed it to just The inferno suggestion

**Comment by Alexsuperfly** [comment]
these are two distinctly separate features, can you make a separate issue for each

**Comment by Lajnux** [comment]
Come up with dynamic and interesting ways of implementing this in to the bot that would be based on knowledge about current inferno. 

Make a new suggestion with title ''Inferno'' and gather ideas and information that would be helpful towards making this a thing in future, take help from wiki, other peoples opinions and so on, and think of it from a global standpoint for both bots and not just BSO. 

Close issue and make a new suggestion that got some meat on the bones so to say.
