### ISSUE TITLE
Untradeables mystery box item

### ISSUE THREAD

**Issue by KrugGrunt** [oldschoolgg/oldschoolbot#571]
I opened an untradeables mystery box on BSO a few minutes ago and received an initiate platebody. Initiate armor is tradeable.

**Comment by kevinsmendes** [comment]
Please, run the following command: `=b 10619a`. If it shows `You have 1x Initiate hauberk`, then it is currently working (we have a PR for this fix). OSRS has two IDS for the Initiate hauberk, one being Tradeable_on_ge with the id 5575 and another duplicate, that is not Tradeable_on_ge, with the ID 10619.

**Comment by Lajnux** [comment]
#559 will close this issue.

**Comment by Lajnux** [comment]
merged #559
