### ISSUE TITLE
Agility arena - cant repeat trip

### ISSUE THREAD

**Issue by LuxrayElite** [oldschoolgg/oldschoolbot#5716]
## 🐛 Bug Report

This report is prior to the changes going live but raised it here with no response:
https://github.com/oldschoolgg/oldschoolbot/commit/eb23dd523a2d6bf02bbdc7a14cd5a48d92f6da92#r138944932

Users will be unable to repeat the agility arena trips

**Comment by TastyPumPum** [comment]
It was duplicated and the duplicated one has been removed. Tested and the repeat function is working.
