### ISSUE TITLE
Harry not giving bonus marks of grace

### ISSUE THREAD

**Issue by DarkBugz** [oldschoolgg/oldschoolbot#5723]
Title. Appears to have broken when Divination was released. Also might be possible that gorajan shards arent dropping at daemonheim but it's difficult to know if that's the case since they're so rare.

**Comment by nwjgit** [comment]
![Discord_AWpH2sV7Oo](https://github.com/user-attachments/assets/b2ad9f24-38b9-4ba5-a1e1-b3eaccfd335e)
![Discord_JAyLOcNmdu](https://github.com/user-attachments/assets/f6790b08-815f-4597-a7c3-5e0174afda82)

This was about 6 weeks ago and everything appears to be working fine. If you have any other context feel free to re-open and post.
