### ISSUE TITLE
BSO: Return from cooking trip showed double the amount 

### ISSUE THREAD

**Issue by AbandonThyShip** [oldschoolgg/oldschoolbot#573]
Doing cooking of wines in BSO and when returning from trip it showed I cooked 1k jug of wines and received 2k jug of wines
![09DE729E-AB8D-4089-9C38-F621F144844A](https://user-images.githubusercontent.com/46854310/91671734-1a1d7980-eade-11ea-8d2a-fec74b10dd94.jpeg)

**Comment by thievious1** [comment]
your trip was doubled, you got a mystery box with your wines

**Comment by AbandonThyShip** [comment]
Still learning all the little quirks of BSO I guess sorry. Thanks!
