### ISSUE TITLE
Completionist cape doesn't work at Solis

### ISSUE THREAD

**Issue by Usvaaa** [oldschoolgg/oldschoolbot#5736]
## 🐛 Bug Report

Completionist cape doesn't work at Solis in place of Combatant's cape, even though completionist cape should have all the effects of the master capes

![ZKjpk3p 1](https://github.com/oldschoolgg/oldschoolbot/assets/145182372/6b8cf698-e563-47d7-80f9-b89a2e0cd574)

**Comment by nwjgit** [comment]
comp and comp t are now similar items to combatant's cape.
