### ISSUE TITLE
Atomic energy isn't being tracked when created.

### ISSUE THREAD

**Issue by Coollegolas** [oldschoolgg/oldschoolbot#5738]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

Making atomic energy via /create item:revert x energy does not add it to your CL for creatable items. I've created over 3m and have 0 tracked. 

Let me know if you need more info, but it's fairly easy to reproduce.

**Comment by nwjgit** [comment]
This now properly tracks
