### ISSUE TITLE
Infernal & Seranic Armour?

### ISSUE THREAD

**Issue by EngageV2** [oldschoolgg/oldschoolbot#574]
![B34279DB-045D-4D8A-AEEC-B86EE21050DE](https://user-images.githubusercontent.com/69174970/91711065-43c4b800-eb53-11ea-8c2e-9e3a859da1f3.jpeg)

Would be new BIS for fight caves & inferno if based on accuracy.

Armour pieces can be dropped VERY rare from Chaos ele, Venenatis or maybe a new NPC?

**Suggestion #2** 
Inferno Dragons/Armour?

On the Pserver i played, these were in 30ish wildy looked like a shiny Lava Dragon, and the armour they dropped was called Infernal armour infernal longsword, they also dropped infernal keys.The armour dropped around 1/200 and keys was 1/90

The armour looked like uhh rockshell?
 but shiny same color as the dragon
The Sword looked like some weird looking longsword. Its effect was the spec was a Vesta’s longsword spec but 5-10% stronger. But if not specing it was as strong as d scim iirc
The boots was +2-5 better Strength than Primordial boots
And i think the armour was just some tank gear. cant remember but yeah....

The Infernal keys opened the infernal chest
Which had the Infernal boots in them. 2-10m coins, around 200 uncut dragonstones, 200-400 Dragon bones, 100-200 lava dragon bones, uncut Onyx, 400 anglerfish, and the Infernal longsword

So even if u got a key u was like ohh nice, and the bones always helped

**Comment by gc** [comment]
#bso-vote! if you still want this
