### ISSUE TITLE
New BSO Pet Klik functions like lil lamb

### ISSUE THREAD

**Issue by drbobbert** [oldschoolgg/oldschoolbot#575]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/69747044/91787720-d77aaf00-ec4d-11ea-9f02-b757eea5dce4.png)
I do not own the lil lamb, I just got Klik. Equipped klik and buried a bone and I got the lil lamb message

**Comment by Lajnux** [comment]
Close issue. Resolved.
