### ISSUE TITLE
Add a /toggle option to disable names in openable loot

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#5750]
## 🚀 Feature Proposal

Recent update included names being shown for every item in /open . This makes sense for BSO, but a toggle would be REALLY nice because it clutters up the image. The attached image is what I am referring to: (Applies to stuff like Clue scroll caskets too)
![image](https://github.com/oldschoolgg/oldschoolbot/assets/63373565/e8ac27cd-d44e-4d0f-9811-27386a33a51c)

**Comment by nwjgit** [comment]
`/config user toggle name:Disable Names on Opens`
