### ISSUE TITLE
Wines of Zamorak Fail rate

### ISSUE THREAD

**Issue by Azemotay** [oldschoolgg/oldschoolbot#5751]
## 🐛 Bug Report
![image_2024-03-06_031005419](https://github.com/oldschoolgg/oldschoolbot/assets/161771721/28ab225b-918f-4dd5-bfd9-3f0bb44c8025)

99 cooking with a 25% fail rate on wines. Should be 100% at level 98.
(Especially since you made me buy bologas blessings 1 tithe point at a time....)

**Comment by TastyPumPum** [comment]
![image](https://github.com/oldschoolgg/oldschoolbot/assets/79149170/b6e39bc8-a260-4fd6-b8ec-3eec65ba59e2)

Had a look and it looks like the rates are still being used prior to the 1st March 2023 update.
