### ISSUE TITLE
allow TMB Bellator Ring to count as BIS

### ISSUE THREAD

**Issue by TURB042O** [oldschoolgg/oldschoolbot#5753]
## 🚀 Feature Proposal

so there is the Bellator Ring that is created and the one that is from TMB `ID: 28316`. I think both should work as BIS.

**Comment by nwjgit** [comment]
The issue is the beta id's haven't been removed yet. refer to this issue thread: https://github.com/oldschoolgg/oldschoolbot/issues/5284
