### ISSUE TITLE
sell all command

### ISSUE THREAD

**Issue by ralphmtk** [oldschoolgg/oldschoolbot#578]
It would be cool to have a "+sell all" command that basically just sells everything in your bank in exchange for gp.
I really only use the bot to fund my virtual dicing addiction, as i'm sure many others do, and this would be a nice QoL update.

**Comment by Lajnux** [comment]
#600 closes this issue for BSO (maybe OSB in future?)

**Comment by Lajnux** [comment]
a version of this have been implemented. #1130
