### ISSUE TITLE
[OSB] Tempoross combat achievement - rng task

### ISSUE THREAD

**Issue by Lewis7777** [oldschoolgg/oldschoolbot#5781]
Combat achievement - Why Cook? - Subdue Tempoross, getting rewarded with 10 reward permits from a single Tempoross fight.
The osb wiki states: 1/30 chance to be given per kill

This is so much rng for absolutely no reason, the task is easily a 1n done on osrs just by following a little guide for example
https://www.youtube.com/watch?v=wwbglocJf-U

hoping the rng could be tuned down a whole lot, maybe to like a 1/3 chance to get the ca.

**Comment by nwjgit** [comment]
Demonic Weakening should also be reduced to something such as 1/3. it doesn't take 30 attempts to accomplish this ca.
