### ISSUE TITLE
Teak Trees and Forestry Events

### ISSUE THREAD

**Issue by TastyPumPum** [oldschoolgg/oldschoolbot#5786]
Currently you can 1.5t teaks and participate in forestry events, as you can only 1.5t teak at the farming patches this isn't possible in osrs.

It should be changed to 2t teaks while doing forestry events, and 1.5t when not participating in them and you have 35 farming or higher too.

https://oldschool.runescape.wiki/w/Pay-to-play_Woodcutting_training#Levels_35%E2%80%9399:_Teak_trees

![image](https://github.com/oldschoolgg/oldschoolbot/assets/79149170/f822f526-b0d8-47b3-870b-d354d9224388)

**Comment by nwjgit** [comment]
double check all the `/sell` forestry items give anima

https://oldschool.runescape.wiki/w/Sturdy_beehive_parts
