### ISSUE TITLE
Drygore axe not working from bank

### ISSUE THREAD

**Issue by bigsquid69** [oldschoolgg/oldschoolbot#5787]
Unequipped and enabled, /chop only allows 8x multiplier for Dwarven axe . Had to equip drygore axe to make it work. Says on the invention it should work from bank. Thanks 🙏

**Comment by TURB042O** [comment]
> Unequipped and enabled, /chop only allows 8x multiplier for Dwarven axe . Had to equip drygore axe to make it work. Says on the invention it should work from bank. Thanks 🙏

![SmartSelect_20240327_105452_Spck Editor.png](https://github.com/oldschoolgg/oldschoolbot/assets/133211494/dc12d474-47a5-43ac-ba3e-153f875e033f)

its coded to work from bank.

**Comment by TURB042O** [comment]
> Unequipped and enabled, /chop only allows 8x multiplier for Dwarven axe . Had to equip drygore axe to make it work. Says on the invention it should work from bank. Thanks 🙏

#5804

**Comment by gc** [comment]
This definitely should be working from bank, if you're sure it isn't, posting a screenshot or something would be helpful.

**Comment by nwjgit** [comment]
I found the issue to this, its cause of the invention.flags. Drygore Axe is the only one that has two `['equipped', 'bank']` but in invention.ts L678 equipped gets processed before it ever checks for bank and returns false to chop.ts L 221.
