### ISSUE TITLE
No trip return when a boss unique is gained

### ISSUE THREAD

**Issue by bigsquid69** [oldschoolgg/oldschoolbot#5793]
## 🐛 Bug Report

I recently got a purple monkey from MMR and never got a trip return. This trip (i think) netted me a statue and big banana. But i also didnt get a bso notifications popup for completion of the cl .
I went to Scurrius on a /k trip. Completed the cl there. Got trip returns for everything (birdhouse and all /k trips) until the trip contained a boss unique. (Spine) also no return trip. And no bso notification log either

**Comment by bigsquid69** [comment]
This has also continued into grifolaroo's. No trip return or bso notification on completion there either

**Comment by bigsquid69** [comment]
New update. Iron was able to get purps and trip returns. But on completion of cl. It broke. And didnt give a return message again.

**Comment by nwjgit** [comment]
This should have been fixed here: https://github.com/oldschoolgg/oldschoolbot/pull/5833
