### ISSUE TITLE
[BSO] Dice Chuck

### ISSUE THREAD

**Issue by NotShin** [oldschoolgg/oldschoolbot#580]
## 🐛 Bug Report

When you dice all of your GP, it can say the minion ignores your amount and dices your entire cash stack. I think this statement should either be removed or modified so your minion decides to dice a random amount between 10-99% of your GP.

![image](https://user-images.githubusercontent.com/21049385/91857509-fff6af00-ec35-11ea-87c6-a7abf261b0fc.png)

**Comment by Lajnux** [comment]
I don't understand this issue, you want it so if someone wanna dice whole cash stack intentionally you want it to do 10-99% instead?

**Comment by Lajnux** [comment]
resolved #612
