### ISSUE TITLE
[BSO] Lottery System

### ISSUE THREAD

**Issue by kevinsmendes** [oldschoolgg/oldschoolbot#581]
## 🚀 Feature Proposal

Add a lottery system on BSO. Users can buy a ticket once a day for 1m/10m (amount to be decided) and at the end/start of the day, the bot chooses the winner.  The winner gets the entire amount that was used to buy the tickets minus tax (20%+). Maybe it could be made so there is a chance that no one would win the lottery, increasing the total amount of the next day.

With that, a new taxing section can be added, to show how much was lost to tax on lottery.

**Comment by Lajnux** [comment]
A system of this have been implemented.
