### ISSUE TITLE
Barrows sets in required items

### ISSUE THREAD

**Issue by juggalojosh** [oldschoolgg/oldschoolbot#582]
## 🚀 Feature Proposal

It would be awesome if you could add barrows sets to work as required items for boss fights.
Example: to kill vetion you need to have all 4 pieces of verac's, but if you have 1 verac's armour set (in its box set form) it won't let you kill vetion as it dosent use the box set as a required item even though it contains all 4 required items 

I hope I have worded this in a way that makes sense, but otherwise thanks for reading an I hope you have a good day.

**Comment by Alexsuperfly** [comment]
you need the items in item form not a packaged box, how is you minion supposed to wear a box
