### ISSUE TITLE
nex fake mass uses 4x as much ammo

### ISSUE THREAD

**Issue by robotex140** [oldschoolgg/oldschoolbot#5823]
## 🐛 Bug Report

It seems to me that fake mass in nex, you use 4 times as much ammo. When I tested, running a duo with another player for 2 nex kills, it consumed 22 ruby bolts which is correctly around the 50-60 ammo per kill times 0.2 for avas. But when doing a solo fake mass for 5 kills, 233 ruby bolts were consumed. it should consume 50-60 ammo when using avas. I would guess that this is because the fake mass is made from a team that is 4 copies of yourself, and while it does seem like the loot is correctly split for nex since 3 of the copies are marked as "ghosts," so their portion of the loot is deleted, but this logic doesn't seem to be applied when the ammo costs are applied

**Comment by TastyPumPum** [comment]
hey @ellipsis-dev can you implement this?

**Comment by TastyPumPum** [comment]
@ellipsis-dev implement this plan
