### ISSUE TITLE
Question: loot html creation

### ISSUE THREAD

**Issue by MatthewLoller** [oldschoolgg/oldschoolbot#5824]
Hi! I've had your discord bot in my server for a very long time and it's been awesome.

One feature I love is the boss kill simulation and specifically how you generate the image to show the boss loot you get.

I want to build my own bot and generate a similar image for collection logs. I was wondering if the open source js library had something I could leverage to make the images with item IDs and quantities? Or if you could provide guidance on how the feature was made so I can try it. 

Generate html and take a screenshot with a headless browser?

Thanks for any assistance you can offer 😊.

**Comment by MatthewLoller** [comment]
![bank](https://github.com/oldschoolgg/oldschoolbot/assets/25853228/41646e27-e312-46d1-9594-0cf10b7ee913)

**Comment by nwjgit** [comment]
I believe this was answered here: https://discord.com/channels/342983479501389826/648196527294251020/1228909812943687721 if not feel free to ask in chat/make a thread here again.
