### ISSUE TITLE
Wintertoad

### ISSUE THREAD

**Issue by EngageV2** [oldschoolgg/oldschoolbot#584]
Obtained from normal firemaking ANY logs, or from wintertodt?

Upon receiving when doing Wintertodt gives you a good chance at receiving a Mystery Box upon Completion. Also Gives extra bonus xp? 

Or... 

Can give 3-5x the amount of loot.
 Cuz rn idk wintertodt loot pretty poop. Maybe we can spice up the drops just overall? Like idk chance at Full Dragon. Like helm platebody legs or something.

**Comment by Lajnux** [comment]
Close issue, Wintertoad now exist in BSO and boosts fightcaves
