### ISSUE TITLE
Bug With Sale of Zippy Pet

### ISSUE THREAD

**Issue by Hynloran** [oldschoolgg/oldschoolbot#585]
Sale of Zippy pet went through but I do not have the pet nor does the person who sold it to me. It looks like it was a bug when two people tried to sell me items at once...

https://imgur.com/a/xNP9xAH

**Comment by kevinsmendes** [comment]
Do you have the Fremennik Kilt?

**Comment by Hynloran** [comment]
Yes I received the kilt

**Comment by Lajnux** [comment]
This was a combined bug where a mass is sent out at the exact same time as a trade resulting in the bank commands overlapping. Haven't happen since the queue fix.
