### ISSUE TITLE
Add alternative recipes (e.g. super combat potion created using torstol unf potion)

### ISSUE THREAD

**Issue by aneelm** [oldschoolgg/oldschoolbot#5901]
## 🚀 Feature Proposal

Allow players to create certain potions, like Super combat potion(4)	or Anti-venom+(4) using alternative recipes, like using unfinished potions, instead of needing the herb. That way, if you have accidentally make your torstols into unfinished potions, they aren't wasted but can still be utilized they way you meant to. OSRS was updated to allow such recipes in 2019 and 2022 https://oldschool.runescape.wiki/w/Torstol_potion_(unf).

**Comment by DayV-git** [comment]
`/buy name:Torstol` will convert unf potions to torstols
