### ISSUE TITLE
Barbarian Assult boost working backwards?

### ISSUE THREAD

**Issue by bigsquid69** [oldschoolgg/oldschoolbot#5914]
As my kc goes up. My waves get longer and i get less per trip? Seems backwards

<:whiteMinion:673561609913892899> **BigSquid69** is now off to do 20 waves of Barbarian Assault. Each wave takes 2 minutes, 30 seconds - the total trip will take 50 minutes, 7 seconds.

**Boosts:** 30% for honour level, 5.15% for average KC, Each wave takes 2 minutes, 30 seconds.

<:whiteMinion:673561609913892899> **BigSquid69** is now off to do 19 waves of Barbarian Assault. Each wave takes 2 minutes, 39 seconds - the total trip will take 50 minutes, 37 seconds.

**Boosts:** 30% for honour level, 6.15% for average KC, Each wave takes 2 minutes, 39 seconds.

<:whiteMinion:673561609913892899> **BigSquid69** is now off to do 18 waves of Barbarian Assault. Each wave takes 2 minutes, 51 seconds - the total trip will take 51 minutes, 28 seconds.

**Boosts:** 30% for honour level, 7.10% for average KC, Each wave takes 2 minutes, 51 seconds.

**Comment by nwjgit** [comment]
I believe you're just seeing the random variation thrown in. Each wave time is base 4 minutes + or - 10% then all the boosts are calculated in. so each wave for an entire trip could have +24 seconds added to the base 4 min timer, and if you're doing 20 waves thats + 8 minutes to your total trip time. But the inverse is just as likely and it removes 8 minutes. 

The code is here if you would like to see more: https://github.com/oldschoolgg/oldschoolbot/blob/master/src/mahoji/lib/abstracted_commands/barbAssault.ts#L254

Also ventator bow was just added and gives 10% to wave time.
