### ISSUE TITLE
New Pet (By Duramox)

### ISSUE THREAD

**Issue by imgidedin** [oldschoolgg/oldschoolbot#592]
## 🚀 Feature Proposal

1 pet named Dura

Option  on pet  gambels your loot 

" dura " decided to dice against  zulrah and lost and left u with no loot 

" dura " decided to dice against zulrah your items got doubeld!!

All loot can maybe be changed to only uniqs

**Comment by Lajnux** [comment]
Close issue. Connected with #560 and should be posted as comment there.
