### ISSUE TITLE
Double trips

### ISSUE THREAD

**Issue by TalkativeOrphan** [oldschoolgg/oldschoolbot#593]
## 🐛 Bug Report
When i finished with my mole trip i did a +fletch 100 yew short bow trip for some xp, but then it didn't get me the level so when it came back it asked if i wanted another, so i said 'yes' bit it did a trip of the yew bows and the mole trip from earlier, both running the same time
![2020-09-03 23_48_31-Window](https://user-images.githubusercontent.com/70737182/92197558-183a1a00-ee40-11ea-91d6-a77bdb235e1d.png)

**Comment by Alexsuperfly** [comment]
the mole trip response was still watching for a yes, since your fletching trip was so fast it came back before
 mole timed out.  This is a mainly just a problem with patrons and their extended 10 min response timer
