### ISSUE TITLE
bsominigames baxtorian_bathhouses

### ISSUE THREAD

**Issue by Wasted-Ellis** [oldschoolgg/oldschoolbot#5931]
## 🐛 Bug Report

When doing Baxterian bathhouse it doesn't notify you when you get a purple no icon or anything the collection log item used to show up with a purple square next to the start of the finished session. Now it just has it to where it shows just the items in the screen of other items you get and nothing else. 

TO give a better example it would be like playing Monkey Rumble and nothing to indicate a purple monkey. 

![Discord_FWjElKIHL8](https://github.com/oldschoolgg/oldschoolbot/assets/173967502/e7c0ee4d-5eff-4102-aea6-ffca3d2fb7b8) (shows how it used to be when you got a CL LOG)

**Comment by nwjgit** [comment]
This message was removed and replaced with a loot image in this commit: https://github.com/oldschoolgg/oldschoolbot/commit/240751bd3006f7231f40af1a4e7c1ec5f1306564#diff-7e81daea05a153bfd4fc85eb887c43507da66ecab9c8b6bfc6f020768a26f311 

This isn't a bug but feel free to open a new thread if you would like to suggest it be changed.
