### ISSUE TITLE
Smithing bank tag bug

### ISSUE THREAD

**Issue by mmekker** [oldschoolgg/oldschoolbot#594]
When showing the bank using the --sm tag, it shows all godsword shards instead of blades. The blades are shown correctly for the --smithing tag.
"+b --smithing"
![file-1](https://user-images.githubusercontent.com/13545687/92288893-9815c200-eedc-11ea-8b7f-2ae74277fc59.jpg)
"+b --sm"
![file](https://user-images.githubusercontent.com/13545687/92288894-98ae5880-eedc-11ea-832f-4aaf85117bb7.jpg)

**Comment by Alexsuperfly** [comment]
you crafted the blade between commands

**Comment by mmekker** [comment]
no
