### ISSUE TITLE
Editing a gear preset sometimes removes item from ammo slot in that preset

### ISSUE THREAD

**Issue by Usvaaa** [oldschoolgg/oldschoolbot#5961]
I've noticed my blessing being removed from the ammo slot of the preset, when editing the preset. So for example I have rada's blessing 4 in the gear preset -> edit the preset to change the item in the helm slot -> rada's blessing 4 is no longer in that preset. I've only tried this in the preset for "Wildy".

![JPPx2zj 1](https://github.com/user-attachments/assets/bcec863c-bd22-492c-a0cd-277182fd3f31)

**Comment by gc** [comment]
Fixed in next update
