### ISSUE TITLE
Adding runners to RC

### ISSUE THREAD

**Issue by bowiRS** [oldschoolgg/oldschoolbot#5976]
A simple Yes/No toggle for runners when doing RC which will cost gp. Sort of how you can solo a ‘mass’ in pvm you simulate people running for you

**Comment by TastyPumPum** [comment]
https://github.com/oldschoolgg/oldschoolbot/pull/5327

Magna wanted the relevant discussion on this  with a general consensus for it. before it gets added, fishy already did the code and it got denied.
