### ISSUE TITLE
Black Mask (10) completely broken

### ISSUE THREAD

**Issue by Jamsterman25** [oldschoolgg/oldschoolbot#5983]
## 🐛 Bug Report

My iron minion has 2 black mask (10)’s I cannot create a slayer helm, I cannot imbue them, I cannot uncharge them. Please fix this.

**Comment by nwjgit** [comment]
Can you clarify which bot this is on BSO/OSB. Also did you try the command `/create item:Uncharged black mask`

**Comment by Jamsterman25** [comment]
Omg thank you!!! Uncharge command worked

**Comment by nwjgit** [comment]
great!
