### ISSUE TITLE
100% Brimstone keys from konar slayer task supperiors

### ISSUE THREAD

**Issue by Lewis7777** [oldschoolgg/oldschoolbot#5999]
If you kill a supperior slayer monster on a konar slayer task, you should 100% recieve a brimstone key.

https://oldschool.runescape.wiki/w/Brimstone_key
"A brimstone key is always dropped by a [superior slayer monster](https://oldschool.runescape.wiki/w/Superior_slayer_monster) assigned by Konar."

**Comment by TastyPumPum** [comment]
Fixed in #5942 once it's been tidied and merged
