### ISSUE TITLE
Add the full Time To Max on all skill (+TTM) interrogation 

### ISSUE THREAD

**Issue by permedd** [oldschoolgg/oldschoolbot#60]
![image](https://user-images.githubusercontent.com/37475765/59375759-bd9e3500-8d46-11e9-9b13-c08f3b05e7a1.png)

can u do something like this for +ttm? this is the twisty bot !ttm it shows how long of ehp left till i get 99 i only use that bot for that but i use ur bot as well but it would be awesome if u do something like that?
example +ttm all and it only shows the how long (in times) left for the ones thats not 99 more clearer then twisty bot i like the +xp /+stats etc so clean

**Comment by permedd** [comment]
can you also add it for +200all as well.

**Comment by gc** [comment]
For any contributors looking at doing this, it should be possible to just copy how CML does the calculations in the client-side JS on the website here: http://crystalmathlabs.com/tracker/suppliescalc.php?player=Mgby
