### ISSUE TITLE
/k kalphite king show-info still doesn't work tag:BSO BUG REPORT

### ISSUE THREAD

**Issue by AvariceBrah** [oldschoolgg/oldschoolbot#6038]
https://github.com/oldschoolgg/oldschoolbot/blame/9627c5ec1692204af356e2d539b4fe35789756ce/src/lib/minions/data/killableMonsters/custom/bosses/KalphiteKing.ts#L44C11-L44C11

I was able to find the src for the requirements but when running the k command with show-info field set to trust it says it doesn't have that monster, which approximately a year and a half or more ago, I was bitching about in regards to that being the case for basically every custom killable+ some vanilla. 

Can we get that fixed or can I be pointed to the file in which the show-info is pulled from so I can compile what I find is missing? 

Driving me bonkers. Lol

**Comment by AvariceBrah** [comment]
Continuance of 

https://github.com/oldschoolgg/oldschoolbot/pull/5638#issue-2113593926

**Comment by DaughtersOfNyx** [comment]
Hi, I can fix that in a while after I finish up the stuff I'm currently working on, in the meantime you can see KK boosts [here](https://github.com/oldschoolgg/oldschoolbot/blob/bso/src/mahoji/lib/abstracted_commands/kkCommand.ts)

**Comment by nwjgit** [comment]
Don't post new threads for issues you already have open. I'm tracking your previous thread and it will be fixed when somone can get around to it.
