### ISSUE TITLE
Global lb bug

### ISSUE THREAD

**Issue by DarkBugz** [oldschoolgg/oldschoolbot#6049]
Global lb xp for bso is showing the max as 24 skills.  E.g. ruben has 104% max xp.

**Comment by gc** [comment]
I don't see where this is happening. Can you post a screenshot

**Comment by DarkBugz** [comment]
![Screenshot_20240919_070424_Discord](https://github.com/user-attachments/assets/2fe8ba5f-2da6-4c86-9be2-6a9e40b07dd3)

**Comment by nwjgit** [comment]
> I don't see where this is happening. Can you post a screenshot

issue is the static value in the query for globalLb(). Could probably make this a dynamic value based off the count of skills to prevent this from happening in the future, especially since we got sailing coming eventually too.

**Comment by gc** [comment]
Fixed in next update
