### ISSUE TITLE
Exorcise Cursed Onyx Doubling

### ISSUE THREAD

**Issue by elevor6433** [oldschoolgg/oldschoolbot#6052]
## 🐛 Bug Report

When casting "Exorcise Cursed Onyx" spell you can roll 2x loot on BSO. This is not aligned with other gem related activities.

![SmartSelect_20240916_122434_Discord](https://github.com/user-attachments/assets/4d1dbafa-41e3-42fa-8618-a0e14f83d7d1)

**Comment by nwjgit** [comment]
Not sure what you mean by `not aligned with other gem related activities` exorcising cursed onyx is a castable action similar to plank make, enchanting jewellery, super glass make, etc etc. These all have a chance to double loot on trip return.

**Comment by Lilbourne** [comment]
> ## 🐛 Bug Report
> When casting "Exorcise Cursed Onyx" spell you can roll 2x loot on BSO. This is not aligned with other gem related activities.
> 
> ![SmartSelect_20240916_122434_Discord](https://private-user-images.githubusercontent.com/181767936/367879863-4d1dbafa-41e3-42fa-8618-a0e14f83d7d1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MTYzODcsIm5iZiI6MTcyNjcxNjA4NywicGF0aCI6Ii8xODE3Njc5MzYvMzY3ODc5ODYzLTRkMWRiYWZhLTQxZTMtNDJmYS04NjE4LWEwZTE0ZjgzZDdkMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwMzIxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDZkYzA5NjdkY2Q3NzZkY2NlYmZlZDFhZmE5NWI2NmQyYjhhMTQ5NjFhZmM4MjJiZGY5ODdhOWQ3ZmQ0NmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QWoYqf3C7z_YqMz1541cuD5ruxeq-W7WCn_t3UNIIFs)

For the record, onyx doubling still exists on crafting as well. This was never deemed an issue as the price of Onyx's are like 10% of the value of Zenyte's.

**Comment by nwjgit** [comment]
I talked this over with elevor in discord and pretty much came to the same conclusion and this is by design. It could be changed with poll though.
