### ISSUE TITLE
/k boost string says "..., Using ,....." and does not list anything being used (blank) if nothing's being used

### ISSUE THREAD

**Issue by wontonstrips** [oldschoolgg/oldschoolbot#6088]
## 🐛 Bug Report

When using /k with a scythe equipped the boost string says "..., Using 360 Scythe of vitur charges, ......"

When using /k with nothing being used (afaik no scythe no tumeken shadow) the boost string says "..., Using ,....."

Noticed this while doing barrows on OSB and also later reported while testing tormented demons on test server.  This is where it was made known to me is a bug with /k

Thanks,
wonton

**Comment by gc** [comment]
This should be fixed.
