### ISSUE TITLE
/casket command never loads, only says "OSB is thinking..."

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#6099]
## 🐛 Bug Report

Happens with any tier, any quantity. /kill sim works fine
![image](https://github.com/user-attachments/assets/8e3af6a2-be0f-49f9-a44c-948e4b30a222)

**Comment by nwjgit** [comment]
Probably the same issue BSO was having https://github.com/oldschoolgg/oldschoolbot/pull/6071

**Comment by gc** [comment]
Fixed in next update
