### ISSUE TITLE
"Autoslay EHP" for Araxyte tasks sends a normal trip, without cannon or barrage active.

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#6100]
## 🐛 Bug Report

Autoslay EHP is meant to automatically send a trip with max efficiency if possible, ie cannon & barrage. For Araxytes, it only sends a trip with neither of those options despite being able to do a trip with cannon and barrage manually. 
![image](https://github.com/user-attachments/assets/ae396f89-79e4-454f-85d5-464f3b62f2eb)

Hard to show the autoslay ehp being clicked in image, but i did click it

**Comment by gc** [comment]
Should be fixed in next update
