### ISSUE TITLE
Allowed Imbued Slayer helmets, and Nid to create Amulet of Rancour (s)

### ISSUE THREAD

**Issue by RLChristof** [oldschoolgg/oldschoolbot#6103]
## 🚀 Feature Proposal

After testing it's come to light that in order to create the amulet of rancour (s) you are unable to use Nid, or the imbued Araxyte Slayer Helmet. 

To match it like in game, please push an update to include both Nid (non-transmoged version) and the Araxyte Slayer Helmet (i) to the list of items that are required to create the Amulet of Rancour (s)

**Comment by gc** [comment]
Should be fixed in next update
