### ISSUE TITLE
[CI] `dpdm` should not check the packaged code

### ISSUE THREAD

**Issue by GrinZero** [oldschoolgg/oldschoolbot#6131]
## 🐛 Bug Report

`dpdm` should not check the packaged code, but should check `src/index.ts`, which is the source code. Otherwise, the inspection results are meaningless.

**Comment by gc** [comment]
Not true. The javascript files are the files which are actually executed, and that's where the circular import actually causes issues(at runtime). ideally they wouldn't be in the TS files either, but it doesn't really matter.
