### ISSUE TITLE
Gnome Bench exp/h

### ISSUE THREAD

**Issue by bowiRS** [oldschoolgg/oldschoolbot#6133]
Just like with mahogany dining tables they use 6 mahogany planks and in the bot they have the same exp/h. It is however possible to make benches way faster. Right now with all boosts you get like 775k exp/h but you can get up to 1.1m exp/h. The minions always do skilling at maximum efficiency so while it is a tryhard method in the maingame, the minions should be able to do it.

Here is a youtube video of someone showing how fast it can be

https://www.youtube.com/watch?v=tlbOBqXRFY4&t=3s

**Comment by gc** [comment]
Marked as accepted
