### ISSUE TITLE
Teleport scrolls for pvm

### ISSUE THREAD

**Issue by bowiRS** [oldschoolgg/oldschoolbot#6134]
At Araxxor you get a 10% speed boost for using Spider cave teleports, a consumable you get from Araxxor itself. This is a really good idea but unfortunately, not all bosses get this treatment. Tormented Demons were added a few days later and their teleport scroll does not have a use in this game. Cerberus and Zulrah were added before Araxxor created this new precedent and their scrolls have not been given the same treatment.

I would like for all bosses to get the same treatment as Araxxor

**Comment by SamPatrick95** [comment]
Also Revenant Caves teleport as a possible boost to revs. Maybe smaller, like 5%

**Comment by bowiRS** [comment]
Revenant is a good shout, I only looked at bosses so I overlooked them
