### ISSUE TITLE
Doug

### ISSUE THREAD

**Issue by ordinaryId** [oldschoolgg/oldschoolbot#614]
Maybe something is wrong. I'm not sure I was just told to report it. I did a trip of 40 runite ore and only received 3.
![Screenshot_20200907-132833(1)](https://user-images.githubusercontent.com/68664696/92413030-dfd25e80-f113-11ea-8a35-ea04309b79bc.png)

**Comment by Lajnux** [comment]
intended randomness with the new doug update. Close issue.

**Comment by kevinsmendes** [comment]
I think it should be changed to `loot[randOre.id] = (loot[randOre.id] ?? 0) + qty`. Looks like it replaced the rune ores he should have received with the bonus ores.

**Comment by Lajnux** [comment]
#657 resolved this issue. Can be closed.
