### ISSUE TITLE
Update nightmareCommand.ts 

### ISSUE THREAD

**Issue by jin-dii** [oldschoolgg/oldschoolbot#6143]
Rancour needs to be updated for BIS for Phosani's Nightmare

const phosaniBISGear = new Gear({
	head: "Inquisitor's great helm",
	neck: 'Amulet of torture',
	body: "Inquisitor's hauberk",
	cape: 'Infernal cape',
	hands: 'Ferocious gloves',
	legs: "Inquisitor's plateskirt",
	feet: 'Primordial boots',
	ring: 'Ultor ring',
	weapon: "Inquisitor's mace",
	shield: 'Avernic defender',
	ammo: "Rada's blessing 4"
});

**Comment by gc** [comment]
Done in next update
