### ISSUE TITLE
[BSO] Collection log items you don't own are now filled in, instead of being greyed out.

### ISSUE THREAD

**Issue by mylife212** [oldschoolgg/oldschoolbot#6153]
## 🐛 Bug Report

Expected behavior is the collection log item being grey, indicating you don't own it yet. Now, it looks like an item you obtained despite not having done so. Its very confusing 
![image](https://github.com/user-attachments/assets/ade3209a-a1dd-4893-b70d-277b99e29851)

**Comment by gc** [comment]
Fixed
