### ISSUE TITLE
games broken

### ISSUE THREAD

**Issue by wyattos** [oldschoolgg/oldschoolbot#616]
https://cdn.discordapp.com/attachments/720678538360914044/752737836549013531/unknown.png

**Comment by Alexsuperfly** [comment]
this is intentional and you know that

**Comment by wyattos** [comment]
ah yea because on a gamemode where literally everything is tradeable this is intentional 🤡

**Comment by gc** [comment]
This is because the item is a pet with no g.e value, so the sacrifice command has no gp value to use for it, even though we still let you trade it. You could make a suggestion to allow to sacrifice it but it wouldn't be different from just dropping it.
