### ISSUE TITLE
pin specific items to top of bank

### ISSUE THREAD

**Issue by 000000653** [oldschoolgg/oldschoolbot#620]
## 🚀 Feature Proposal
Allow pinning of specific items to the top of banks, an example of where this may be useful on bso is pinning all the different mystery boxes. On osb, you could pin low-value skilling gear like graceful, prospectors, etc that is commonly swapped out when you do different activities (clues, mining, fming, etc). Or pinning coins so they're always first regardless of how much you currently have.

**Comment by Lajnux** [comment]
#628 closes this issue.
