### ISSUE TITLE
Konars Assigned Task amounts

### ISSUE THREAD

**Issue by TastyPumPum** [oldschoolgg/oldschoolbot#6209]
![image](https://github.com/user-attachments/assets/e1578b8f-ee33-44dc-9e04-9ef38e596a42)

https://oldschool.runescape.wiki/w/Konar_quo_Maten#Tasks

Konar has the wrong task and extended task amounts for ankous, haven't checked other tasks from her

**Comment by DayV-git** [comment]
I don't see an issue
![image](https://github.com/user-attachments/assets/cb38ffec-3d94-4631-be1c-d56efbf2f893)
