### ISSUE TITLE
Amulet of Torture OR has a weird name and bugged [BSO]

### ISSUE THREAD

**Issue by adam55419** [oldschoolgg/oldschoolbot#623]
Amulet of torture with the ornament attached for some reason has the name "wilderness champion amulet" on BSO. It is tradeable however its not equip-able. can this be fixed and the name correcting please

**Comment by kevinsmendes** [comment]
This is not a glitch. This amulet actually exists and has the ID 21433. It was probably received from an Untradeable Mystery Box. The actual Amulet of Torture (or) has the ID 20366.
