### ISSUE TITLE
Mostdrop bug 

### ISSUE THREAD

**Issue by ahmalla** [oldschoolgg/oldschoolbot#624]
Today someone did =mostdrops for gilded axe and on that list it showed I only had 2, Which is incorrect. My CL shows the 5 that I have gotten correctly, however.

**Comment by osrsolympus** [comment]
![1AD749DB-B2C7-42F4-AB50-1AD445CE5BE2](https://user-images.githubusercontent.com/65320787/92986390-5b236f80-f488-11ea-8397-5a707de4a7c7.jpeg)

**Comment by ahmalla** [comment]
Hmm idk what I thought I saw, thanks! Sorry for the clutter
