### ISSUE TITLE
Inferno Cape Minigame (BSO?)

### ISSUE THREAD

**Issue by EngageV2** [oldschoolgg/oldschoolbot#630]
Mainly a BSO proposal unless osb would want it aswell

**Description**: Literally same as fightcaves with a few twists

**How it would work**: Same as =fightcaves but the KC bonus is effectively reduced in half, so would take twice as many KC for the fast reduction time.
*wintertoad still cuts in half*

**Requirements**: Requires 10 fire cape trade ins to be able to start doing the =inferno.

**Alternative ways to get cape:** (since inferno capes should be removed from Untradeable mystery boxes upon release of minigame 🤷🏽‍♂️) 
If you cash in 100 Fire capes you instantly get a inferno cape.
If you cash in 200 you can get Infernal max cape? (Idk)

![4EB800D2-C789-4819-94F0-D22960B6EAE4](https://user-images.githubusercontent.com/69174970/93000470-b12efc00-f4f6-11ea-87fb-7a243fb8fafc.png)

**Comment by osrsolympus** [comment]
Why should infernal capes be removed? This is incongruous with how other obtainable untradable items are dealt with.

**Comment by Lajnux** [comment]
inferno is planned coming and will be PRed both for OSB and BSO once done, this suggestion would devalue infernal once released and therefor not worth coding.
