### ISSUE TITLE
Infernal max cape not equip-able 

### ISSUE THREAD

**Issue by Voice-Guy** [oldschoolgg/oldschoolbot#633]
## 🐛 Bug Report

Unable to equip infernal max cape. As of at least Aug 28th the cape was shown to be equip-able (see bso main channel logs).
Have attempted many iterations of the command to equip, as well as the workaround for the "bug" 3rd age items had, that being the inclusion of a 1 preceding the item name.

**Comment by osrsolympus** [comment]
Which infernal max cape do you have? The regular one? The interface one? The locked one? The broken one?

**Comment by Lajnux** [comment]
no more information was given, assume it was a broken or duplicate item
