### ISSUE TITLE
Cavalier Mask BSO

### ISSUE THREAD

**Issue by JeremyBekkers** [oldschoolgg/oldschoolbot#644]
## 🐛 Bug Report
Hi, so I got a Cavalier Mask from a tmb i think and it shows in bank when I do =b --search=cavalier. But when I do =b Cavalier Mask it says that I have 0 Cavalier Mask.

https://media.discordapp.net/attachments/668073484731154462/756061353353019392/image0.png?width=417&height=513

Write a description of the bug here, give all the information you can about what it is, how it happened.

**Comment by Alexsuperfly** [comment]
there are two items with that name, its telling you how many of the first you have, which is 0.
