### ISSUE TITLE
Broken daily(?)

### ISSUE THREAD

**Issue by parallack** [oldschoolgg/oldschoolbot#652]
This may be within the random chance of dailies but seems unlikely. Just did a BSO daily which, when answered correctly, awarded no gp and had the appearance of an incorrect answers reward. It even had the random space and emoji found in failed dailys.
![broken daily](https://user-images.githubusercontent.com/69537065/93689587-a4ca1680-fa95-11ea-9adb-c2bad002f26e.png)

**Comment by kevinsmendes** [comment]
There is a 1 un 73 chance that your coins reward will be 0. The bank image removes the 0 qty item, that is why the empty space.

**Comment by parallack** [comment]
Hmmm okay so it was within the random chance. Just wanted to make sure.
