### ISSUE TITLE
Clue scrolls

### ISSUE THREAD

**Issue by eyeslangmeat** [oldschoolgg/oldschoolbot#655]
## 🚀 Feature Proposal

I've been having a lot of fun on BSO lately, and one thing I'd like is if on OSB clues stacked like they do on BSO. To keep from making this super OP or devaluing items like Ranger boots mainly you could make it so they could still only complete 1 clue at a time?

**Comment by Lajnux** [comment]
In the main game clues are not stackable, and the main bot OSB tries to follow that concept.
