### ISSUE TITLE
Use the new +/=fav command to arrange/order the items within our banks?

### ISSUE THREAD

**Issue by Shadax-OSB** [oldschoolgg/oldschoolbot#665]
At the moment i do believe that items are still sorted by value, so a +fav armadyl crossbow is going to be placed before a bandos godsword for instance. 

Would it be possible to add a +/=fav (item) (number) so we can sort them into any order we please?

Example of the command - +favourite armadyl crossbow 1

A bit like how we can see each bank page with;

+bank 2

I imagine this would not be a very high priority ticket, but my OCD compells me to make the suggestion! 

Thank you, and sorry if im being a pain!

**Comment by Shadax-OSB** [comment]
Sorry, edits for my poor grammer.

**Comment by Lajnux** [comment]
#2594 resolve this issue

**Comment by Lajnux** [comment]
A similar system is now added in the bots for patreons.
