### ISSUE TITLE
dwarven pickaxe is unequippable & provides no boost

### ISSUE THREAD

**Issue by 000000653** [oldschoolgg/oldschoolbot#666]
## 🐛 Bug Report
In BSO, the dwarven pickaxe cannot be equipped and provides no boost to mining (or is overridden by 3rd age pickaxe maybe? unsure). I expect this also occurs with other dwarven equipment however I cannot confirm as I do not have them. I do not know if it providing no boost is the same bug or even if that's unintentional.

![Discord_i1474iDalv](https://user-images.githubusercontent.com/40111569/93836330-03cf8d00-fc48-11ea-8e26-98f2ba5fd5f1.png)

**Comment by kevinsmendes** [comment]
Same root as #653 
#664 Fixes both these issues

**Comment by 000000653** [comment]
Both issues have now been fixed. I still can't test other equipment since I don't have em but if they were broken I expect they're also fixed now.
