### ISSUE TITLE
Max item in bank useage 

### ISSUE THREAD

**Issue by umido** [oldschoolgg/oldschoolbot#667]
It would be nice if instead of saying we don’t have enough of one item in bank to use, it uses what we have if max limit is not reached. 

For example I’m trying to smelt gold bars and I get to 448 ore left. Instead of doing those it says I don’t have enough since max limit becomes default if we don’t specify quantity. 

maybe add a if/then statement to the bot command? if max amount useable isn’t reached then use amount in bank. 

Not much food at wording things but hope y’all understand. Much love ❤️

**Comment by kevinsmendes** [comment]
You are probably talking about OSB, right? This have been fixed already (kinda, it created another glitch). It is currently deployed to BSO and will later be ported to OSB when all problems are fixed.

**Comment by Lajnux** [comment]
This is added for most things now.
