### ISSUE TITLE
+m pat lb

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#675]
## 🚀 Feature Proposal

LET US COMPETITIVELY SHOW OUR LOVE AND RESPECT FOR OUR MINIONS +lb pat

**Comment by 000000653** [comment]
Maybe make it so you can only pat once every 30 minutes, and keep it so that patting is still impossible while minion is on a trip

**Comment by osrsolympus** [comment]
Apparently this would encourage botting for ranks and that’s not a good thing.
