### ISSUE TITLE
Abyssal Dragon drop table (BSO)

### ISSUE THREAD

**Issue by EngageV2** [oldschoolgg/oldschoolbot#682]
With a name like abyssal dragon i 100% think 

It should have a 1/500 chance of dropping a byssal bludgeon
1/321 chance at abyssal whip
1/2500 chance at abyssal Godsword
1/725 Abyssal necklace: When worn gives you a 10% boost increase when doing Raids 3(nightmare)

This new godsword valued at 250m Gp
Has the stats of the other godswords + 15 in All melee offensive categories

**Comment by Lajnux** [comment]
The dragon is called Malygos now.

**Comment by osrsolympus** [comment]
The Nightmare isn’t Raids 3 and imo the drop table is already op with the DLH, DHCB, Abyssal Lance, Abyssal Defender, Abyssal Cape, and Abyssal Thread providing massive boosts to PvM and some skilling generally already. 

2nd Godswords are kinda shit melee weapons, and are designed around their spec, so why would it be worth so much more if it’s an objectively less useful item?
