### ISSUE TITLE
Prayer bank bg

### ISSUE THREAD

**Issue by gc** [oldschoolgg/oldschoolbot#686]
## 🚀 Feature Proposal

prayer bank bg:
- requires 99 prayer?
- requires sacrificing LOTS of bones?
- requires you complete the god books or only 1?
- requires sacricicing ring of the gods?
- sacrifice a spirit shield

draft:
![file](https://user-images.githubusercontent.com/30398469/94213243-ab371300-ff19-11ea-85c8-5394cc82c218.png)

**Comment by imTURBObruh** [comment]
bump

**Comment by imTURBObruh** [comment]
bump![PrayerBANKBG.png](https://user-images.githubusercontent.com/90441459/156868228-7eba9611-aeba-4125-adf1-871fe4a1856c.png)

@gc what whatchya think of this?

**Comment by imTURBObruh** [comment]
bump![PrayerBANKBG.png](https://user-images.githubusercontent.com/90441459/156868228-7eba9611-aeba-4125-adf1-871fe4a1856c.png)

@gc what whatchya think of this?
