### ISSUE TITLE
Rada's blessing

### ISSUE THREAD

**Issue by Ijsberg2** [oldschoolgg/oldschoolbot#699]
## 🐛 Bug Report

As far as I know there is no ''rada's blessing', only 1,2,3 and 4 for achievement diary rewards. I just bought ''rada's blessing'' from a discord member as it showed as ''rada's blessing 3''. I can't equip it, but it shows in my bank under the name of ''Rada's blessing'' 
cheers :)

**Comment by kevinsmendes** [comment]
Item ID 22803 is called Rada's blessing. It is not a duplicate item, but it is marked as 'incomplete' and have equipable set to false. So, it is just one of those rare items that can drop from UMBs.
