### ISSUE TITLE
Fixing broken equipment on bso

### ISSUE THREAD

**Issue by tg03-1** [oldschoolgg/oldschoolbot#703]
## 🚀 Feature Proposal

Describe the feature you're suggesting here, give lots of information and describe it as best you can. Please check that the feature hasn't already been suggested first, by searching the issues in this repository.
Would it be possible to fix broken equipment on bso? I.E avernic defender (broken) and make it useable again for a fee? Or infernal max cape (broken) etc

**Comment by Lajnux** [comment]
This have been resolved. Do +create fix infernal max cape for example.
