### ISSUE TITLE
Malygos Suggestion (BSO)

### ISSUE THREAD

**Issue by EngageV2** [oldschoolgg/oldschoolbot#712]
Lore: Back around the godwars malygos was sent by Zamorak to take over the eastern region of Glieonor, however before malygos could arrive the Legendary Armadyl general (blah blah blah) stopped Malygos in its tracked, however both the general and malygos died as their wounds were fatal to each other. The general was entrusted with using the Armadyl Godsword which aided them in battle. This weapon is now known as one of the many powerful weapons that can defeat demonic dragons such as Malygos

Suggestion: armadyl godsword is a required item to kill Malygos?

New drop suggestion: Abyssal Ring; ONLY IF EQUIPPED IN THE SKILLING GEAR SETUP has a 1/888 chance and gives a 10-15% boost when runecrafting (this ring helps control the abyss itself)

New drop suggestion: Abyssal Necklace 1/1257 chance (valued at 82m Coins) this necklace When worn gives you a 10% boost when killing ANY abyssal creatures. This necklace was worn by the general given by The Leader of armadyl Nation back in the day.

**Comment by Lajnux** [comment]
The abyssal dragon Malygos is already the strongest content in BSO PvM wise. No need to add more value to it.
