### ISSUE TITLE
Allow for the —names flag when +opening things

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#713]
## 🚀 Feature Proposal

Let us +open (openable) —-names and have the loot received display the name tags of the items received. Would be very useful for BSO boxes, but would also have increased utility when Fishy’s openables expansion is released.

From Benny: --text flag would also be good

**Comment by osrsolympus** [comment]
Bump

**Comment by osrsolympus** [comment]
Bump

**Comment by osrsolympus** [comment]
Bump

**Comment by coolbop32** [comment]
can now do this
