### ISSUE TITLE
(BSO) DFW once made is untradable 

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#714]
## 🐛 Bug Report

+create d a dragonfire ward which is now giving the unsearchable and untradable error even tho it’s in my bank. Presumably looking up the other version of the ward I don’t have.

**Comment by gc** [comment]
If this bug is as a result of the item argument, or something like that - we need a test case for this in master.

**Comment by Lajnux** [comment]
resolved
