### ISSUE TITLE
BSO Add Imbued (Mage Arena) Max cape to CoX boosts

### ISSUE THREAD

**Issue by JeremyBekkers** [oldschoolgg/oldschoolbot#724]
## 🐛 Bug Report
I bought one and not just for me, but I thought it would be fair if those capes would give at least the same boosts as a regular imbued  mage cape.

Write a description of the bug here, give all the information you can about what it is, how it happened.

**Comment by kevinsmendes** [comment]
#706 will fix this issue.

**Comment by Lajnux** [comment]
a temp solution merged #761
