### ISSUE TITLE
(BSO) add Avernic Defender (L) to CoX boost

### ISSUE THREAD

**Issue by Zohibso** [oldschoolgg/oldschoolbot#725]
## 🐛 Bug Report

I had bought an avernic defender (l) and equipped it to test gear score for Chambers. I had nothing previously in shield slot, when my raid got sent out, my gear score was still the same as before. I'm assuming the regular Avernic was only added to gear scores and not Locked versions. a fix would be great, thanks.

**Comment by Lajnux** [comment]
merged #761
