### ISSUE TITLE
Dwarf boss changes

### ISSUE THREAD

**Issue by IronBump** [oldschoolgg/oldschoolbot#734]
Remove the dwarven skilling items/ore/bar from tradeable mystery boxes. 
Same as cox/same as how the dwarven crates are now only available from the boss.

**Comment by kevinsmendes** [comment]
It is already like that since the the last update \o

https://github.com/oldschoolgg/oldschoolbot/blob/4f3ea74022515ec9665538434e90617cf16cea64/src/lib/openables.ts#L291

**Comment by gc** [comment]
Yep - this is now like this.

**Comment by lyanrewis** [comment]
wasn't removed as multiple tools have been opened from boxes in the last couple days.
