### ISSUE TITLE
BSO COX drop table is wrong

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#736]
## 🐛 Bug Report

BSO COX drops elven crystals (at least Trahaearn) which isn’t supposed to be on it’s drop table. Seems like a bug since it _wasn’t mentioned_ anywhere and _isn’t in the public cox code_.

**Comment by osrsolympus** [comment]
Also you can still get Olmlet without a purp in your name which is an actual drop table bug.

**Comment by osrsolympus** [comment]
![0DB1CFE9-3CBA-45AC-9798-EFC22655A4CC](https://user-images.githubusercontent.com/65320787/96024125-55230480-0e21-11eb-9893-24ab9d7ce0b6.png)

oh wow the nightmare drop table in bso is wrong too oh geez someone really needs to fix this

**Comment by ard35** [comment]
Congrats on the drop! :)

**Comment by Lajnux** [comment]
gratz on the drop, not a bug.
