### ISSUE TITLE
a lot

### ISSUE THREAD

**Issue by wyattos** [oldschoolgg/oldschoolbot#741]
## 🐛 Bug Report

not only is 164 points wrong (pictured here https://cdn.discordapp.com/attachments/736644823808999516/760272743736016936/unknown.png)

magic doesnt have any boots that give points

max points is 49 + 49 + 40 + 15 idk what smoke you were cracking when u calculated 164 but i want some of it

**Comment by Lajnux** [comment]
#737 closes this issue.

**Comment by wyattos** [comment]
> #737 closes this issue.

no boots on wiki = no boots in raid code perfect logic https://cdn.discordapp.com/attachments/546399073125662743/760273872200663070/unknown.png
