### ISSUE TITLE
Nightmare of Ashamallama suggestions (BSO)

### ISSUE THREAD

**Issue by EngageV2** [oldschoolgg/oldschoolbot#743]
**Add Mystic Smoke Staff as a uncommon Drop (to increase value is ur gonna get complete dogmeat junk 99% of the time, this is to give players somewhat of a chance at a slightly better gp/hr it’ll still be dogmeat but this just helps)
Add Zamorakian Godsword Orn kit as common drop**

New Custom Item: Shade Necklace (can pick a diff name lol); This necklace, (with the same Stats as a fury) gives the player if equipped a 10% boost to All GWD bosses 
Also Gives a 5% boost to ALL wilderness Bosses

**Necklace of Dreams** (Catspeak necklace model? Idk)
This necklace when worn gives the player a 
XYZ

The Nightmare Pet: if this pet is equipped the player has the option to set themselves for a 4-6 trip. This is limited to certain NPCs this Idea is mainly for people who are going to be busy/sleeping and want to set their bot up to be pvming for a long time this DOES stack with Dwarven Warhammer (has to be wiped from everyones bank first)

Add a  🟪 Chance for Crystal crown (the Lowerth one, or a custom Black/Grey Crystal crown)
Valued at 250M Its just a cosmetic that can be equipped or sold i have no idea for any Special effect. Just a very rare item that can be sold for alot of gp. (Alternative just have a very rare 100m GP cash drop)

**Comment by wyattos** [comment]
add tbow to the drop table too just because
