### ISSUE TITLE
Being able to charge items.

### ISSUE THREAD

**Issue by Mat95** [oldschoolgg/oldschoolbot#750]
## 🚀 Feature Proposal

Were able to Create a Toxic staff of the dead but this version is (uncharged), I propose we add a new command for charging items that can be charged! Example: =charge Toxic staff of the dead (Uncharged)

But instead of doing the normal amount required from in game i suggest making the requirement 10x what it needs, As this Charged item wont deplete like all things currently on OSB or BSO. So instead of 11k scales make it like 100k or 110k.

We could charge stuff like Glories for 10 Charge dragonstone jewellery scrolls or any other items listed here: https://oldschool.runescape.wiki/w/(uncharged)

**Comment by Lajnux** [comment]
A system to charge some items been implemented and will be further worked on when/if needed.
