### ISSUE TITLE
BSO Mystery Box Questions

### ISSUE THREAD

**Issue by Lilbourne** [oldschoolgg/oldschoolbot#752]
## 🐛 Bug Report

Answering the item questions seems to fail when answering correctly after the recent update.

![Screenshot_20200930-033856_Discord](https://user-images.githubusercontent.com/70830013/94657226-21979480-02cf-11eb-962c-cb47f99ead8f.jpg)

**Comment by Lajnux** [comment]
spawnbox havn't had any recent bugs so most likley resolved.
