### ISSUE TITLE
Spawnbox Issue

### ISSUE THREAD

**Issue by NotShin** [oldschoolgg/oldschoolbot#755]
## 🐛 Bug Report

A box was spawned and only ~2 seconds were seemingly given to answer the trivia.

https://discordapp.com/channels/342983479501389826/732207379818479756/760884482156265532

![image](https://user-images.githubusercontent.com/21049385/94705889-8bd02980-030f-11eb-93b1-463ea8248d36.png)

Lois got the answer correct, so it may be related to this change.
https://github.com/oldschoolgg/oldschoolbot/commit/1292b37e239a298d34c3bfac1fc301e7862d061f#diff-467d126bdf98c4f61a608cb925a20efbR53

It must not be getting the box they won and throws the error instead.

**Comment by Lajnux** [comment]
No further reports of this type have been reported so either fixed or discord/bot server lag.
