### ISSUE TITLE
Over 900??! Qp for maly

### ISSUE THREAD

**Issue by thesauce69** [oldschoolgg/oldschoolbot#758]
## 🚀 really rare pet 
Suggestion: having a super rare item/pet drop that lets you kill maly without having 999 quest points?

**Comment by kevinsmendes** [comment]
999 QP is 20% of what is needed currently for max QP on BSO. It won't take too much of your time to get 1K QP and start killing Malygos. It already have a very, very good drop table. It is worth your time.

**Comment by BrandonEnglish848** [comment]
Questing and qp rates in BSO are drastically different than OSB rates. 1k QP is not a difficult barrier for a boss that will be presumably dropping BIS items. If the other bosses are any indicator of how valuable these custom boss drops are, the time it has taken to gather qp will not have been in vain.
