### ISSUE TITLE
Remove Stat Requirements from Bosses

### ISSUE THREAD

**Issue by KakronPrime** [oldschoolgg/oldschoolbot#766]
Using equipment stats as a pure factor to determine whether you can fight a boss in is unrepresentative to the main game. 

Take for example nightmare, not that you should ever use these weapons but near max melee with sara sword is unable to fight nightmare. On the other hand the dead arse slow torag’s hammers on their own can. 

If you must lock bosses behind simple requirements please do so behind stats or gear rather than gear stats.

**Comment by Lajnux** [comment]
A combat version have been worked on that will tackle some of this #1039
