### ISSUE TITLE
Nightmare MvP calculation bug?

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#768]
## 🐛 Bug Report

Not sure if this is really a bug or not, but in a 4 kill nightmare mass there was only 1 big bones drop even though I only died once (the lowest number of deaths in the group).
![91057EFD-5938-45E8-9460-7791BB7FA647](https://user-images.githubusercontent.com/65320787/94769739-c02ffe00-0380-11eb-8bf7-84263a942408.jpeg)

Idk how it’s calculated but shouldn't there be 1 mvp and consequently 1 big bones drop per kill?

**Comment by nwjgit** [comment]
Nightmare calcs mvp properly now.
