### ISSUE TITLE
Capitals in Runecrafting

### ISSUE THREAD

**Issue by TwiceUponATaco** [oldschoolgg/oldschoolbot#771]
## 🐛 Bug Report

When runecrafting with "+rc" if the rune is typed out in all caps or anything other than first letter capitalized it will fail. Other things like bosses don't seem to mind as much, but +RC NATURES will fail saying it's not a valid rune that you can craft.

**Comment by TwiceUponATaco** [comment]
Clarification on what works....
+rc Natures - Works
+rc natures - works
+rc Nature - works
+rc nature - works
+rc NATURE - works
+rc NATURES - doesn't work

**Comment by Lajnux** [comment]
merged
