### ISSUE TITLE
I will not let me equip little nightmare

### ISSUE THREAD

**Issue by Carnitas07** [oldschoolgg/oldschoolbot#773]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
I type out +equippet little nightmare and it keeps saying I do not have the pet. Even tho I obtained it from nightmare mass

**Comment by Carnitas07** [comment]
That's not a pet, or you do not own this pet.


![](https://cdn.discordapp.com/attachments/637804600753389580/761329845220540416/file.jpg)

**Comment by Carnitas07** [comment]
![](https://media.discordapp.net/attachments/736774315256840342/761652334827667497/file.jpg)

**Comment by gc** [comment]
This will be fixed in the next update - thanks for reporting.
