### ISSUE TITLE
Minion is stuck 

### ISSUE THREAD

**Issue by tickfart** [oldschoolgg/oldschoolbot#777]
## 🐛 Bug Report

My minions been stuck for about 3 hours now. He won’t respond to any commands other than +bank. The last thing I was doing was killing 65-75 guards at a time hunting medium clues for ranger boots. I stacked 2 caskets in my bank, maybe that’s why?

**Comment by BrandonEnglish848** [comment]
If you try to issue commands in this channel at the link below, (Main OSB Channel) does your minion respond?

https://discord.com/channels/342983479501389826/346304390858145792

If you are issuing the commands on a different Discord server that is NOT the official OSB server, please make sure that the bot has the correct privileges enabled for both the server and channel you are sending the commands in.

**Comment by gc** [comment]
You should be unstuck now.
