### ISSUE TITLE
OSB - Mass Roles Pings

### ISSUE THREAD

**Issue by wildchickenz** [oldschoolgg/oldschoolbot#778]
Creating a second role.

Having +pm default to pinging to corp as it has always been the long term ping for corp and should going forward.
Create a second role that would be pinged with its own command. At the moment a lot of people are massing Nightmare so +nm could ping those with a corresponding role. 

ALSO
Would it be possible to check if the minion is busy for that person when the ping is sent? As to only ping those that are not busy therefor able to join the mass.

**Comment by Lajnux** [comment]
resolved
