### ISSUE TITLE
Cannot Locate Ancient Wyvern Shield

### ISSUE THREAD

**Issue by BrandonEnglish848** [oldschoolgg/oldschoolbot#784]
## 🐛 Bug Report

My friend has an Ancient Wyvern Shield in their bank and is trying to sell me it. The shield appears in their:

- bank image (even with the --sv added)
![image](https://user-images.githubusercontent.com/25591206/94929641-fb1e5880-048a-11eb-9525-d35ba44ff7b5.png)
- =b --full --text
"Ancient wyvern shield: 1"

But when attempting to sell it this is the message that the bot responds:
"You dont have 1x Ancient wyvern shield."
Also when he does =b Ancient wyvern shield the bot responds:
"You dont have 1x Ancient wyvern shield."

Please help, because MALY

**Comment by Lajnux** [comment]
sorted by itemID with several items having same item ID. By instead doing the sell command using the correct itemID instead of itemName. some items like ancient wyvern shield now also got the uncharged version renamed to make this easier, resolved.
