### ISSUE TITLE
(BSO) Make Zamorakian Hasta Count for Cerb requirement (as that's what it's used for)

### ISSUE THREAD

**Issue by swahsam** [oldschoolgg/oldschoolbot#797]
Make Zamorakian Hasta Count for Cerb requirement (as that's what it's used for)

**Comment by Alexsuperfly** [comment]
hasta in game does half damage to corp, so no that is not what its used for

**Comment by swahsam** [comment]
Cerb is not corp

**Comment by Alexsuperfly** [comment]
doh
