### ISSUE TITLE
BSO full bank search with names

### ISSUE THREAD

**Issue by LookImHigh** [oldschoolgg/oldschoolbot#800]
## 🐛 Bug Report

=b -full -names & =b —search= give a error every time. 

There is some sort of WTF-# in the bank text list. 

=b # —names works until the page with the WTF item.

![Screenshot_20201003-094226_Discord.jpg](https://user-images.githubusercontent.com/68685674/94994402-004bd800-055d-11eb-8e8c-acb1aa9d9d83.jpg)

![Screenshot_20201003-094355_Discord.jpg](https://user-images.githubusercontent.com/68685674/94994407-06da4f80-055d-11eb-9150-926dbbc5cdd2.jpg)

![Screenshot_20201003-094500_Discord.jpg](https://user-images.githubusercontent.com/68685674/94994424-1eb1d380-055d-11eb-862d-42bf36f9ad57.jpg)

**Comment by kevinsmendes** [comment]
This was solved early today.

**Comment by imTurbo** [comment]
> This was solved early today.

Saw that. So happy. Thanks guys :)
