### ISSUE TITLE
(BSO) Bugged Item breaking =b --names command

### ISSUE THREAD

**Issue by broveh** [oldschoolgg/oldschoolbot#809]
## 🐛 Bug Report

My friend received an item from a mystery box (located at A3 in the screenshot) that appears to be "Chicken Legs" but the item doesn't respond to search commands and when attempting to do =b 4 --names the bot returns "An unexpected error occurred"

When attempting to find the problematic item using =b --text --full we found an item by the name of "WTF-11018" 
I believe this is what the item is actually named.

He is unable to sell/drop or trade this item.

![Broken](https://user-images.githubusercontent.com/72098949/95003407-1da89280-05ad-11eb-8886-adfbb3ab2afa.JPG)

**Comment by kevinsmendes** [comment]
When did your friend received that item?

**Comment by kevinsmendes** [comment]
This issue was fixed early today.
