### ISSUE TITLE
(OSB) Forcibly added to corp mass

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#826]
## 🐛 Bug Report

DogeCharger was doing nightmare masses and was forcibly added to a Corp mass, making him busy on the launch of the nightmare mass. Idk what happened but people shouldn’t be added to masses without clicking the join reaction. 

Pictures showing the chat re: him 1) joining the nightmare mass, 2) the nightmare mass failing, and 3) Doge saying he didn’t join 4) the corp mass in question. 
![8588E50B-0BA3-47A0-9C96-6811B2D0CEBA](https://user-images.githubusercontent.com/65320787/95028961-8ad22b80-0672-11eb-9f6a-acc1fac622b8.jpeg)
![A175149A-D5EB-4560-B2CB-6A4DE6CC57F9](https://user-images.githubusercontent.com/65320787/95028963-8c035880-0672-11eb-9aa1-a262eeb3ba53.jpeg)
![025E1A6C-965C-4CA2-8543-A137FDBF41D6](https://user-images.githubusercontent.com/65320787/95028965-8c035880-0672-11eb-8c07-e1748dae3254.jpeg)
![E93A6AA7-4050-411F-AF1F-280CC6FB6D19](https://user-images.githubusercontent.com/65320787/95028966-8c035880-0672-11eb-8d44-22a03fcd9b8a.jpeg)

**Comment by Lajnux** [comment]
![image](https://user-images.githubusercontent.com/68188574/104249590-10ccf200-546c-11eb-87e4-7fa912474cc5.png)

Resolved.
