### ISSUE TITLE
Nightmare staff + Orbs

### ISSUE THREAD

**Issue by DrugsOsb** [oldschoolgg/oldschoolbot#833]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

Harmonised Nightmare staff has no value, ples fix

**Comment by TwiceUponATaco** [comment]
Staff + orb isn't tradeable so shouldn't have a value

**Comment by BIRDIE13** [comment]
When the Nightmare staff is upgraded with an orb (eldritch/harmonised/volatile) the upgraded version become untradable. However, in OSRS players can revert the upgrade and sell the staff or orb again
