### ISSUE TITLE
show commands like +sbank as --wide

### ISSUE THREAD

**Issue by chefslav** [oldschoolgg/oldschoolbot#834]
## 🚀 Feature Proposal

basically any command that shows a long bank should show as --wide instead. it just looks better. 

- look how long this monstrosity is. disgusting. give it some girth

![file](https://user-images.githubusercontent.com/72408891/95114101-08e11180-0709-11eb-9da0-7eb6f77a1a22.png) 

kthanksloveu

**Comment by osrsolympus** [comment]
Perhaps let’s not intentionally disable a feature that most people have been using for months just because Slav can’t handle the fact it bears some resemblance to himself.

**Comment by chefslav** [comment]
> 
> 
> Perhaps let’s not intentionally disable a feature that most people have been using for months just because Slav can’t handle the fact it bears some resemblance to himself.

look man... there was no need for that drive by
![KermitHam](https://user-images.githubusercontent.com/72408891/95116354-80fd0680-070c-11eb-99c4-11d31cce5471.png)

**Comment by Lajnux** [comment]
with slash bank it's now more customization, resolves this
