### ISSUE TITLE
Ancient Dhide Shield spawnbox timer

### ISSUE THREAD

**Issue by imTurbo** [oldschoolgg/oldschoolbot#841]
## 🐛 Bug Report

![SmartSelect_20201006-031255_Discord.jpg](https://user-images.githubusercontent.com/68685674/95176051-f0610d80-0781-11eb-9a2e-e222b9ee0c82.jpg)

Wasn't even spawned for more than a few seconds and it said nobody got it. When it was answered correctly

**Comment by kevinsmendes** [comment]
This was fixed with the last update. It was a problem with the bot own trivia spawn and not spawnbox command.
