### ISSUE TITLE
Tradeables mystery box not giving item

### ISSUE THREAD

**Issue by ArtMatters** [oldschoolgg/oldschoolbot#846]
I opened a TMB on the BSO bot and it gave a staff of bob the cat however the item did not show up in my bank. This is not a big deal for this item but it could be a bit of an issue for more valuable items potentially. The item does show up in my =cl easy.

ArtMatters#3174 ; BSO ; Staff of bob the cat ; TMB 

https://cdn.discordapp.com/attachments/343218314694361088/763153943714594866/file.jpg

**Comment by Lajnux** [comment]
resolved
