### ISSUE TITLE
(BSO) Sepulchre Loot Problem

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#850]
## 🐛 Bug Report

BSO Sepulchre seems to be dropping the wrong Ring of Endurance (uncharged) 
![3180F134-7741-45AF-866D-22C16570B705](https://user-images.githubusercontent.com/65320787/95452651-943fea00-0937-11eb-814c-5cb8977cc376.png)

**Comment by osrsolympus** [comment]
![71E6BDBA-DCE6-4B0F-806F-86E231ACAA47](https://user-images.githubusercontent.com/65320787/95453361-b128ed00-0938-11eb-84c5-90233e3511ca.png)
Also item drop quantities seem to be off (like the old bug from testing that Zohi reported)

**Comment by gc** [comment]
Should be fixed now. Thank you for reporting.
