### ISSUE TITLE
Sepulchre CL not logging ring of Endurance

### ISSUE THREAD

**Issue by vohlk** [oldschoolgg/oldschoolbot#852]
Got the ring of Endurance from sepulchre and it doesn't show up under the collection log, I've attached a screenshot.
![Screenshot_20201008-084310](https://user-images.githubusercontent.com/72558115/95460486-0407a200-0943-11eb-8b82-faad856b1520.png)

Waiting and redoing +cl sepulchre doesn't change anything.

**Comment by gc** [comment]
Fixed in next update.
