### ISSUE TITLE
Iron man mass at nightmare 

### ISSUE THREAD

**Issue by specialtyson** [oldschoolgg/oldschoolbot#864]
## 🐛 Bug Report
Having issues trying to get 2 ironman accounts to join the same nightmare mass.

**Comment by ard35** [comment]
Duplicate of issue #769.

It isn't possible for an ironman account to join a mass at this time. They can only create one. This is fixed in PR #861, which we can hope to be reviewed and deployed soon. 

Closing this issue since it is a dupe.
