### ISSUE TITLE
Hallowed Sepulchre Drops

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#865]
## 🐛 Bug Report

The sepulchre drops the strange old lockpick and not the strange old lockpick (full). The former is also what’s being tracked on the cL.

**Comment by jbrem07** [comment]
This was addressed in the News update upon release:

The Strange old lockpick is different to ingame. It drops at a rarer rate, but doesn't require charges and doesn't degrade. It gives a 8% speed boost to Barrows (ontop of the 1% boost to sepulchre)
