### ISSUE TITLE
Ironman Nightmare Mass

### ISSUE THREAD

**Issue by jbrem07** [oldschoolgg/oldschoolbot#885]
## 🐛 Bug Report

Currently Ironmen cannot join a mass, they must host one themselves. 
When hosting a mass and clicking "Start" to start early, nothing happens. It takes the full 2 minutes to have the mass begin.

**Comment by ard35** [comment]
Duplicate issue of #769. 

I assume your talking about OSB. The fix (see #861) is merged and awaiting deployment. You should be able to join as an ironman after the next OSB update. 

For BSO, the fix (#861) is already merged and deployed since BSO had an update earlier today.

**Comment by jbrem07** [comment]
Thank you!! I tried to search before posting, greatly appreciated.
