### ISSUE TITLE
Trip counting twice BSO

### ISSUE THREAD

**Issue by ArtMatters** [oldschoolgg/oldschoolbot#886]
So I got 2 messages telling me my malygos trip was finished at 3:03 PM Eastern. Before this I attempted to send my OSB minion on a mission -offer dragon bones (which failed bc it did not have any dragon bones). I then Send my OSB minion on a malygos trip =m kc malygos. After realizing the OSB minion did not leave I sent it on a mission for superior dragon bones -offer superior dragon bones. When my BSO minion returned It returned twice with different loot & different KC. I can confirm my kc went up by 6 instead of 3 as well.(the OSB minion did not return until 3 minutes later) The only other thing that could be a factor was I was on mobile and my data is sometimes spotty, but it did not send any messages twice. This is of course in a different discord server than the main one. I don't mind this bug. ;)

ArtMatters#3174; BSO; Malygos; double trip

https://i.imgur.com/PnhLVCg.png

https://i.imgur.com/f4uXAOP.png

**Comment by Lajnux** [comment]
resolved
