### ISSUE TITLE
Hallowed Sepulcre items not equipable

### ISSUE THREAD

**Issue by Mcloughlinj101** [oldschoolgg/oldschoolbot#890]
Hello guys,

I tried equipping the Hallowed Grapple and Hallowed ring in my 'skilling' setup but was presented with the error:

Command used: +equip skilling hallowed ring
Return: You don't have enough of this item to equip, or its not equippable.

Command used: +equip skilling Hallowed grapple
Return: You don't have enough of this item to equip, or its not equippable.

I managed to equip the Hallowed symbol and Halloed Focus with no issues.

P.S great with with the bot as a whole, I see so many people and servers using it, it's great!

Take care
James

**Comment by Lajnux** [comment]
resolved
