### ISSUE TITLE
Vork uniques not on boss only CL

### ISSUE THREAD

**Issue by Shodowxx** [oldschoolgg/oldschoolbot#915]
## 🐛 Bug Report

+cl Vork does not include the Bonecrusher necklace, Skeletal Visage, Draconic Visage, Vork Head, Jar of Decay or Vorki.

**Comment by gc** [comment]
Can confirm this looks bugged - could be a bug in oldschooljs.

![file](https://user-images.githubusercontent.com/30398469/98144365-7063ca00-1f1e-11eb-9196-5fc90473a42b.png)

**Comment by gc** [comment]
This is because of how vorkath is coded:
```ts
		for (let i = 0; i < quantity; i++) {
			loot.add(VorkathTable.roll());
			loot.add(VorkathTable.roll());

			if (roll(50)) loot.add("Vorkath's head");
			if (roll(65)) loot.add('Clue scroll (elite)');
			if (roll(1000)) loot.add('Dragonbone necklace');
			if (roll(3000)) loot.add('Jar of decay');
			if (roll(3000)) loot.add('Vorki');
			if (roll(5000)) loot.add('Draconic visage');
			if (roll(5000)) loot.add('Skeletal visage');
		}

```
it could definitely be fixed by just refactoring this into using a single loottable, and not using roll()
