### ISSUE TITLE
BSO mythical cape won't show in bank when you type "=b Mythical Cape" command

### ISSUE THREAD

**Issue by 69420BLAZEIT** [oldschoolgg/oldschoolbot#925]
## 🐛 Bug Report

I went through my bank with =b --full --text and found the Mythical cape: 1, but when I type =b Mythical Cape in chat it says x0.

MARYSVILLE B T W

**Comment by Sethmare** [comment]
It looks like there are multiple items in the Jagex database with the name "mythical cape", and doing "=b mythical cape" only looks for one of those (I believe it is the bolded one it searches for). So you probably have the other item number.
![image](https://user-images.githubusercontent.com/66145237/96658931-0256ba80-1303-11eb-835f-2a3482d4bcec.jpeg)

**Comment by Sethmare** [comment]
You should be able to do =b t,[item number] to see which variant you have. Probably not incredibly helpful because you likely wouldn't be able to use it, but at least you would know :)

**Comment by 69420BLAZEIT** [comment]
> 
> 
> You should be able to do =b t,[item number] to see which variant you have. Probably not incredibly helpful because you likely wouldn't be able to use it, but at least you would know :)

I actually equipped it and it works, and has correct stats. Thanks for the reply :)
