### ISSUE TITLE
Sarachnis Gear Boosts

### ISSUE THREAD

**Issue by osrsolympus** [oldschoolgg/oldschoolbot#931]
## 🚀 Feature Proposal

Let crush attack gear boost Sarachnis kill times in addition to the food reduction provided by gear stats.

Specifically, the Tyrannical Ring, and other mid/low level type items which would be used by the average player camping sarachnis for drops or the cL.

-Bowi

**Comment by drbobbert** [comment]
To support this, sythe then bludgeon then cudgel is bis for bso while cugel is bis for osb. Karils is bis defence at sarachnis because the only theorical damage is taken from spider lings dealing both melee and mage damage

**Comment by Lajnux** [comment]
Dragon claw currently boosting, might come more in future resolved
