### ISSUE TITLE
Bso Channels

### ISSUE THREAD

**Issue by Ava-Addams** [oldschoolgg/oldschoolbot#941]
## 🚀 Feature Proposal
I would like to see more love to BSO and currently i feel its slightly neglected.

Channels:
Add either a gambling channel for BSO
or some remove bots being sent from there.
Along with removing this popping up : extremely frustrating when reading and talking in chat.
![image](https://user-images.githubusercontent.com/72924043/97043432-6202cf00-156a-11eb-99c4-778d91f4b127.png)

Bso chat is very active and i feel this only hinders the chat over benefiting it.

**Comment by drbobbert** [comment]
While I'm all for this suggestion, the notion that bso is neglected isn't reflected in the number of updates... There's been like 5 to 1. In addition, it has been made clear by magna that OSB is the main bot and bso is for fun and the priority is always osb

**Comment by gc** [comment]
This isn't something I want to do currently, I am keeping on eye on things though and will make changes if I feel its needed.
