### ISSUE TITLE
UMB item not appearing in bank

### ISSUE THREAD

**Issue by biggaybear** [oldschoolgg/oldschoolbot#944]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
I opened a UMB, got
![image](https://user-images.githubusercontent.com/73394074/97084008-de99ba00-160b-11eb-871e-de9969413a44.png)
 a bloody mourner shirt, it is not in my bank though.

![](https://cdn.discordapp.com/attachments/668073484731154462/769557800942305280/file.png)

![](https://cdn.discordapp.com/attachments/707880896203718701/769552707614015548/file.jpg)

**Comment by Lajnux** [comment]
resolved
