### ISSUE TITLE
Dwarven Bars missing when successfully smelted 5/7 bars (BSO)

### ISSUE THREAD

**Issue by Craftpure** [oldschoolgg/oldschoolbot#951]
I smelted 7 dwarven bars with Kilk equipped.
Got message saying only 2 out of 5 failed
After some time looked into bank and only have the 2 there I previously had.
The bars are Fav'd but i don't think this would effect anything. Attached Screenshots
![Make Bars](https://user-images.githubusercontent.com/68561490/97137695-51ab4980-174e-11eb-8442-cbe2c466cfe1.JPG)
![Bank](https://user-images.githubusercontent.com/68561490/97137697-5243e000-174e-11eb-828c-b630369e2490.JPG)

I have also been advised by: BigSquid69 that he is missing a Dragonfire shield yesterday will log on his behalf (BSO)

**Comment by ard35** [comment]
Just want to confirm. So in this case, `2 there I previously had` means you already had those 2 in the bank prior to the smelting 7 activity and the smelting 7 activity provided you with 0 bars?

**Comment by Craftpure** [comment]
Ard35, yep. I have pictures of my bank with 7 ore and 2 bars of you require proof

**Comment by ard35** [comment]
I believe you, I was just trying to get a better understanding of what happened.

Those 7 ores, you still have them? So they did not even get consumed during the trip? Or was this a picture you took prior to smelting?

**Comment by Lajnux** [comment]
resolved
