### ISSUE TITLE
Created Dragonfire Shield did not appear in bank (BSO)

### ISSUE THREAD

**Issue by Craftpure** [oldschoolgg/oldschoolbot#952]
Reporting on behalf of BigSquid69:
User created a shield and it did not appear in his bank. 
![image](https://user-images.githubusercontent.com/68561490/97139032-794fe100-1751-11eb-8ad7-3f471fa9244b.png)

He later created an additional to fulfill the 2 Shields he was making on behalf of: Grieve4Nieve#4593

He has advised the items were not fav'd

**Comment by Lajnux** [comment]
dragonfire shield got two IDs one for charged and one for uncharged.

when doing =b dragonfire shield the charged version is searched for and displayed.

if he does =b --search=dragonfire he would find the shield.

**Comment by osrsolympus** [comment]
^^ Still something that (ask QOL for both players and the people who answer these questions every day) should be fixed somehow.

**Comment by Craftpure** [comment]
Sorry Dev team this was a ID107 User error and i'm one for logging it >.>
