### ISSUE TITLE
Saradomin brews counting as healing food.

### ISSUE THREAD

**Issue by TheBaits** [oldschoolgg/oldschoolbot#953]
When attempting to join the Nightmare mass you must have 1600 HP in food to enter, I currently have 97 3 dose brews which at 99 HP is equal to 4656 HP in health, however i still cannot join the Nightmare as it doesnt recognise the brews as capable of healing. Can we have it changed so that Brews count as healing food?

**Comment by Lajnux** [comment]
brews needs to be combined with restores to be reasonable since they lower stats when used.
