### ISSUE TITLE
`c` clue continuation bug with nightmare

### ISSUE THREAD

**Issue by thievious1** [oldschoolgg/oldschoolbot#956]
🐛 Bug Report

Upon receiving a clue from nightmare, currently you do not get the option to do the clue with the patron perk of `c`
![DA093CA4-B895-4EE7-B8C6-26677B97F274](https://user-images.githubusercontent.com/65054062/97337654-8dc5d380-184e-11eb-91e7-8c506fc1cda0.jpeg)

**Comment by ard35** [comment]
Should be fixed with #791 once it is reviewed and merged.
