### ISSUE TITLE
BSO bug with Takon + Dwarven greathammer

### ISSUE THREAD

**Issue by Veras2020** [oldschoolgg/oldschoolbot#971]
## 🐛 Bug Report
The bug is that you can't use Takon + Dwarven greathammer at the same time (the 2 boosts work together.) 
When smithing a 30 minutes trip of "dart tips" you use 493 bars. So you can use the ''dwarven greathammer'' to get 2x of this amount > 986 bars used per 30 minutes trip. 
With ''Takon" you get a 5x resulting in 1972 bars used per 30 minutes trip.
But when you try to use both at the same time, only the 2x of the dwarven greathammer works (using 986 bars), then it looks like takon don't exist or isnt equipped(but you still get the message that hes smithing for you, when he is not.) 
Hope you could understand the bug.

**Comment by gc** [comment]
This is intentional.
