### ISSUE TITLE
Bring back trickortreat

### ISSUE THREAD

**Issue by Sethmare** [oldschoolgg/oldschoolbot#976]
## 🚀 Feature Proposal

Bring back trick-or-treat for Rick so he can live in a perpetual Halloweentown

**Comment by gc** [comment]
![login](https://user-images.githubusercontent.com/30398469/97952620-34cbe180-1df2-11eb-8499-6cd57a41c1dc.png)

**Comment by Sethmare** [comment]
Sorry @osrsolympus I tried
