### ISSUE TITLE
+sellto item disappeared

### ISSUE THREAD

**Issue by zecture** [oldschoolgg/oldschoolbot#980]
![bugreport](https://user-images.githubusercontent.com/38494964/98112350-bbdc9080-1eaa-11eb-830a-ae215853e722.png)

we succesfully traded a arcane sigil, which my friend turned into a arcane shield, when he traded it back to me the shield disappeared, its neither in my bank or his, as you can see from the screenshot the commands are used correctly afaik.

**Comment by Lajnux** [comment]
bug itself is resolved. reach out to Magnaboy or moderators about compensation if not already resolved.
