### ISSUE TITLE
Type on BSO - Shelldon

### ISSUE THREAD

**Issue by Setetchie** [oldschoolgg/oldschoolbot#987]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.

BSO minion just received pet and it says "A crab steals your fish just as you catch it! After some talking, the crab, called Sheldon, decides to join you on your fishing adventures. You can equip Shelldon and he will help you fish!"
In bank name comes up as "Shelldon", so first one displaying "Sheldon" is a typo.

**Comment by wildchickenz** [comment]
Fix the identity of my fellow comrade Shelldon, please.

**Comment by Lajnux** [comment]
resolved
