### ISSUE TITLE
+lvl broken

### ISSUE THREAD

**Issue by Eutherin** [oldschoolgg/oldschoolbot#988]
## 🐛 Bug Report

Write a description of the bug here, give all the information you can about what it is, how it happened.
![Screenshot_20201105-162653_Discord](https://user-images.githubusercontent.com/25861695/98311244-c6b72400-1f83-11eb-9273-433fefabcea9.jpg)

**Comment by osrsolympus** [comment]
Have you set your rsn to your discord account?

**Comment by gc** [comment]
I tested it and its working, make sure you have a real account set to your rsn, using +setrsn - or provide an RSN in the command, like +lvl smithing woox.
