### ISSUE TITLE
Create expert mining gloves not working

### ISSUE THREAD

**Issue by komania** [oldschoolgg/oldschoolbot#999]
## 🐛 Bug Report
I did command +create expert mining gloves and it says I don't have the requirements even though I have all of the requirements in my bank

**Comment by Lajnux** [comment]
Hey, are you in the main discord? Could you tag @Fishy in bot-channel? Got some followup questions.

**Comment by Lajnux** [comment]
Resolved, didn't have the requirements in bank.
